### PR TITLE
VSTS CI Schema Change

### PR DESCRIPTION
**Pull request by chrispat**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

Updating the VSTS CI configuration to match the latest schema.

### Alternate Designs

N/A

### Why Should This Be In Core?

N/A

### Benefits

As users see the config or try to make changes the config here should match the doc

### Possible Drawbacks

Possible I missed something and break the CI

### Verification Process

Created a build pipeline on my own account based on the update YAML and all three jobs passed successfully

### Applicable Issues

n/a

### CODE REVIEW

**Comment by daviwil** [comment]
Thanks a lot, Chris!  I'll keep an eye on the build and merge when it goes green.

**Comment by chrisrpatterson** [comment]
@daviwil there was a pretty major outage in a data center today and that is possibly the issue.  There should be a new option on the build in the drop down to re-run that build without needed to push an update to the PR now.

**Comment by daviwil** [comment]
Seems to be running smoothly now!

**Comment by daviwil** [comment]
After running "Rebuild" on the previous build, the [new build failed](
https://github.visualstudio.com/Atom/_build/results?buildId=6214&view=logs) because it couldn't upload artifacts:

```
2018-09-05T02:25:15.5585100Z Uploading 1 files
2018-09-05T02:25:20.6729460Z Total file: 1 ---- Processed file: 0 (0%)
2018-09-05T02:25:31.1542370Z Total file: 1 ---- Processed file: 0 (0%)
2018-09-05T02:25:40.6846800Z Total file: 1 ---- Processed file: 0 (0%)
2018-09-05T02:25:43.5478420Z Fail to upload '/Users/vsts/agent/2.139.1/work/1/a/atom-mac.zip' due to 'TF400813: The user '37997752-33c2-4c03-970c-cdc086fbc5e2' is not authorized to access this resource.'.
2018-09-05T02:25:43.5505160Z Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: TF400813: The user '37997752-33c2-4c03-970c-cdc086fbc5e2' is not authorized to access this resource.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
```

Also, any chance we could swap position of "Queue" with "Rebuild" on PR builds?  That's the likely action someone will want to take on a failed build and I don't think folks will realize they should look in the "..." menu.

**Comment by chrisrpatterson** [comment]
@daviwil that is expected when builds come from PRs from forks.  At the moment we don't let those upload artifacts.  It is something we are working to add but for now we block for security reasons.  It is possible to conditionalize those out when the build is a PR from a fork.

**Comment by daviwil** [comment]
Thanks!  Trying this condition to see if it keeps artifact uploads from occurring on PR builds:

```
condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
```

**Review by daviwil — APPROVED** [review]
All green now, thanks Chris!

**Pull request merged**
