### PR TITLE
:arrow_up: language-perl@0.38.0

### PR DESCRIPTION
**Pull request by fank**
This change include 2 large PRs which will improve perl language a lot.
- https://github.com/atom/language-perl/pull/89
- https://github.com/atom/language-perl/pull/90

### CODE REVIEW

**Comment by 50Wliu** [comment]
:zap:

**Comment by 50Wliu** [comment]
@Fank I pressed the merge button too early.  There's a failing test on CircleCI: https://circleci.com/gh/atom/atom/5668

**Comment by Fank** [comment]
Will check tomorrow don't have time for it now, revert it if you dont want to wait.

**Comment by Fank** [comment]
@50Wliu the failing test is a "Error: connect ETIMEDOUT 52.216.0.208:443"

**Comment by 50Wliu** [comment]
This is the error I'm seeing:
```
Package tests failed for language-perl:
....................................................F................................................

Perl grammar
  when encountering `v` followed by dot-delimited digits
    it tokenises it as a version literal
      Expected undefined to equal { value : '', scopes : [ 'source.perl', 'meta.preprocessor.pragma.perl' ] }.
        at jasmine.Spec.<anonymous> (/Users/distiller/atom/node_modules/language-perl/spec/grammar-spec.coffee:693:27)
```

**Pull request merged**
