### PR TITLE
Add copy project path command to text-editor

### PR DESCRIPTION
**Pull request by ypresto**
Fixes: #8319

The same command is available in tree-view, but it requires to focus tree-view.
https://github.com/atom/tree-view/blob/4eea2f197ee4232e25fdf8f680c1dc6a98346bcf/lib/tree-view.coffee#L311

This PR implements it on text-editor too.

### CODE REVIEW

**Comment by 50Wliu** [comment]
Hi @ypresto, it looks like you broke some of the tree view specs fixing this.  Could you please look into that?  Thanks!

**Comment by ypresto** [comment]
@50Wliu It seems upstream problem because other PRs also failed at tree-view. >_<

**Comment by 50Wliu** [comment]
:(

**Comment by joshaber** [comment]
Restarted CI and it seems fine now. Thanks!

**Comment by sandstrom** [comment]
Awesome, thanks! :boat:

**Comment by ypresto** [comment]
:tada:

**Pull request merged**
