### PR TITLE
Parallel Clean

### PR DESCRIPTION
**Pull request by aminya**
### Description of the change

This parallelizes clean by using parallel asynchronous execution of each clean task.

### Benefits 
The clean task is much faster in offline situations since they do not wait for each other to get finished.

### Drawbacks
N/A

### Verification 

Run `./script/clean`

# Requires #21401. Only the last commit is for this feature.

### CODE REVIEW

**Comment by sadick254** [comment]
Hey @aminya Could you clean up the commit history such that we remain with **https://github.com/atom/atom/pull/21431/commits/bd9cb46e1aa9080a7f6964cc7b0bfef99b777c88**.

**Comment by aminya** [comment]
@sadick254 This calls the `clean` function asynchronously. That requires making the `build` script asynchronous. I have done this inside #21401 

https://github.com/atom/atom/pull/21431/files#diff-99b83631df533ea1d9c97396a043a4670464f523d0c1e60b0a1cab6dddd440f9R163

**Comment by sadick254** [comment]
@aminya This now has conflicts. Could you please resolve them?

**Comment by sadick254** [comment]
Thanks for the PR!

That would definitely be a useful addition to our build process. However, it is not something that is within the scope that we have envisioned for Atom. We are not planning to make any major improvements to our build process for the time being. We are focused on fixing user-facing bugs. For that reason, I'm going to close this.

Thanks again for contributing to Atom :+1:

**Pull request closed without merging**
