### PR TITLE
replace _.extend in favor of Object.assign

### PR DESCRIPTION
**Pull request by Connormiha**
Since Chromium 45 supports native `Object.assign` for merging objects. Let's get rid `extends` from `underscore` in favor of native method.

### CODE REVIEW

**Comment by YuriSolovyov** [comment]
I guess you might need [`Object.setPrototypeOf`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf) for doing inheritance

**Comment by Connormiha** [comment]
> I guess you might need Object.setPrototypeOf for doing inheritance

`Object.assign` and `_.extends` for merge objects (not inheritance) and the are equals.
`Object.setPrototypeOf`does something quite different.

**Comment by YuriSolovyov** [comment]
sorry, got confused with `@prototype`

**Comment by lee-dohm** [comment]
What benefit does this give?

**Comment by Connormiha** [comment]
> What benefit does this give?

Just a little less depending of extend library. Why use extend function if browser has equal function?

**Comment by lee-dohm** [comment]
Thanks for contributing!

**Pull request merged**
