### PR TITLE
Add comment to atom-environment.coffee

### PR DESCRIPTION
**Pull request by fjwldap**
### Description of the Change

I add comment to atom/src/atom-environment.coffee in line 566.
Most of them has comment of the function. For example, like in line 562, "# Extended: Returns a {Boolean} that is `true` if the current window is maximized." 
But function 'maximizeWindow()' doesn't have a comment about it.
So I add the comment.

### Why Should This Be In Core?

It will be little bit more helpful to understand with comment. 

### Benefits

It will be little bit more helpful to understand with comment. 

### Possible Drawbacks

it is just comment...

### CODE REVIEW

**Comment by 50Wliu** [comment]
@atom/maintainers is this a method that we want to expose to the public API?

**Comment by lee-dohm** [comment]
> is this a method that we want to expose to the public API?

In my opinion, not really? I don't think that it will be any great cost but I'm not certain that packages should be maximizing the Atom window?

**Comment by maxbrunsfeld** [comment]
@fjwldap These comments affect the documentation that gets generated for Atom. In general, we don't necessarily want to document every method on every class, because we don't want Atom packages to start depending on every method.

In addition, this method is so trivial that the comment doesn't add substantially to the code's readability.

Thanks anyway for taking the time to contribute, we are definitely open to documentation improvements in general.

**Comment by pyaephyoswe** [comment]
pyaephyoswe569@gmail.com

**Pull request closed without merging**
