### PR TITLE
Update GitHub package on beta

### PR DESCRIPTION
**Pull request by smashwilson**
Update atom/github on the beta channel to include atom/github#1847 in the next stable release.

### CODE REVIEW

**Comment by smashwilson** [comment]
```
Code-signing executable at C:\projects\atom\out\Atom Beta x64\Atom.exe
SignTool Error: The specified PFX password is not correct.
Error: Command C:\projects\atom\script\node_modules\electron-winstaller\vendor\signtool.exe sign /f C:\Users\appveyor\AppData\Local\Temp\1\win.p12 /p ****** /fd sha256 /tr http://timestamp.digicert.com /td sha256 "C:\projects\atom\out\Atom Beta x64\Atom.exe" exited with code 1
  at signFile (C:\projects\atom\script\lib\code-sign-on-windows.js:43:13)
  at module.exports (C:\projects\atom\script\lib\code-sign-on-windows.js:21:7)
  at binariesPromise.then.then.then.packagedAppPath (C:\projects\atom\script\build:100:13)
  at <anonymous>:null:null
Command exited with code 1
```

@daviwil are we supposed to be trying to code-sign executables in PR builds... ?

**Comment by daviwil** [comment]
I believe that since you're PR'ing into a release branch, the AppVeyor automation decided to make a signed release build.  We had to roll the Windows signing certs recently, let me see if the password got broken there.

**Comment by daviwil** [comment]
Kicked off an Azure Pipelines build for final verification, once that passes I'll merge this!

https://github.visualstudio.com/Atom/_build/results?buildId=26392

**Review by daviwil — APPROVED** [review]

**Comment by daviwil** [comment]
Good to go!

**Pull request merged**
