### PR TITLE
penguin: Respect DISPLAY env variable in Unix like environments

### PR DESCRIPTION
**Pull request by J5**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

Please advise on a test I can write. I have not been able to successfully compile HEAD so I'm not sure if I can test or if this code is complete. It is a small patch so feel free to just fork it. Note that I did manually test the concept by using the --socket-path option on startup and writing the socket path in the same way that it would be constructed in this code.

### Description of the Change

Atom connects to a socket to determine if it is already running
and if it should launch a new window in the same process.
This socket is named with the user's name but ignores the user's
display. If a user has multiple displays, such as running a
remote display server, Atom will pop up the new window on the display
that it was first started on.

This patch adds the display name to the socket name if it exists
in the env. Because a separate socket is being opened Atom does
the correct thing and launches on the display it was started on.

### Alternate Designs

No alternatives. On linux it should be using D-Bus to avoid these lifecycle/session issues but this is good enough with the benefit that it will work across different Unix like envs.

### Why Should This Be In Core?

Atom windows should open up on the display they are started on.

### Benefits

Users who remote into a different display (such as I have to do for work) will be able to start Atom without first stopping Atom processes running on a different display.

### Possible Drawbacks

None. This is proper behavior. Applications should always respect the environment they are started in.

### CODE REVIEW

**Comment by J5** [comment]
Tried to make it testable. Let me know if there is a better way to mock. I will see if I can build this on my Fedora box at home.

**Comment by J5** [comment]
Note that I got it to build successfully on Fedora 25 but apm test does not run correctly. Something about not being able to sandbox when launching chrome. Looking into it.

**Comment by sadick254** [comment]
Hey @J5. Apologies for not looking into this on time. I know this PR has been here for a very long time, during that time Atom has seen a number of changes. Due to the changes, this PR has now become outdated. Is it possible for you to resolve the conflicts?

**Comment by sadick254** [comment]
Thank you for your PR!

We haven't gotten a response to our conflict resolution request. I'm going to close this but don't hesitate to reach out if you have or find time to resolve the conflicts, we'll be happy to reopen the PR.

**Pull request closed without merging**
