### PR TITLE
Add async implementation of GitRepositoryProvider.repositoryForDirectory

### PR DESCRIPTION
**Pull request by lgeiger**
### Description of the Change

This PR converts  `scr/git-repository-provider.coffee` to JS and converts the synchronous filesystem calls inside `GitRepositoryProvider.repositoryForDirectory` to async.
As far as I know this doesn't make it fully async since `Repository.open` still does some synchronous calls, but it's a starting point for future optimisations.

### Alternate Designs

I'd prefer to fully remove `GitRepositoryProvider.repositoryForDirectorySync` to reduce the amount of code but this would be a breaking change for any packages that might be using this method or `atom.project.addPath()`.

`atom.project.addPath()` is the only place where `repositoryForDirectorySync` is currently used inside Atom:
https://github.com/atom/atom/blob/6c066f8db10f5fe1a44d1f0b1b67abcde54c1a5e/src/project.js#L373
I think adding a optional async implementation of `atom.project.addPath()` in a future PR would be the easiest thing to do.

A quick look through the community packages reveals that it's not really used there either
<details>
<summary>
<b>Cick here to see the full output of searching through all community packages</b>
</summary>
<pre><code>
> grep -r "repositoryForDirectorySync" packages/
packages//svn/lib/svn-repository-provider.coffee:    Promise.resolve(@repositoryForDirectorySync(directory))
packages//svn/lib/svn-repository-provider.coffee:  repositoryForDirectorySync: (directory) ->
packages//atom-hg/lib/hg-repository-provider.coffee:      Promise.resolve(@repositoryForDirectorySync(directory))
packages//atom-hg/lib/hg-repository-provider.coffee:    repositoryForDirectorySync: (directory) ->
grep: packages//hipsum/node_modules/.bin/hipster-ipsum: No such file or directory
grep: packages//dynapp-atom/dynapp-atom: No such file or directory
grep: packages//docker/docker: Too many levels of symbolic links
grep: packages//parcel/parcel: Too many levels of symbolic links
packages//atom-tsd/typings/atom/atom.d.ts:        repositoryForDirectorySync(directory? : Pathwatcher.Directory) : any;
grep: packages//run-file/node_modules/.bin/csonc: No such file or directory
grep: packages//quilt-completions/quilt-completions: No such file or directory
packages//atom-yeoman/typingsTemp/atom/atom.d.ts:        repositoryForDirectorySync(directory? : Pathwatcher.Directory) : any;
grep: packages//epitools/.#amin.c: No such file or directory
packages//omnisharp-atom/typingsTemp/atom/atom.d.ts:        repositoryForDirectorySync(directory? : GitRepository) : GitRepository;
grep: packages//web-view/web-view: Too many levels of symbolic links
grep: packages//orionsoft/atom: No such file or directory
packages//nuclide/pkg/nuclide-hg-repository/lib/HgRepositoryProvider.js:    return Promise.resolve(this.repositoryForDirectorySync(directory));
packages//nuclide/pkg/nuclide-hg-repository/lib/HgRepositoryProvider.js:  repositoryForDirectorySync(directory: Directory): ?HgRepositoryClient {
packages//nuclide/pkg/nuclide-hg-repository/lib/HgRepositoryProvider.js:    return trackTiming('hg-repository.repositoryForDirectorySync', () => {
packages//nuclide/pkg/nuclide-remote-connection/lib/RemoteConnection.js:  // ::repositoryForDirectorySync, so we need the repo information to already be
grep: packages//tree-view-click/.eslintrc: No such file or directory
packages//json-schema/typingsTemp/atom/atom.d.ts:        repositoryForDirectorySync(directory? : GitRepository) : GitRepository;
</code></pre>
</details>

### Why Should This Be In Core?

It's already in Core

### Benefits

This removes synchronous IO from Atom Core which should help when using Atom together with network attached file systems.

### Possible Drawbacks

This adds similar/duplicate code to  `git-repository-provider.js`.

### Verification Process

Unit tests.

### Applicable Issues

#1766, https://github.com/atom/atom/issues/12159#issuecomment-345874321

### CODE REVIEW

**Review by cozyplanes — APPROVED** [review]

**Comment by 50Wliu** [comment]
* svn uses its own `repositoryForDirectorySync` implementation
* atom-hg uses its own `repositoryForDirectorySync` implementation
* nuclide-hg-repository uses its own `repositoryForDirectorySync` implementation

All of your other results appear to be errors from grep.  So it looks like Atom core is the only place that uses `repositoryForDirectorySync` unless I missed something.

**Comment by lgeiger** [comment]
> So it looks like Atom core is the only place that uses `repositoryForDirectorySync` unless I missed something.

Yes, it's only used by [`atom.project.addPath()`](https://github.com/atom/atom/blob/6c066f8db10f5fe1a44d1f0b1b67abcde54c1a5e/src/project.js#L324) but I fear making it use the async version may be a breaking change for some use cases.

**Comment by t9md** [comment]
One example, making it async affects my project-folder pkg.
(I'm not particularly opposing change, just sharing sample case which affects)

https://github.com/t9md/atom-project-folder/blob/af22038737ca6f427a429f9cd10e6042152d9bf2/spec/project-folder-spec.js#L22

Maybe popular project-manager be affected too?

**Comment by lgeiger** [comment]
Thanks for merging, I totally forgot about this PR 😄

**Comment by lee-dohm** [comment]
You're welcome! And thank you very much for the quality submission.

**Pull request merged**
