### PR TITLE
Fix typo in function call

### LINKED ISSUE #10783: findOrCreateBottommostSibling not working as expected
I hope I'm not missing anything here...

Shouldn't [this](https://github.com/atom/atom/blob/master/src/pane.coffee#L716) be a call to `splitDown` instead of `splitRight`.

@bencolon

### PR DESCRIPTION
**Pull request by lee-dohm**
Fixes #10783

### CODE REVIEW

**Comment by 50Wliu** [comment]
Seems correct to me!

**Comment by maxbrunsfeld** [comment]
Thanks @lee-dohm! :+1:

**Comment by acontreras89** [comment]
Thanks @lee-dohm :unamused:

**Comment by lee-dohm** [comment]
Thanks @acontreras89 for finding the typo and pointing me to it :grinning:

**Pull request merged**
