### PR TITLE
CI: Use Cache@2 task in place of the old SaveCache@1

### PR DESCRIPTION
**Pull request by DeeDeeG**
<details><summary>Requirements for Adding, Changing, or Removing a Feature (from template)</summary>

### Requirements for Adding, Changing, or Removing a Feature

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must contribute a change that has been endorsed by the maintainer team. See details in the template below.
* The pull request must update the test suite to exercise the updated functionality. For guidance, please see <https://flight-manual.atom.io/hacking-atom/sections/writing-specs/>.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see <https://github.com/atom/.github/tree/master/CONTRIBUTING.md#pull-requests>.

</details>

### Issue or RFC Endorsed by Atom's Maintainers

https://github.com/atom/atom/pull/19437

^ The initial CI caching PR for Atom mentioned looking into using official Azure Pipelines Caching when it was implemented. Caching has been officially implemented in Azure Pipelines for some time now, via the `Cache@2` task.

### Description of the Change

This (`Cache@2`) is the officially supported successor to the old,
unofficial, Microsoft-DevLabs-hosted `SaveCache@1` task.

It is simpler/easier to configure, and thus much easier for forks of Atom to set up.

(It "just works" without further configuration, actually.)

---

Cache the `[repo_root]/node_modules`, `script/node_modules` and `apm/node_modules` folders with the official [`Cache@2`](https://docs.microsoft.com/azure/devops/pipelines/release/caching?view=azure-devops) task, rather than the Microsoft DevLabs [Lighthouse-branded caching task](https://marketplace.visualstudio.com/items?itemName=1ESLighthouseEng.PipelineArtifactCaching).

This has several benefits: First, it's a newer, official project with a [dedicated and active support team behind it](https://github.com/microsoft/azure-pipelines-artifact-caching-tasks/issues/40#issuecomment-619713944). (the Lighthouse caching task is a DevLabs project, and is ["not officially supported"](https://github.com/microsoft/azure-pipelines-artifact-caching-tasks/issues/33#issuecomment-580041758).) The Lighthouse caching task must be installed from the marketplace, `Cache@2` "just works", no install needed. The Lighthouse caching task needs a `vstsFeed` (Universal Artifact Feed) ID, which means manual reconfiguration for every fork. The new `Cache@2` task doesn't ask for a feed ID, so it can work across any and all forks of Atom, no re-configuration needed!

### Alternate Designs

Use the old `SaveCache@1` task with the `vstsFeed` set to an environment variable, rather than hard-coded. See: https://github.com/atom-ide-community/atom/pull/13 ([commit](https://github.com/atom-ide-community/atom/pull/13/commits/6f64df61c958f25998f6ac0d1503b2e6ec043d9a))

### Possible Drawbacks

The `Cache@2` task only saves its cache if the entire job (bootstrap, build, test) completes.

There is no explicit "save" action we can do like there was in the Lighthouse caching task. `Cache@2` only implicitly saves cache after the "job" completes. (We could split bootstrapping out into a separate job, but that's more refactoring than I want to do in one PR).

If there are issues with building a given branch, or the branch doesn't pass tests (including for cases of flaky tests), bootstrap cache won't be saved from that run.

That said, this effect is mitigated by the fact that caches from recent runs of `master` branch can be used. Furthermore, previous runs of the same branch can be used. For pull requests, previous runs of the target branch (to be merged into) can also be used. [Docs for opportunistic cache hits across different branches/refs](https://docs.microsoft.com/azure/devops/pipelines/release/caching?view=azure-devops#cache-isolation-and-security).

Once this PR has been around merged into the repository (especially `master`) for a bit, the chance of cache misses should go down a fair amount, so we should see less bootstrapping in CI.

Some cache misses will still occur if we modify one or more of the `script/vsts/platforms/[linux.yml, macos.yml, windows.yml]` files, or any of the `[[repo_root], script/, apm/][package.json, package-lock.json]` files. But this is necessary, because in those cases it is fairly likely we do need to bootstrap again.

<details><summary>Thoughts for further improvement</summary>

Edit: see prior reasoning given here (https://github.com/atom/atom/pull/19504/commits/8d9a7aa97869a561eb4a9358807391539d28f2c7) for why the `script/vsts/platforms/*.yml` files are in the cache identifier: https://github.com/atom/atom/pull/19504

Essentially, if we update Node in the CI config, we want to do a fresh bootstrap.

---

~~Not a regression in this PR, but a chance to maybe do better than the status quo, which I didn't try yet: (Perhaps the `script/vsts/platforms/*.yml` files can be taken out of the cache identifier. I think this might just have been a crude way of splitting out the caches by OS, and I copied it in case there was some other reason I'm unaware of. But bootstrapping "in the real world" (outside of CI) doesn't need these `vsts` files, so maybe we should drop them from the cache identifier for fewer cache misses. Hopefully we don't modify the `vsts` files too much, and it would be moot? Worth thinking about, though. The question is: Do changes to the `script/vsts/platforms/*.yml` files really indicate a need to do a fresh bootstrap? If yes, keep them in the cache identifier. If no, remove them. I suspect the answer is "no", and we can remove them.)~~

</details>

### Verification Process

Ran CI with these changes.

As expected: If the build/testing succeeds, cache saving also succeeds. Then on any subsequent run with a similar enough state of the repository (`package[-lock].json` files and `script/vsts/platforms*.yml files` are the same) the cache is restored and bootstrapping is skipped.

I anticipate fewer cache misses for a given platform after this hits `master` and there is at least one successful CI run on `master` for that platform.

Also, I read [the docs](https://docs.microsoft.com/azure/devops/pipelines/release/caching?view=azure-devops) fairly closely.

### Release Notes

N/A

### CODE REVIEW

**Comment by DeeDeeG** [comment]
cc @aminya

**Review by aminya — APPROVED** [review]
This speeds up the CI builds. It is fully tested.

**Comment by DeeDeeG** [comment]
We've taken advantage of Azure DevOps templates as well: https://docs.microsoft.com/azure/devops/pipelines/process/templates?view=azure-devops

So this PR:
- Updates the cache task from unofficial v1 to official v2
- Takes advantage of templates for less repetitive, more readable code; And the code is all in one place so you can update it for all platforms simultaneously if you ever need to update it.

We'd recommend templates even if you decide not to update the Cache task to v2. We'd be glad to put together a PR with the features you might be interested in, just let us know. (me and @aminya).

_(Of course, we think the two features go well together...! So we included both in this PR.)_

**Comment by aminya** [comment]
@DeeDeeG Could you apply this commit here? I moved the cache.yml file to the templates folder.

 https://github.com/atom-ide-community/atom/pull/31/commits/c6dc2e3c9f4cec8922954d0f555b332e4721d6e6

**Comment by aminya** [comment]
I think we should either rebase this or close it in favor of #21081

**Review by aminya — CHANGES_REQUESTED** [review]
I think we should either rebase this or close it in favor of #21081

**Comment by DeeDeeG** [comment]
I think it's upstream's call which approach they like, if either.

This is a very limited change. #21081 is a more all-around revamp of the CI config.

**Comment by DeeDeeG** [comment]
I have to say, my personal preference is to stay on the old SaveCache@1 task. It's simpler to use. And it still works. Sad to say @aminya and I haven't really agreed on this point.

Here are the options I would support:
- Just use SaveCache@1
  - Ideally we would set `vstsFeed` set from a Pipelines UI variable so forks don't have to change the yml.
- I have a [WIP branch](https://github.com/atom-ide-community/atom/compare/master...DeeDeeG:CI-synced-caches) that makes Cache@2 behave similarly to SaveCache@1.
  - It repeats a lot of hard-coded strings, but it's what you have to do until [a PR to improve Cache@2](https://github.com/microsoft/azure-pipelines-agent/pull/2834) gets reviewed and merged.

**Comment by sadick254** [comment]
I would prefer the second option since we would be using the official supported `Cache@2` task. And the fact that you have a `WIP` making it similar to `SaveCache@1` is a bonus. 👍

**Comment by aminya** [comment]
@DeeDeeG Could you open a PR with your WIP branch? We need to test it and merge it to this.

**Comment by sadick254** [comment]
@aminya I have tested this on my personal fork of atom. I am happy merging it as it is for now. @DeeDeeG 's WIP should be a follow up.

**Comment by DeeDeeG** [comment]
Hi folks, sorry I was away yesterday. I suppose the synced caches follow-up will my top thing on my agenda today.

**Comment by sadick254** [comment]
@DeeDeeG Thank you for working on the cache improvement.

**Pull request merged**
