### PR TITLE
Update windows' load settings when project paths change

### PR DESCRIPTION
**Pull request by maxbrunsfeld**
/cc @mostafaeweda

### CODE REVIEW

**Comment by mostafaeweda** [comment]
I didn't test this commit, but this doesn't fix the multi folder reload issue, does it?

**Comment by maxbrunsfeld** [comment]
@mostafaeweda Yeah, I believe it fixes that issue. Let me know if you notice any more problems related to that.

**Comment by mostafaeweda** [comment]
@maxbrunsfeld  :+1: , it works as promised - I overlooked some lines of the PR code.

**Comment by mostafaeweda** [comment]
@maxbrunsfeld please bump a release with the fix.

**Pull request merged**
