### PR TITLE
Upgrade to Electron 3.1.10

### LINKED ISSUE #19372: Segfault in AllocateJSPromise after upgrading to Electron 3
We're experiencing a new render process crash that seems to correlate with the upgrade to Electron 3. It originates from `AllocateJSPromise` within V8.

Observed by @rafeca on macOS while using the app [(See gist for details)](https://gist.github.com/rafeca/373e8a8cb8cb879ca4ac4de88f1bfb34):

```
Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   libnode.dylib                 	0x0000000110212e93 v8::internal::Heap::AllocateJSPromise(v8::internal::JSFunction*, v8::internal::PretenureFlag) + 83 (heap.cc:3405)
1   libnode.dylib                 	0x00000001106dba3a v8::internal::Factory::NewJSPromiseWithoutHook(v8::internal::PretenureFlag) + 122 (factory.cc:3130)
2   libnode.dylib                 	0x00000001106dbc8f v8::internal::Factory::NewJSPromise(v8::internal::PretenureFlag) + 15 (factory.cc:3137)
3   libnode.dylib                 	0x000000011015e864 v8::Promise::Resolver::New(v8::Local<v8::Context>) + 340 (api.cc:7297)
4   libnode.dylib                 	0x000000010fdacb4d node::util::CreatePromise(v8::FunctionCallbackInfo<v8::Value> const&) + 29 (node_util.cc:147)
5   libnode.dylib                 	0x00000001102b7dd4 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) + 516 (api-arguments.cc:30)
6   libnode.dylib                 	0x000000011030a352 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) + 578 (builtins-api.cc:110)
7   libnode.dylib                 	0x0000000110309a3c v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) + 252
8   ???                           	0x00001e8d8288427d 0 + 33593129190013
```

Observed by @nathansobo and @as-cii in a VM running on @as-cii's machine while running render process tests:

### PR DESCRIPTION
**Pull request by as-cii**
Fixes #19372

Previously, we had merged the Electron 3 upgrade branch into master, but quickly discovered several ways in which Atom could crash. That caused us to revert the upgrade so that we could investigate where the problem was occurring.

All of the crashes could ultimately be traced back to `mksnapshot`, which was compiled with a set of flags that would confuse Node once the snapshot was loaded into V8 (see https://github.com/electron/electron/issues/18420). This pull request builds on top of #18916 but uses Electron 3.1.10 instead, which fixes the snapshot issue.

Note that, with this pull request, we are also bumping `@atom/nsfw` to v1.0.23. While not technically needed for the Electron upgrade, this new version contains several fixes that had been introduced in the upstream repository but that our fork wasn't yet using. For more information, see https://github.com/atom/nsfw/pull/6.

I have been using this branch for 10 days now and, after several stress tests, I couldn't observe the hard crashes anymore. It was relatively easy to reproduce them with the buggy `mksnapshot`, so I am reasonably confident those issues have finally been resolved.

This pull request only contains a few minor changes in addition to #18916, so I am planning to merge it to master as soon as we get a green build.

### CODE REVIEW

**Comment by as-cii** [comment]
Builds are green, I ended up canceling https://github.visualstudio.com/Atom/_build/results?buildId=41619 because I think AppVeyor mistakenly thought this was a production branch. Going ahead and merging this.

**Comment by mfonville** [comment]
I can confirm that the nightly based on Electron 3 works great on Ubuntu :-)

**Comment by mfonville** [comment]
Just a heads up that Electron did release 3.1.11

**Comment by mfonville** [comment]
With Electron v3, shouldn't this issue be fixed: https://github.com/electron/electron/issues/2073 (https://github.com/atom/atom/blob/119fead6925c0b6b30e9ce837c551bffaca42989/src/main-process/atom-application.js#L285)  and this TODO be resolved? https://github.com/atom/atom/blob/119fead6925c0b6b30e9ce837c551bffaca42989/src/main-process/atom-application.js#L110

**Comment by Arcanemagus** [comment]
Reviewing all `TodoElectronIssue` comments is now part of our review process for new Electron versions, it simply [hasn't happened yet](https://github.com/atom/atom/pull/19373#issuecomment-505465463) for the Electron 4 upgrade.

Thanks for bringing it up though!

**Comment by rafeca** [comment]
Thanks for bringing that up @mfonville ! we need to do some verification in order to remove these two TODOs, but it's under our radar 😄

**Pull request merged**
