### PR TITLE
Export TextBuffer for external package usage

### PR DESCRIPTION
**Pull request by mostafaeweda**
@kevinsawicki @bolinfest

### CODE REVIEW

**Comment by bolinfest** [comment]
@kevinsawicki Is there any reason why this wasn't exported before?

**Comment by kevinsawicki** [comment]
>  Is there any reason why this wasn't exported before?

Probably because no packages ever needed it. They always accessed the buffer from the editor and so they never needed to create one directly.

**Comment by bolinfest** [comment]
OK, cool, just making sure there wasn't any trickiness like there is for `Directory`.

**Comment by kevinsawicki** [comment]
So are you planning on creating the text buffer manually and passing into a manually created text editor?

**Comment by mostafaeweda** [comment]
Yep, that's our existing case but we require the original text-buffer it in a tricky way.
We will extend `TextBuffer`'s `setPath` function (https://github.com/atom/text-buffer/blob/master/src/text-buffer.coffee#L326) to create the remote file instance we have instead of it being created using `new File()` which is pathwatcher's version of the `File`

Also, after this, I'll do another PR to the `text-buffer` that makes the existing setPath call a method: `createFile(path)` - where we can simply extend and provide our version of the file instead of having to copy the contents of the `setPath` function.

And this way, we don't require the added `setFile` function to the API introduced in https://github.com/atom/text-buffer/pull/42 - then we don't even need this PR.

**Comment by kevinsawicki** [comment]
Merging this sounds good to me then, @nathansobo/@benogle any objections?

**Comment by mostafaeweda** [comment]
@kevinsawicki could we also have this with a new atom version release?

**Comment by mostafaeweda** [comment]
PING

**Comment by nathansobo** [comment]
No objections, though we may be replacing `TextBuffer` with a new document model some time in the next few months. We can make it API-compatible however and we're already exposing instances anyway.

**Pull request merged**
