### PR TITLE
Add missing docs for GitRepository

### PR DESCRIPTION
**Pull request by ssorallen**
Add argument and return type docs to fill in the documentation site.

### CODE REVIEW

**Comment by ssorallen** [comment]
Build error looks unrelated; due to a timeout. Is it possible to rerun tests without pushing a new commit?

**Comment by thomasjo** [comment]
I just triggered a new build; hopefully it passes this time (sadly spec suite on Travis is a little flakey).

**Comment by ssorallen** [comment]
:beers:

**Comment by kevinsawicki** [comment]
Awesome, thanks, apologies for the flaky build status

**Pull request merged**
