### PR TITLE
Upgrade to Babel 5.8.3

### PR DESCRIPTION
**Pull request by bolinfest**
Once https://github.com/babel/babel/issues/2028 is fixed, we can start
picking up new versions of Babel again.

/cc @sebmck

### CODE REVIEW

**Comment by sebmck** [comment]
Should have this fixed in the next couple hours.

**Comment by bolinfest** [comment]
@sebmck I see v5.8.3 is now available on https://www.npmjs.com/package/babel-core, but I only see up to v5.8.1 in https://github.com/babel/babel/commits/master.

In any event, what do you think I should change this to? `^5.8.1`?

**Comment by sebmck** [comment]
@bolinfest Travis is supposed to be merging from the [`development`](https://github.com/babel/babel/commits/development) branch into `master` on CI success, looks like that malfunctioned. `^5.8.3` would be best since there were some issues with the publishing process were a file wasn't included with borked the install.

**Comment by bolinfest** [comment]
Sounds good: changed to `^5.8.3`.

**Comment by thomasjo** [comment]
Pretty confident the one CI failure was caused by problems on the Travis side of things, but I kicked off a new build anyway to be on the safe side. I'll merge when it goes :green_heart:

**Comment by thomasjo** [comment]
PR build is :green_heart:, so I'll ignore the failing "push" build (likely due to a forced push or some such).

**Pull request merged**
