### PR TITLE
Always open all CLI paths in the same window

### LINKED ISSUE #770: Multiple folders in projects
In Sublime I can have multiple folders in the side bar. If Atom already has this, I haven't been able to figure out how to do it.

screen shot 2013-08-29 at 10 17 32 am

### PR DESCRIPTION
**Pull request by maxbrunsfeld**
No more `atom --multi-folder`

Closes #770.

### CODE REVIEW

**Comment by philipgiuliani** [comment]
There is no way to disable this behaviour or? Im used to have a window for every project.. :)

**Comment by maxbrunsfeld** [comment]
We definitely want this new behavior to be the default, but I'm willing to consider adding a flag if this is really important. So you're saying you often want to quickly open multiple folders in separate windows at the same time? Can't you just do this?

```shell
atom dir1
atom dir2
```

**Comment by philipgiuliani** [comment]
Ah if that still works its ok thanks, i though this PR overwrote that behaviour. Currently im always starting atom with `atom .`

**Comment by maxbrunsfeld** [comment]
:+1: This PR is just for handling multiple path arguments (`atom dir1 dir2`).

**Comment by philipgiuliani** [comment]
Ahh i understand thanks :) than i like the nrw behaviour, i dont even knew thats its possible to open multiple folders like this ;) will use it more often now :)

**Comment by Zireael07** [comment]
Thanks a lot for this change, it made it possible to use the Project Manager package to open two or three root folders at once. 

I don't think I'll go back to ST 3... :D

**Comment by kimegede** [comment]
`atom --help` doesn't says anything about a flag for `append`.

This makes 2 windows, where I only wanted 1.
```bash
atom dir1
atom dir2
```

**Pull request merged**
