### PR TITLE
Add configuration for enabling folding.

### LINKED ISSUE #3709: Add ability to disable folding icons in gutter
See: https://discuss.atom.io/t/how-do-you-turn-off-folding/12371

### PR DESCRIPTION
**Pull request by russlescai**
Fixes #3709.

Adds configuration item to enable or disable folding.

This includes disabling the Folding menu item.

### CODE REVIEW

**Comment by russlescai** [comment]
@izuzak I have recreated the PR for disabling folding, which works with the current master branch.

Happy for feedback etc.

**Comment by krainboltgreene** [comment]
What can I do to help this get in?

**Comment by russlescai** [comment]
@krainboltgreene It's been waiting for review since 31 March, I presume other issues for v1.0 have been higher priority.

@izuzak is this PR still in the mix? If so, I'll create a new PR from master, to simplify the rebase. 

Otherwise, I'll turn it into a separate package.

**Comment by igael** [comment]
Hello, I tried to enable it but it doesn't seem to work. has the code changed since?

**Comment by thedaniel** [comment]
What's the motivation for disabling folding? Just to hide the fold controls in the gutter?

**Comment by igael** [comment]
@thedaniel as a Web developer i often unintentionally click it instead of selecting the line(s) (it is too close from it)

**Comment by russlescai** [comment]
It was originally raised by Mark Hahn as a desired feature, and I wanted to contribute to Atom and be part of the community so created this PR to help out. :)

**Comment by alminde** [comment]
This would be a really sweet feature!

**Comment by a2sheppy** [comment]
Bummer that patches for this keep bit-rotting. Code folding is one of those things I know lots of people like but it drives me nuts, especially since I don't use it and it's so easy to trigger by accident. Then it gets very confusing. I hope someone is able to actually make this stick!

**Comment by thedaniel** [comment]
Thanks for this PR - we talked about it a bit amongst the core team, and we decided not to merge this. We're concerned about finding the right balance between configurability and having an overwhelming settings page, and we think that because folding is both a core part of the editor's functionality and very unobtrusive, adding an option to turn it off and on doesn't meet the bar to be added to settings.

For now you can patch the TextEditor prototype yourself in `init.coffee` like so:

```coffeescript
{TextEditor} = require('atom')
TextEditor.prototype.isFoldableAtBufferRow = -> false
```

**Comment by alminde** [comment]
I had the impression Atom was all about overwhelming settings pages.

Cool init script patch though. Thanks, @thedaniel.

**Comment by jussi-kalliokoski** [comment]
Can this decision be revisited? Folds are hardly unobtrusive since the default for the built-in Java package for example is to fold all import and package declarations every time you switch tabs.

**Comment by morgyface** [comment]
I too think this should be revisited, whilst the folding toggle button is visually unobtrusive it's flippin' annoying due to it's close proximity to the editor canvas. I frequently, and I mean frequently, click fold instead of positioning my cursor at the start of the line. I also never, ever use folding. I'm sure there are people that get on with it, but at least provide an option to disable. Alternatively revisit the design/ux so it's perhaps positioned to the left of the line numbers and away from the editor.

**Comment by lee-dohm** [comment]
We aren't going to be revisiting this. Thanks for the feedback.

**Pull request closed without merging**
