### PR TITLE
Fix memory issues

### PR DESCRIPTION
**Pull request by larsenv**
### Description of the Change

I fixed all memory issues, or at the very least made Atom better in every way possible.

### Quantitative Performance Benefits

Your computer should not be slow.

### Possible Drawbacks

Name change, user interface might be different.

### Verification Process

I tested this like crazy.

### Applicable Issues

None.

### Release Notes

I fixed EVERYTHING. No one will have to make PRs anymore.

Examples:

- Better code editing.
- Cooler name
- Still powered by Electron

### CODE REVIEW

**Review by Artuto — APPROVED** [review]
looks good to me merge ASAP

**Comment by Apfel** [comment]
This is perfection

**Comment by larsenv** [comment]
@Aerijo Why was this closed? I worked really hard on this!

**Comment by TripingPC** [comment]
this work is very _sublime_

**Pull request closed without merging**
