### PR TITLE
New text wrapper, measuring actual text widths

### PR DESCRIPTION
**Pull request by saschanaz**
Fixing #1783. Both Soft Wrap and Soft Wrap At Preferred Line Length works.

PS: Well, I just found there's another pull request which seems to have similar purpose. I don't know... Hmm.

### CODE REVIEW

**Comment by benogle** [comment]
Hey @SaschaNaz thanks for the PR. We're currently changing the underpinnings of buffer storage, including the way soft wrapping is handled in https://github.com/atom/text-document. We'd rather not potentially destabilize the current implementation at this time, and should fix this issue with the https://github.com/atom/text-document upgrade. Please check out and follow that repo for more information.

**Comment by SaschaNaz** [comment]
@benogle Okay, let's just stick to the current external package. Well... I think `text-document` still soft-wraps based on "column", not actual text width. Does it currently receive pull requests?

**Comment by nathansobo** [comment]
Hey @SaschaNaz. Reopening this for conversation purposes, but I think we'll need to structure things differently. As I mentioned in your other PR, I think we need to tackle text measurement in a general way and then apply it to soft wrapping as one specific case. Any interest in experimenting with the approach to measurement I discussed in #6083?

**Comment by SaschaNaz** [comment]
@nathansobo Sorry for my late response. I'm not sure what's next, did you mean we have to replace canvas with iframe+DOM Range API? Was there some performance comparison test between these two approach?

**Comment by nathansobo** [comment]
@as-cii will probably resuming work on #6083 in a couple of weeks. He can probably speak more to this, because he's tried both approaches. @as-cii, maybe we could post some profile information comparing the two? Ultimately, I want to use whatever is fastest. In the event of a tie, I'd rather use the DOM approach because I'm not that excited about depending on the canvas and the DOM having the same rendering code path forever. It's true now, and on this browser, but if we can avoid tying ourselves to it I think it would be better.

**Comment by as-cii** [comment]
I apologize for replying a bit late but hopefully the following insights will be worth the delay.

So, at the moment I do not have any fancy graphic at hand but the canvas approach takes approximately ~ 4ms to measure every new line, whereas the `getBoundingClientRect` technique can take up to twice more. In a tight loop like scrolling, however, neither are sufficiently fast and, therefore, we need to tackle this problem in a different way. Moreover, as @nathansobo pointed out, it is better not to rely on canvas to measure text as its rendering path could diverge from the DOM one unexpectedly. We need a resilient, yet fast solution.

For these reasons, we opted to try out a new approach where we don’t measure every new line eagerly but, instead, we do it lazily using `getBoundingClientRect`. This should reduce wasted computation to a minimum, thereby allowing to complete measurements before reaching the 16ms budget we have for each animation frame. On a side note, using the canvas here could potentially be wasteful, as we would need to compute all the positions preceding the requested character’s one in order to calculate it. Any solution that I can think of feels quite hacky, but I am afraid this is what we’ll end up employing before a real measurement API lands in Chromium.

You can find more insights about this technique on https://github.com/atom/atom/issues/6055#issuecomment-110858502: I plan to resume the work I made on this pretty soon, so I will definitely keep you guys posted meanwhile I make progress.

**Comment by SaschaNaz** [comment]
> it is better not to rely on canvas to measure text as its rendering path could diverge from the DOM one unexpectedly

This is a real problem as my current package cannot correctly measure a text with a thickened text inside it.

> For these reasons, we opted to try out a new approach where we don’t measure every new line eagerly but, instead, we do it lazily using `getBoundingClientRect`.

I think it may make our code much more complicated, but it's anyway interesting. I'd love to test it with my package.

**Pull request closed without merging**
