### PR TITLE
Use apm from `core.apmPath` config if it exists

### PR DESCRIPTION
**Pull request by kuychaco**
Add the ability to install packages via git urls. See https://github.com/atom/apm/pull/518 and https://github.com/atom/settings-view/pull/743.

Signed-off-by: Michelle Tilley binarymuse@github.com /cc @BinaryMuse

### CODE REVIEW

**Comment by lee-dohm** [comment]
Actually, since this is a change to the public API behavior, it should be documented in the doc comments too.

**Comment by BinaryMuse** [comment]
@lee-dohm Updated the doc comment and added a couple specs for good measure

**Comment by lee-dohm** [comment]
Thanks! Looks good to me :rocket:

**Pull request merged**
