### PR TITLE
Weekly Focus: 2018-04-02

### PR DESCRIPTION
**Pull request by smashwilson**
Weekly focus PR: please fill in your project-specific highlights from last week and focus for this week. I'll merge this Monday evening, Eastern time.

- [x] @annthurium
- [x] @as-cii
- [x] @damieng
- [x] @daviwil
- [x] @jasonrudolph 
- [x] @kuychaco
- [x] @maxbrunsfeld
- [x] @nathansobo

### CODE REVIEW

**Comment by nathansobo** [comment]
Since @as-cii is out today and we're working on similar stuff, I went ahead and checked his box. Antonio obviously feel free to add anything, just didn't wanna block this.

**Comment by smashwilson** [comment]
👍 Totally fine to check other people's boxes if you're pairing or coordinating and writing stuff up for multiple people at once.

**Comment by daviwil** [comment]
I was working on stuff outside of Atom last week so nothing to report!

**Comment by as-cii** [comment]
Thanks for checking my box, @nathansobo. 🙇 

@smashwilson: I think this is ready to merge 👍

**Pull request merged**
