### PR TITLE
More aggressive wrapping

### PR DESCRIPTION
**Pull request by Rezayovan**
### Description of the Change
Wrapping now includes wrap on dash and slash. This is a response to issue #16904, in which the user wanted more "aggressive" wrapping. To implement this change, the isWrapBoundary variable was given character checks for spaces, slashes, and dashes as wrap boundaries.

### Alternate Designs
The proposed version was selected because it produced the simplest fix to this problem. 

### Why Should This Be In Core?
This should be in the core because it has to do with editor functionality. 

### Benefits
A much more intuitive soft-wrap functionality that doesn't breakup words in the middle if it doesn't have to. 

### Possible Drawbacks
None

### Verification Process
The new soft-wrap was tested with tests such as these: 
screen shot 2018-04-14 at 11 34 11 pm

### CODE REVIEW

**Comment by Rezayovan** [comment]
Any idea on why these are failing given the addition of only one line of code?

**Comment by maxbrunsfeld** [comment]
The failings tests deal explicitly with soft wrapping. I'm guessing you'll want to change the tests since you're changing the soft-wrapping behavior?

Also, in prose, the convention is that dashes should stay at the end of the line. Can you adjust this code so that the dash is not moved to the following line?

**Comment by lee-dohm** [comment]
@Rezayovan Do you have any questions around this?

**Comment by maxbrunsfeld** [comment]
Closing this out since we haven't heard back. Let us know if you're interested in picking this back up and we can reopen it.

**Comment by ariasuni** [comment]
https://github.com/atom/atom/blob/3c9620dfa54d1cb8e1a5f356d9a5c095b95788e9/src/text-utils.js#L105-L106

should be replaced by

```javascript
const isWrapBoundary = (previousCharacter, character) =>
  isWordStart(previousCharacter, character) || isCJKCharacter(character) ||
  previousCharacter === '-' || character === '/' || character === ' '
```

I would have preferred to create a PR myself, I can’t seem to get a dev environment for Atom.

**Comment by ariasuni** [comment]
I finally managed to set up a dev environment, and I’m seeing an issue (which was already here): the cursor can’t be after the last character, because it’s the same position than the beginning of the following line, and so “Move to end of line” puts the cursor before the last character of the line visually.

**Pull request closed without merging**
