### PR TITLE
Fix auto-indent issue in text editor #10407

### PR DESCRIPTION
**Pull request by Aakash1312**
indentation being changed on paste despite auto indent on paste unchecked. 
#10407

### CODE REVIEW

**Comment by Aakash1312** [comment]
atom auto aligns the pasted text according to the indent of the first pasted line. This leads to wrong alignment when the first line is empty. Hence this special case should be taken care of.

**Comment by benogle** [comment]
Can you write a spec for this that fails without the fix?

**Comment by Aakash1312** [comment]
@benogle  Sure.

**Comment by Aakash1312** [comment]
I am not sure what is causing the specs commit to fail. Travis build is failing in settings-view specs which I didn't even touch. o_O

**Comment by Socialery** [comment]
Throwing both ifs on one line would probably be a bit cleaner / uniform with the rest of the code

```coffee
    if options.indentBasis? and firstInsertedLine isnt ''
```

**Comment by sadick254** [comment]
Hey @Aakash1312, I know this PR has been open for a long time. Apologies for not being able to look into it in a timely manner. There have been many changes on Atom since this PR was authored i.e We migrated a good number of our source files from `CoffeeScript to `Javascript`. This has led to some conflicts on this PR that are not easily resolvable. 

I have created a separate PR that supersedes this one. I will close this for now but don't hesitate to reach out in case of any queries. 

Thank you for your contribution.

**Pull request closed without merging**
