### PR TITLE
Add textEditors.getActiveTextEditor() method

### PR DESCRIPTION
**Pull request by pfitzseb**
as per #12702. Also clarify (I think) the docs for `workspace.getActiveTextEditor()` etc.

Two caveats:
- I have no idea if the fallback implementation for when there's no shadow DOM anymore actually works.
- No clue if the spec is correct, since I can't run specs locally right now (something about `Failed to execute 'registerElement' on 'Document': Registration failed for type 'atom-styles'. A type with that name is already registered.`).

### CODE REVIEW

**Comment by 50Wliu** [comment]
> No clue if the spec is correct, since I can't run specs locally right now (something about Failed to execute 'registerElement' on 'Document': Registration failed for type 'atom-styles'. A type with that name is already registered.).

Check https://github.com/atom/atom/issues/10719#issuecomment-181890766 for how to fix this.

**Comment by pfitzseb** [comment]
Thanks for the link! The spec from this PR does seem to work now.

As an aside: Atom still shows loads of testing errors for me -- is that to be expected? Also, why aren't the specs run on travis/appveyor (I guess the display specs won't work in headless mode or something?)?

**Comment by 50Wliu** [comment]
What OS are you on?  The reason the specs aren't run on Travis and Appveyor is because the specs were initially only intended to be run on macOS.  There's been some work to fix that, but a number them still fail on other platforms.

**Comment by pfitzseb** [comment]
I'm on Windows, so I guess that explains it.

**Review by ghost — APPROVED** [review]

**Comment by aminya** [comment]
@pfitzseb Is this still relevant? If so, we need to fix the conflicts.

**Review by sadick254 — APPROVED** [review]
@pfitzseb Congratulations on your first contribution. 👍

**Pull request merged**
