### PR TITLE
[autoflow] Fix bug #18030

### PR DESCRIPTION
**Pull request by QiyueSun**
### Identify the Bug

The link for this bug: #18030

### Description of the Change

1. Find the first substring that matches `%`, considering the case that `\%` is not a comment symbol;
2. Record the index of `%` in the text (characters after this index are all comments);
3. Decide whether or not to add `%` at the beginning of a new line based on the index.

### Alternate Designs

Alternative: Check if `segment == '%'` for each segment instead of using index.

It is possible that there are many `%` in the text, which is hard to distinguish using the alternative. The index is the unique feature to locate the symbol in the text.

### Possible Drawbacks

I fixed the bug for comment symbol `%` as described in #18030 but didn't consider other comment symbols. Further enhancement can be made for other comment symbols, such as `#` in Python.

### Verification Process

I typed texts for the following 4 cases in a .tex file, and pressed Edit -> Reflow Selection (MacOS 10.14.1).
1. plain text without comment symbols;
2. text starting with comment symbols;
3. text with `%` in the middle;
4. text with `\%` (`\%` isn't treated as comment symbol).
5. text with `\\%` (`%` should still be treated as. comment symbol).

The first 2 cases are original features while the last two are new. I tested that the first two still work correctly after changing the codes. Here is the outcome for 3, 4 and 5.

Example 1:
```
Lorem ipsum dolor sit amet, % consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore
```
After Reflow Selection,
```
Lorem ipsum dolor sit amet, % consectetur adipisicing elit, sed do eiusmod 
% tempor incididunt ut labore et dolore
```

Example 2:
```
Lorem ipsum dolor sit amet, \% consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore
```
After Reflow Selection,
```
Lorem ipsum dolor sit amet, \% consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore
```

Example 3:
```
Lorem ipsum dolor sit amet, \\% consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore
```
After Reflow Selection,
```
Lorem ipsum dolor sit amet, \\% consectetur adipisicing elit, sed do eiusmod
% tempor incididunt ut labore et dolore
```

I also tested for longer text:
Example 4:
```
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. % Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```
After Reflow Selection,
```
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. % Duis aute irure dolor in reprehenderit in voluptate velit esse
% cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
% proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

### Release Notes

N/A

### CODE REVIEW

**Comment by Aerijo** [comment]
How does this handle `\\%`?

**Comment by QiyueSun** [comment]
> How does this handle `\\%`?

Yeah I think I forget this situation. At present `\\%` is also treated like `\%`. I will update ASAP. Thank you so much!

**Comment by qyj233** [comment]
It failed in the test case in Windows X64 "renders visible block decorations between the appropriate lines, refreshing and measuring them as needed". 

Could anyone give some hint on this?

**Comment by QiyueSun** [comment]
Have no idea why this test case failed. 😢Anyone can help?

**Comment by rsese** [comment]
Thanks @QiyueSun - looks like you addressed @Aerijo's comment?  Were there any other changes you wanted to make?

**Comment by QiyueSun** [comment]
> Thanks @QiyueSun - looks like you addressed @Aerijo's comment? Were there any other changes you wanted to make?

Yes I addressed that problem. I think that's all the changes I can come up with so far.

**Comment by rsese** [comment]
Thanks @QiyueSun, someone from the team will take a look as soon as they can.

**Comment by as-cii** [comment]
Thanks for submitting this pull request, @QiyueSun! 🙇 

@nathansobo and I looked into the implementation and it seems very LaTeX-specific. We are a bit unsure about whether it is worth introducing this complexity for such a specific situation, and therefore we would recommend publishing a fork of this package that caters to LaTeX users' needs.

**Pull request closed without merging**
