### PR TITLE
Revert "Fixes context menu not working"

### PR DESCRIPTION
**Pull request by kelvinhomeboy**
Reverts atom/atom#22046

### CODE REVIEW

**Comment by ThatXliner** [comment]
Does this fix a regression?

**Comment by aminya** [comment]
> Does this fix a regression?

No. It seems like an automated spam bot.

**Comment by ThatXliner** [comment]
> > Does this fix a regression?
> 
> 
> 
> No. It seems like an automated [spam bot](https://github.com/cli/cli/pull/1037#pullrequestreview-619581596). 

Yeah I figured. But sometimes, [stuff aren't actually spam](https://github.com/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee)

**Comment by ThatXliner** [comment]
Another thing: how did he manage to make a commit with no changes?

Screen Shot 2021-03-30 at 3 08 33 PM

**Comment by aminya** [comment]
Funny commit history here 😄 
https://github.com/kelvinhomeboy/kelvinhomeboy/commits/main

**Comment by ThatXliner** [comment]
Yeah, I guess we should close this and report. The main reason I posted the original comment was because I wonder what the spammer would react if we actually asked him/her a legit question.


Here's another one:
Screen Shot 2021-03-30 at 3 17 18 PM

**Comment by aminya** [comment]
I did report it. I think GitHub needs to prevent the bots from registering in the first place.

**Pull request closed without merging**
