### PR TITLE
close window on last pane

### LINKED ISSUE #863: Add option to have cmd-w close the window when there are no editors open
When I have multiple buffers open in tabs and a tree view, my past editors (TextMate, Sublime) have conditioned me to expect that a repeated ⌘+w close each buffer's tab, then close the frame and its tree list after the last buffer has been closed.  Atom does not behave this way, and I'm curious if this is by design.

It is worth noting that Brackets does also hold the frame open after repeated ⌘+w presses. Is this similarly by design in Atom? Must I switch fingers to ⌘+⇧+w to close the frame?

### PR DESCRIPTION
**Pull request by thedaniel**
fixes #863 

Sets this behavior as the default.

### CODE REVIEW

**Comment by izuzak** [comment]
Here's some more information to help us reach a decision here:

1. SublimeText has an option called `close_windows_when_empty`, which has this description

  > Set to true to close windows as soon as the last file is closed, unless there's a folder open within the window. This is always enabled on OS X, changing it here won't modify the behavior.

2. I've received some feedback about my the-closer package (via email), and I've been asking which option is more useful to users. Here's a typical response:

  > I use cmd-w to slide the last document, and then cmd-w again to close the project. It's pretty common that I want to close all docs, but leave the project open. 

3. The feedback on [the forum](https://discuss.atom.io/t/closing-whole-editor-instance-on-cmd-w/2272/7) and [the original issue](https://github.com/atom/atom/issues/863) seems to be in favor of the "close window when no tabs empty but not together with the last tab" behavior. 

I agree with @thedaniel that we shouldn't be adding checkboxes for every option. :+1: However, we now also have the option of making this a [dropdown choice](https://atom.io/docs/api/v0.184.0/Config#enum), so we could have a single setting with the options "nope", "close after last tab is closed", "close together with the last tab". :lightbulb:

I also wouldn't mind picking the more popular option (close _after_ last tab is closed, not with it), and asking users to install a package if they want more options.

Any other thoughts, everyone? Also, @thedaniel -- are you still interested in working on this? I noticed that this PR no longer merges cleanly, so it probably needs some cleanup or someone could open a new one if you have a full plate.

**Comment by lee-dohm** [comment]
I'm ok with this being a dropdown setting now that it's an option.

**Comment by thedaniel** [comment]
@izuzak Happy to work on it, I just didn't push this because it seemed most of the work was in debating the various kinds of behavior, not the code :)

**Comment by kevinsawicki** [comment]
Closing this out since it pretty outdated now and no longer merges cleanly, feel free to reopen when updated.

**Pull request closed without merging**
