### PR TITLE
Update docs/README.md

### PR DESCRIPTION
**Pull request by kodemonster**
### Requirements for Contributing Documentation

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only contribute documentation (for example, markdown files or API docs). To contribute other changes, you must use a different template. You can see all templates at https://github.com/atom/atom/tree/master/.github/PULL_REQUEST_TEMPLATE.

### Description of the Change

Changed the paragraph, in my opinion there was grammar mistake.

### CODE REVIEW

**Comment by kodemonster** [comment]
why Atom pull request failed? help anyone? i am beginner

**Comment by lee-dohm** [comment]
Thanks very much for the suggestion.

Since the content was moved some time ago, "now" doesn't really apply. And "following" is one of those words like "here" that shouldn't be used to reference a link. Because of these reasons, we feel that the current wording is more correct.

Thanks again for your help and passion for Atom 😀

**Comment by kodemonster** [comment]
Thanks for your response, As I stated that I have just started is there anything that I can contribute to?

**Comment by lee-dohm** [comment]
Please see the [How Can I Contribute section](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute) of the CONTRIBUTING guide.

**Pull request closed without merging**
