### PR TITLE
Implementing tree-sitter based indentation logic

### PR DESCRIPTION
**Pull request by chfritz**
### Issue or RFC Endorsed by Atom's Maintainers

This approach was supported by @maxbrunsfeld in https://github.com/atom/language-javascript/issues/594#issuecomment-420415412. It also addresses a number of indentation logic related issues such as https://github.com/atom/atom/issues/6655, https://github.com/atom/language-javascript/issues/560, and potentially [others](https://github.com/atom/language-javascript/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+indentation+).

### Description of the Change

Implements a tree-sitter based indentation logic. This was previously developed and tested in the sane-indentation package (> 0.9). Refer to https://github.com/atom/language-javascript/issues/594#issuecomment-420415412

By itself this does nothing. The new logic is only used if the language package for the current language contains the necessary configuration (e.g., which scopes to indent on). So this PR goes together with, e.g., https://github.com/atom/language-javascript/pull/608 in language-javascript.

### Alternate Designs

I went through a number of iterations developing this code in the sane-indentation package. I first used the scopes array directly, but found that it only got me so far because it was lacking context. So I switched to this new tree-walk approach. It is more concise and has more context to make indentation decisions on. As reported in https://github.com/atom/language-javascript/issues/594#issuecomment-423780452, I found this enough to implement proper indentation for a variety of languages.

### Possible Drawbacks

I have not found any cases where the new indentation logic is worse that the previous, regex based logic. In particular it uses the already-present parse tree from tree-sitter, so it seems faster and more comprehensive.

### Verification Process

I developed this code [over the course of the last two months in the sane-indentation package](https://github.com/chfritz/atom-sane-indentation/commits/master) (which monkey patches the `suggestIndentForBufferRow` function to replace the atom indentation logic with this new logic. As proposed by @maxbrunsfeld (https://github.com/atom/language-javascript/issues/594#issuecomment-420415412), I worked on adding support for other languages besides javascript to make sure the logic is general enough to support various types of languages. As reported in https://github.com/atom/language-javascript/issues/594#issuecomment-423780452, I found this logic sufficient for implementing proper indentation for Javascript (incl. JSX), HTML, Python, C and C++. I have not yet tried others.

The most comprehensive test was using this new logic in my every-day development (Javascript, JSX, and HTML) for over a month now.

### CODE REVIEW

**Comment by chfritz** [comment]
Sorry about those linting errors. I'll fix them.

**Comment by maxbrunsfeld** [comment]
This is very, very cool.

@chfritz Just letting you know - because this is a big and important new feature, (and we're currently addressing regressions that we discovered after enabling Tree-sitter by default), it will probably take some time for us to get to this and review it. But I'm definitely very interested.

Some initial questions:

1. It seems like we'd want to have *one* place where indentation is configured for a language, as opposed to having one place in a `.cson` file, and another place that [involves JavaScript code](https://github.com/atom/language-javascript/pull/608/files#diff-16b7d75b70953cbf4755508170f2f24cR61). Is there a way to convert the JS code into a declarative format that can be loaded through JSON/CSON? If not, maybe the entire configuration should be through a JS API.

2. Even more meta - do you think it's feasible to have Atom automatically infer these indentation rules from an example source code file? That seems like the holy grail, but is perhaps too complicated.

**Comment by chfritz** [comment]
@maxbrunsfeld sorry for the delay in responding. I somehow broke my dev mode (it keeps crashing with a segfault), and haven't been able to try a few things on Item 1 that I wanted to try. I'll get back to you as soon as I get past this impasse.

On Item 2: that's a really interesting idea. I need to think this through further. I'm not yet sure whether the correct (i.e., desired) indentation can be inferred from just one example in all cases, or how many variables the implied set of equations has. If the only logic is scopes, then yes, this should be possible. But those additional conditions (Item 1) seem to span a much bigger space.

The current solution actually already provides a fair bit of room for customization, because users can decide for themselves which scopes should cause indentation. That way, issues that are more of a matter of opinion such as https://github.com/atom/language-javascript/issues/298 can be made a thing of the past.

**Comment by chfritz** [comment]
@maxbrunsfeld at long last I've gotten my dev-mode back into a working condition to test changes to this PR.

I evaluated translating the code-based config to something declarative, but that was just getting too convoluted. So I've now gone the other way you suggested and moved all config to code, see [my example for language-javascript](https://github.com/atom/language-javascript/pull/608/files).

I think this is ready for review now.

**Comment by chfritz** [comment]
Good news, @maxbrunsfeld , I was wrong! I did find a way to get rid of the non-declarative part of the configuration after all. The language-specific configuration is now all declarative as it should be: https://github.com/atom/language-javascript/pull/608/files.

**Comment by maxbrunsfeld** [comment]
Woah, that’s looking very very clean. Nice work, @chfritz!

**Comment by chfritz** [comment]
Thanks!

**Comment by lee-dohm** [comment]
@chfritz This sounds pretty awesome. Unfortunately, before we can spend a bunch of time reviewing it, we're going to need comprehensive tests added so that we can ensure we don't accidentally regress any of the functionality you've painstakingly built here.

**Comment by chfritz** [comment]
Unfortunately I'm still having a hose of issues with my source build on Linux. My dev mode crashes all the time, and when I try to run tests I get:
```
> atom --dev --test --timeout 60 spec/config-spec.js 
...../../third_party/tcmalloc/chromium/src/free_list.h:118] Memory corruption detected. 
Renderer process crashed, exiting
```
This doesn't seem to depend on the specs I'm testing. Even some of the tiniest specs fail:
```
> atom --dev --test --timeout 60 spec/typescript-spec.coffee 
.../../third_party/tcmalloc/chromium/src/free_list.h:118] Memory corruption detected. 
Renderer process crashed, exiting
```
This is after a clean checkout of master, `./script/clean` and `./script/bootstrap`.

Furthermore `./scripts/build` also crashes with:
```
Verifying if snapshot can be executed via `mksnapshot`
/home/cfritz/github/atom/out/startup.js:1
var snapshotAuxiliaryData={lessSourcesByRelativeFilePath:{"static/atom-ui/_index.less":{content:'// Atom UI\n\n// Private! Don\'t use these in packages.\n// If you need something, feel free to open an issue and it might can be made public\n@import "styles/private/scaffolding.less";\n\n@import "styles/private/alerts.less";\n@import "styles/private/close.less";\n@import "styles/private/code.less";\n@import "styles/private/forms.less";\n@import "styles/private/links.less";\n@import "styles/private/navs.less";\n@import "styles/private/sections.less";\n@import "styles/private/tables.less";\n@import "styles/private/utilities.less";\n\n\n// Public components\n// Open the Styleguide to see them in action\n@import "styles/badges.less";\n@import "styles/button-groups.less";\n@import "styles/buttons.less";\n@import "styles/git-status.less";\n@import "styles/icons.less";\n@import "styles/inputs.less";\n@import "styles/layout.less";\n@import "styles/lists.less";\n@import "styles

Error: Cannot require module "fs".
To use Node's require you need to call `snapshotResult.setGlobals` first!
    at require (/home/cfritz/github/atom/out/startup.js:1:660391)
    at customRequire (/home/cfritz/github/atom/out/startup.js:1:660842)
    at get_fs (/home/cfritz/github/atom/out/startup.js:11:258467)
    at getElectronPath (/home/cfritz/github/atom/out/startup.js:11:258623)
    at Object.../../../../node_modules/electron/index.js (/home/cfritz/github/atom/out/startup.js:11:258976)
    at customRequire (/home/cfritz/github/atom/out/startup.js:1:660732)
    at Object.../src/atom-environment.js (/home/cfritz/github/atom/out/startup.js:1:665279)
    at customRequire (/home/cfritz/github/atom/out/startup.js:1:660732)
    at Object.<anonymous> (/home/cfritz/github/atom/out/startup.js:1:661073)
    at Object.../src/initialize-application-window.js (/home/cfritz/github/atom/out/startup.js:1:665145)
Error: Command failed: /home/cfritz/github/atom/out/atom-dev-1.36.0-dev-4979677-amd64/atom /home/cfritz/github/atom/script/verify-snapshot-script /home/cfritz/github/atom/out/startup.js
```

I have been struggling with issues of this sort since end of October and frankly, they make developing for atom.io quite annoying. Any idea what might be going wrong? By now I've spent more time trying to debug why the development environment doesn't work than I've spent on the actual contribution I'm trying to make.

For completeness:
```
> apm --version
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 2.7.12
git 2.7.4
> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```

**Comment by chfritz** [comment]
I was able to develop and add tests by using the deb-package installation of atom (9 tests, 292 assertions). The bulk of the test cases are defined in terms of correctly indented [sample files](https://github.com/atom/atom/tree/35677c5386cf756efdb93d89bc4f60b49ab8bbfb/spec/fixtures/indentation). For each of these tests it is verified that the proposed indentation matches the one in the file.

They pass on all platforms. The failing test on Mac OS is unrelated to this commit.

**Comment by rafeca** [comment]
Hey! 👋

We have recently started using [`prettier`](http://prettier.io/) and this has caused major style changes on the Atom JS codebase (you can check [the related PR](https://github.com/atom/atom/pull/19391)).

This is good news: now the Atom code is more consistent and it's much easier to re-format the code to follow the codestyle (now you only need to run `script/lint --fix`).

This change caused conflicts on your PR that we have automatically solved, hope you don't mind 😄

With ❤️, the Atom team.

**Comment by chfritz** [comment]
It's now been almost a year since I've opened this PR and more than six months since finishing all requested changes. Are there any plans to still consider this, or will this PR go the same route as [the one I opened  three years ago](https://github.com/atom/atom/pull/10367), which never got merged? It's a little frustrating to work on something that was [endorsed](https://github.com/atom/language-javascript/issues/594#issuecomment-420415412) by the core developers and then see it being ignored forever and ever.

**Comment by chfritz** [comment]
PS: needless to say that this PR yet again out of date by now I need to put more work into catching up with changes that happened elsewhere. But I'd like to have some assurance that all that work is not for nothing like it has been (just like the work I put into a [related PR](https://github.com/atom/atom/pull/10367) I created three years ago).

**Comment by chfritz** [comment]
This is amazing. Apparently this PR has inspired tree-sitter based indentation logic for both emacs and neovim. Both of these seem to have been merged. Maybe if we give it another two years we can put a plan together to merge this into atom as well?

**Comment by sadick254** [comment]
@chfritz I know this has been long overdue. I have resolved some conflicts on this PR to give you an easy time should you choose to fix the failing tests.
In case you are busy I would like to offer to continue working on this PR and fix the failing tests. I am interested in this feature and would like to see it land on Atom stable version. Let me know.

**Comment by sadick254** [comment]
@chfritz For now you can ignore any errors that are not relevant to the indentation work.

**Comment by chfritz** [comment]
I think the test that is failing is just about specifying what is correct indentation. The new logic changes the indentation -- to the better, I would argue, of course. So the "fix" would be to change the specification. Can you help me find "spec/tree-indenter-spec.js"? I can't find it in the source tree.

**Comment by sadick254** [comment]
@chfritz No worries. Just let me know if you need any assitance. I am keen to see this go through.

**Comment by chfritz** [comment]
I've been trying to compile atom for the last two days, with no luck. It gets stuck on this bizarre error:
```
> vscode-ripgrep@1.9.0 postinstall /home/cfritz/github/_atom/node_modules/vscode-ripgrep
> node ./lib/postinstall.js

Finding release for v12.1.1
GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v12.1.1
Deleting invalid download cache
Downloading ripgrep failed: Error: Request failed: 401
```
Any advise?
```
> node --version && npm --version && lsb_release -r
v12.22.1
6.14.12
Release:	20.04
```

**Comment by chfritz** [comment]
ok, I got past that by upgrading the version of vscode-ripgrep to the latest. Now I get:
```
> ./out/atom-dev-1.59.0-dev-a3d4f9cdb-amd64/atom 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: The module '/home/cfritz/github/_atom/out/atom-dev-1.59.0-dev-a3d4f9cdb-amd64/resources/app.asar.unpacked/node_modules/nslog/build/Release/nslog.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

**Comment by sadick254** [comment]
Could you try running `npx electron-rebuild -v 9.4.4`.

**Comment by chfritz** [comment]
@sadick254 : at long last I've been able to get atom to compile again (in a lxc container), migrate my changes (had to manually re-add all changes, since the package-locks seems have been messing things up), and fixed the issue. The fix was trivial -- literally just a `+ 1` missing that became necessary with atom 1.40 -- ancient history! :-)

All tests are now passing.

Looking forward to having this PR finally get merged -- [five years after making my first attempt](https://github.com/atom/atom/pull/10367) to improve the indentation logic.

Thanks for your help and for picking this back up!

**Review by sadick254 — APPROVED** [review]
This looks very good. It's working well as I expected. Thank you for the awesome work @chfritz.

**Pull request merged**
