### PR TITLE
Allow to set Vibrancy

### PR DESCRIPTION
**Pull request by the0neyouseek**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

Allow to set the vibrancy of the browserWindow with the setVibrancy method.

### Alternate Designs

/

### Why Should This Be In Core?

Allow to use vibrancy in themes

### Benefits

See above

### Possible Drawbacks

none

### Applicable Issues

See #14162

### CODE REVIEW

**Comment by simurai** [comment]
You could call `setVibrancy` directly in Electron. E.g.

```js
require('electron').remote.getCurrentWindow().setVibrancy('medium-light');
```

But maybe still a good idea to let people use a more official "Atom" API?

/cc @atom/feedback

**Comment by the0neyouseek** [comment]
@simurai I tried that beforehand but it did not work because `remote.getCurrentWindow()` does not have a `setVibrancy` function (at least not in `1.18.0`)

**Comment by simurai** [comment]
Ohh.. right. It's only available from `1.19`, currently still in [Atom Beta](https://atom.io/beta).

**Comment by lee-dohm** [comment]
Thanks very much for the work on this.

On further review, we have decided that we aren't going to accept this feature at this time. Since, as @simurai points out, people or theme authors can enable this on an individual basis anyway, we don't feel that an official API is necessary or justifies the maintenance cost.

Thanks again for the help and your interest in Atom :+1:

**Pull request closed without merging**
