### PR TITLE
:arrow_right: Migrate core package 'about' into ./packages

### PR DESCRIPTION
**Pull request by daviwil**
### Description of the Change

This PR migrates the core [`about`](https://github.com/atom/about) package into `atom/atom`.  See issue #17832 for more information.

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
I'm guessing we can also delete `PULL_REQUEST_TEMPLATE.md`, `ISSUE_TEMPLATE.md`, `package-lock.json`, `.travis.yml`, and `appveyor.yml`.

**Comment by Arcanemagus** [comment]
Should these repo specific files be being migrated?
* `.travis.yml`
* `ISSUE_TEMPLATE.md`
* `PULL_REQUEST_TEMPLATE.md`
* `appveyor.yml`

The package specs should be being run as part of Atom's own CI builds now, never mind the fact that they are now in a different repo, so the CI configurations are completely useless. The GitHub repo files are also pointless now as they are superseded by the Atom ones.

**Comment by daviwil** [comment]
Yes, they can be removed, I'll do that before merging.

**Comment by daviwil** [comment]
Added a [README.md](https://github.com/atom/atom/blob/dw-migrate-about/packages/README.md) with details about core package locations.  This will be updated for future package migrations.

**Comment by daviwil** [comment]
Gonna go ahead and get this merged so that I can move forward on finishing the migration of this package.  Please let me know if there's anything else you'd like for me to address and I'll be happy to do it in another PR tomorrow!

**Comment by maxbrunsfeld** [comment]
📈 💥

**Pull request merged**
