### PR TITLE
Disallow OS text selection in atom buffers.

### LINKED ISSUE #17799: Right Clicking Creates a Different Type of Text Selection
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

There are currently two distinct kinds of selection in Atom. It seems like one may be an uncanceled native one, however, simply ignoring it isn't enough to really fix the behavior.

### Steps to Reproduce

1. Make a normal text selection. In the One Dark theme, it'll be highlighted in gray.
2. Right click another word. This will highlight that word in blue.
3. Select copy from the context menu. It will copy the Atom (gray-highlighted) selection.

**Expected behavior:** [What you expect to happen]

Right clicking a word updates the Atom selection. The word should then be highlighted in gray. There should be no blue selection.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

OSX

```
$ atom --version
Atom    : 1.29.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3
$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.29.0
python 2.7.10
git 2.13.5
```

cc @daniel-ohayon who originally raised this bug with the Nuclide team 😊

### PR DESCRIPTION
**Pull request by queerviolet**
This admittedly odd-looking change disables OS-level text selection in Atom text buffers. We generally prevent native selection operations anyway (instead managing the selection ourselves), but in some cases (macOS right click, frex), we would still get one (which wouldn't be attached to anything, creating confusion and sowing discord).

Fixes #17799
Fixes atom/spell-check#251

### CODE REVIEW

**Comment by Aerijo** [comment]
@queerviolet Also appears to fix https://github.com/atom/spell-check/issues/251. The cursor still moves to the word, but that's a separate issue.

**Review by daviwil — APPROVED** [review]
Awesome, looks good!

**Review by maxbrunsfeld — APPROVED** [review]
⚡️

**Comment by queerviolet** [comment]
Ugh. What an annoying failure—the spec isn't quite testing the right thing. Copy/paste from MD preview does actually work. 😔

**Comment by matthewwithanm** [comment]
thanks!! ❤️

**Comment by alshhrymhmd008** [comment]
Vick

**Pull request merged**
