### PR TITLE
:arrow_up: electron v0.37.0

### PR DESCRIPTION
**Pull request by drewmnoel**
Update electron to the latest upstream. Supersedes PR #10983.

### CODE REVIEW

**Comment by drewmnoel** [comment]
Build failures in OS X are due to missing ffmpeg libraries in electron?

**Comment by ZakariaRidouh** [comment]
@drewmnoel

as a temporary fix (to allow running v0.37.0), copy

`Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib`

and paste it to

`/usr/local/lib`

**Comment by drewmnoel** [comment]
@ZakariaRidouh the build errors are on Travis actually!

**Comment by 50Wliu** [comment]
@drewmnoel I would keep your existing 0.36 PR open and bump it up to 0.36.11, as minor version bumps for Electron (especially this one as it updates to a new Chrome version) usually take longer to review and test for regressions.

**Comment by ZakariaRidouh** [comment]
@50Wliu its been fixed over at atom/electron#4769 (electron version 0.37.1)

**Comment by drewmnoel** [comment]
Re-opened previous PR, doesn't require a minor level bump.

**Pull request closed without merging**
