### PR TITLE
Upgrade text-buffer for marker performance improvements

### PR DESCRIPTION
**Pull request by maxbrunsfeld**
See https://github.com/atom/text-buffer/pull/58.

Currently this branch uses a pre-release of text-buffer, `6.0.0-beta.1`, introduced in the above PR.
- [x] Publish the `text-buffer@6.0.0` and switch to using that.

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
@atom/core @atom/non-github-maintainers - If anyone has a chance to build this branch and use it for a little while, I would really appreciate it. I think the main areas to look for regressions are movement of markers, and undo/redo. Also, if anyone uses or maintains any packages that make non-trivial use of markers, it'd be great to check that they're still working ok against this branch.

**Comment by lee-dohm** [comment]
Building it now and I'll see what I can see. Working on some stuff with Linter enabled ... so hopefully that will help vet the marker stuff.

**Comment by lee-dohm** [comment]
I haven't seen any regressions so far. I'll play with it again some more in the morning.

**Comment by lee-dohm** [comment]
I worked with it a bit more this morning and I didn't see anything. I didn't do any really rigorous testing though, just typical editing stuff.

**Comment by maxbrunsfeld** [comment]
:bow: Thanks a lot for looking at it @lee-dohm.

**Comment by thomasjo** [comment]
Building now, will test it out over the next couple of hours. Will let you know if I find any issues.

**Comment by as-cii** [comment]
Awesome! :dragon:

**Pull request merged**
