### PR TITLE
:memo: Suggest branch name section in CONTRIBUTING

### PR DESCRIPTION
**Pull request by kenju**
# What
- Suggestion for writing `branch-name` section in `CONTRIBUTING.md`
- What I wrote is just for the first draft, and should be reviewed and improved
# Why
- With the more contributor is getting joined with this community, there are a bunch of branch name
  without any under coherence
# How
- I strongly believe that beginning with Github Username is easy to find and at the same time recognizable
- As for the latter part (topic categories and branch name style), I would like to hear more contributor's opinions

### CODE REVIEW

**Comment by 50Wliu** [comment]
I'm :-1: on this for the following reasons:
* In general the Atom team (those with push access to atom/atom) uses the format `initials-short-description`, eg `mb-adjust-app-name-by-channel` or `wl-github-desktop`
* If you're creating a PR from a fork, the author's name is both on the PR itself and also in front of the branch name, such as `scv119:native-modules`
* The branch name is not particularly important since it's the issue and commit contents that define the PR, not the branch name
* As far as I know, branch names aren't searchable (or at least I haven't found the filter for that yet :grin:)

/cc @atom/feedback

**Comment by lee-dohm** [comment]
I generally agree with @50Wliu. For me, branch names should be short and memorable. When working in my own repository, I have branch names like `fix-typos` for quick fixes or `bug-1234` for things that have more information associated. When working in Atom repositories, I prepend `ld-` to it. But that's what works for me ... I don't think we need to impose any particular style on people working in their own forks.

**Comment by izuzak** [comment]
Hey, @KENJU -- thanks for taking the time to open a pull request for this. I've never considered making guidelines for branch names, so it's great to see your thoughts.

In general, I agree with @50Wliu and @lee-dohm -- I don't see the benefit of having strict guidelines for branch names for all contributors. I think pull request titles and descriptions, and commit messages are much more important there. 

However, for maintainers who create branches in atom/atom and other Atom-owned repositories, I think it would be helpful to mention the general guideline we try to follow: `initials-short-description` e.g. `iz-example-change-to-fix-everything`. That makes sense for branches created in Atom-owned repositories since it allows us to see at a glance who created which branch and what they're working on (helpful when you want to reach out to someone working on a branch or when cleaning up old branches).

I'd be :+1: on adding a note about branch names primarily targeted at maintainers who can create branches in Atom-owned repositories based on the above guideline, and perhaps add a line saying that other community members are free to use this guideline as well. If that sounds good to you and you want to modify this PR in that direction -- I'd be happy to review that. If not, I think we can close this and I'll add this note about branch names in another PR.

Thanks again! :bow:

**Comment by KENJU** [comment]
Thanks for your fruitful comment and review, @50Wliu and @lee-dohm , and @izuzak. Thanks to your feedbacks, now I have clear mind over branch name and rule in atom community! :grin: 

I a little bit wondered is there any rule for branch name in atom community when I firstly created a branch in my forked repo, because in my company there is a rule for adding version name or bug-fix-num as a prefix.

Even though if there is no rule for branch name, I have thought that it would be better that there is no rule or strict guideline for this, so am glad to see the conclusion of @izuzak comment. I am newbie to atom community, so would you close this issue and add a new line in another PR, @izuzak? 

Thanks!

**Comment by izuzak** [comment]
Sure thing, @KENJU, I'll open a new PR -- thanks again for starting this discussion. :blue_heart:

**Comment by KENJU** [comment]
@izuzak That's my line, thanks all :)

**Pull request closed without merging**
