### PR TITLE
README.md Tranlation to Simplified Chinese

### PR DESCRIPTION
**Pull request by LShun**
Hello, this is a translation of the README.md to simplified Chinese. I translated this using Google Translate as well as using my understanding towards the language to correct confusing sentences and words. However, it still needs some tweaking. I did not translate “Flight Manual" because there isn't a Chinese version for it that I can point to. 

Thank you.

### CODE REVIEW

**Comment by LShun** [comment]
Hello, I think its a bit of weird, I only added a .md file with text and formatting but it has 2 failed tasks. Can someone help me to check if I had mistype something? Both of the two tests reported timed out. Thank you.

**Review by wjz27 — COMMENTED** [review]
In line 20,  (./ apm-rest-api.md)
Here has an extra space between '/' and 'apm'.
Same with line 21.

**Comment by LShun** [comment]
@wjz27 Thanks for letting me know! I made some changes to fix the links.

**Comment by damieng** [comment]
The brackets on lines 20 and 21 are the wrong type - they need to be normal ascii ( to create hyperlinks.

You can see them not rendering correctly if you click Files Changed and then View on the file.

**Comment by sadick254** [comment]
Thanks for the submission!

The addition of simplified Chinese `README.md` is a good idea, however, I don't see it adding a lot of value to what we already have. This would have been useful if the `README-zh.md` was being picked up by the flight-manual.io site but that's, not the case. I will have to close this PR for now.

Thanks again for your contribution.

**Pull request closed without merging**
