### PR TITLE
Automatically resize command-palette for small screens

### LINKED ISSUE #10603: Atom cuts command palette window if global window size is too small
I'm sure this one is cosmetic, but Atom cuts command palette window if global window size is set too small.
screen shot 2016-01-27 at 18 10 49

### PR DESCRIPTION
**Pull request by Aakash1312**
Fixes #10603 

Now command palette is automatically resized when global window size is very small.

### CODE REVIEW

**Comment by lee-dohm** [comment]
Are there any unit tests that can be written for this to prevent us from accidentally breaking it in future changes?

**Comment by benogle** [comment]
Also, it looks like this makes the modals always scale to the width of the window. I think, if we are to fix this, we should keep the current width, and only scale when the window is too small.

**Comment by Aakash1312** [comment]
Although the resize function is called every time window is resized, modals are scaled only when window width is less than the default modal size, ie, 50em. otherwise it sets the modal size to default value.
Is there any problem with this?

**Comment by philipgiuliani** [comment]
I think this could be completly solved in CSS, or do i miss something? @simurai

```css
width: 80%; /* or different */
max-width: 50em;
transform: translateX(-50%); /* instead of - margin left */
```

**Comment by simurai** [comment]
> And what if a theme wants to overwrite the width?

Yeah, some themes are probably overriding it. The `50em` comes actually from the One themes. Default from core is `500px`.

I can take a look.. maybe it's also possible with Flexbox or using a Media Query.

**Comment by simurai** [comment]
Ok, here a fix using a CSS Media Query: https://github.com/atom/atom/pull/10782

@philipgiuliani `transform: translateX(-50%);` would work too, but it seems to make text blurry.

Flexbox would be nice, but more themes might be affected and needs more testing for side effects.

**Comment by simurai** [comment]
#10782 that uses a CSS Media Query is now merged and closes this one. It should be easier to customize and maybe less taxing on performance.

@Aakash1312 Thanks alot for your initial PR. 🙇

**Pull request closed without merging**
