### PR TITLE
Workspace.open() support for splitting up/down 

### PR DESCRIPTION
**Pull request by lpommers**
Closes https://github.com/atom/atom/issues/7059
Related to https://github.com/atom/markdown-preview/issues/99

Add ability to call `atom.workspace.open()` with `up` / `down` split properties.

### CODE REVIEW

**Comment by walles** [comment]
+1

I just tried this. Built it, installed the "git plus" plugin, changed something invoked "Git Plus: Diff".

Works fine with "Git Plus" configured for right, up and down.

Doesn't work with "Git Plus" configured for "left" (it opens the diff in the current pane), but IMO fixing that is out of scope for this PR.

**Comment by gvc** [comment]
:+1:

**Comment by mnquintana** [comment]
Having some specs for this behavior would be great.

**Comment by lpommers** [comment]
I haven't forgotten about this.. just been on vacation and I've been having trouble with some of the tests.. I might have to make some changes

**Comment by walles** [comment]
@lpommers, ping?

**Comment by lpommers** [comment]
I haven't look at this in a long time. I'll get this branch up to date...

**Comment by lee-dohm** [comment]
This was added in another PR. Sorry for the mixup :blush:

**Pull request closed without merging**
