### PR TITLE
Upgrade electron to 1.8.6

### PR DESCRIPTION
**Pull request by ungb**
Initial PR for Electron upgrade to 1.8.6.  

Fixes https://github.com/atom/settings-view/issues/924

### CODE REVIEW

**Comment by damieng** [comment]
Definitely appear to be some issues here that the new Electron is causing - rather than CI failures.  This will require more investigation from the team - I've not been involved in any of the previous Electron upgrades so probably not the best person to dig into this solo.

**Comment by ungb** [comment]
Yeah, same here. I wanted to get this PR up as I was talking to electron team it's good to identify these issues early on.   Wonder if @ckerr can help with this.  


I think @as-cii and @nathansobo helped with the last electron upgrade and might have some insight on these failures?

**Comment by swrobel** [comment]
Interesting to know that the electron & atom teams are now two separate entities. I always figured they were one in the same. Regardless, looking forward to this upgrade!

**Comment by yzgyyang** [comment]
Looking forward to this upgrade. How's it going?

**Comment by jasonrudolph** [comment]
Now that #17273 has merged, we're running on Electron 2.0.0, so I'm gonna close this out.

**Pull request closed without merging**
