### PR TITLE
Upgrade to Electron 0.30.7

### PR DESCRIPTION
**Pull request by kevinsawicki**
Upgrades Electron to prevent a file handle leak on Windows and an uncaught exception when reading an invalid path in the `.asar` archives.

Refs https://github.com/atom/electron/issues/2871
Closes https://github.com/atom/atom/issues/8834
Closes https://github.com/atom/atom/issues/8882
Closes https://github.com/atom/tree-view/issues/580
Closes https://github.com/atom/settings-view/issues/653

### CODE REVIEW

**Comment by nathansobo** [comment]
Thanks @kevinsawicki for diagnosing this and @zcbenz for addressing it promptly.

**Comment by maxbrunsfeld** [comment]
Yeah, I'm so glad you guys tracked this down. Awesome :sparkles:.

**Pull request merged**
