### PR TITLE
bump up electron + bootstrap versions

### PR DESCRIPTION
**Pull request by z11h**

### CODE REVIEW

**Comment by 50Wliu** [comment]
What is your rationale behind upgrading Bootstrap?

In addition, there is already an Electron PR open at #10983.

**Comment by lee-dohm** [comment]
Thanks for your contribution @ZakariaRidouh. We're not looking to continue our dependency on Bootstrap. We also like to keep our Electron upgrades separate from other things so that we can test independently.

**Comment by ZakariaRidouh** [comment]
@lee-dohm Sure :smile:

Also may I ask what Bootstrap is currently being used for? If nothing why not remove it completely + other unused dependencies? Thanks!

**Comment by lee-dohm** [comment]
It's being used for certain parts of the UI that we haven't been able to take off of Bootstrap yet.

**Pull request closed without merging**
