### PR TITLE
Fix `git-diff` nested repositories REDUX

### LINKED ISSUE #1149: Does not work for Github subfolder within project directory
I develop WordPress plugins and as such my porject directory is then entire WordPress root folder, which means that my github folder is acatually a sub-folder within the wp-content/plugins/ folder.

Is there anyway to get githb.atom.io package to work from a given sub-folder?

### LINKED ISSUE #1835: Git integration doesn't work if .git/ not in top level
*@alexwhitman commented on May 13, 2014, 8:40 AM UTC:*

If the `.git/` directory isn't in the top level directory then git integration doesn't work:

[atom-git](https://cloud.githubusercontent.com/assets/422013/2954963/0ade5726-da7a-11e3-9917-63747fe240ae.png)

*This issue was moved by [rsese](https://github.com/rsese) from [atom/atom#2203](https://github.com/atom/atom/issues/2203).*

### LINKED ISSUE #21630: git-diff: Doesn't detect subfolder as repos
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

If you add a project folder which is not a git repo but it contains folders which are git repos, git diff won't work.
You can get it to work by adding the git repos as project folders, but it should be above the main project folder.

### Steps to Reproduce

1. Create the following tree:
|-- mainFolderWithoutGit
.....|-- someFolderWithGit
..........|-- .git
2. Add mainFolderWithoutGit as a project.
3. Make any changes to any file in someFolderWithGit

**Expected behavior:**

Changes should be detected by git-diff package

**Actual behavior:**

Changes are not detected

**Reproduces how often:**

100%

### Versions

1.52 and 1.53-beta0

### Additional Information

Fixed it here: https://github.com/atom/atom/pull/21631
Corresponding issue in tree-view: https://github.com/atom/tree-view/issues/1366

### PR DESCRIPTION
**Pull request by M3TIOR**
# Identify the Bug

Fixes #21630
Fixes atom/github#1149
Fixes atom/github#1835

Linked PRs:
tree-view: atom/tree-view#1367
tabs: atom/tabs#560
status-bar: aminya/status-bar#4
atom: atom/atom#21631
minimap-git-diff: atom-minimap/minimap-git-diff#31
file-icons: file-icons/atom-fs#9
linter: steelbrain/linter#1715

## Description of the Change
By using atom.project.repositoryForPath function instead of matching the path with added directories, subfolders will get identified.

## Alternate Designs
None.

## Possible Drawbacks
Since atom.project.repositoryForPath is an async function, there maybe a little lag when loading file which already has changes.

## Verification Process
Create two duplicate repositories, one within the other. If `git-diff` shows file changes on any of the nested files, then it cannot be targeting the correct repository and must be targeting an ancestor.

### Release Notes
 * Fixed subfolders of project folders not getting detected as git repositories.

### CODE REVIEW

**Comment by icecream17** [comment]
same as https://github.com/atom/atom/pull/23446?

**Comment by M3TIOR** [comment]
Yeah, I coudn't figure out what was breaking the build when I tried to help implement these changes in the other PR. Lucky for me completely starting over from scratch fixed everything. I included Utkarsh Gupta as a contributor on the fix commit via co-contributors. This also removes the middleman between me and fixing this problem lol. Utkarsh seems distracted and I'd rather not bother them if I don't have to.

**Review by sadick254 — APPROVED** [review]
@M3TIOR Thanks for your contribution. This looks good. 👍

**Comment by ian-bertolacci** [comment]
🎉

**Pull request merged**
