### PR TITLE
Prevent committing `blob-store`

### PR DESCRIPTION
**Pull request by sparanoid**
`blob-store` is accidentally committed to my .atom repo recently: https://github.com/sparanoid/.atom/tree/master/blob-store

I think these files should be avoided.

### CODE REVIEW

**Comment by as-cii** [comment]
@sparanoid: :cool:, thanks so much for submitting this!

**Comment by as-cii** [comment]
Just noticed the specs are failing for a git-related problem. I think it's a false negative caused by a problem we had on master when this PR was first opened: could you rebase this against master so that a new build spawns and we can :shipit:?

**Comment by sparanoid** [comment]
@as-cii now LGTM :D

**Comment by as-cii** [comment]
Thanks, @sparanoid! :balloon:

**Pull request merged**
