### PR TITLE
⬆️ Bump language-css to 0.44.5

### LINKED ISSUE #226: Color for 'cursor' for sass (SCSS) is wrong
_From @Binaryify on July 18, 2017 7:24_

- VSCode Version:1.14.1
- OS Version: 10.12.5
'cursor' had wrong color in SCSS file, but in the css file it had right color
image
image
 The 'cursor' key had the same scope with html tag in the 'scss' file
image
image

_Copied from original issue: Microsoft/vscode#30907_

### LINKED ISSUE #21954: Please update language-css core package version
## Summary

Please update the version of `language-css` used as a core package to the latest `0.44.5`.

## Motivation

 It contains a fix that solves atom/language-sass/issues/226

## Describe alternatives you've considered

None

## Additional context

~~I did try to update the version myself in a forked version of Atom to make a PR, but I can't figure out how to upgrade a core package version.~~

EDIT: Someone showed me how. I'm working on it now.

### PR DESCRIPTION
**Pull request by DeeDeeG**
### Requirements for Contributing a Bug Fix

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only fix an existing bug. To contribute other changes, you must use a different template. You can see all templates at <https://github.com/atom/.github/tree/master/.github/PULL_REQUEST_TEMPLATE>.
* The pull request must update the test suite to demonstrate the changed functionality. For guidance, please see <https://flight-manual.atom.io/hacking-atom/sections/writing-specs/>.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see <https://github.com/atom/.github/tree/master/CONTRIBUTING.md#pull-requests>.

### Identify the Bug

Closes: https://github.com/atom/atom/issues/21954

Closes: https://github.com/atom/atom/pull/21955
(This PR is a re-do of https://github.com/atom/atom/pull/21955)

### Description of the Change

Bumping version of language-css from 0.44.4 to 0.44.5

This includes changes that should fix https://github.com/atom/language-sass/issues/226

### Alternate Designs

None.

### Possible Drawbacks

None.

### Verification Process

CI should pass.

### Release Notes

:arrow_up: language-css 0.44.5 (fixes some incorrect code highlighting)

### CODE REVIEW

**Comment by DeeDeeG** [comment]
I'm seeing this error:

```
CSS property name and value autocompletions
  SASS files
    pseudo selectors
      it CSS property name and value autocompletions SASS files pseudo selectors autocompletes without a prefix
        TypeError: Cannot read property 'length' of null
          at jasmine.Spec.<anonymous> (/Users/runner/work/1/s/node_modules/autocomplete-css/spec/provider-spec.coffee:903:28)
          at jasmine.Spec.args.<computed> (/Users/runner/work/1/s/spec/jasmine-test-runner.coffee:89:27)
```

If anyone knows how to solve it, that would be much appreciated.

**Comment by DeeDeeG** [comment]
Here's the failing line of the failing test in `autocomplete-css`:

https://github.com/atom/autocomplete-css/blob/v0.17.5/spec/provider-spec.coffee#L903

**Comment by DeeDeeG** [comment]
I found the cause of the test failure. This PR in `language-css` broke the `autocomplete-css` test: https://github.com/atom/language-css/pull/127

**Comment by sadick254** [comment]
I am closing this PR we now have https://github.com/atom/atom/pull/22931.

**Pull request closed without merging**
