### PR TITLE
permit any whole number for tabLength

### LINKED ISSUE #8261: Cannot easily specify variable Tab Length
Why does Atom feel the need to choose which tab lengths I'm allowed to use? So many other editors let you specify this value (XCode/ST2/ST3/TW/KE/VisualStudio/even Word). And it's useful for all kinds of random tasks: sometimes I need to view/edit a massive variable-length TSV, so, elsewhere, I just throw my tab length to 40/60/whatever and edit faster than Excel thanks to regexes and [column selection](#2306).

The Tab Length item in the Settings panel should be a field, like Font Size, Line Height, and every other reasonable option: not a dropdown.

### LINKED ISSUE #9147: Long tab lengths fail, and default back to 4
Manually setting the tab length beyond 8, say to `16` or `40`, causes the tab length to become 4. This is true both when set from the user's config file and when specified in the settings of a package. Long tabs are useful for spreadsheet editing, given that neither Excel nor Numbers support multiple cursors or regex-find-replace.

This is indirectly related related to #8261. I can't fathom why Atom moralizes on tab length. Sure, 4-length soft tabs are superior, but there are legitimate reasons for using other permutations.

### PR DESCRIPTION
**Pull request by alexchandel**
Fixes #8261 
Fixes #9147

### CODE REVIEW

**Comment by 50Wliu** [comment]
Do you think there should be a maximum for this?  Would setting a tab length of eg 2000 have any negative performance effects?

**Comment by alexchandel** [comment]
@50Wliu no, [there shouldn't be a maximum](https://en.wikipedia.org/wiki/Zero_one_infinity_rule). There isn't for any other parameter, including line height, and I just tested a tab length of 2000 in ST3 with no issues. Specs?

**Comment by benogle** [comment]
IMO, there should be a max of something like 100 or 200. 

> Specs?

Yes, please.

**Comment by 50Wliu** [comment]
For context, specs: https://github.com/atom/atom/blob/master/CONTRIBUTING.md#specs-styleguide

**Comment by alexchandel** [comment]
@benogle the thing is, there are always use cases where artificial caps are hit. For example, last week I had to do some text work a massive TSV with 512 length tabs; horizontal selection & regexs in ST made the task easy. I'm probably unusual for eschewing clunky spreadsheet programs for text editors, but I'm sure there are other situations. I just don't understand. Why is it so necessary to artificially limit tabs? Just give users the freedom to push the editor.

@50Wliu Could you give me an example of what I should edit in the spec folder? I only see four references to `tabLength` in `spec/config-spec.coffee`.

**Comment by benogle** [comment]
> Why is it so necessary to artificially limit tabs?

Because 99.99% of the time, a huge tab length like that is not what people want. If they did enter something that large, it will have been in error. So I'd rather protect the majority of users than allow this strange edge case.

**Comment by 50Wliu** [comment]
I say that if there's no performance decrease then it might not be necessary to add an upper limit.  I mostly asked in the first place because I remember one issue where someone accidentally made their font size 20000 or something which froze Atom.

**Comment by benogle** [comment]
We can merge this when a spec has been written.

**Comment by alexchandel** [comment]
@benogle Sure. However I don't understand what that entails. Afaik there weren't any specs to begin with. What file should I change?

**Comment by benogle** [comment]
You should add a spec in [text-editor-spec.coffee](https://github.com/atom/atom/blob/master/spec/text-editor-spec.coffee)

**Comment by alexchandel** [comment]
@benogle So around [https://github.com/atom/atom/blob/master/spec/text-editor-spec.coffee#L107](text-editor-spec.coffee#L107), change the 4->8 `tabLength` test to test a larger range of `tabLength`s instead ?

**Comment by benogle** [comment]
Yep, that sounds good.

**Comment by alexchandel** [comment]
So, from L124, something like this?
```coffee
        atom.config.set('editor.tabLength', 8)
        atom.config.set('editor.softWrap', false)
        atom.config.set('editor.softTabs', true)
        atom.config.set('core.fileEncoding', 'macroman')

      waitsForPromise ->
        atom.workspace.open('dir/b').then (o) -> editor2 = o

      runs ->
        expect(editor2.getTabLength()).toBe 8
        expect(editor2.isSoftWrapped()).toBe false
        expect(editor2.getSoftTabs()).toBe true
        expect(editor2.getEncoding()).toBe 'macroman'
        for tab in [5..128]
          atom.config.set('editor.tabLength', tab)
          expect(editor2.getTabLength()).toBe tab
```

**Comment by 50Wliu** [comment]
@alexchandel I think testing every possibility from 5 to 128 seems a bit excessive...how about trying -1 (which should fail and set it to 1), 2, and maybe one or two other numbers?

**Comment by alexchandel** [comment]
@50Wliu Ok like this? And it's ok to leave it in the same `runs` block?
```coffee
        atom.config.set('editor.tabLength', 8)
        atom.config.set('editor.softWrap', false)
        atom.config.set('editor.softTabs', true)
        atom.config.set('core.fileEncoding', 'macroman')

      waitsForPromise ->
        atom.workspace.open('dir/b').then (o) -> editor2 = o

      runs ->
        expect(editor2.getTabLength()).toBe 8
        expect(editor2.isSoftWrapped()).toBe false
        expect(editor2.getSoftTabs()).toBe true
        expect(editor2.getEncoding()).toBe 'macroman'
        atom.config.set('editor.tabLength', -1)
        expect(editor2.getTabLength()).toBe 1
        atom.config.set('editor.tabLength', 2)
        expect(editor2.getTabLength()).toBe 2
        atom.config.set('editor.tabLength', 17)
        expect(editor2.getTabLength()).toBe 17
        atom.config.set('editor.tabLength', 128)
        expect(editor2.getTabLength()).toBe 128
```

**Comment by 50Wliu** [comment]
Maybe separate it out into a different test.  @benogle?

**Comment by alexchandel** [comment]
Would that involve just another
```coffee
waitsForPromise ->
        atom.workspace.open('dir/b').then (o) -> editor2 = o
```
except with `dir/c`?

**Comment by benogle** [comment]
I think adding a couple lines to the current test is fine

**Comment by alexchandel** [comment]
Tests pass after rebase.

**Comment by benogle** [comment]
Thanks! It will be in 1.7. We only do patch releases for regressions and major issues.

**Comment by alexchandel** [comment]
@benogle Since 1.6.0 is still in beta, could it make it there?

**Comment by benogle** [comment]
No, sorry. 1.7 will be in beta next week.

**Pull request merged**
