### PR TITLE
Define npm_config_jobs env variable in build scripts

### PR DESCRIPTION
**Pull request by Aerijo**
### Requirements for Adding, Changing, or Removing a Feature

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must contribute a change that has been endorsed by the maintainer team. See details in the template below.
* The pull request must update the test suite to exercise the updated functionality. For guidance, please see <https://flight-manual.atom.io/hacking-atom/sections/writing-specs/>.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see <https://github.com/atom/.github/tree/master/CONTRIBUTING.md#pull-requests>.

### Issue or RFC Endorsed by Atom's Maintainers

None

### Description of the Change

Adds the `npm_config_jobs` env variable across build scripts that may benefit from it (ones that run `apm install`). This variable is used by node-gyp to compile native code with a number of threads equal to the reported CPU core count. I'm guessing this is mostly responsible for the speedup reported in #21308, and experimentally confirmed it was responsible for most of the speedup in #21303.

It is guarded such that any existing value is used if possible.

### Alternate Designs

The `JOBS` variable is used if `npm_config_jobs` is not defined. However `npm_config_jobs` is less ambiguous and less likely to be set for an unrelated purpose. The `npm_config_*` style is also more consistent with how `apm` and the Azure scripts configure the environment too.

### Possible Drawbacks

1. It is possible for compilers to run out of memory and fail if they try to spawn more threads than can fit in memory. This appears to be primarily a concern for resource constrained devices like Raspberry PI's though. And it can always be controlled by setting the variable explicitly.

2. "Exotic" environments like CI may report more CPU cores available than are actually allowed to be used. This may cause suboptimal performance. ~~This PR currently contains a check for this in the bootstrap script, but it may be removed if the result looks sane.~~
    - [results](https://github.visualstudio.com/Atom/_build/results?buildId=81346&view=results): Linux reported 2, macOS reported 4, cancelled the job before Windows got to bootstrap. Seems like Azure reports the correct core counts though.

### Verification Process

CI passes

### Release Notes

NA

### CODE REVIEW

**Review by aminya — CHANGES_REQUESTED** [review]
Instead of putting this in every single file, you should define it in one common place which is `config.js`.

See my pull request which already includes this.
https://github.com/atom/atom/pull/21308/commits/66739b0abb5a1fc43c88b9dc52093df8fc9c4dc3

**Comment by Aerijo** [comment]
Looks like a related failure:
```
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
```

#### Full error
```
Node:	v12.16.3
Npm:	v6.14.8
Python:	v3.8.5
Installing script dependencies
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\npm\prefix\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\hostedtoolcache\\windows\\node\\12.16.3\\x64\\node.exe" "C:\\npm\\prefix\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\a\1\s\script\node_modules\minidump
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! minidump@0.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the minidump@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\npm\cache\_logs\2020-09-16T15_16_57_373Z-debug.log
child_process.js:651
    throw err;
    ^

Error: Command failed: C:/npm/prefix/npm.cmd --loglevel=error ci
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\npm\prefix\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\hostedtoolcache\\windows\\node\\12.16.3\\x64\\node.exe" "C:\\npm\\prefix\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\a\1\s\script\node_modules\minidump
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! minidump@0.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the minidump@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\npm\cache\_logs\2020-09-16T15_16_57_373Z-debug.log

    at checkExecSyncError (child_process.js:630:11)
    at Object.execFileSync (child_process.js:648:15)
    at module.exports (D:\a\1\s\script\lib\install-script-dependencies.js:11:16)
    at Object.<anonymous> (D:\a\1\s\script\bootstrap:41:1)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer 0a 3e 20 63 6f 72 65 2d 6a 73 40 32 2e 36 2e 31 31 20 70 6f 73 74 69 6e 73 74 61 6c 6c 20 44 3a 5c 61 5c 31 5c 73 5c 73 63 72 69 70 74 5c 6e 6f 64 65 ... 734 more bytes>,
    <Buffer 67 79 70 20 45 52 52 21 20 62 75 69 6c 64 20 65 72 72 6f 72 20 0a 67 79 70 20 45 52 52 21 20 73 74 61 63 6b 20 45 72 72 6f 72 3a 20 60 43 3a 5c 50 72 ... 1070 more bytes>
  ],
  pid: 7328,
  stdout: <Buffer 0a 3e 20 63 6f 72 65 2d 6a 73 40 32 2e 36 2e 31 31 20 70 6f 73 74 69 6e 73 74 61 6c 6c 20 44 3a 5c 61 5c 31 5c 73 5c 73 63 72 69 70 74 5c 6e 6f 64 65 ... 734 more bytes>,
  stderr: <Buffer 67 79 70 20 45 52 52 21 20 62 75 69 6c 64 20 65 72 72 6f 72 20 0a 67 79 70 20 45 52 52 21 20 73 74 61 63 6b 20 45 72 72 6f 72 3a 20 60 43 3a 5c 50 72 ... 1070 more bytes>
}

```

**Comment by aminya** [comment]
No, it's not. It happens randomly on other PRs too.
https://github.visualstudio.com/Atom/_build/results?buildId=81818&view=logs&j=9e553d4d-6360-5a42-fcf6-9ca3e737bdc9&t=5433f756-13c0-5ea0-e043-7761504edb2e&l=16

I believe it is because of using Node 12.16.3 instead of Node 12.4.0
https://github.com/atom/atom/pull/21284

**Review by sadick254 — CHANGES_REQUESTED** [review]
Hey @Aerijo, Thank you for your contribution. This looks good to me. Could you address this comment by @aminya? 
> Instead of putting this in every single file, you should define it in one common place which is `config.js`.

It makes a lot of sense having this check in one place.

**Comment by Aerijo** [comment]
I didn't want the config file to change the environment simply because it was `require`d, but there is no wrapper around child_process that can be used to set the default environment of processes either, so I suppose it's the easiest and least invasive way to consolidate the uses.

**Comment by DeeDeeG** [comment]
If wanting to be more conservative, there could be a `config.setNpmJobsMax()` function exported by config.js that has all the actual logic in it. Or put the function in a tiny single-function `script/lib/set-npm-environment.js` file?

Just proposing that in response to discussion above; Not meaning to really weigh in strongly for that approach, but rather suggest it for consideration. I haven't put much thought into what's best here, and using multi-threaded builds in general seems cool.

**Comment by aminya** [comment]
I don't think making things complex has any benefits here. This is just a simple environment variable setting.

**Review by sadick254 — APPROVED** [review]
Hey @DeeDeeG @Aerijo @aminya Am ok with this as it is. Let keep things simple.

**Review by DeeDeeG — APPROVED** [review]
CI passes, which means the build still works properly.

This theoretically should have zero impact on the final built Atom. So I can't really complain if it works.

Note: I don't see consistent, all-around speed improvements to the CI jobs. I see a mix of faster and slower jobs, with a sample size of one control run and one run with this change. So, I would want to double-check that `npm` and `apm` actually are seeing these config options. And I would say even if merging this it's not a silver bullet for performance. (If it's observably making any difference -- I haven't collected enough data to really say either way, but so far it isn't blowing me away with a huge and unmistakable performance improvement. At least not at my fork.)

**Comment by Aerijo** [comment]
@DeeDeeG This was raised around the time we were looking into improving the CI time, so I was watching the build times on each commit, in particular bootstrapping Linux. I recall it had a normal time of 4--5 minutes, whereas the original timing is in the 5--7 minute range.

WIthout this change:
- [6:48](https://github.visualstudio.com/Atom/_build/results?buildId=96323&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=cccdf131-0893-5d7b-ccea-9ccfc8953f95)
- [5:36](https://github.visualstudio.com/Atom/_build/results?buildId=96150&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=cccdf131-0893-5d7b-ccea-9ccfc8953f95)
- [7:18](https://github.visualstudio.com/Atom/_build/results?buildId=95891&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=cccdf131-0893-5d7b-ccea-9ccfc8953f95)
- [7:20](https://github.visualstudio.com/Atom/_build/results?buildId=95794&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=cccdf131-0893-5d7b-ccea-9ccfc8953f95)
- [6:50](https://github.visualstudio.com/Atom/_build/results?buildId=95761&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=cccdf131-0893-5d7b-ccea-9ccfc8953f95)
- [6:50](https://github.visualstudio.com/Atom/_build/results?buildId=95746&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=cccdf131-0893-5d7b-ccea-9ccfc8953f95)
- [6:58](https://github.visualstudio.com/Atom/_build/results?buildId=95742&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=cccdf131-0893-5d7b-ccea-9ccfc8953f95)
- [7:36](https://github.visualstudio.com/Atom/_build/results?buildId=95699&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=cccdf131-0893-5d7b-ccea-9ccfc8953f95)
- [5:37](https://github.visualstudio.com/Atom/_build/results?buildId=96447&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=cccdf131-0893-5d7b-ccea-9ccfc8953f95)
- [6:43](https://github.visualstudio.com/Atom/_build/results?buildId=96448&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=cccdf131-0893-5d7b-ccea-9ccfc8953f95)
- [6:31](https://github.visualstudio.com/Atom/_build/results?buildId=96449&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=cccdf131-0893-5d7b-ccea-9ccfc8953f95)
- [4:58](https://github.visualstudio.com/Atom/_build/results?buildId=96550&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=cccdf131-0893-5d7b-ccea-9ccfc8953f95)

With this change:
- [4:28](https://github.visualstudio.com/Atom/_build/results?buildId=96434&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=cccdf131-0893-5d7b-ccea-9ccfc8953f95) (this PR)

I was going to add more here, but I haven't seen any other commits with this change included yet and the nightly build restored it's bootstrap from cache. Do you have a link to the runs you've made with this change? I had a look at your fork but it doesn't seem to have pulled this commit yet.

**Comment by DeeDeeG** [comment]
@Aerijo I rebased this PR onto a more-recent commit in `master` branch it, so it ended up with new commit hashes.

- Baseline run https://dev.azure.com/DeeDeeG/b/_build/results?buildId=1017
- Baseline + cherry-picked this PR https://dev.azure.com/DeeDeeG/b/_build/results?buildId=1020

Admittedly almost all the runs are either a lot faster, or the same, or very slightly slower (1-2 minutes slower for a 20 or 30 minute job). Maybe I had accidentally tabbed back and forth in the wrong order and lost track of which numbers were for which branch.

These two runs aren't super scientific, though... I'd have to run it a bunch more times.

I understand that users at home with many multiple cores could probably benefit a lot from this, irrespective of what it does on CI. If there is any consistent regression found for CI, we can look at not setting this config if `process.env.CI` evaluates `true`, and/or we gate it by OS, and/or explicitly un-sett it in certain jobs if the need arises. So if studied properly, whatever regression it might or might not have could be pretty easily managed.

**Comment by lokera07** [comment]
> ### Requirements for Adding, Changing, or Removing a Feature
> * Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
> * The pull request must contribute a change that has been endorsed by the maintainer team. See details in the template below.
> * The pull request must update the test suite to exercise the updated functionality. For guidance, please see https://flight-manual.atom.io/hacking-atom/sections/writing-specs/.
> * After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see https://github.com/atom/.github/tree/master/CONTRIBUTING.md#pull-requests.
> 
> ### Issue or RFC Endorsed by Atom's Maintainers
> None
> 
> ### Description of the Change
> Adds the `npm_config_jobs` env variable across build scripts that may benefit from it (ones that run `apm install`). This variable is used by node-gyp to compile native code with a number of threads equal to the reported CPU core count. I'm guessing this is mostly responsible for the speedup reported in #21308, and experimentally confirmed it was responsible for most of the speedup in #21303.
> 
> It is guarded such that any existing value is used if possible.
> 
> ### Alternate Designs
> The `JOBS` variable is used if `npm_config_jobs` is not defined. However `npm_config_jobs` is less ambiguous and less likely to be set for an unrelated purpose. The `npm_config_*` style is also more consistent with how `apm` and the Azure scripts configure the environment too.
> 
> ### Possible Drawbacks
> 1. It is possible for compilers to run out of memory and fail if they try to spawn more threads than can fit in memory. This appears to be primarily a concern for resource constrained devices like Raspberry PI's though. And it can always be controlled by setting the variable explicitly.
> 2. "Exotic" environments like CI may report more CPU cores available than are actually allowed to be used. This may cause suboptimal performance. ~This PR currently contains a check for this in the bootstrap script, but it may be removed if the result looks sane.~
>    
>    * [results](https://github.visualstudio.com/Atom/_build/results?buildId=81346&view=results): Linux reported 2, macOS reported 4, cancelled the job before Windows got to bootstrap. Seems like Azure reports the correct core counts though.
> 
> ### Verification Process
> CI passes
> 
> ### Release Notes
> NA

**Pull request merged**
