### PR TITLE
Export File and Directory through require('atom')

### PR DESCRIPTION
**Pull request by jessegrosjean**
This exports the pathwatcher File and Directory classes through require('atom').

I think this makes sense since those classes are already publicly documented as part of the [Atom platform API](https://atom.io/docs/api/v0.178.0/Atom), but currently there's no way for a package to require and instantiate them. The alternative is to add the pathwatcher module to my own package, but this seems redundant since File and Directory are already documented as part of the Atom platform.

### CODE REVIEW

**Comment by kans** [comment]
Besides ease of use, atom throws when I add a pathwatcher to my package that is a different version that what atom ships with:

```
Failed to activate package named 'floobits' Error: Module version mismatch. Expected 41, got 43.
    at Error (native)
    at Object.module.(anonymous function) [as .node] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/Users/kans/atom-plugin/node_modules/pathwatcher/lib/main.js:6:13)
    at Object.<anonymous> (/Users/kans/atom-plugin/node_modules/pathwatcher/lib/main.js:207:4)
    at Module._compile (module.js:475:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:138:21)
```

**Comment by izuzak** [comment]
@jessegrosjean Seems like some of your other commits (unrelated to pathwatcher) ended up in this PR.

**Comment by jessegrosjean** [comment]
@izuzak Hum... I haven't worked much with pull requests before and think I messed things up. I'm going to close this request recreate it using a separate topic branch in my fork of atom.

**Comment by jessegrosjean** [comment]
@izuzak Ok, I've recreated this using a separate topic branch here: #6202

**Pull request closed without merging**
