### PR TITLE
Adding install instructions for binary packages

### PR DESCRIPTION
**Pull request by fusion809**
Hi,

In this pull request I am adding install instructions for Atom binary packages built using `script/grunt mkdeb` / `script/grunt mkrpm`. 

Thanks or your time,
Brenton

### CODE REVIEW

**Comment by lee-dohm** [comment]
Can you fix the merge conflicts?

**Comment by jeremyf** [comment]
Ping @fusion809

**Comment by fusion809** [comment]
Not even sure how to fix them. Do you mean the travis issue or the conflicts due to the several changes to the atom repo since I started this pull?

**Comment by aminya** [comment]
> Not even sure how to fix them. Do you mean the travis issue or the conflicts due to the several changes to the atom repo since I started this pull?

Now you can use the Github's UI to fix the conflict issues.
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github

**Comment by sadick254** [comment]
Thank you for your PR!

We haven't gotten a response to the comments above. We still have conflicts on this PR that have not been resolved. I'm going to close this but don't hesitate to reach out if you resolve the conflicts, we'll be happy to reopen the PR.

**Pull request closed without merging**
