### PR TITLE
Remove `isValidDimensions`; add `dimensionsAreOnScreen`

### LINKED ISSUE #6939: Atom always displayed on second screen, regardless whether second screen exist.
### Reproducible Steps
- Use a laptop with docking station connected with dual monitor setup.
- Move atom editor to second screen.
- Quit atom editor.
- Remove laptop from docking station (or use single screen setup).
- Try open atom editor again.
- Atom editor displayed on second screen, regardless whether second screen exist.
- No easy way to force atom to display on first screen.

### Tested Environment
Atom 0.201.0
Windows 7

### LINKED ISSUE #15019: Window dimensions and position not being saved
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom 1.18.0 is not saving window positions on multi-monitor Mac setups, in particular circumstances.

### Steps to Reproduce

1. On a Mac with 2 monitors, arrange them so that the secondary monitor is positioned higher and to the left of the primary monitor, like so: screen shot 2017-07-13 at 5 39 33 pm
2. Open Atom and mentally note the window size and position.
3. Open settings to ensure that "Restore Previous Windows On Start" is set to "always".
4. Move Atom's application window fully onto the secondary monitor, so that the top left corner of it is positioned above the height of the primary window. Optionally, resize the window to be noticeably different than the original size. 
5. Open the Developer tools and enter `atom.getPosition()` into the console.
6. Observe that the current widow position x and y values are both negative, like so: 
screen shot 2017-07-13 at 5 56 51 pm
7. Quit Atom via CMD+Q or via the File menu.
8. Open Atom.

**Expected behavior:** Atom should restore the window position and size due to the "Restore Previous Windows On Start" setting.

**Actual behavior:** The window will open in the position it was in at step 2. 

**Reproduces how often:** 100% (if the above steps are followed)

### Versions

**Atom:**
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

**apm:**
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.10

**MacOS:**
System Version:	macOS 10.12.5 (16F73)
Mac Model Identifier:	MacBookPro13,2 

### Additional Information

The issue appears to be caused by an assumption that window positions are calculated relative to the monitor they reside on, not relative to the primary monitor position. The validation logic is found in the `isValidDimensions` method of `atom-environment.coffee` at line 635:
```
# Returns true if the dimensions are useable, false if they should be ignored.
# Work around for https://github.com/atom/atom-shell/issues/473
    isValidDimensions: ({x, y, width, height}={}) ->
    width > 0 and height > 0 and x + width > 0 and y + height > 0
```
The intent seems to be to prevent saving positions that would place the window outside the viewable area of the monitors, but in our case it generates a false negative due to the way the position data is calculated, and therefore the window position is not saved if your setup is as described above.

### PR DESCRIPTION
**Pull request by icecream17**
### bug

Since a second monitor could have a negative displacement compared to the first monitor, the original logic leads to false negatives.

See #15019

<sup>Keyword for detection: Fixes #15019; Fixes #6939</sup>

__Edit: See [the comment directly below this one](https://github.com/atom/atom/pull/22973#issuecomment-924168285)__

### Explain change

Currently, `isValidDimensions` is used for both checking when validating in storeWindowDimensions and getDefaultWindowDimensions.

But sometimes it returns a false positive for storing window dimensions.
It's impossible to predict whether window dimensions would be invalid in the future, so the use in `storeWindowDimensions` is removed.

For `getDefaultWindowDimensions` it should check whether the window would be on a screen.
For example, if a window was opened on screen 2, then exited, then screen 2 was turned off; the window should reopen on screen 1.

### Possible Drawbacks

none?

I imported `electron.screen`, but maybe there's another way. This was the easiest.
It would probably be better to allow some of the screen to be offscreen.

### Verification Process

Wow, green!

- [ ] add tests (then make ready for review)

### Release notes

<s>Fix false negatives when checking if window dimensions can be stored.</s>
Remove check for whether window dimensions are valid since that was fixed in electron.
Prevent windows from opening offscreen.

### CODE REVIEW

**Comment by sadick254** [comment]
@icecream17  I don't think we need the `isValidDimensions` check anymore. Even when a window is minimized,  `browserWindow.getPosition()` is still able to give correct window dimensions.

```
  storeWindowDimensions() {
    this.windowDimensions = this.getWindowDimensions();
    localStorage.setItem(
      'defaultWindowDimensions',
      JSON.stringify(this.windowDimensions)
    );
  }
```
I would also encourage you to think about what happens when you quit Atom, disconnect the second monitor and reopen Atom from your laptop alone.

Do you mind updating this PR?

**Comment by icecream17** [comment]
I think I understand, the code shouldn't reopen the window in an impossible-to-see location. (Which originally corresponded to a disconnected screen.)

Also my last commit is invalid, since `getDefaultWindowDimensions` calls `isValidDimensions`. So `isValidDimensions` should be reimplemented to check whether the dimensions are visible or not.

(Note: It might take a while for me to code that)

**Comment by sadick254** [comment]
@icecream17 The dimensions will always be valid. The invalid dimensions were a result of a bug in electron where if the window was minimized it returned invalid dimensions. Now, this is not the case since that bug has been fixed on electron. We don't need to reimplement `isValidDimensions`.

**Comment by icecream17** [comment]
I'm not sure how to turn screens on/off. Maybe I should just manually check

**Pull request closed without merging**
