### PR TITLE
Add portable mode on Linux

### PR DESCRIPTION
**Pull request by kevinsawicki**
/cc @raelyard

### CODE REVIEW

**Comment by 50Wliu** [comment]
No way! :heart_eyes:  I thought portable mode was just going to be for Windows :open_mouth:.

**Comment by kevinsawicki** [comment]
> I thought portable mode was just going to be for Windows

Yeah, the plan is to support all platforms, there will be another PR for Mac soon.

**Comment by ryanpcmcquen** [comment]
Nice work! :sparkles:

**Comment by remzr7** [comment]
How does one use the portable mode?

**Comment by raelyard** [comment]
@remzr7 Having a directory sibling to the Atom installation directory called .atom is the trigger for portable mode and that .atom functions as the Atom home directory.  Running atom with the --portable switch will create such a portable .atom home directory if it doesn't already exist.  For instance, if you run Atom from a directory in your Dropbox and execute atom --portable, you'll now have a .atom in your Dropbox that will take your customizations with you.

**Pull request merged**
