### PR TITLE
Update openSUSE dependencies in linux.md

### PR DESCRIPTION
**Pull request by shoelzle**
Packages for openSUSE updated

### CODE REVIEW

**Comment by ryanpcmcquen** [comment]
@shoelzle maybe you could rename this pull request to `Update openSUSE dependencies`, or something more descriptive?

**Comment by lee-dohm** [comment]
@shoelzle Is this something that still needs to be updated? My apologies, but I'm not familiar with openSUSE :frowning:

**Comment by shoelzle** [comment]
@lee-dohm Building tag 1.4.3 without the updated dependency installed works on openSUSE Leap.
Neither rpm-devel nor rpmdevtools need to be installed.

**Comment by lee-dohm** [comment]
Thanks for the follow up! I'm going to go ahead and close this PR then. Thank you for contributing and my apologies for it taking so long for us to follow up on it.

**Pull request closed without merging**
