### PR TITLE
apm upgrade

### PR DESCRIPTION
**Pull request by smashwilson**
:boom: This brings in a prerelease version of apm based on atom/apm#796 to see how horribly it breaks everything. :boom:

#### To verify

apm's test suite is actually fairly comprehensive. Just the same, we should manually verify that major functionality that shells out to or calls into npm still works.

_Test case packages_

* Packages without native dependencies: teletype; atom-lcov
* Packages with native dependencies: atom-ide-ui; hydrogen; latex; github
* Packages with a package-lock.json: git-plus

- [x] macOS
  - [x] apm --version
  - [x] apm install: from atom.io
   - [x] ensure proxy settings are read from `.apmrc`
  - [x] apm install: with native dependencies
  - [x] apm install: from local directory
  - [x] apm install: from git repository
  - [x] apm uninstall
  - [x] apm config
  - [x] apm clean
  - [x] apm dedupe
  - [x] apm rebuild
  - [x] apm publish
- [x] Linux
    - [x] apm --version
    - [x] apm install: from atom.io
    - [x] ensure proxy settings are read from `.apmrc`
    - [x] apm install: with native dependencies
    - [x] apm install: from local directory
    - [x] apm install: from git repository
    - [x] apm uninstall
    - [x] apm config
    - [x] apm clean
    - [x] apm dedupe
    - [x] apm rebuild
    - [x] apm publish
- [x] Windows
    - [x] apm --version
    - [x] apm install: from atom.io
    - [x] ensure proxy settings are read from `.apmrc`
    - [x] apm install: with native dependencies
    - [x] apm install: from local directory
    - [x] apm install: from git repository
    - [x] apm uninstall
    - [x] apm config
    - [ ] ~apm clean~ _broken on master_
    - [x] apm dedupe
    - [x] apm rebuild
    - [x] apm publish

#### To fix

- [x] `(node:82366) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.`

- _Windows_ ~`apm clean` deletes all scoped packages in an infinite loop~ _replicated on master: atom/apm#746_

#### To ship

- [x] Merge atom/apm#796.
- [x] Publish a major version bump release of apm.
- [x] ⬆️ to the non-prerelease version of apm on this branch.

### CODE REVIEW

**Comment by daviwil** [comment]
my body is ready

**Comment by daviwil** [comment]
It seems to be working... :pray:

**Comment by thomasjo** [comment]
@smashwilson I think we need to test some (major) community packages that use native node modules, to verify that they still compile (and run) with the upgrade.

**Comment by smashwilson** [comment]
@thomasjo Absolutely.

Did you have any specific ones in mind that have caused us challenges in the past? I was planning to do a `find ~/.atom/packages -name '*.node'` to find some good candidates.

**Comment by smashwilson** [comment]
It looks like atom-ide-ui uses a few, but they're installed from prebuilts... other than that, atom/github certainly uses keytar...

**Comment by thomasjo** [comment]
@smashwilson I think Nuclide has native stuff? My own [LaTex package](https://atom.io/packages/latex) has a native module dependency, though hardly a major community package.

**Comment by smashwilson** [comment]
[Hydrogen](https://github.com/nteract/hydrogen) uses 0mq which is a native dependency...

```
smashwilson @ hubtop ~/src/atom/apm (aw/massive-npm-version-bumps=)
$ apm install hydrogen
(node:82123) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Installing hydrogen to /Users/smashwilson/.atom/packages ✓
smashwilson @ hubtop ~/src/atom/apm (aw/massive-npm-version-bumps=)
$ find /Users/smashwilson/.atom/packages/Hydrogen/ -name '*.node'
/Users/smashwilson/.atom/packages/Hydrogen//node_modules/zeromq/build/Release/zmq.node
```

**Comment by smashwilson** [comment]
Okay, I've identified a few packages as good test candidates for a variety of criteria. More are always welcome 👍

**Comment by thomasjo** [comment]
@smashwilson Cool. Did you check the PlatformIO ecosystem?

**Comment by smashwilson** [comment]
Nope! 😆 Do we test there? Is there someone we can ping (or a repo we can file an issue on) to check it out?

**Comment by thomasjo** [comment]
I think the main repo is [platformio/platformio-atom-ide](https://github.com/platformio/platformio-atom-ide). Haven't followed the dependency chain all the way, but might be some native modules via [platformio/platformio-node-helpers](https://github.com/platformio/platformio-node-helpers) maybe.

**Comment by thomasjo** [comment]
Just noticed that [git-plus](https://github.com/akonwi/git-plus) has a `package-lock.json` file. Probably a good candidate.

**Comment by smashwilson** [comment]
Oh huh! I just noticed that npm added package dependencies to `package.json` in atom/atom:

```
  "dependencies": {
    "@atom/nsfw": "^1.0.18",
    "@atom/source-map-support": "^0.3.4",
    "@atom/watcher": "1.0.3",
    "about": "https://www.atom.io/api/packages/about/versions/1.10.0/tarball",
    "archive-view": "https://www.atom.io/api/packages/archive-view/versions/0.65.1/tarball",
    "async": "0.2.6",
    "atom-dark-syntax": "https://www.atom.io/api/packages/atom-dark-syntax/versions/0.29.0/tarball",
    "atom-dark-ui": "https://www.atom.io/api/packages/atom-dark-ui/versions/0.53.2/tarball",
    "atom-keymap": "8.2.10",
  }
```

**Comment by smashwilson** [comment]
Here's a preliminary set of performance data based on timing [a bunch of apm commands](https://github.com/smashwilson/apm-benchmarking/blob/master/work-it.js) from a cold cache:

| **Command**| 1.19.0| 1.19.0-0|
| -- | -- | -- |
| [ '--version' ] | 822ms | 686ms _(-136ms)_ |
| [ 'uninstall',  'teletype',  'atom-lcov',  'atom-ide-ui',  'hydrogen',  'latex',  'github',  'git-plus' ] | 16330ms | 11872ms _(-4458ms)_ |
| [ 'install', 'teletype' ] | 5597ms | 4880ms _(-717ms)_ |
| [ 'install', 'atom-lcov' ] | 3637ms | 4281ms _(+644ms)_ |
| [ 'install', 'atom-ide-ui' ] | 25641ms | 19351ms _(-6290ms)_ |
| [ 'install', 'hydrogen' ] | 71410ms | 33564ms _(-37846ms)_ |
| [ 'install', 'latex' ] | 19115ms | 13936ms _(-5179ms)_ |
| [ 'install', 'github' ] | 29325ms | 15613ms _(-13712ms)_ |
| [ 'install', 'git-plus' ] | 16313ms | 10738ms _(-5575ms)_ |
| [ 'install', 'atom/github' ] | 81752ms | 40520ms _(-41232ms)_ |
| [ 'rebuild', 'hygrogen' ] | 1553ms | 1111ms _(-442ms)_ |
| [ 'rebuild' ] | 1524ms | 1160ms _(-364ms)_ |

Not bad, not bad.

**Comment by daviwil** [comment]
That is hella fast, should shave a decent chunk of time off of full Atom builds!

**Comment by smashwilson** [comment]
No regressions detected across all three platforms other than that `apm clean` thing. :tada:

**Comment by daviwil** [comment]
Railcars are rolled...  Perhaps this can be merged on Monday? :)

**Pull request merged**
