### PR TITLE
Only build pushes to master on Appveyor

### PR DESCRIPTION
**Pull request by mnquintana**
To mirror Travis config, refs https://github.com/atom/atom/pull/8110

### CODE REVIEW

**Comment by mnquintana** [comment]
Hmmm, weird that this didn't kick off an Appveyor build – does [that config](https://www.appveyor.com/docs/appveyor-yml) not mean what I think it means? :disappointed:

**Comment by lee-dohm** [comment]
The way that reads to me is that it only builds `master`, since this isn't on `master` yet ... it won't kick off an Appveyor build?

**Comment by mnquintana** [comment]
That's true for branches, but I was expecting Appveyor to still build PRs with this config like Travis does. After looking into it more, it seems that we don't have the setting for building PRs enabled on Appveyor itself (see http://help.appveyor.com/discussions/questions/203-auto-run-tests-on-pull-requests).

**Comment by benogle** [comment]
Yo @mnquintana, whats the status of this?

**Comment by mnquintana** [comment]
So I think someone with admin access on Appveyor needs to flip the switch for allowing builds on PRs

**Comment by joshaber** [comment]
@mnquintana I updated that setting :+1: Wanna make a dummy push to make sure this works?

**Comment by mnquintana** [comment]
@joshaber Looks good, thanks!

**Pull request merged**
