### PR TITLE
Add encoding auto-detection logic

### LINKED ISSUE #24: Default encoding can't be set to 'auto-detect'
The 'Default file encoding' in the prefernces doesn't have 'auto-detect' as a choice.

### PR DESCRIPTION
**Pull request by winstliu**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

This is one out of four parts necessary to move encoding auto-detection logic into core, the other three being https://github.com/atom/node-pathwatcher/pull/120, https://github.com/atom/text-buffer/pull/220, and https://github.com/atom/encoding-selector/pull/42.

Specifically, this PR adds the option in the config schema to turn on encoding auto-detection and sets up the logic to detect the encoding whenever a file is opened.  It does _not_ actually do any detection (that is handled by PathWatcher).  The existing file encoding option is used as a fallback for when auto-detection fails.

This PR should be the third one to be merged, after https://github.com/atom/text-buffer/pull/220.

### Alternate Designs

This design was based on how the existing `setEncoding` and `getEncoding` methods were implemented.  An alternate design would be to move the actual detection logic into atom/atom, though that feels unnecessary.  Furthermore, `detectEncoding` could be changed to `detectAndSetEncoding`, though I think some package authors may want to only detect the encoding.

### Why Should This Be In Core?

We already offer the option to set a default encoding, but the ability to auto-detect the encoding is far more useful for people who regularly work with files with different encodings.

### Benefits

There will be no need to have to manually select the auto-detect option for each file.

### Possible Drawbacks

I can't think of any.

### Applicable Issues

Closes atom/encoding-selector#24
Supersedes and closes #12127

Many thanks to @tinymins for starting the implementation.  Most of my work was based off of his, though unfortunately I couldn't cherry-pick his commit over to my branch because his branch had been deleted.

### CODE REVIEW

**Comment by adammertzenich** [comment]
cool

**Comment by tinymins** [comment]
My branch is still waiting for merge, not been deleted. https://github.com/tinymins/atom/commits/master 😄

**Comment by 50Wliu** [comment]
Well then!  I'm don't remember where exactly I was looking, but the PR branch info displayed as "unknown repository" and opening it in GitHub Desktop didn't do anything.  My apologies!

**Comment by tinymins** [comment]
The PR branch info displayed as "unknown repository", is that means I should create a new PR?

**Comment by 50Wliu** [comment]
It's fine - my PR is slightly different in that it moves the actual logic to text-buffer, whereas yours did it in core.

**Comment by tinymins** [comment]
When will this feature become available in the latest build?

**Comment by 50Wliu** [comment]
When all four portions of this are reviewed and merged.  I do not know when that will happen.

**Comment by 50Wliu** [comment]
Now that I've managed to link Pathwatcher (thanks @Ben3eeE!) I can confirm that all four portions of this PR work as expected.  Opening a cp1255-encoded file automatically sets the encoding to Windows 1255.

**Review by iolsen — APPROVED** [review]

**Comment by Ben3eeE** [comment]
You can edit the file before the encoding is detected. In that case the encoding never updates but the encoding selector shows the detected encoding. /cc: https://github.com/atom/encoding-selector/issues/33.

**Comment by 50Wliu** [comment]
Steps to test:
* link pathwatcher to text-buffer
* link pathwatcher to atom/atom (maybe this isn't needed? not sure)
* link text-buffer to atom/atom
* `apm rebuild` atom/atom
* `apm develop encoding-selector` (or link it, whatever)
* Start Atom in development mode

^ Commenting so that I don't forget how to test this again :P

**Review by nathansobo — CHANGES_REQUESTED** [review]
It seems like this we should just pass an `autoDetectEncoding` option when constructing the buffer and avoid any interaction with this setting in the `TextEditor`.

**Comment by MarcoPixel** [comment]
+1, would love when this issue finally gets fixed :)

Is there an ETA when the required changes will be sent for review?

**Comment by 50Wliu** [comment]
> Is there an ETA when the required changes will be sent for review?

I will try to address them soon, but no, I don't have an ETA.

**Comment by 50Wliu** [comment]
@nathansobo what should happen if the auto-detect setting is switched on after the buffer is constructed?  I think the most sensible option would be to auto-detect all open files, but how would that happen if the option is only passed on buffer construction?  An event hook maybe?

**Comment by nathansobo** [comment]
> @nathansobo what should happen if the auto-detect setting is switched on after the buffer is constructed?

Could you call a method on the buffer to re-detect its encoding? This would basically start over with the same process we perform on load.

**Review by Dhmmi — APPROVED** [review]

**Comment by rafeca** [comment]
Hey! 👋

We have recently started using [`prettier`](http://prettier.io/) and this has caused major style changes on the Atom JS codebase (you can check [the related PR](https://github.com/atom/atom/pull/19391)).

This is good news: now the Atom code is more consistent and it's much easier to re-format the code to follow the code style (now you only need to run `script/lint --fix`).

This change caused conflicts on your PR that we have automatically solved, hope you don't mind 😄

With ❤️, the Atom team.

**Comment by sadick254** [comment]
Hey @50Wliu. Apologies for not looking into this on time. I know this PR has been here for a very long time, during that time Atom has seen a number of changes. Due to the changes, this PR has now become outdated. Is it possible for you to resolve the conflicts?

**Comment by 50Wliu** [comment]
Yes - but I don't recall if this PR is in a mergeable state. It looks like there were still some outstanding concerns that I was unable to address.

**Comment by 50Wliu** [comment]
Resolved to the best of my ability. Might not work though, no idea how this new `update*` logic works vs the `set*` functions I was dealing with back in 2017 😁

**Comment by sadick254** [comment]
@50Wliu Thank you for resolving the conflicts. I will test it out and see if it works, if not suggest any necessary changes to make it work.

**Comment by 50Wliu** [comment]
@sadick254 Looks like the build logs expired; mind re-kicking off CI? I'll see if the failures are something I can easily resolve.

**Comment by sadick254** [comment]
@50Wliu You can view the results of the CI run [here](https://github.visualstudio.com/Atom/_build/results?buildId=116674&view=results)

**Comment by 50Wliu** [comment]
@sadick254 after reviewing this thread, it's clear to me that there's still some unresolved concerns, such as the one from Nathan about doing the detection when constructing the buffer vs doing it in the TextEditor, or the open concerns about redundant IO in the text-buffer PR.

As such, even if I were to fix the CI failures, I don't feel comfortable to have these PRs merged, and I also don't feel like I'm the right person at this point to drive this effort to completion. Sorry :(.

I'll close these PRs but leave the branches active in case you'd like to resurrect them into your own branch.

**Pull request closed without merging**
