### PR TITLE
Updated to New Dependencies.

### PR DESCRIPTION
**Pull request by yoginth**
Updated out of dated and Pinned, out of date to new Stable Dependencies.

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### CODE REVIEW

**Comment by alexandernst** [comment]
Extremely brave

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by alexandernst** [comment]
@50Wliu Just so that @yoginth doesn't feel pushed away and keeps trying to contribute, it might be a good idea to explain why this PR is actually being rejected. 

@yoginth Filling the template is a requirement, but your PR is being rejected because it utterly breaks everything. You blindly updated all dependencies without realising that most of them have incompatible API changes, which require further changes in Atom itself.

**Comment by 50Wliu** [comment]
@alexandernst thanks for the suggestion.  @yoginth I did primarily close this PR because it didn't have the template completed, which is pretty important for a PR that updates eighteen packages that Atom depends on to run.  When updating dependencies, you should give a clear explanation of _why_ you are doing so and _what_ benefits updating will provide.  Any upgrade should also be thoroughly tested to ensure that the possibility of regressions is as small as possible.  Given that Atom didn't even *build* with these changes, this PR is in no shape to be merged.

And yes, the Atom team is aware that many of the dependencies are outdated, and it would definitely be nice to update some of them.  However, they still work, and there are currently higher priorities for the Atom team.  If you would like to take this task on, feel free to do so, but please keep in mind my comments above.  It would probably be safest to update only one dependency at a time.

**Comment by yoginth** [comment]
ok sorry! and thanks for your suggestions!

**Pull request closed without merging**
