### PR TITLE
:memo: Make TextEditor::getBuffer public

### LINKED ISSUE #6224: Make TextEditor::getBuffer public?
See: https://discuss.atom.io/t/how-to-get-cursor-position-as-buffer-offset-one-dimensional-in-chars/15892

Shall we make the [`TextEditor::getBuffer` method](https://discuss.atom.io/t/how-to-get-cursor-position-as-buffer-offset-one-dimensional-in-chars/15892) a public API?

/cc @abe33 @kevinsawicki

### PR DESCRIPTION
**Pull request by lee-dohm**
Fixes #6224

### CODE REVIEW

**Comment by kevinsawicki** [comment]
This makes sense to meet since you can `{TextBuffer} = require 'atom'`.

Any objections @atom/core?

**Comment by thedaniel** [comment]
:+1:

**Comment by kevinsawicki** [comment]
:ship: Thanks @lee-dohm for this

**Comment by lee-dohm** [comment]
You're welcome :grinning:

**Pull request merged**
