### PR TITLE
Update to Electron v0.33.x

### LINKED ISSUE #3593: Crash on Ubuntu when dragging a Firefox window over Atom
Atom Version: 0.129.0
Video of me triggering the bug: http://ara.sh/private/atom-crash.ogv
Reproducible every time.

Environment:
Ubuntu 14.04 (all updates installed as of filing this issue)
Unity desktop environment

Repro steps:
1) Launch atom from the Terminal
2) Open a Firefox window (or use an existing one)
3) Drag the Firefox tab anywhere over the Atom window

Actual behavior:
It crashes

Expected behavior:
Not crash :-)

Additional Information:
The terminal prints out the following after the crash:
```
[7950:0920/180947:ERROR:browser_main_loop.cc(161)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[7950:0920/180947:ERROR:browser_main_loop.cc(189)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
ATTENTION: default value of option force_s3tc_enable overridden by environment.
App load time: 88ms
[7984:0920/180947:INFO:renderer_main.cc(227)] Renderer process started
[7950:0920/180948:INFO:CONSOLE(18)] "Window load time: 778ms", source: /opt/atom/resources/app/src/window-bootstrap.js (18)
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAtom (invalid Atom parameter)'.
  (Details: serial 1360 error_code 5 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

### LINKED ISSUE #7061: Large library size
``` bash
du -hs ~/Library/Application\ Support/com.github.atom.ShipIt/
9.0G
```

And there're 45 update.*\* files inside, 203M each. Seem to be a cleanup issue.

P.S.: Mac OS 10.10.3

### LINKED ISSUE #8508: Atom will not build against iojs 3.2.0+ / node 4
I have commented on the node-runas issue which I believe to be the cause of this, but perhaps it should be a new issue (and will get more exposure here):

```
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:682:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.17
gyp ERR! command "/usr/bin/iojs" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/SBo/atom-1.0.7/build/node_modules/runas
gyp ERR! node -v v3.2.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 3.10.17
npm ERR! argv "/usr/bin/iojs" "/usr/bin/npm" "--userconfig=/tmp/SBo/atom-1.0.7/build/.npmrc" "install" "--loglevel" "error"
npm ERR! node v3.2.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/SBo/atom-1.0.7/build/npm-debug.log
```

Here is the full npm-debug.log: https://gist.github.com/ryanpcmcquen/8e798b2d172b96c5d9ab

And the node-runas issue:

https://github.com/atom/node-runas/issues/11

### PR DESCRIPTION
**Pull request by zcbenz**
Node modules to update:
- [x] runas
- [x] pathwatcher
- [x] nslog
- [x] oniguruma
- [x] git-utils
- [x] spellchecker
- [x] scrollbar-style
- [x] keyboard-layout
- [x] atom-keymap
- [x] first-mate
- [x] scandal
- [x] text-buffer
- [x] apm
- [x] highlights
- [x] ctags

Atom packages to update:
- [x] bracket-matcher
- [x] link
- [x] markdown-preview
- [x] symbols-view
- [x] tree-view
- [x] spell-check

Fixes #8508
Fixes #7061
Fixes #3593

### CODE REVIEW

**Comment by gisenberg** [comment]
I tried to check out the CI failures for git-utils, but Janky is reporting that the repository doesn't exist. Is there a way for me to see what went wrong? I did a local build from this branch, which yielded a bunch of gateway/network connectivity errors that didn't repro on master. 

Also, I have a PR to update scrollbar-style to nan 2.0 over here: https://github.com/atom/scrollbar-style/pull/9

**Comment by mnquintana** [comment]
> I tried to check out the CI failures for git-utils, but Janky is reporting that the repository doesn't exist.

You'll want to take a look at the Travis build instead of Janky: https://travis-ci.org/atom/atom/builds/80163437

**Comment by zcbenz** [comment]
This branch now compiles on all platforms, though we still have many failing specs.

**Comment by as-cii** [comment]
While having a look at the failing specs, I have noticed that this warning messages was logged out:

```
[51599:0922/092254:INFO:CONSOLE(0)] "::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)
```

This could potentially break third party themes in future versions of Chrome so it's something to keep in mind the next time we upgrade electron, although it doesn't block this specific PR.

P.s. awesome work on this, @zcbenz! :sparkles:

**Comment by as-cii** [comment]
I think that code-wise this is good to go! :sparkles: I'll change the label to `needs-review` and test this out for a couple of days.

@zcbenz: do you think there's anything else holding this up?

**Comment by nathansobo** [comment]
I'm noticing that using `cmd-o` to open a file/directory in a new window isn't working for me on OS X. It displays the dialog, but never opens a new window with what I select.

**Comment by nathansobo** [comment]
Also having problems opening an additional window via the `atom` command from the command line.

**Comment by nathansobo** [comment]
Seeing some issues positioning overlay decorations wrong... not *sure* it's this branch but I want to investigate.

**Comment by nathansobo** [comment]
Ugh, specs are hanging on CI after my latest commit. Not sure what's going on there.

Also, I'm noticing that overlay decorations are positioned incorrectly to the right side of longer lines upon first loading a window, but not after reloading it.

**Comment by thomasjo** [comment]
@nathansobo CI failures started after @50Wliu bumped Electron to v0.33.3, so there's likely something broke in either v0.33.2 or v0.33.3. I haven't got time to investigate further right now though, sorry.

**Comment by zcbenz** [comment]
I believe the failing specs are caused by https://github.com/atom/electron/issues/2935.

**Comment by as-cii** [comment]
> I believe the failing specs are caused by atom/electron#2935.

@zcbenz: :clap: Great finding! Do you think we can release a `0.33.4` version with https://github.com/atom/electron/pull/2950?

**Comment by zcbenz** [comment]
> @zcbenz:  Great finding! Do you think we can release a 0.33.4 version with atom/electron#2950?

Sure, will cut a new release today.

**Comment by thomasjo** [comment]
@zcbenz Specs are passing now! :sparkles:

**Comment by thomasjo** [comment]
This seems good to go. Will test a rebased build of this today to hunt for possibly undetected regressions.

**Comment by nathansobo** [comment]
The only thing failing was docs generation, which is fixed on master. Merging this now.

**Comment by thomasjo** [comment]
Nice!

**Pull request merged**
