### PR TITLE
🐛 fix #12187

### LINKED ISSUE #12187: editor:move-to-beginning-of-screen-line moves cursor to the end of the previous line
### Steps to Reproduce
1. Open file with at least one line of text
2. Turn Soft Wrap on, if it's not already
3. Indent line at least once
4. Resize window so line soft wraps
5. Fire `editor:move-to-beginning-of-screen-line` with cursor positioned anywhere on any screen line, except for the first screen line or any other screen line's first character

Soft-wrapped lines with indentation

**Expected behavior:** Cursor moves to beginning of current line

**Actual behavior:** Cursor moves to the end of the previous line
### Versions

OS X 10.11.5
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

### PR DESCRIPTION
**Pull request by WSlatton**
This fixes issue #12187 with the command `editor:move-to-beginning-of-screen-line` when used on indented soft-wrapped lines. I've testing it with soft-wrapping on and off, with no indentation, one level of indentation, and multiple levels of indentation, and it seems to give the expected behavior.

### CODE REVIEW

**Comment by mnquintana** [comment]
Would you mind adding some tests for this? Thanks!

**Comment by WSlatton** [comment]
I added the tests.

**Comment by WSlatton** [comment]
@mnquintana I added the tests.

**Comment by sadick254** [comment]
Hey @WSlatton. Apologies for not looking into this on time. I know this PR has been here for a very long time, during that time Atom has seen a number of changes. Due to the changes, this PR has now become outdated. Is it possible for you to resolve the conflicts?

**Comment by sadick254** [comment]
Thank you for your PR!

We haven't gotten a response to our conflict resolution request. I'm going to close this but don't hesitate to reach out if you have or find time to resolve the conflicts, we'll be happy to reopen the PR.

**Pull request closed without merging**
