### PR TITLE
Fold comment with empty line inside of it (Fix #4140)

### LINKED ISSUE #4140: Collapsing Multi-line comments does not work at all
If I write comments without a empty new line, it works. But if I don't do that, Atom only collapses the part before the new line (instead of the whole comment), like if they were single-line comments (I have to click the two arrows of the multi-line comment to semi-collapse it):

(I' using Atom 144 and my OS is Linux Mint 17)

Before collapsing them - After Collapsing
before collapsing after collapsing2

### PR DESCRIPTION
**Pull request by hakatashi**
I need this fixed and I tried to fix it.

This also changes the behavior of TokenizedLine.isComment(), which is not documented in API docs and I believe this is not harmful... It now treats empty lines inside a block comment (not a single-line comment) as a comment. Thanks.

Fix #4140

### CODE REVIEW

**Comment by 50Wliu** [comment]
Bump-this would be nice to have :).

**Comment by russlescai** [comment]
:+1:

**Comment by itochan** [comment]
:+1:

**Comment by mnquintana** [comment]
Would you mind merging in / rebasing master and fixing the merge conflicts?

**Comment by hakatashi** [comment]
I'll perform rebase tonight.

**Comment by hakatashi** [comment]
@mnquintana everything seems to be ok now.

**Comment by fuckdagamz** [comment]
,,,,,,

0

@ Ok

M??ll Iloilog 
Polo ttseahe your t

What's this mean

**Comment by nathansobo** [comment]
Great improvement. Sorry for the extremely long delay. We have some new members on the team and processes in place to work through valuable PRs like this one more effectively.

I'm awaiting the build status of a merge commit here: https://github.com/atom/atom/compare/fold-comment-with-empty-line

**Comment by nathansobo** [comment]
Merged this via a787eb9674b09d3f9d5dedc3b107d6892a0357dc with conflicts resolved. Thanks a ton @hakatashi!

**Pull request closed without merging**
