### PR TITLE
Update to Electron v0.34.x

### PR DESCRIPTION
**Pull request by winstliu**
Coming right after #8779...I present Electron v0.34! :P
Made this because 0.34 doesn't seem to be a major bump for Atom, and I'd like to get the rest of the 0.33 changes in.

### CODE REVIEW

**Comment by thomasjo** [comment]
At first glance this looks super-promising with zero broken specs etc. I'll be testing this out for the rest of the day. Going to merge at the end of the day unless I encounter any regressions. Thanks @50Wliu :clap:

**Comment by nathansobo** [comment]
Just rebased. Will build and live on this for a bit myself.

**Comment by thomasjo** [comment]
Completely forgot that I was going to merge this. @nathansobo Let's merge this today? I've had zero problems with this branch. Also been running it for a few hours since the rebase you did — experienced zero regressions.

**Comment by nathansobo** [comment]
Thanks for getting this going @thomasjo.

**Pull request merged**
