### PR TITLE
Focus on launch tweaks

### LINKED ISSUE #6828: Annoying behavior: Atom steals window focus during startup
Here's a GIF: http://g.recordit.co/XVdFRbpFRV.gif

After launching Atom from terminal, I clicked on the terminal window to maintain focus, but while Atom was starting, it stole focus (as in the current active window) many times.

It's specially annoying since Atom is slow and I want to use the time it takes to be ready in other activities.

Atom is `0.199.0` on OS X Yosemite.

### PR DESCRIPTION
**Pull request by kevinsawicki**
Only grab focus once when launching instead of multiple times.

Closes #6828

### CODE REVIEW

**Comment by kevinsawicki** [comment]
@mnquintana could you try out this branch when you get a chance?

**Comment by mnquintana** [comment]
Just tested this out – seems good to me :shipit:

**Comment by kevinsawicki** [comment]
> Just tested this out – seems good to me

Thanks! Merging this.

**Comment by maxbrunsfeld** [comment]
Awesome.

**Pull request merged**
