### PR TITLE
Fixed open empty editor on start bug (issue #10623)

### PR DESCRIPTION
**Pull request by Persing**
There seems to be a lot of confusion about the function of the "Open Empty Editor On Start" option in the settings. From what I was able to tell the intent of the option was to open a new blank file for editing if when Atom starts if there are no files open. In my build of the current master branch this option has no effect. I have modified the function according to these assumptions. Because many people expected this option to open Atom with all previously open files closed. With this demand in mind I made a new menu option for this feature. It works by closing all files that were to be reopened upon launching Atom. When Atom is closed is stores even the unsaved buffers, so on launch with this option checked it will still ask the user if they would like to save the file. 
Here is a link to a screen capture to demonstrate the way the bug fix and new feature work: https://youtu.be/JCFOm3LdLoU

### CODE REVIEW

**Comment by Persing** [comment]
Fixed the style problem that caused the check to fail the last commit

**Comment by seanknox** [comment]
Hey @50Wliu et al, is there anything else needed for this to be accepted aside from fixing the failing spec?

**Comment by 50Wliu** [comment]
@seanknox Someone from the Atom team with experience with this section of the codebase needs to review it.  The team is currently understaffed though so PRs may take some time to get to.

**Comment by sadick254** [comment]
Hey @Persing, I know this has been open for a long time. The feature you are describing on your PR is currently available on the latest release. It was probably fixed a while back. For that reason am going to close this. Let me know in case I misunderstood your proposals on this PR.

**Pull request closed without merging**
