### PR TITLE
Update tree-sitter to 0.19.0

### LINKED ISSUE #966: Incompatible language version 0. Compatibility range 13 through 13.
Hi, I'm generating my grammar with ts-cli >=0.18.x https://github.com/stsewd/tree-sitter-comment/pull/2, build and tests are good, but when generating the wasm file and opening the web interface I get this weird error in the js console.

> Incompatible language version 0. Compatibility range 13 through 13.

Tried with firefox and chromium, same result. With ts-cli <=0.17.x it works. I have another similar grammar where the web interface still works with >=0.18.x, so I'm not sure if there is something with my grammar or if there is a problem with tree-sitter.

Note that the grammar generated with 0.19.x works great in neovim, just the web interface doesn't work

### PR DESCRIPTION
**Pull request by aminya**
### Description

This updates tree-sitter dependency to 0.19.0

### Benefits

Allows using new tree-sitter-* packages generated using LANGUAGE_VERSION 13. This includes all the tree-sitter packages such as tree-sitter-python 0.19.2.

Fixes https://github.com/tree-sitter/tree-sitter/issues/966 for Atom.

### Drawbacks 
None

### Release notes
- update tree-sitter to 0.19.0

### CODE REVIEW

**Comment by icecream17** [comment]
The tests themselves depend on language parsers: https://github.com/atom/atom/blob/master/spec/text-editor-spec.js#L19

**Comment by aminya** [comment]
We should probably regenerate all the parsers or ask @maxbrunsfeld to do so in their packages.

**Comment by BonaBeavis** [comment]
I want to add language support for turtle and sparql and this is currently blocking. Is there a timeline? Or a guide how to build the parsers to target different tree-sitter versions?

**Comment by claytonrcarter** [comment]
So will all of the language packages that have a tree sitter parser need to depend on tree-sitter 0.19, or can a package still work if it depends on an older version of tree-sitter?

**Comment by mr-martian** [comment]
tree-sitter parsers don't have tree-sitter as a dependency. tree-sitter compiles the grammar to C and has an ABI version for which Atom currently supports versions 9-12, but any tree-sitter grammar which has been edited since February 25, 2021 is most likely on ABI 13.

**Comment by claytonrcarter** [comment]
OK, thanks for clearing that up, but the main point still stands (just worded differently 😄): will all of the language packages that have a tree sitter parser need to be regenerated for ABI 13 or can a package still work w/ tree sitter 0.19 if it was generated for ABI 9-12? (I'm just trying to figure out if there's a way to unblock this and/or help it move forward.)

**Comment by sadick254** [comment]
This has now been superseded by https://github.com/atom/atom/pull/23068. Please subscribe for updates there.

**Pull request closed without merging**
