### PR TITLE
:art: :green_heart: Fixed the test script.

### PR DESCRIPTION
**Pull request by jussi-kalliokoski**
Also removed duplicated logic to run grunt.

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
Could you explain what bug you fixed in the script? Thanks!

**Comment by jussi-kalliokoski** [comment]
Yes, so the test script didn't find grunt:

```
Node: v0.10.33
npm: v2.5.1
Installing build modules...
Installing apm...
Installing modules ✓
Deduping modules ✓
/bin/sh: node_modules/.bin/grunt: No such file or directory
```

(because `grunt` is located in `build/node_modules/.bin/grunt` instead) nor the gruntfile.

**Comment by izuzak** [comment]
@maxbrunsfeld I was just looking at this I think this makes sense. The actual bug is in [this line](https://github.com/atom/atom/pull/6246/files#diff-0e2bc0f03fe54e5e0fff129205e6ee92L8) -- it's trying to run grunt from `node_modules/.bin/grunt`, instead of `build/node_modules/.bin/grunt`. I _think_ that should have been updated as a part of https://github.com/atom/atom/pull/1145.

The other changes are refactoring.

**Comment by maxbrunsfeld** [comment]
This looks good to me. Thanks for the fix, @jussi-kalliokoski!

**Comment by izuzak** [comment]
@kevinsawicki just wondering if you have any :thought_balloon: on this fix+refactoring before it's merged -- you've been maintaining these scripts and making sure things are working as smooth as possible. :blue_heart:

**Comment by kevinsawicki** [comment]
Very cool, thanks for fixing this :ship:

**Comment by jussi-kalliokoski** [comment]
:+1: :tada:

**Pull request merged**
