### PR TITLE
Change select-to-end-of-line to work like move-to-end-of-line

### PR DESCRIPTION
**Pull request by cinnamonKale**
See discussion in atom#7159

### CODE REVIEW

**Comment by nathansobo** [comment]
@lee-dohm can you take a look at this and maybe help it across the 🏁 line? I definitely think it makes sense to have `selectToEndOfLine` match the behavior of `moveToEndOfLine`, but we don't want to behavior of default key bindings.

**Comment by kylesimmonds** [comment]
@nathansobo thanks for the comment. I'm trying to get the build to work locally to test it, but having some issues. See #12120 for all my issues :expressionless:.

That's all to say, I prematurely made this pull request without testing it locally first. I definitely welcome any help with this, but I also don't want to waste anyone's time with something I may need to work out myself.

**Comment by lee-dohm** [comment]
@kylesimmonds There are a few things that need to happen all at the same time in this PR:

* [x] `TextEditor.moveToEndOfLine` and `TextEditor.selectToEndOfLine` need to work the same
* [ ] Create a `TextEditor.selectToEndOfScreenLine` function that works the way `TextEditor.selectToEndOfLine` works currently
* [ ] Write specs for the above
* [ ] Create an `editor:select-to-end-of-screen-line` command that calls the new `TextEditor.selectToEndOfScreenLine` function
* [ ] Map all keybindings that currently map to `editor:select-to-end-of-line` to the new `editor:select-to-end-of-screen-line`

**Comment by kylesimmonds** [comment]
As I stated in the new PR, I completely screwed up my local repo and just started over. New PR is here: atom/atom#12186

**Pull request closed without merging**
