### PR TITLE
Upgrade electron to 1.7.10

### LINKED ISSUE #15696: 1.20.0: Popup jump when using macOS Chinese IME
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
The popup panel will jump from top left corner to the bottom of current line when using Chinese pinyin IME(includes macOS built-in and squirrel and others).

It should keep under the bottom of current line.

### Steps to Reproduce
1. Open Atom (1.20.0)
2. Choose a Chinese IME
3. Try to input something

image

You can see more [here](https://github.com/atom/atom/issues/14911#issuecomment-330604185) and [here](https://github.com/atom/atom/issues/14911#issuecomment-330606144)

**Expected behavior:** The popup should keep under current line, not jump from top left corner.

**Actual behavior:** The popup jump from top left corner when try to type something.

**Reproduces how often:** Every time

### Versions
Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.14.1

### Additional Information
This issue has already discussed [here](https://github.com/atom/atom/issues/14911#issuecomment-330472422)

### LINKED ISSUE #15737: Font Rendering issue with freetype 2.8.1
### Prerequisites

* [X ] Put an X between the brackets on this line.

### Description

The fonts are looking strange,
I tried to reinstall atom three times (including the .atom directory) manually,
Tried to run on safe mode, development mode, and disabled gpu.

### Steps to Reproduce

1. Install Northen Dark Syntax And UI Themes.
2. Use Them.
3. Restart atom and see.

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

OS: Void Linux x86_64
Model: H55M-D2H
Kernel: 4.12.13_1
Shell: zsh 5.4.2
Resolution: 1920x1080
CPU: Intel i3 540 (4) @ 3.059GHz
GPU: NVIDIA GeForce GTX 650
Memory: 7915MiB

apm --version:
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.14
git 2.14.1

atom --version:
Atom    : 1.20.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information
2017-09-24-204828_1920x1080_scrot

### PR DESCRIPTION
**Pull request by leroix**
☝️ 

Fixes #15696
Fixes #15737

### CODE REVIEW

**Comment by leroix** [comment]
I think there are going to be a few failing tests that we'll need to figure out. That's what I'm seeing locally. Overall, it doesn't look too bad.

**Comment by leroix** [comment]
I realized later that this is still failing when run in standard mode (non-dev).

**Comment by leroix** [comment]
I've been narrowing down the cause of the crashes, and I've gotten down to this diff:

~~~diff
diff --git a/src/config.coffee b/src/config.coffee
index b8bf8a7..67b00d3 100644
--- a/src/config.coffee
+++ b/src/config.coffee
@@ -1064,7 +1064,7 @@ class Config
         continue unless scopeSchema.hasOwnProperty('default')
         scopedDefaults[scope] = {}
         setValueAtKeyPath(scopedDefaults[scope], keyPath, scopeSchema.default)
-      @scopedSettingsStore.addProperties('schema-default', scopedDefaults)
+        #@scopedSettingsStore.addProperties('schema-default', scopedDefaults)
 
     if schema.type is 'object' and schema.properties? and isPlainObject(schema.properties)
       keys = splitKeyPath(keyPath)
@@ -1140,7 +1140,7 @@ class Config
 
     settingsBySelector = {}
     settingsBySelector[selector] = value
-    @scopedSettingsStore.addProperties(source, settingsBySelector, priority: @priorityForSource(source))
+    #@scopedSettingsStore.addProperties(source, settingsBySelector, priority: @priorityForSource(source))
     @emitChangeEvent()
 
   getRawScopedValue: (scopeDescriptor, keyPath, options) ->
diff --git a/src/package-manager.js b/src/package-manager.js
index 17a5f22..a4d5a8a 100644
--- a/src/package-manager.js
+++ b/src/package-manager.js
@@ -511,7 +511,7 @@ module.exports = class PackageManager {
 
     pack = metadata.theme ? new ThemePackage(options) : new Package(options)
     pack.preload()
-    this.preloadedPackages[packageName] = pack
+    //this.preloadedPackages[packageName] = pack
     return pack
   }
~~~

**Comment by leroix** [comment]
Lately, I've been modifying the startup script "out/startup.js" directly, creating a new snapshot, and starting up Atom to debug the crashes.

To create a new snapshot:
```
./script/node_modules/electron-mksnapshot/bin/mksnapshot out/startup.js --startup_blob out/Atom.app/Contents/Frameworks/Electron\ Framework.framework/Resources/snapshot_blob.bin
```

The feedback loop is a bit faster.

**Comment by leroix** [comment]
Note: commenting out the package preload stops the crashes i.e.

```js
//pack.preload()
//this.preloadedPackages[packageName] = pack
```

**Comment by leroix** [comment]
Yet another twist:

In the atom repo with a snapshot blob from `./script/build`:
```
$ npm install electron@1.7.9
$ cp out/Atom.app/Contents/Frameworks/Electron\ Framework.framework/Resources/snapshot_blob.bin './node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/snapshot_blob.bin'
$ ./node_modules/electron/cli.js out/app/src/main-process/main.js
```
You should see Atom load without crashing.

**Comment by leroix** [comment]
I've narrowed things down a bit further. If I made the following changes in "./out/startup.js" and create a new snapshot, Atom does not crash:

Comment out this line:
```
//this.preloadedPackages[packageName] = pack
```

Change the parse function in atom-slick to:
```
     var parse = function(expression){
          if (expression == null) return null
          //expression = ('' + expression).replace(/^\s+|\s+$/g, '')
          expression = ('').replace(/^\s+|\s+$/g, '')
          return cache[expression] || (cache[expression] = new Expressions(expression))
      }
```

Then, I create a new snapshot and run Atom:
```
$ ./script/node_modules/electron-mksnapshot/bin/mksnapshot out/startup.js --startup_blob ./out/Atom.app/Contents/Frameworks/Electron\ Framework.framework/Resources/snapshot_blob.bin && ./out/Atom.app/Contents/MacOS/Atom .
```

**Comment by leroix** [comment]
I found another patch that doesn't crash. Besides all the language packages (no idea why those are causing crashes), it only removes two packages (github and whitespace).

~~~diff
diff --git a/package.json b/package.json
index cca8ea9..e1df733 100644
--- a/package.json
+++ b/package.json
@@ -109,7 +109,6 @@
     "exception-reporting": "0.42.0",
     "find-and-replace": "0.215.0",
     "fuzzy-finder": "1.7.3",
-    "github": "0.8.3",
     "git-diff": "1.3.6",
     "go-to-line": "0.32.1",
     "grammar-selector": "0.49.8",
@@ -134,41 +133,13 @@
     "tree-view": "0.221.3",
     "update-package-dependencies": "0.13.0",
     "welcome": "0.36.6",
-    "whitespace": "0.37.5",
     "wrap-guide": "0.40.3",
-    "language-c": "0.58.1",
     "language-clojure": "0.22.5",
-    "language-coffee-script": "0.49.3",
-    "language-csharp": "0.14.3",
-    "language-css": "0.42.8",
-    "language-gfm": "0.90.2",
-    "language-git": "0.19.1",
-    "language-go": "0.44.3",
-    "language-html": "0.48.3",
     "language-hyperlink": "0.16.3",
-    "language-java": "0.27.6",
-    "language-javascript": "0.127.7",
-    "language-json": "0.19.1",
-    "language-less": "0.34.1",
-    "language-make": "0.22.3",
     "language-mustache": "0.14.4",
-    "language-objective-c": "0.15.1",
-    "language-perl": "0.38.1",
-    "language-php": "0.42.2",
-    "language-property-list": "0.9.1",
-    "language-python": "0.45.5",
-    "language-ruby": "0.71.4",
     "language-ruby-on-rails": "0.25.2",
-    "language-sass": "0.61.3",
-    "language-shellscript": "0.25.4",
-    "language-source": "0.9.0",
-    "language-sql": "0.25.8",
     "language-text": "0.7.3",
-    "language-todo": "0.29.3",
-    "language-toml": "0.18.1",
-    "language-typescript": "0.2.3",
-    "language-xml": "0.35.2",
-    "language-yaml": "0.31.1"
+    "language-todo": "0.29.3"
   },
   "private": true,
   "scripts": {
diff --git a/src/initialize-application-window.coffee b/src/initialize-application-window.coffee
index f8f670c..ec5469b 100644
--- a/src/initialize-application-window.coffee
+++ b/src/initialize-application-window.coffee
@@ -29,7 +29,7 @@ if global.isGeneratingSnapshot
   require('dalek')
   require('find-and-replace')
   require('fuzzy-finder')
-  require('github')
+  #require('github')
   require('git-diff')
   require('go-to-line')
   require('grammar-selector')
@@ -54,7 +54,7 @@ if global.isGeneratingSnapshot
   require('tree-view')
   require('update-package-dependencies')
   require('welcome')
-  require('whitespace')
+  #require('whitespace')
   require('wrap-guide')
 
 clipboard = new Clipboard
~~~

**Comment by 50Wliu** [comment]
All the whitelisted languages don't contain a settings folder, except for language-clojure.

**Comment by macrozone** [comment]
electron 1.7.10 has been released which seems to fix a problem with nvidia graphic cards on mac os high sierra. Maybe we could update to 1.7.10 directly instead of 1.7.9

**Comment by as-cii** [comment]
Okay, I think this might be ready for a test drive. 

I have fixed the failing tests and, along with @nathansobo and @leroix, we finally figured out why snapshots were making Atom crash during startup (see https://github.com/electron/electron/issues/11387 for all the details). The good news there is that it was a bug in V8 which is already fixed on V8 6.3 and we just have to wait until a version of Electron that embeds such version gets released (presumably Electron 1.9 or later).

@ungb @rsese @Ben3eeE @50Wliu: can you help us test this pull-request? After a cursory look everything _seems_ reasonable. I briefly tested the IME interaction and it seemed to work correctly, although I'd love to get a more thorough QA pass on that, especially since I have removed some workarounds that we added specifically for Chrome 56 in 69799d3.

**Comment by ungb** [comment]
For the following test, it seems that the `l` character resolves to `-` and doesn't seem to resolve to the keybinding.  For h,j,k, this works correctly.

### Key binding with composition characters are ignored https://github.com/atom/atom/issues/15189
**macOS:**

**This should be tested on macOS**
#### Steps to repro:
1. Open your keymap.cson file and add the following:
```cson
# general
'atom-text-editor':
# use jkl; vim-like when pressing alt (word by word, paragraph by paragraph)
# or alt (letter by letter)
  'alt-h': 'core:move-left'
  'alt-j': 'core:move-down'
  'alt-k': 'core:move-up'
  'alt-l': 'core:move-right'
```
2. Save keymap.cson and reload atom.
1. Try the new keymappings under `ABC - Extended` keyboard layout

**Expected**: the keybindings work

**Issues we've seen:** it types out the modified keys and ignores the key mapping



I've tried stable and it seems to be the same behavior so this isn't a regression I suppose.

**Pull request merged**
