### PR TITLE
atom/watcher upgrade

### PR DESCRIPTION
**Pull request by smashwilson**
Upgrading `@atom/watcher` to 1.0.8 appears to consistently break the npm we bundle within apm:

```
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/distiller/atom/node_modules/.staging/abbrev-6970c326' -> '/Users/distiller/atom/node_modules/@atom/watcher/node_modules/abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/distiller/atom/node_modules/.staging/abbrev-6970c326' -> '/Users/distiller/atom/node_modules/@atom/watcher/node_modules/abbrev'
```

I _suspect_ the solution may be "upgrade npm in apm".

### CODE REVIEW

**Comment by sstt011** [comment]
Doesn't fix... same error.

**Comment by smashwilson** [comment]
Grrr.

```
Node:	v8.9.3
Npm:	v5.3.0
Installing script dependencies
Installing apm
npm ERR! path /Users/distiller/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/abbrev
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/distiller/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/abbrev' -> '/Users/distiller/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/.abbrev.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/distiller/.npm/_logs/2018-07-30T13_28_20_673Z-debug.log
child_process.js:624
    throw err;
    ^

Error: Command failed: /Users/distiller/atom/script/node_modules/.bin/npm --global-style --loglevel=error install
```

I'm guessing we also need to update the version of `npm` we're installing in `script/`. 🤔

**Comment by daviwil** [comment]
Weird, I never noticed that we're installing a specific npm version in there.  Can we get rid of that now since I think we only did it to fix issues on AppVeyor?

https://github.com/atom/atom/pull/15041

**Comment by smashwilson** [comment]
It looks like that `npm` installation is used to install apm and (somehow?) other `script/` dependencies?

Let's at least bump it and see if that solves the bootstrapping problem... if not, I can investigate getting rid of it and using system npm for simplicity.

**Pull request merged**
