### PR TITLE
Drop libgconf dependency for electron7+

### PR DESCRIPTION
**Pull request by mfonville**
Drop the libgconf debian packaging dependency. Not necessary for Electron 7 and higher. See for more information https://github.com/atom/atom/issues/21422#issuecomment-702402584

### CODE REVIEW

**Comment by aminya** [comment]
You should also remove it from here: https://github.com/atom/atom/blob/f1b0e3b47b30ed9379821b341b3337696b8a2a12/script/vsts/platforms/templates/preparation.yml#L7

**Comment by mfonville** [comment]
Thanks, will do!

**Comment by mfonville** [comment]
@sadick254 I think you can merge this in your branch :-)

**Review by sadick254 — APPROVED** [review]
Looks good.

**Pull request merged**
