### PR TITLE
Upgrade to Electron 3.0

### LINKED ISSUE #6666: no mnemonics in menus (File, Edit, ...)
My system:
Linux
Desktop: KDE 4.14.6

In the menus there are any mnemonics shown at all!
(the menu buttons themselves show mnemonics when pressing ALT)
E.g. in File menu:

```
New Window
New File
Open File
...
```

don't show any mnemonics. Also when pressing "ALT" while menu is opened.
Nevertheless, mnemonics seem to be there (but not shown). If I press "n" while in File menu (found out by guessing) Atom opens a new file.

### LINKED ISSUE #17819: Upgrade Atom to Electron 3.0
This is a tracking issue for getting Atom updated to Electron 3.0.  The biggest effort in this migration will likely be updating Atom's native modules to conform to the V8 6.x APIs in Node 10.

- [x] Identify native modules to be updated for Node 10 (code compiles, tests are passing)
  - [x] [`@atom/nsfw`](https://github.com/atom/nsfw)
  - [x] [`cached-run-in-this-context`](https://github.com/atom/cached-run-in-this-context) -- Needs code changes
  - [x] [`fs-admin`](https://github.com/atom/fs-admin)
  - [x] [`git-utils`](https://github.com/atom/git-utils)
  - [x] [`keyboard-layout`](https://github.com/atom/keyboard-layout/)
  - [x] [`node-ctags`](https://github.com/atom/node-ctags)
  - [x] [`node-oniguruma`](https://github.com/atom/node-oniguruma)
  - [x] [`node-pathwatcher`](https://github.com/atom/node-pathwatcher) -- Not building on Windows
  - [x] [`node-keytar`](https://github.com/atom/node-keytar)
  - [x] [`nslog`](https://github.com/atom/nslog)
  - [x] [`scrollbar-style`](https://github.com/atom/scrollbar-style)
  - [x] [`spellchecker`](https://github.com/atom/node-spellchecker)
  - [x] [`superstring`](https://github.com/atom/superstring)
  - [x] [`tree-sitter`](https://github.com/tree-sitter/tree-sitter/)
  - [x] [`tree-sitter-bash`](https://github.com/tree-sitter/tree-sitter-bash/)
  - [x] [`tree-sitter-c`](https://github.com/tree-sitter/tree-sitter-c/)
  - [x] [`tree-sitter-cpp`](https://github.com/tree-sitter/tree-sitter-cpp/)
  - [x] [`tree-sitter-embedded-template`](https://github.com/tree-sitter/tree-sitter-embedded-template/)
  - [x] [`tree-sitter-go`](https://github.com/tree-sitter/tree-sitter-go/)
  - [x] [`tree-sitter-html`](https://github.com/tree-sitter/tree-sitter-html/)
  - [x] [`tree-sitter-javascript`](https://github.com/tree-sitter/tree-sitter-javascript/)
  - [x] [`tree-sitter-python`](https://github.com/tree-sitter/tree-sitter-python/)
  - [x] [`tree-sitter-ruby`](https://github.com/tree-sitter/tree-sitter-ruby/)
  - [x] [`tree-sitter-typesscript`](https://github.com/tree-sitter/tree-sitter-typescript/)
  - [x] [`watcher`](https://github.com/atom/watcher)
- [x] Produce a successful build of the [`electron-3-0`](https://github.com/atom/atom/tree/electron-3-0) branch
- [ ] Run through the Electron upgrade checklist

### LINKED ISSUE #18535: Items in the Menu Bar are invisible on Ubuntu 18.10 when atom window is focused.
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Items in the Menu Bar are invisible on Ubuntu 18.10 when atom window is focused.

### Steps to Reproduce

1. Launch Atom.

**Expected behavior:** Menu Bar items (File, Edit, etc) visible.

**Actual behavior:** Menu Bar items invisible.

**Reproduces how often:** Always.

### Versions
Atom    : 1.33.0
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.33.0
python 2.7.15+
git 2.19.1

Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic

Linux buddy 4.18.0-11-generic #12-Ubuntu SMP Tue Oct 23 19:22:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu is apt-upgraded as of today.

### Additional Information
screenshot from 2018-12-03 13-09-52
screenshot from 2018-12-03 13-11-23

### PR DESCRIPTION
**Pull request by daviwil**
This change upgrades Atom to Electron 3 :electron:.  This gives us (and package authors) access to Chromium 66 and Node 10.

#### Related Issues

Fixes https://github.com/atom/atom/issues/17819.
Fixes https://github.com/atom/atom/issues/6666.
Fixes #18535.

#### TODO

- [x] Fix test failures
- [x] Check to see whether this PR needs to be merged: https://github.com/atom/tabs/pull/552

---

### General testing

- [x] Review issues tagged with [`electron`](https://github.com/search?utf8=%E2%9C%93&q=org%3Aatom+label%3Aelectron+is%3Aopen+is%3Aissue) to see if any of them are fixed
- [x] Verify that you can collaborate with Teletype
	- [x] Host using Atom's current stable release can collaborate with guest using Atom with the new version of Electron
	- [x] Guest using Atom's current stable release can collaborate with host using Atom with the new version of Electron
	- [x] Host and guest can collaborate when both are using Atom with the new version of Electron
  <details>
  <summary>Steps</summary>
	1. Open a file
	1. Share a portal
	1. Have a guest join the portal
	1. When guest edits the text in the file, verify that the host sees those changes
	</details>

#### Text Input/Keybindings

See how to [setup keyboard layouts](https://github.com/atom/maintainers-log/blob/master/how-tos/setup-keyboard-layouts.md).

- [x] IME not working (https://github.com/atom/atom/issues/14911)
	- [x] macOS
	- [x] Windows 10
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Install an IME layout, for example Pinyin simplified  
  1. Open Atom and use the layout you installed as the keyboard layout
  1. Example, if you picked Pinyin simplified type in `zhongwenshuru`

  **Expected:** in Pinyin simplified `中文输入` is expected

  gif

  **Issues we've seen:** Only shows latin first character and not every character typed.

  gif
  </details>

- [x] macOS: Key binding with composition characters are ignored (https://github.com/atom/atom/issues/15189)
  <details>
  <summary>Repro steps</summary>

  1. Open your keymap.cson file and add the following:
      ```cson
      'atom-text-editor':
        # use hjkl; vim-like when pressing alt (word by word, paragraph by paragraph)
        # or alt (letter by letter)
        'alt-h': 'core:move-left'
        'alt-j': 'core:move-down'
        'alt-k': 'core:move-up'
        'alt-l': 'core:move-right'
      ```
  1. Save keymap.cson and reload atom.
  1. Try the new keymappings under `ABC - Extended` keyboard layout

  **Expected**: the keybindings work

  **Issues we've seen:** it types out the modified keys and ignores the key mapping
  </details>

- [x] macOS: Composition characters mess up insertion point (https://github.com/atom/atom/issues/15344)
  <details>
  <summary>Repro steps</summary>

  1. Open keymap.cson and add the following:
      ```cson
      'atom-text-editor':
        'alt-n': 'core:move-down'
        'alt-o': 'core:move-down'
      ```
  1. Have the following in your buffer:
      ```
      Foo
      Bar
      ```
  1. Have the cursor at the beginning of file(before F character) Type alt-n, then arrow right, then insert a character. Observe that the character is inserted at the beginning of the line (where the alt-n left you).
  1. Repeat steps using <kbd>alt-o</kbd> instead of <kbd>alt-n</kbd>.

  **Expected**: Both alt-o and alt-n behave the same

  **Issues we've seen:**
  bug

- [x] Ubuntu: Keystrokes involving <kbd>ctrl</kbd> resolve to the default layout instead of the active layout (https://github.com/atom/atom/issues/13170)

  <details>
  <summary>Repro steps</summary>

  **This should be tested on Linux with gnome**

  1. Install a Linux ditro with gnome, for example Ubuntu
  1. Install French AZERTY and English US QWERTY layouts
  1. Change the default layout to be French AZERTY
  1. Open Atom and switch to English US QWERTY layout
  1. Press ctrl-w

  **Expected**: `core:close` to dispatch (Or the keybinding-resolver to resolve to ctrl-w). Should be resolving to the keyboard layout that is chosen and not the OS default layout.

  **Issues we've seen:** `core:undo` dispatched because it was resolved as ctrl-z because AZERTY has Z where W is on QWERTY.
  </details>

- [x] Other keyboard layouts on new Electron version
  - [x] macOS: ABC - Extended
  - [x] macOS: Slovak
  - [x] macOS: U.S. International
  - [x] macOS: Squirrel (https://github.com/rime/squirrel)
  - [x] macOS: Full-Width Alphanumeric (Google) - Japanese layout  (https://www.google.co.jp/ime/)
  - [x] Windows: U.S.
  - [x] Linux: Pinyin Simplified

#### UI

- [x] tree-view drag image (https://github.com/atom/tree-view/pull/1054)
	- [x] macOS
	- [x] Windows 10
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Open a project in Atom with multiple files and a few folders
  1. Drag a file into a folder

  **Expected:**  
  image

  **Issues we've seen:**

  image
  </details>

- [x] drag-and-drop indicator (https://github.com/atom/tree-view/pull/1055, https://github.com/atom/tabs/pull/426, https://github.com/atom/tabs/pull/437)
	- [x] macOS
	- [x] Windows 10
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Open Atom with a few folder projects on tree-view (you can do this on terminal in a directory that has existing folder and having a space between each folder. Example: `atom folderA folderB folderC`)
  1. Drag and drop all of the folders to reorder them on Atom

  **Expected:**
  The placeholder indicates where the folder/project is being dropped to.

  screen shot 2017-03-29 at 16 31 16

  **Issues we've seen:**
  No placeholder shows up after drag and dropping

  screen shot 2017-03-29 at 16 30 51
  </details>

- [x] Large file rendering (https://github.com/atom/atom/issues/16591)
	- [x] macOS
	- [x] Windows 10
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Open a file that has over one million lines
  1. Scroll down to the bottom

  **Expected:** To not regress the number of lines that can be rendered. Rendering to be correct for lines past a certain point. Atom 1.25  can render around 800k to 1 million lines correctly.

  **Issues we've seen:** Increased number of lines rendered but bad rendering past a certain point

  bad renderer
  </details>

- [x] Loss of subpixel AA when the cursor is at the end of long lines (https://github.com/atom/atom/issues/16889, https://github.com/atom/atom/pull/16595)
	- [x] macOS
	- [x] Windows 10
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Open [text-editor.js](https://github.com/atom/atom/blob/2e19cf4a7c0a4d624b1f9c1072cd292de112cdb0/src/text-editor.js) in Atom
  1. Copy the first 21 lines to a new untitled window
  1. Turn on soft wrapping and change language mode to javascript
  1. Resize the Window so it's soft wrapped
  1. On line 15 type `a` until the you reach the end of the window

  **Expected:** To not lose subpixel AA

  **Issues we've seen:** Loss of subpixel AA. Both when soft wrapping was [enabled](https://github.com/atom/atom/pull/16943) and [disabled](https://github.com/atom/atom/pull/16595).

  subpixel aa loss softwrap
  </details>

- [x] Scrolling horizontally shift + scroll wheel (https://github.com/atom/atom/pull/12696#issuecomment-288615912)
	- [x] macOS
	- [x] Windows 10
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Open a file that has long lines
  1. Turn off soft wrapping and resize the window so you have a horizontal scrollbar
  1. Press shift and scroll in both directions using the mouse wheel

  **Expected:** File to scroll horizontally in both directions

  **Issues we've seen:** File does not scroll horizontally at all in any direction
  </details>

- [x] Scrollbars misbehaving on the first file that is opened (https://github.com/atom/atom/pull/12696#issuecomment-251299649)
  <details>
  <summary>Repro steps</summary>

  1. Open Atom
  1. Open some file that has content enough to have a vertical scrollbar
  1. Close Atom
  1. Open Atom and look at the vertical scrollbar

  **Expected:** Scrollbar to be visible

  **Issues we've seen:** Scrollbar is not visible and is flickering when you are editing
  </details>

- [x] Middle clicking on unsaved tab (https://github.com/atom/atom/issues/15197)
	- [x] macOS
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Open Atom and open a new unsaved file.
  1. Make edits to the unsaved file and middle click on the tab.

  **Expected:**
  Clicking save/cancel or the options on the dialog works.

  **Issues we've seen:**
  The UI and the dialog is unable to receive mouse clicks. You can still choose options via Keyboard, but not mouse.
  </details>

- [x] Linux: Atom scrolls even when not focused (https://github.com/atom/atom/issues/15482)
  <details>
  <summary>Repro steps</summary>

  1. Open Atom with a large enough file that has a scrollbar
  1. Open a different application and place it over the Atom window
  1. Scroll with the mouse inside the other window
  1. Focus the Atom window

  **Expected:** Atom window should keep the original scroll position

  **Issues we've seen:** The Atom window scrolls after it is focused
  </details>

#### Other

- [x] Deprecation warnings (https://github.com/atom/atom/pull/12696#issuecomment-288871751)
	- [x] macOS
	- [x] Windows 10
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  **This should be tested on macOS, Linux and Windows with community packages installed**

  1. Open Atom
  1. Open the Developer tools console on the master branch and check for deprecation warnings
  1. Open the Developer tools console on the electron upgrade branch and check for deprecation warnings
  1. Compare the two outputs

  **Expected:** No new deprecation warnings

  **Issues we've seen:** New deprecation warnings both from core and community packages
  </details>

- [x] Supported Versions of OS (https://github.com/atom/atom/issues/15297)
	- [x] macOS
	- [x] Windows 10
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Check the list of supported platforms [Electron Master](https://github.com/electron/electron/blob/master/docs/tutorial/supported-platforms.md)
  1. Check what version is listed as minimum for each platform on https://atom.io and https://atom.io/faq

  **Expected:** https://atom.io and https://atom.io/faq to display the same versions as the Electron documentation

  **Issues we've seen:** macOS version support changed and https://atom.io and https://atom.io/faq was not updated
  </details>

- [x] macOS : Native tabs (https://github.com/atom/atom/pull/14711)
  <details>
  <summary>Repro steps</summary>

  1. Open two atom windows on mac
  1. Go to View in menus and check `Show Tab Bar`
  screen shot 2017-06-03 at 5 10 32 pm
  1. Do this for both Atom windows.
  1. Drag one atom window to the other via tab bar

  **Expected:**
  Native Tab bar shows up and able to drag different windows to each other.  Also make sure UI isn't messed up.

  **Issues we've seen:**
  Native Tab Bar doesn't work and messes up UI when enabled
  </details>

- [x] Ubuntu with KDE: Menu uses 100% CPU (https://github.com/electron/electron/issues/8455, https://github.com/atom/atom/issues/13885)
  <details>
  <summary>Repro steps</summary>

  1. Install Atom on Ubuntu KDE. [[instructions](https://linuxconfig.org/how-to-install-kde-plasma-desktop-on-ubuntu-18-04-bionic-beaver-linux)]
  1. Enable KDE plasma global menu: Right-click on the desktop -> Add Panel => Application Menu Bar. [[demo](https://youtu.be/qo5fhiXAUbI)]
  1. Start Atom.
  1. Try to use the desktop menu.

  **Expected:**
  Desktop menu items work

  **Issues we've seen:**
  Desktop menu items do nothing when you click on things.
  </details>

- [x] macOS: Slovak QWERTZ (https://github.com/atom/atom-keymap/issues/223)
  <details>
  <summary>Repro steps</summary>

  1. Install Slovak keyboard layout on mac
  1. Open keyboard viewer to see the keys are are suppose to show up and open keyboard resolver on atom.
  1. hit `cmd+'`.

  **Expected:**  Resolves to `cmd+'` like it shows on keyboard viewer on mac.

  **Issues we've seen:** It resolves to `ctrl+§`
  </details>

- [x] macOS: IME jump (https://github.com/atom/atom/issues/15696)
  <details>
  <summary>Repro steps</summary>

  1. Install an IME layout, for example Chinese pinyin
  1. Type one character

  **Expected:**
  Expected the IME to be positioned at under the character you entered
  **Issues we've seen:** The IME window is in the top left corner. When you enter the second character it jumps to be positioned under the text
  </details>

### CODE REVIEW

**Comment by Aerijo** [comment]
Segmentation fault in [this issue](https://github.com/atom/atom/issues/18624). Looks like somethings been deprecated.

**Comment by 50Wliu** [comment]
Deprecations have already been fixed in fs-plus 3.1.1, which is in this PR.

**Comment by ChrisLahaye** [comment]
> Over in Arch Linux, we've been packaging an unofficial electron 3.x package for the past month. Although it mostly works, we did receive a bug report with a proposed resolution that we've forwarded to [atom/tabs#552](https://github.com/atom/tabs/pull/552)

Which package? In the official repository or AUR?

**Comment by eli-schwartz** [comment]
In the official repository:
https://www.archlinux.org/packages/community/x86_64/atom/
https://www.archlinux.org/packages/community/x86_64/electron/
https://www.archlinux.org/packages/community/x86_64/apm/

It's kind of a requirement for entry, since we don't really want to provide packages with large vendored dependencies (especially ones that don't use our packaging CFLAGS etc.) and we have a standalone electron package.

**Comment by Ben3eeE** [comment]
There are some workarounds in `atom-keymap` that we should be able to remove when this is merged.

https://github.com/atom/atom-keymap/blob/81bd7b80ab1a52594500bf62977a5ad61f02ff87/src/helpers.coffee#L218-L222

https://github.com/atom/atom-keymap/blob/81bd7b80ab1a52594500bf62977a5ad61f02ff87/src/helpers.coffee#L231-L232

**Pull request merged**
