### PR TITLE
Stop babel from logging to stderr during compilation

### PR DESCRIPTION
**Pull request by maxbrunsfeld**
Fixes https://github.com/atom/atom/issues/10056
Refs https://github.com/atom-minimap/minimap/issues/426

This stops babel from logging to stderr in the case where the user has the `DEBUG` environment variable set to `*` or `babel`. Babel doesn't have an API (except for the env var) for disabling this logging, so I've monkey-patched its `Logger` class, and created a feature request for adding a programmatic API: https://phabricator.babeljs.io/T6955.

### CODE REVIEW

**Comment by joshaber** [comment]
Amazing. Thanks for digging into that!

**Comment by maxbrunsfeld** [comment]
Ok, that snippets test failure looks unrelated to this change. Gonna :ship: this to get it into v1.5.0-beta0.

**Comment by maxbrunsfeld** [comment]
Made an issue for the flaky snippets spec: https://github.com/atom/snippets/issues/188.

**Comment by abe33** [comment]
Thank you for taking care of that! :bow:

**Pull request merged**
