### PR TITLE
Update Mac icon to be flatter, to work with Yosemite styling

### PR DESCRIPTION
**Pull request by ParkerK**
Yosemite has a much flatter look to it, and all of the default Mac apps have had their icons changed. I updated the Atom icon to fit in with these theme a little better. Any feedback would be appreciated :)

Old: atom
New: f2b4523d650ae78d-64x64

### CODE REVIEW

**Comment by ahmadseleem** [comment]
@kevinsawicki @benogle @nathansobo 
I made these **4** icons:
**https://github.com/ahmadseleem/Atom-Classy-icons**

What do you guys think ?

**I use this personally:** 

**Classy Atom**

alt tag

**Comment by ahmadseleem** [comment]
This icon looks even much better when used  and rendered as an icon.
Try it and you'll see what I mean.

**Comment by batjko** [comment]
Ref: 
https://discuss.atom.io/t/atom-classy-icons-is-what-atom-deserves-for-an-icon/19071/5

**Comment by ahmadseleem** [comment]
If you still prefer green background:

*Greener* is also cool:

alt tag

**Pull request closed without merging**
