### PR TITLE
:memo: Clarify that stack only has an effect if detail is present as well

### PR DESCRIPTION
**Pull request by winstliu**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

Lost quite a bit of time on this until I poked around in notification-element's source code and discovered that supplying `stack` won't do anything unless `detail` is also specified.

### Alternate Designs

Stack could be made independent of detail, but that would require HTML/CSS changes in atom/notifications.

### Why Should This Be In Core?

Documentation change.

### Applicable Issues

Goes hand-in-hand with atom/notifications#148

### CODE REVIEW

**Comment by sadick254** [comment]
Hey @50Wliu. Apologies for not looking into this on time. I know this PR has been here for a very long time, during that time Atom has seen a number of changes. Due to the changes, this PR has now become outdated. Is it possible for you to resolve the conflicts?

**Comment by 50Wliu** [comment]
Yes, of course!

**Comment by 50Wliu** [comment]
7401 commits! That must be a record for me 😄

**Review by sadick254 — COMMENTED** [review]
@50Wliu Thank you for resolving the conflicts. I appreciate your efforts.

**Review by sadick254 — APPROVED** [review]

**Pull request merged**
