### PR TITLE
check if testRunner is es module

### PR DESCRIPTION
**Pull request by UziTech**
### Requirements for Contributing a Bug Fix

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only fix an existing bug. To contribute other changes, you must use a different template. You can see all templates at <https://github.com/atom/.github/tree/master/.github/PULL_REQUEST_TEMPLATE>.
* The pull request must update the test suite to demonstrate the changed functionality. For guidance, please see <https://flight-manual.atom.io/hacking-atom/sections/writing-specs/>.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see <https://github.com/atom/.github/tree/master/CONTRIBUTING.md#pull-requests>.

### Identify the Bug

If the `atomTestRunner` is transpiled by typescript or anything else using `atomTranspilers` into an ES module the test runner will not run.

https://github.com/UziTech/terminal/blob/a116a214b6690390dfa656f61813c0596ba7523e/package.json#L30-L36

### Description of the Change

set `testRunner` to `testRunner.default` if `testRunner.__esModule` is set to `true`;

### Possible Drawbacks

none

### Verification Process

compiled Atom and with this fix and tested the code at https://github.com/UziTech/terminal/tree/custom-runner-ts

### Release Notes

Allow `atomTestRunner` to point to an ES Module

### CODE REVIEW

**Comment by aminya** [comment]
A similar patch is applied for packages in #21112.

**Review by aminya — APPROVED** [review]

**Comment by UziTech** [comment]
That PR seems a lot more robust than this one. Do we want to make that a util function somewhere so we can use it in more places?

**Comment by aminya** [comment]
Sure, I can do that. Do tastRunners have "activate" function too? I did an extra check for the "activate" function in that PR (I assumed all packages have "activate"). If that's not the case. I will drop that extra check.

**Comment by UziTech** [comment]
No `testRunner` should just be a function.

**Comment by UziTech** [comment]
You only need to test for `__esModule === true`. The only reason for a module to have that property is if it wants to be treated like an es module.

**Comment by aminya** [comment]
I added the function. 

Here is how to use it: https://github.com/atom/atom/pull/21112/files#diff-a1e5876f027cf761e7ec01e3a21fd32319f0d64d015915e4595add656077aa7fR11

You should change the target of your PR to my branch I think.

**Comment by sadick254** [comment]
Closing this in favour of https://github.com/atom/atom/pull/21112

**Pull request closed without merging**
