### PR TITLE
Add auto detect encoding option to config.

### PR DESCRIPTION
**Pull request by tinymins**
New feature: Detect file encoding on file opening.

### CODE REVIEW

**Comment by rugk** [comment]
Why not enable this by default?

**Comment by tinymins** [comment]
@rugk I am worrying about if enable it by default will change user's habits?

**Comment by alexandernst** [comment]
The default behavior is broken anyways, so...

**Comment by rugk** [comment]
Yes, I also think all other editors automatically detect the encoding.

**Comment by tinymins** [comment]
@rugk Already set enable as default config. :-)

**Comment by lee-dohm** [comment]
We need some specs before this could be accepted.

**Comment by leo-joseph** [comment]
When this feature will be merged ?

**Comment by sadick254** [comment]
Thank you for opening this PR!

We haven't gotten a response to our comment above from lee-dohm. I'm going to close this but don't hesitate to reach out if you add specs on this PR, we'll be happy to reopen the issue.

**Pull request closed without merging**
