### PR TITLE
Appendable scopes in Tree-sitter grammars

### LINKED ISSUE #20147: Append scopes instead of overriding them in tree-sitter grammars
## Summary

When creating a grammar, there needs to be an option to append scopes instead of overriding them.

## Motivation

When targeting tree-sitter nodes in a grammar file, scopes inevitably get repeated. This makes grammars cumbersome and hard to maintain.

## Describe alternatives you've considered

None.

## Additional context

Consider the following example:

```cson
# Identifier
'identifier': [
  {
    # Match a long list of exceptions
    match: '^(Exception|TypeError|VeryLongListOfExceptions)$',
    scopes: 'entity.class.exception'
  },
  'entity'
]

# Inherited class
'class_definition > argument_list > identifier': [
  {
    # Match a long list of exceptions (again)
    match: '^(Exception|TypeError|VeryLongListOfExceptions)$',
    scopes: 'entity.class.exception.inherited'
  },
  'entity.class.inherited'
]
```

Would be much easier to maintain if scopes were appendable:

```cson
# Identifier
'identifier': [
  {
     # Match a long list of exceptions
    match: '^(Exception|TypeError|VeryLongListOfExceptions)$',
    scopes: 'entity.class.exception'
  },
  'entity'
]

# Inherited class
'class_definition > argument_list > identifier': + 'class.inherited' # Append
```

### PR DESCRIPTION
**Pull request by chbk**
## Issue

Fixes #20147

## Current state

In a Tree-sitter grammar file, the scopes of the most specific selector override other scopes. That leads to many repetitions of identical rules for different selectors. An example:

```cson
'identifier': [
  # Some rules
  {
    exact: 'String',
    scopes: 'entity.type.support' # String
  },
  {
    match: '^[0-9_]*[A-Z]',
    scopes: 'entity.type' # Type
  },
  'entity.variable' # variable
]

'call > identifier': [
  # The same rules
  {
    exact: 'String',
    scopes: 'entity.type.support.constructor.call' # String()
  },
  {
    match: '^[0-9_]*[A-Z]',
    scopes: 'entity.type.constructor.call' # Type()
  }
  'entity.function.call' # function()
]

'attribute > identifier:nth-child(2)': [
  # The same rules again
  {
    match: '^[0-9_]*[A-Z]',
    scopes: 'entity.type.member' # _.Type
  },
  'entity.variable.member' # _.member
]
```

Grammars quickly become convoluted. This PR introduces two features to alleviate this issue.

## New feature: appendable scopes

Appendable scopes start with a period and are simply appended to less specific scopes:

```cson
'identifier': [
  {
    exact: 'String',
    scopes: 'entity.type.support'
  },
  {
    match: '^[0-9_]*[A-Z]',
    scopes: 'entity.type'
  },
  'entity.variable'
]

'call > identifier': '.call' # Append '.call'

'attribute > identifier:nth-child(2)': '.member' # Append '.member'
```

## New feature: "with" rules

The "with" rule matches already applied scopes:

```cson
'identifier': [
  {
    exact: 'String',
    scopes: 'entity.type.support'
  },
  {
    match: '^[0-9_]*[A-Z]',
    scopes: 'entity.type'
  },
  'entity.variable'
]

'call > identifier': [
  {
    with: 'entity.type', # If the token has the scopes 'entity' and 'type'
    scopes: '.constructor.call' # Append '.constructor.call'
  },
  'entity.function.call' # Else, override all previously applied scopes with 'entity.function.call'
]

'attribute > identifier:nth-child(2)': [
  {
    with: 'entity.type.support', # If the token has the scopes 'entity' and 'type' and 'support'
    scopes: 'entity.type.member' # Override all previously applied scopes with 'entity.type.member'
  },
  '.member' # Else, append '.member'
]
```

## Scopes selection logic

Scopes for a token are applied with the following algorithm:
1. Go to the least specific selector.
2. Set `overridable = true`.
3. Go to the first ruleset of the selector.
4. Select the first matching rule, or go to step 7 if there are no matches.
5. If the rule's scopes are appendable, append them to previously applied scopes.
6. Else, if `overridable == true`, override all previously applied scopes, and set `overridable = false`.
7. If there is another ruleset for the selector, continue to that ruleset and go to step 4.
8. If there is a more specific selector, continue to that selector and go to step 2.

When there are no appendable scopes in the grammar, this algorithm outputs the same scopes as before.

### Examples

```cson
# selector: ruleset
'identifier': [
  {
    # rule
    exact: 'String',
    scopes: 'entity.type.support' # String
  },
  {
    # rule
    match: '^[0-9_]*[A-Z]',
    scopes: 'entity.type' # Type
  },
  # rule (default)
  'entity.variable' # variable
]

# selector: ruleset
'attribute > identifier:nth-child(2)': [
  {
    # rule
    with: 'entity.type.support',
    scopes: 'entity.type.member' # _.String
  },
  # rule (default)
  '.member' # _.member
]

# selector, selector: ruleset
'''
call > identifier,
call > attribute > identifier:nth-child(2)
''': [
  {
    # rule
    with: 'entity.type',
    scopes: '.constructor.call' # Type()
  },
  # rule (default)
  'entity.function.call' # function()
]

# selector: ruleset
'call > attribute > identifier:nth-child(2)': {
  # rule
  with: 'entity.function',
  scopes: '.method' # _.method()
}
```

`_.String()` will be scoped:  
`entity.type.support` -> `entity.type.member` -> `.constructor.call` = `entity.type.member.constructor.call`

`_.method()` will be scoped:  
`entity.variable` -> `.member` -> `entity.function.call` -> `.method` = `entity.function.call.method`

#### `src/tree-sitter-grammar.js`

- `scopeSelectors[selector]` is now always an array of rulesets.
- `preprocessScopes()` now translates null/undefined scopes to `'.'` (= append nothing).
- `preprocessScopes()` parses "with" rules.  
- `preprocessScopes()` requires strings for "match", "exact", and "with" rules.  

#### `src/syntax-scope-map.js`

- Changed the switch statement in `addSelector()` to a series of if conditions to avoid code repetition since the linter doesn't allow fallthroughs (cases without breaks).
- Tweaked the structure of `SyntaxScopeMap.namedScopeTable` and `SyntaxScopeMap.anonymousScopeTable`. They are now:
    ```
    table = {
        node: {
            indices: {
                (nth-child number or *): {
                    results: ...,
                    parents: {
                        node: {
                            ...
    ```
    So for example, the selector `a > *:nth-child(3) > b:nth-child(1)` will give this table:
    ```
    namedScopeTable = {
        b: {
            indices: {
                1: {
                    parents: {
                        *: {
                            indices: {
                                3: {
                                    parents: {
                                        a: {
                                            indices: {
                                                *: {
                                                    results: ...
    ```
- Changed `setTableDefaults()` so that results of wildcards are prepended to results of other selectors, and created `setTableResults()` so that results of less specific selectors are prepended to results of more specific selectors. Results are now deep arrays of selectors sorted by specificity and rulesets sorted by order of appearance:
    ```
                       selector                             selector
       |----------------------------------------|   |---------------------|
       |           ruleset           ruleset    |   |       ruleset       |
       |  |----------------------|  |--------|  |   |  |---------------|  |
    [  [  [  rule,  rule,  rule  ], [  rule  ]  ],  [  [  rule,  rule  ]  ]  ]
    ```
- `get()` now returns that deep array.

#### `src/tree-sitter-language-mode.js`

- `applyLeafRules()` now parses a deep array to return a string of scopes.

## Possible Drawbacks

No regressions. Scopes in existing Tree-sitter grammar files are applied like before.

## Verification Process

- Added extensive specs with complex test cases.
- Built atom from this branch and tested the changes in many languages.

## Release Notes

- Allow appendable scopes in Tree-sitter grammars.

### CODE REVIEW

**Review by therobgirl — APPROVED** [review]

**Comment by aminya** [comment]
@jeff-hykin Could you review this?

**Comment by chbk** [comment]
@sadick254 @darangi @maxbrunsfeld Any chance of getting this merged?

**Review by icecream17 — APPROVED** [review]
LGTM

<details>
<summary> Here's a dump of notes I took while staring at the code </summary>

#### `src/syntax-scope-map.js`
(See the original description of changes above)

That's a silly linter error...

I assume the second last change was done in the (switch to if statement) rewrite, but I didn't look too closely there.

The last change seems to be done by renaming `table.result` to `table.results` and implementing it in `mergeTable`.

<details>
<summary>mergeTable is basically equivalent</summary>

The new function isn't literally equivalent because the `||` operator short circuits...
In the new function, if defaultTable.indices, it skips defaultTable.parents.
...but in practice the case where both `indices` and `parents` exist never happens
(see old switch statement code)

The if statement now at the top (necessary precedence) now says

`if (defaultTable.results) table.results = [].concat(defaultTable.results, table.results || []);`

which implements the result --> results change

</details>

`setTableResults` is called all the way back at the start

#### `src/tree-sitter-language-mode.js`

<details>
<summary> applyLeafRules() </summary>

Here's some manual typing
```ts
array path (= string[])
 depth > 1: string path
 depth = 1: [head, tail] | undefined
    head: [...(string path)[0]] | undefined
    tail: [...(string path)[1]] | undefined
 depth = 0: string | undefined
string path: [] | [undefined, string[]] | [string[] | []]
  aka
  [undefined, undefined] | [undefined, string[]] | [string[], undefined]
object path: array path
```

which I think is quite helpful for understanding this function.
</details>

For the rest, the original post covers everything

</details>

**Comment by chbk** [comment]
Thanks for checking out the code @icecream17

**Comment by sadick254** [comment]
@chbk Thank you for all the work you have done on this PR. 🙇 
Am sorry to say, this is not a feature we are interested in at the moment. We are currently interested in features or fixes that have a direct impact on Atom users. I am happy to revisit this feature sometime in the future when the verbosity of the grammar become a real user issue.

**Pull request closed without merging**
