### PR TITLE
add support for jasmine.any

### PR DESCRIPTION
**Pull request by UziTech**
### Description of the Change

Add back support for [jasmine.any](https://jasmine.github.io/1.3/introduction.html#section-Matching_Anything_with_<code>jasmine.any</code>)

### Benefits

jasmine.any can be used in tests

### Possible Drawbacks

none

### CODE REVIEW

**Comment by UziTech** [comment]
sorry this is the wrong place to fix this

**Comment by UziTech** [comment]
never mind this actually is probably the best way to fix this

**Comment by UziTech** [comment]
still in needs-review

**Comment by jasonrudolph** [comment]
:wave: Hi @UziTech: Thanks for this pull request. When you have a moment, can you describe the process you followed to verify that your change has the desired effects?

Note: This information is [something we've started requesting as part of the pull request template](https://github.com/atom/.github/blame/e4f568e0b4b22aab0f8513e5d18d564764cffce8/.github/PULL_REQUEST_TEMPLATE/feature_change.md#L40-L50), but your pull request was opened prior to that change to the template. Nevertheless, it would be a big help if you could add this info to the pull request body.

Thanks for your help!

**Comment by UziTech** [comment]
I added a test

**Pull request merged**
