### PR TITLE
Faster `mergeIntersectingSelections`

### PR DESCRIPTION
**Pull request by as-cii**
This pull-request introduces a performance improvement in `mergeIntersectingSelection`. Before changing it the cost of this function was `O(n^2)`: selections were accessed always and in sparse order, causing the traversing time to increase exponentially as more and more selections were added. 

Before merging selections, we now order them first and try to intersect the current selection with the previous one only. This brings the cost of `mergeIntersectingSelections` down to `O(n log n)`, changing this:

screen shot 2015-02-22 at 14 01 32

To this:

screen shot 2015-02-22 at 14 00 31

:racehorse: :racehorse: :racehorse: 

_(Benchmarks based on splitting into lines the entire selection of a 400 lines file)_

All the specs are green, therefore this "new algorithm" shouldn't have changed the behavior of `mergeIntersectingSelections`. It would be great to have some more :eyes: to detect any possible regression.

Hopefully, this should be a significant step forward towards #5163 :smile:

### CODE REVIEW

**Comment by as-cii** [comment]
/cc: @nathansobo @gregersrygg

(as you were discussing about this in #5163 and I thought it might have been relevant to you :wink:)

**Comment by nathansobo** [comment]
@as-cii Fantastic work here. 

If you're interested in optimizing this further, I have some ideas. I recently introduced the `TextEditorPresenter` layer to synchronously and incrementally maintain a state object based on model changes. The intuition on this was that for small changes like a single cursor movement or a single character insertion, recomputing the entire presenter state was wasteful and it would be better to make a small change. Unfortunately, when there are ton of little changes before the next display update, we end up paying more for each incremental update than we would pay if we waited and just recomputed everything at the end.

I see two paths of attack on this.

1) We could do a better job on the incremental updates. Some of them are way more wasteful than they need to be in that they update every line when one line updated, etc.

2) We could apply a heuristic for when we think a bunch of incremental changes might be applied. For example, we could handle 1 cursor movement or text change incrementally, but if we get a second in either category we could flip into batch mode where we defer any further updates until it's time to render to the screen, then recompute everything async.

Not sure if you're interested in investigating this but since you're already doing a great job in other areas, I thought I'd suggest it.

**Comment by nathansobo** [comment]
Refs https://github.com/atom/atom/issues/5025.

Any further discussion should probably actually take place there.

**Comment by gregersrygg** [comment]
@as-cii Awesome speed improvement :zap: :smile:

**Pull request merged**
