### PR TITLE
script: Update npm to 6.14.4 for Python 3 support

### PR DESCRIPTION
**Pull request by DeeDeeG**
### Identify the Bug

Addresses part of #20585 

### Description of the Change

Update package dependencies for the build scripts, so as to support building Atom with Python 3.

Updates the `npm` package in `package.json` and `package-lock.json` under the `scripts/` directory of this repo; Updates `npm` to 6.14.4, which comes with `node-gyp` 5.1.0, which now supports Python 3.

_Does not affect anything but the build process itself. Should not affect the end result or change the built Atom packages. This is about still being able to build Atom as distros begin to drop Python 2._

### Alternate Designs

N/A

### Possible Drawbacks

None that I am aware of. This is just a minor version bump of `npm` in the dependencies for the  build scripts.

### Verification Process

I successfully built Atom with only Python 3 installed on my system using the changes in this PR.

### Release Notes

N/A because not end-user facing? But this could work:

- Atom can now be built using Python 3. Ensures Atom can be built on upcoming OS releases without Python 2, such as Ubuntu 20.10 or Debian 11.

### CODE REVIEW

**Comment by DeeDeeG** [comment]
cc @lkashef.

This, along with #20670, are the final pieces of the puzzle to be fully ready for a "Python 3" future, while remaining fully compatible with Python 2.

**Comment by lkashef** [comment]
Thanks @DeeDeeG

I reviewed this, the CI is mainly failing due to a known flaky test on Windows + Slow ubuntu servers.

Once the tests pass, I will go ahead and merge this.

**Comment by DeeDeeG** [comment]
Now that this is merged, I suppose I can update the review PR (#20716) to say so.

**Comment by lkashef** [comment]
@DeeDeeG  Yeah sure, just taking it a step by step

**Pull request merged**
