### PR TITLE
Add subword cursors - take 4

### LINKED ISSUE #1982: Support subword navigation
SublimeText supports navigation by subwords (underscore separated or hills in camelcase):
```
{ "keys": ["alt+left"], "command": "move", "args": {"by": "subwords", "forward": false} },
{ "keys": ["alt+right"], "command": "move", "args": {"by": "subword_ends", "forward": true} },
{ "keys": ["alt+shift+left"], "command": "move", "args": {"by": "subwords", "forward": false, "extend": true} },
{ "keys": ["alt+shift+right"], "command": "move", "args": {"by": "subword_ends", "forward": true, "extend": true} }
```

It would be nice if Atom also supported `move*`, `delete*`, `backspace*`, `select*` editor commands based on subwords.

### PR DESCRIPTION
**Pull request by dsandstrom**
Add commands for moving, selecting, and deleting camelCase words.

Fixes #1982 and an alternative to #3961. Also, hopefully can used with atom/vim-mode#377.

Replaces #4429.

### CODE REVIEW

**Comment by nathansobo** [comment]
Apologies for the long delay in reviewing this. Have been taking a look this afternoon. I'd like to investigate whether `TextBuffer.prototype.scanInRange` can be inclusive of its start position so we don't need the hack at the beginning of the file.

**Comment by nathansobo** [comment]
Thanks very much for doing this. It's a really nice addition. Apologies again for the delay. We got pretty swamped in the approach to 1.0.

**Comment by adrianoresende** [comment]
I installed now, Atom 1.7.4 in OS X El Capitan 10.11.4 and this default CTRL + ARROW not work for me in editor.

**Comment by dsandstrom** [comment]
Its ctrl-alt-arrow on osx: https://github.com/atom/atom/blob/master/keymaps/darwin.cson#L143

**Comment by adrianoresende** [comment]
@dsandstrom But CTRL + ARROW it is not standard?

**Comment by dsandstrom** [comment]
Who's standard?  In Atom, ctrl-arrow runs the current OS' "native" command.  In OSX, I believe this is used by Mission Control to switch desktops by default.  Alt is already being used to go the beginning/end of the line, cmd is being used to go the beginning/end of a word.  So, we are stuck with ctrl-alt on OSX.

**Pull request merged**
