### PR TITLE
API guidelines doc

### PR DESCRIPTION
**Pull request by benogle**
This is super in-progress. A lot of this information is sort of tribal knowledge, but I wanted to get it in out in the open and us on the same page.

This should give us somewhere to look when we're like "how should I name that method/event?", or "how do I doc a method that takes a callback that takes an options hash."

### CODE REVIEW

**Comment by kevinsawicki** [comment]
@benogle just looking at old PRs and came across this, it this something we want to :ship: or :snowflake: ?

**Comment by benogle** [comment]
It would be nice to eventually update it and ship it.

**Comment by mark-hahn** [comment]
Sorry for an off-topic stupid question, but what does the snowflake mean?

**Comment by benogle** [comment]
Ice

**Comment by mark-hahn** [comment]
So icing means what?  I thought an issue could only be open or closed.

**Comment by benogle** [comment]
Yeah, he was asking if we wanted to close it.

**Comment by kevinsawicki** [comment]
> Sorry for an off-topic stupid question, but what does the snowflake mean?

the opposite of :ship: essentially

**Comment by kevinsawicki** [comment]
This still something we want to ship or should this be closed?

**Comment by benogle** [comment]
Ugh, maybe it doesnt matter now. Would be nice, but not a big deal.

**Pull request closed without merging**
