### PR TITLE
Replaced the old Atom document icon with the Big Sur icon

### PR DESCRIPTION
**Pull request by andylin2004**
### Issue or RFC Endorsed by Atom's Maintainers

#21128 (for parity purposes)

### Description of the Change

I replaced the older default icon for Atom with the Big Sur-style icon for Atom for Macs only. Windows icons is still the same.

### Alternate Designs

Keeping the icon as is: this would fragment the Atom icon use on macOS (between the old and new icons)
Adding the "Use system generated icons" variable and setting to YES (to load the Atom icon as the document icon automatically): this would not replicate the previous file icon behavior where the Atom icon appeared on the title bar and in the filesystem. In addition, I don't know how far back OS-wise this workaround will go back, as the lowest version Atom supports is OS X 10.10.
Using the new layered icon technique as depicted in https://developer.apple.com/news/?id=5i6jlf4d : adding new Document Type Identifiers is not worth the time, as Atom uses a single file icon and to repeat this process for many file types would be time consuming. I am open to doing this as a pet project on the side. In addition, I don't know how far back OS-wise this technique will go, as the lowest version Atom supports is OS X 10.10.

### Possible Drawbacks

The document icon is based off the one in macOS Big Sur, meaning that any user using macOS Catalina or lower will see the newer style document icon, instead of the one used in macOS Catalina and lower.

### Verification Process

The verification process is not needed, as this is just an icon swap with the same file extension (between the icon being replaced and replacement icon).

### Release Notes

The document icon for files openable by Atom and on the title bar on macOS has been changed to the new app icon to reflect the style in macOS Big Sur.

### CODE REVIEW

**Comment by lildaddy423** [comment]
Who gives a flying fuck can you make something where someone aint constantly keeping up with what I do through my phone laptop etc they have humiliated they have stole they called my jobs and showed them messages recording images etc... I downloaded git hub to help and atom but it's not what you need to catch the virus or program they are so good they make it look like nothing is going on and it has made me look crazy 

Sent from Yahoo Mail on Android 
 
  On Thu, May 13, 2021 at 5:19 PM, Andy ***@***.***> wrote:   
Issue or RFC Endorsed by Atom's Maintainers

#21128 (for parity purposes)

Description of the Change

I replaced the older default icon for Atom with the Big Sur-style icon for Atom for Macs only. Windows icons is still the same.

Alternate Designs

Keeping the icon as is: this would fragment the Atom icon use on macOS (between the old and new icons)
Adding the "Use system generated icons" variable and setting to YES (to load the Atom icon as the document icon automatically): this would not replicate the previous file icon behavior where the Atom icon appeared on the title bar and in the filesystem. In addition, I don't know how far back OS-wise this workaround will go back, as the lowest version Atom supports is OS X 10.10.
Using the new layered icon technique as depicted in https://developer.apple.com/news/?id=5i6jlf4d : adding new Document Type Identifiers is not worth the time, as Atom uses a single file icon and to repeat this process for many file types would be time consuming. I am open to doing this as a pet project on the side. In addition, I don't know how far back OS-wise this technique will go, as the lowest version Atom supports is OS X 10.10.

Possible Drawbacks

The document icon is based off the one in macOS Big Sur, meaning that any user using macOS Catalina or lower will see the newer style document icon, instead of the one used in macOS Catalina and lower.

Verification Process

The verification process is not needed, as this is just an icon swap with the same file extension (between the icon being replaced and replacement icon).

Release Notes

The document icon for files openable by Atom and on the title bar on macOS has been changed to the new app icon to reflect the style in macOS Big Sur.

You can view, comment on, or merge this pull request online at:

  https://github.com/atom/atom/pull/22421

Commit Summary
   
   - replaced the old atom document icon with the big sur icon

File Changes
   
   -  M resources/mac/file.icns (0) 
   -  M script/package-lock.json (16901) 

Patch Links:
   
   - https://github.com/atom/atom/pull/22421.patch
   - https://github.com/atom/atom/pull/22421.diff

**Review by ThatXliner — COMMENTED** [review]
Looks good but why did you delete so much in the package-lock.json?

**Comment by andylin2004** [comment]
That was unintentional. I have committed the old package lock back

**Comment by ThatXliner** [comment]
> That was unintentional. I have committed the old package lock back

The easiest way is to uncommon those, remove the changes on package-lock.json, commit and force-push

**Comment by ThatXliner** [comment]
Yep, that seems about right

**Review by ThatXliner — APPROVED** [review]
Looks good

**Comment by LucasSeth** [comment]
Hi, I think it would be better to use the system generated icons.

Otherwise your icon is blurry on my system and the icon background is not fully transparent.

**Comment by ThatXliner** [comment]
> Hi, I think it would be better to use the system generated icons.
> 
> 
> 
> Otherwise your icon is blurry on my system and the icon background is not fully transparent.

Can you show us a screenshot?

**Comment by LucasSeth** [comment]
The icon is a bit blurry, especially at the edges:

screenshot

If you zoom in, we can see that the background of the icon is slightly gray (this is also notable in the capture above):

screenshot 2

Moreover, depending on the size of the icon, we have different styles (3 styles, which is a lot):

icon

Wouldn't it be better to use the files icons that are automatically generated by the system? (as does Sketch, Pixelmator and soon Transmission)

Since the current icon is simple, there is no reason to create a specific one:

> https://developer.apple.com/news/?id=5i6jlf4d
> By default, if you don’t specify a document icon for a file type in your app, macOS will automatically create one for you by compositing your app’s icon together with the correct extension name. This is a common pattern for imported document types or non-proprietary file formats that your application can open such as MP3, JPG or PNG.

**Comment by ThatXliner** [comment]
The description of this PR says
> Adding the "Use system generated icons" variable and setting to YES (to load the Atom icon as the document icon automatically): this would not replicate the previous file icon behavior where the Atom icon appeared on the title bar and in the filesystem. In addition, I don't know how far back OS-wise this workaround will go back, as the lowest version Atom supports is OS X 10.10.

but ok

**Review by sadick254 — APPROVED** [review]
Looks good.

**Pull request merged**
