### PR TITLE
Fix window state not saving on close

### LINKED ISSUE #13909: Window close does not trigger save window state
### Description

Closing the Atom window does not save the window UI state, _read_ window size and position. To save the window state I have to **blur** (click outside) the window, then close it. Reopening the window after blurring it works.

According to the code in `window-event-handler.coffee` the window state should be stored both when a window closes and when blurred:
```coffee
handleWindowBlur: =>
    @atomEnvironment.storeWindowDimensions()

handleWindowBeforeunload: (event) =>
  @atomEnvironment.storeWindowDimensions()
```

### Steps to Reproduce

1. `atom .` to open project of your choice
2. Resize window, maintain window focus
3. Close window
4. Back to terminal, `atom .` again

Redo step **1-2** and before closing the window in step **3**, **blur** the window, click your desktop. Then close the window and continue with step **4**, the new window should open with the same dimensions as the window you just closed.

**Expected behavior:** The window you open in step **4** should be restored to the resized state, when you closed the window.

**Actual behavior:** The window you open in step **4** is restored back to the state before you resized, in step **2**.

### Versions

Atom    : 1.14.4
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
macOS 10.12.3

### Additional Information

I did try to start Atom in safe mode, and also with the `--clear-window-state` flag. Even deleting my `~/.atom/storage`.

You can also reload the window and see the same behaviour, instead of closing and re-opening a window. Resize Atom window then reload, watch it reset back to old dimensions, before reload. Watch the gif for a demo:

window-state

### PR DESCRIPTION
**Pull request by richardsimko**
### Description of the Change

Fix #13909. It seems there have been fixes for saving window state previously however these only save on `blur`, and `beforeUnload`. None of these are triggered if you immediately close the window.

### Alternate Designs

None

### Why Should This Be In Core?

It's a bug fix.

### Benefits

The bug is fixed.

### Possible Drawbacks

None

### Applicable Issues

#13909

### CODE REVIEW

**Comment by richardsimko** [comment]
I would love some help on why the test case I added seems to cause a timeout when building.

**Comment by dannyparker** [comment]
Can someone please help on how to start contributing to open source, I am new.

**Comment by 50Wliu** [comment]
@richardsimko can you uncomment the test?  In some cases, it helps to see the failing output.

(Also, you have a typo in the test: winodw -> window)

**Comment by richardsimko** [comment]
@50Wliu Sure thing! That typo might be the explanation, I'll check ;)

**Comment by richardsimko** [comment]
@50Wliu Any chance for a new review? :)

**Comment by rsese** [comment]
Just a heads up that @50Wliu is out till next week /cc https://github.com/atom/language-less/pull/82#issuecomment-334293564.

**Comment by richardsimko** [comment]
Oh, thanks for the heads up! It wasn't specifically directed at him really I'm just looking for some help getting the test to run ;)

**Comment by iolsen** [comment]
Once we have green builds we're 👍 on this change.

**Comment by 50Wliu** [comment]
I'm not sure why the test would be timing out the entire build rather than just the test itself.  The lack of any output is also annoying.  When I have time I may try to investigate locally.

**Comment by ungb** [comment]
I've created a PR addressing the merge conflicts but it seems that something in the test are still failing.  

Also wanted to note while testing if you run `window:close` this will save the windows dimension but on mac if you close the window with the red x or run `cmd+q` this doesn't save the windows dimension.

**Comment by richardsimko** [comment]
That's annoying, I figured it would trigger the same event. Do you know if there's a different event to listen to?

The failing tests are weird as mentioned above, for some reason it times out waiting for something however I couldn't figure out a way to show what it's waiting for.

**Comment by 50Wliu** [comment]
Superseded by #16295.  Thanks for the initiative on this @richardsimko!

**Pull request closed without merging**
