### PR TITLE
Return command value

### PR DESCRIPTION
**Pull request by UziTech**
### Description of the Change

Right now `atom.commands.dispatch` returns true/false to tell whether a dispatched command exists.

This would return an array of information for the executed commands including the `currentTarget`, `dispatchEvent`, and return value of the command.

This will allow the dispatcher to view the information for each listener of the command. 

### Alternate Designs

I was going to return a `Promise` with `Promise.all()` but I thought this would be better for a couple reasons.

 - `Promise.all()` will reject if only 1 `Promise` fails and the rest of the listeners info will be lost.
 - `Promise.all()` will only let us get the return value of each listener.

To keep backwards compatibility I return false if there are no matches. We could change that in the future.

### Why Should This Be In Core?

This requires changes to the command registry in core.

### Benefits

- Ability to get a return value from a command.
- Ability to tell when an async command actually finishes.
- Ability to dispatch commands in series.

### Possible Drawbacks

none

### Applicable Issues

#13195

### CODE REVIEW

**Comment by 50Wliu** [comment]
> To keep backwards compatibility I return false if there are no matches.

Curious: what if a package was doing a strict equality check for `true`?  It seems like this only preserves backwards compatibility for when the command doesn't exist.

**Comment by UziTech** [comment]
That is correct. This will break backwards compatibility if they are strictly checking for `true`

**Comment by UziTech** [comment]
In testing this seems a bit less practical than I originally thought.

The problem is that a command listener can be added by any package and knowing which order listeners will be called in (and therefore be returned in) is not easy.

I'm thinking returning a single `Promise.all` or just an array of Promises would be better. At least the dispatcher would be able to use the promise(s) to tell when the command was finished and run the next command in series.

**Comment by UziTech** [comment]
I'm not sure if the `currentTarget` or `dispatchEvent` are needed in the return value

**Comment by UziTech** [comment]
One option to not break backwards compatibility would be to add an `onDidFinish` event

**Comment by UziTech** [comment]
I moved this to a new pull request since it got a little off topic #14931

**Pull request closed without merging**
