### PR TITLE
Delta Packages for Windows + Update Squirrel.Windows

### PR DESCRIPTION
**Pull request by anaisbetts**
This PR enables creating / publishing delta packages for Atom updates, which vastly decreases the amount of data users have to download for every Atom release. Typical delta package sizes for JavaScript-only changes (i.e. not the upcoming release because of Chrome 40) are around 800k-2MB.

This PR also updates us to Squirrel.Windows 0.8.3 which fixes a bunch of issues, see https://github.com/atom/grunt-atom-shell-installer/pull/6 for more info
## TODO:
- [x] Triple-check install + update
- [x] Wait for `grunt-atom-shell-installer@0.21.0` to be published

### CODE REVIEW

**Comment by philipgiuliani** [comment]
Cool are delta updates also planned for os x any time soon?

**Comment by paulcbetts** [comment]
@philipgiuliani Probably not tbh

**Comment by paulcbetts** [comment]
Ran through a full upgrade + clean install pass on Atom this weekend, this should be :Gem:

**Comment by kevinsawicki** [comment]
Thanks @paulcbetts, this is really cool.

Will open an atom.io issue to get this wired up there as well.

**Pull request merged**
