### PR TITLE
Check for updates every 4 hours

### LINKED ISSUE #4936: Periodically check for available updates
Could we get an indicator when there's an update available for Atom, in addition to the file menu?  If someone leaves Atom open for days at a time, they could easily end up several versions behind.

I'm picturing something like Chrome's indicator, where the hamburger icon goes from green->yellow->red depending on how stale the user's version is.  Maybe just a little light in the status bar.

### PR DESCRIPTION
**Pull request by kevinsawicki**
Closes #4936

### CODE REVIEW

**Comment by kevinsawicki** [comment]
@paulcbetts it is okay to run `Update.exe --download` every 30 minutes right? It won't download anything if it already exists on disk right? Thanks.

**Comment by kevinsawicki** [comment]
> It won't download anything if it already exists on disk right?

I mean, it won't re-download packages already downloaded, I would guess it still hits `RELEASES` which is fine.

**Comment by paulcbetts** [comment]
@kevinsawicki Should be fine, yeah

**Comment by Zireael07** [comment]
Will it crash or something if I don't have net access at the moment it runs Update.exe --download? I often work without net access at all (wireless card off/cord not plugged in)

**Comment by kevinsawicki** [comment]
> Will it crash or something if I don't have net access at the moment it runs Update.exe --download?

Nope, it will just do nothing and check again in 30 minutes.

**Comment by kevinsawicki** [comment]
@thedaniel do you have any concerns with all Atoms hitting the `https://atom.io/api/updates` endpoint every 30 minutes?

I could definitely bump it to an hour or 4 hours if you think if would be a better starting value.

**Comment by paulcbetts** [comment]
Hm. So, there is one problem - checking every 30mins has the potential to spam the update log so much that it gets hella big. Probably want to delete it from time to time.

**Comment by thedaniel** [comment]
@kevinsawicki that stuff is pretty heavily cached, I think it's fine.

**Comment by kevinsawicki** [comment]
Downgraded this to every 4 hours just to be conservative to start.

**Comment by bendem** [comment]
That should totally be configurable

**Pull request merged**
