### PR TITLE
Defer activation hooks (#8313)

### PR DESCRIPTION
**Pull request by lierdakil**
This is a first attempt at solving #8313. Actually triggering activation hooks is deferred until all packages that could be activated, are.

Note that there was a little oversight at line 409/411, due to which `did-activate-initial-packages` was emitted late if there were packages with activation hooks, I had to fix that as well.

Not entirely sure on how should I go about adding specs for this. Any advice is welcome.

### CODE REVIEW

**Comment by thomasjo** [comment]
This breaks three specs, all specifically related to activation hooks. Whether that is a problem with the specs or if this breaks the functionality is unknown to me at this point. The failures are legit though, and have to be addressed.

**Comment by lierdakil** [comment]
Yes, sorry about that. Have precious little time ATM, will try to do
something about it by the end of this week.
7 сент. 2015 г. 16:36 пользователь "Thomas Johansen" <
notifications@github.com> написал:

**Comment by lierdakil** [comment]
I finally got around to fixing specs. Anything else I can do from here?

**Comment by lierdakil** [comment]
Bump. I will rebase on `master` once someone takes a look and gives a :+1: or some constructive criticizm.

**Comment by lierdakil** [comment]
Rebased on `master`, hopefully tests are OK.

@joefitzgerald, could you possibly take a look at this patch?  I really want this to work, and I believe that it was your idea to add `grammar-used` hook in the first place.

**Comment by nwolverson** [comment]
@lierdakil looks like the CI tests failed 

>>     it calls callbacks registered with ::onDidActivateInitialPackages
>>       timeout: timed out after 60000 msec waiting for something to happen

**Comment by lierdakil** [comment]
Yep, sorry, had little time to investigate this. A removed call to Grim snuck in during rebase is all.

**Comment by lierdakil** [comment]
Okay, travis timed out. Not my fault. And now there are more conflicts. Unless someone actually commits to merging this (provided I fix conflicts and whatnot), I'm not inclined to put any more work towards this.

**Comment by nathansobo** [comment]
@joefitzgerald, could you please take a look at this and see if it fits into your original vision for these hooks?

**Comment by Arcanemagus** [comment]
Any update on this?

**Comment by joefitzgerald** [comment]
Folks, sorry for being MIA on this for so long. Looking into this.

**Comment by nathansobo** [comment]
:heart:

**Pull request closed without merging**
