### PR TITLE
:fire: Removed deprecated config converter

### PR DESCRIPTION
**Pull request by ThatXliner**
### Requirements for Contributing a Performance Improvement

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only affect performance of existing functionality. To contribute other changes, you must use a different template. You can see all templates at <https://github.com/atom/.github/tree/master/.github/PULL_REQUEST_TEMPLATE>.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see <https://github.com/atom/.github/tree/master/CONTRIBUTING.md#pull-requests>.

### Description of the Change
Removed deprecated code

### Quantitative Performance Benefits
Removed unnecessary operations

### Possible Drawbacks

Since I'm removing a deprecated conversion (it converts some configuration), it *might* break some packages that rely on the deprecated configuration.

### Verification Process

I have not verified this yet.

### CODE REVIEW

**Comment by sadick254** [comment]
Hey @ThatXliner. Congratulations on your first contribution. I have noticed you haven't filled out other parts of the template. For this change the most important sections for me as a maintainer would be, `Possible Drawbacks`  and `Verification Process`. Looking forward to more contributions from you. Welcome to the atom community.

**Comment by ThatXliner** [comment]
@sadick254 I have filled in "possible drawbacks" but I cannot profile this yet. Can you help?

**Comment by DeeDeeG** [comment]
In terms of communicating this change to the community:

- Some attempt could be made to print a deprecation warning for a few releases before removing it.
- Or the change could be made and just point folks to the release notes and say "please switch from `core.useCustomTitleBar` to `core.titleBar: custom`."
- Or leave it forever :shrug:

In terms of assessing possible downsides:

One can use `atom-package-downloader` to download all the packages, apparently. (Sounds like a fair amount of bandwidth and disk usage.) And then do some sort of search for `core.useCustomTitleBar` in all the packages.

But I think this is in people's custom config files as well. So one would have to somehow reach out to Atom users and ask how many are using this setting. (Or maybe the Atom team has access to some anonymous usage statistics about this?)

**Comment by ThatXliner** [comment]
> - Some attempt could be made to print a deprecation warning for a few releases before removing it.

So we'll need to modify the `get` method in `config` (or whatever type that object is), right (I'm not really sure what grim does, wonder if situations like this is what it's for)?
> 
> - Or the change could be made and just point folks to the release notes and say "please switch from `core.useCustomTitleBar` to `core.titleBar: custom`."

That could be easy

> 
> - Or leave it forever :shrug:
> 
> 
I mean, it's deprecated. So if you leave it forever, that's technically leaving it as a legit thing, I guess.

> 
> 
> 
> But I think this is in people's custom config files as well. So one would have to somehow reach out to Atom users and ask how many are using this setting. (Or maybe the Atom team has access to some anonymous usage statistics about this?)

Wonder what kind of statistics they get, anyway.

**Comment by DeeDeeG** [comment]
> I mean, it's deprecated. So if you leave it forever, that's technically leaving it as a legit thing, I guess.

Yeah, I have seen some things where the project in question just said "eh, we'd rather not remove this, let's just un-deprecate it." Example: https://github.com/nodejs/node/pull/28892

(I have no strong other opinion either way, I'm just trying to be helpful and point out some paths forward.)

**Comment by ThatXliner** [comment]
Since I don't think the performance improvements are going to be anything major, I'm probably going to close this for now

**Pull request closed without merging**
