### PR TITLE
Move "Fold all" menu entry to above the "Unfold all" entry

### LINKED ISSUE #13262: Move "Fold all" menu entry to above the "Unfold all" entry
In the Edit > Folding menu, it would make sense, to match Fold/Unfold entries, that "Fold All"/"Unfold All" were also paired, above the separator. Like so:

screenshot 2016-11-18 12 29 47

### Versions

```
$ atom --version
Atom    : 1.12.4
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0

$ apm --version
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.11
git 2.5.4

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F2009
```

### PR DESCRIPTION
**Pull request by ycai2**
Move "Fold all" to above the "Unfold all" and separator. 
Fixes #13262

### CODE REVIEW

**Review by winstliu — APPROVED** [review]
Makes sense to me.
/cc @atom/feedback

**Comment by lee-dohm** [comment]
Thanks for contributing! :grinning:

**Comment by waldyrious** [comment]
@ycai2 I tried making a different change in the menus (rewording an entry) and edited precisely the .cson files that you did in this PR. However, after rebuilding the project by running `script/build`, the changes weren't reflected in the actual program. Is there some additional step that needs to be performed?

**Comment by lee-dohm** [comment]
@waldyrious You have to use the `--install` parameter to install the newly-built version of Atom so you can use it.

**Comment by waldyrious** [comment]
@lee-dohm I had previously installed Atom using brew, so I didn't build the dev version with the --install option on purpose; instead, I symlinked `out/Atom.app/Contents/Resources/app/atom.sh` to `/usr/local/bin/atom-dev`. Running `atom-dev` however, doesn't seem to apply the changes made to the source code, after running the build script. Is there something else I could check to figure out what's going on?

**Comment by lee-dohm** [comment]
@waldyrious This isn't really the place to be having this discussion. Please post something on [Discuss, the official Atom message board](https://discuss.atom.io), and I or someone else will see about helping you out.

**Pull request merged**
