### PR TITLE
Implement naming conventions in default themes

### PR DESCRIPTION
**Pull request by chbk**
### Description of the Change

This is an update of the default syntax themes to implement [naming conventions](https://github.com/atom/flight-manual.atom.io/pull/564) for syntax scopes.

This PR simply adds the [template](https://github.com/atom/apm/pull/883) to each theme with custom colors, to accommodate the naming conventions. There should be no break in compatibility with existing grammars.

As naming conventions are implemented in more language grammars, their old specific stylesheets can be retired.

### Possible Drawbacks

Some colors are changed to stay consistent between languages and to follow the design guidelines by @maxbrunsfeld regarding [color choices](https://github.com/atom/atom/pull/18383#issuecomment-435460854).

### Verification Process

- Tested all the themes with the language grammar PRs linked below.

### Release Notes

- Add naming conventions to default syntax themes

### Applicable Issues

- https://github.com/atom/atom/issues/8430

### Related Pull Requests

- [Naming conventions documentation](https://github.com/atom/flight-manual.atom.io/pull/564)
- [Implementation in template theme](https://github.com/atom/apm/pull/883)
- [Implementation in C and C++ grammars](https://github.com/atom/language-c/pull/351)
- [Implementation in CSS grammar](https://github.com/atom/language-css/pull/167)
- [Implementation in Go grammar](https://github.com/atom/language-go/pull/182)
- [Implementation in HTML grammar](https://github.com/atom/language-html/pull/249)
- [Implementation in JavaScript and Regex grammars](https://github.com/atom/language-javascript/pull/690)
- [Implementation in Python grammar](https://github.com/atom/language-python/pull/313)
- [Implementation in Ruby grammar](https://github.com/atom/language-ruby/pull/291)

### CODE REVIEW

**Comment by chbk** [comment]
Here are some screenshots of the same code snippet translated in different languages. For each theme, notice the difference before and after implementing the naming conventions. Syntax highlighting is really harmonized across languages.

__Solarized Dark__:
solarized-dark

__One Dark__:
one-dark

__Base16 Tomorrow Dark__:
base16-dark

__Atom Dark__:
atom-dark

__Solarized Light__:
solarized-light

__One Light__:
one-light

__Base16 Tomorrow Light__:
base16-light

__Atom Light__:
atom-light


Python:
```python
class Lilac(Tree):

  flowers: bool


  def bloom(self, days: int) -> float:
    self.flowers = True
    return float(days) / 7



if __name__ == "__main__":

  season: Final[str] = "winter \n"
  lilac: Lilac = None

  if season[0] == 'w' and lilac == None:
    snow = "*"
```

C++:
```c++
class Lilac: public Tree {

  bool flowers;


  float bloom(int days) {
    this->flowers = true;
    return (float) days / 7;
  }
};

int main() {

  const char *season = "winter \n";
  Lilac *lilac = nullptr;

  if (season[0] == 'w' && lilac == nullptr) {
    auto snow = "*";
  }
}
```

Go:
```go
type Lilac struct {
  Tree
  flowers bool
}

func (lilac Lilac) bloom(days int) float32 {
  lilac.flowers = true
  return float32(days) / 7
}


func main() {

  const season string = "winter \n"
  var lilac *Lilac = nil

  if season[0] == 'w' && lilac == nil {
    snow := "*"
  }
}
```

**Comment by aminya** [comment]
@chbk I am so glad to see this PR. 🚀

**Review by sadick254 — APPROVED** [review]
Welcome to the Atom community @chbk and congratulations on your first contribution to the Atom repo. You have done an excellent job on this PR. Hopping to see more from you @chbk .

**Comment by chbk** [comment]
Thanks @sadick254, it's great to see this merged!

**Comment by ElderTugBoat786** [comment]
Hi, after the last update the '$' symbol in a php file when the One Dark syntax theme are select is white and not red. 
I have open a issue https://github.com/atom/language-php/issues/423 but after a discussion we think this pr is the source of problem. 

To temporaney solve the problem i have add 
`.syntax--punctuation.syntax--definition.syntax--variable.syntax--php {
color: e06c75;
}` 
to my style.less file. 

@kapitanOczywisty suggested the change this file [https://github.com/atom/atom/blob/master/packages/one-dark-syntax/styles/syntax-legacy/php.less](https://github.com/atom/atom/blob/master/packages/one-dark-syntax/styles/syntax-legacy/php.less) add a specific rules fort this case. If this is the problem I can try to do a PR on that file to fix it

Thanks

**Comment by chbk** [comment]
Hi @ElderTugBoat786, thanks for pointing that out. The purpose of this PR (and related PRs) is to harmonize syntax highlighting across languages, so the color change is an intended consequence. Punctuation marks should be white with the One Dark theme. Variables in PHP should be white as well, like in other languages. Eventually they will be when the legacy stylesheets are retired, but I don't know what the maintainers' plans are with the naming conventions.

**Comment by curtiscarlson** [comment]
This is not the only thing that changed.  now when you double click a variable, it highlights the name with the $.  Yesterday, it only highlighted the text part of the variable name, which was really really useful.

**Comment by KapitanOczywisty** [comment]
@curtiscarlson Theme is not responsible for that. There was mentioned issue, but it was initially fixed in #21910 . However after that it was introduced directly: https://github.com/atom/language-php/pull/412 and merged without any discussion. You can fix that of course by editing language-php options, but this is still annoying how they are merging dumb stuff like that.

**Comment by ThatXliner** [comment]
Can't you configure it?

**Comment by KapitanOczywisty** [comment]
@ThatXliner Yes, you can change it. My problem is that they changed default configuration based on some issue with 3-rd party extension, which is crazy.

**Pull request merged**
