### PR TITLE
Portable mode enhancements

### LINKED ISSUE #5502: ATOM_HOME does not affect default Chromium storage path
hi

i'm on Win7 64bit and downloaded the newest
atom-windows.zip version 0.178.0 from
https://github.com/atom/atom/releases
to test the new ATOM_HOME env var feature.

i've set the env var ATOM_HOME to the path
D:\portable_programs\Atom\ATOM_HOME
and started atom.exe .
now in the folder
D:\portable_programs\Atom\ATOM_HOME
appeared only one dir "compile-cache" and
only one file "config.cson". it looks like
an incomplete part of the files and folders
that would normally be created on the first run
of atom.exe in the folder
C:\Users\ <user> \.atom
the content of "config.cson" looks different
than usual and contains the line
"exception-reporting"

the folder
C:\Users\ <user> \AppData\Roaming\Atom
was created in the same place, like without
a present ATOM_HOME env var. so for the folder
C:\Users\ <user> \AppData\Roaming\Atom
the redirection via ATOM_HOME does not
work in the actual Atom version 0.178.0 .

for the folder
C:\Users\ <user> \.atom
the redirection via ATOM_HOME env var
works partially and the files
.gitignore , init.coffee , keymap.cson ,
snippets.cson and styles.less and the
folder packages were not created, when
ATOM_HOME was set.

also i would expect that the files and folders of
C:\Users\ <user> \.atom
would be placed in the ATOM_HOME env var mode
in the same subfolder .atom like
<path in ATOM_HOME> \.atom
but they landed directly in
<path in ATOM_HOME> \

### LINKED ISSUE #13164: Portable version for macOS
I would LOVE to use two different portable version of Atom running at the same time, not sharing ANYTHING between them.

It seems this is available for Windows users with something like this:
https://github.com/garethflowers/atom-portable

But no love for macOS 😢

### PR DESCRIPTION
**Pull request by damieng**
This PR addresses a number of niggles with portable mode, namely:

1. Add macOS support - just create a .atom directory alongside Atom.app (fixes #13164)
2. Electron/Chromium userdata can now be portable (create electronUserData dir inside .atom - fixes #5502)
3. Removes the confusing `--portable` switch that didn't enable portable mode (it copied data)
4. Checks for a portable .atom folder in expected place before using ATOM_HOME (Comments in #10072)

Flight Manual needs to be updated once this is on stable.

### CODE REVIEW

**Comment by johann1301h** [comment]
Any updates on portable mode for macOS?

**Comment by damieng** [comment]
It shipped in the 1.14 beta yesterday.

**Comment by johann1301h** [comment]
when running beta 1.14.0, the application still creates an .atom folder storing settings, packages etc. Shouldn't this folder exist within the application folder atom.app? (in this case "atom beta.app"). Or perhaps this must be activated after opening the editor?

**Comment by damieng** [comment]
You must manually create a '.atom' folder alongside the atom.app and then Atom will use that folder instead of ~/.atom,

**Comment by johann1301h** [comment]
Yes, that works. Great! But is there any way to change it so that it lies inside Atom.app?

**Comment by damieng** [comment]
No, and you really don't want to do that as the first time you upgrade Atom you'll blow away all your settings, state and installed packages.

**Comment by martinbean** [comment]
Apologies for commenting on a beta feature. But if I install *Atom.app* to *~/Applications*, and I’m supposed to create an *.atom* folder _alongside_ that, how does that make the app portable? Or am I supposed to install *Atom.app* in another, shared location (i.e. my Dropbox folder)?

I guess I’m just trying to understand the process in making Atom portable. I work across multiple Macs in multiple locations, and a portable version that has my settings, packages, snippets, etc on all machines would be a _godsend_.

**Comment by damieng** [comment]
Sorry it's a little confusing - the docs for this aren't merged into the flight manual yet because the flight manual is always at stable not beta.

Basically you could always put Atom.app anywhere you wanted but it would look for a .atom folder in your home directory for its settings/extensions etc.

Atom now looks for a .atom folder first alongside the Atom.app on the mac and will use that instead.  So to get going simply:

Move Atom.app to somewhere 'portable' like a USB drive or dropbox folder then move your .atom folder from your home folder and place it alongside it.  Now you can use them from anywhere.

**Comment by martinbean** [comment]
@damieng Gotcha. Thought that may have been the process. Thanks for clarifying!

**Comment by jaredreich** [comment]
Shouldn't the .atom folder be INISDE Atom.app for this to be truly portable?

**Comment by damieng** [comment]
Then you would lose your settings the first time you upgraded or replaced Atom.  

No macOS application stores individual settings in the .app for this reason.

**Comment by jaredreich** [comment]
Right makes sense, but without that functionality this is not portable at all in the sense of being able to have two Atom app instances on the same machine without them fighting with eachother.

**Comment by damieng** [comment]
'Portable' in this sense is referring to the application being able to live on a location you take between multiple machines - i.e. dropbox/usb.  You can place both the Atom.app and your .atom folder on there and launch the application and take your config/packages/settings with you.

**Comment by jaredreich** [comment]
Thanks for the help!

**Comment by awsdert** [comment]
Isn't the answer to how to make atom portable rather simple? Just add a launcher called atom.exe that defaults to identifying paths like ATOM_BIN, ATOM_LIB & ATOM_USR, all of which should be handed to a file called atom-paths.ini whos path should be passed as a command line argument to either atom-updater.exe or %ATOM_BIN%\atom-bin.exe as ATOM_PATHS_INI.

To get these paths the launcher should first check for ATOM_PATHS_INI in it's own arguments, if it doesn't exist call access( cwd(), R_OK | W_OK ) to check if can default to it's own directory, if not then defaults to %APP_DATA% or whatever variant it was, every update to atom.exe/atom-updater.exe should just download 2 files called atom-tmp.exe and atom.zip/7z etc, once this download is complete atom-tmp.exe should be launched, atom-tmp.exe should then wait for any other executable containing the name atom to finish before deleting atom.exe & atom-updater.exe and unpacking the archive subsequently exiting, when atom.zip/7z etc is detected atom.exe should check if atom-tmp.exe is running, if it is then atom.exe quits, otherwise it deletes atom-tmp.exe and the archive and then continues as normal.

With the above behavior atom would basically be treating local data as a last resort instead of first port of call, it also means it doesn't have to know if it is portable only where to put it's background stuff.

**Pull request merged**
