### PR TITLE
:bug: Fix windows CR LF issue in wordRegExp

### PR DESCRIPTION
**Pull request by dranzerashi**
Issue #7662

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
Thanks for this! Could you write a test for this @dranzerashi?

**Comment by dranzerashi** [comment]
I didn't find a spec for cursor, Is it ok if I try updating the word selection and delete methods in text-editor-spec to cover the changes.

**Comment by dranzerashi** [comment]
The test case concerning the issue already exists in Text-editor-spec, however the sample.js file that is loaded as test-case has unix style line endings. So the test-case always passes even on windows.

**Comment by dranzerashi** [comment]
The text-editor-spec already has suitable test cases concerning the issue, however the sample.js file is written in unix format and hence passes all the test cases without raising errors.

**Comment by maxbrunsfeld** [comment]
Yeah, so we just need a test that converts `sample.js` to use CRLF line endings and checks that `ctrl-delete` still works properly at the end of a line.

**Comment by maxbrunsfeld** [comment]
I included your work in my pull request #9937, which did some additional fixes for `CRLF` line endings. Unfortunately, without thinking, I rebased my branch afterward, so these commits did not get marked as included. My apologies for that, @dranzerashi. Thanks for this work. Through https://github.com/atom/atom/pull/9937, it will be released in Atom 1.4.0.

**Pull request closed without merging**
