### PR TITLE
Upgrade to Electron 2.0.0

### LINKED ISSUE #12338: [Mac OS X] Native Application Menu Defaults is disabled for native dialogs
### Prerequisites
- The problem is reproducible in all versions in all modes on the any Mac OS X version;
- Are you running the latest version of Atom? **Yes, 1.9.4**;
### Description

Native Application Menu Defaults (`File` & `Edit` menus) is disabled for native dialogs.
### Steps to Reproduce
1. Open any native dialog. For example 'File/Open...' or  'File/Add Project Folder...';
2. Press `⌘+G` (standard Finder's hot-key, "command+shift+G") ;
3. Try to copy or/and paste anything. You can't.

**Expected behaviour:** Native menus should work.

**Actual behaviour:** Native menus not works, ~~stupidly~~ disabled.
### Versions

```
Atom    : 1.9.4
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.4
OS X: 10.11.5 (15F34)
```

atom menu issue mov opt

_Why & for what? It's really terrible!_

### PR DESCRIPTION
**Pull request by jasonrudolph**
This pull request is a work-in-progress. [Electron 2.0.0](https://electronjs.org/releases#2.0.0) includes a few breaking API changes that we'll likely need to work through in order to get Atom running smoothly on Electron 2.0.0.

# TODO

- [x] Get CI passing
- [x] Run through Atom's Electron upgrade test manifest (below) to identify any regressions

# Regressions to fix before merging

- [x] [Can't commit via GitHub package](https://github.com/atom/atom/pull/17273#issuecomment-387490306)

# Known bugs resolved by this upgrade

Fixes https://github.com/atom/atom/issues/12338

# Electron Upgrade Test Manifest

- [x] Review issues tagged with [`electron`](https://github.com/search?utf8=%E2%9C%93&q=org%3Aatom+label%3Aelectron+is%3Aopen+is%3Aissue) to see if any of them are fixed
- [x] Verify that you can collaborate with Teletype
    - [x] Host using Atom's current stable release can collaborate with guest using Atom with the new version of Electron
    - [x] Guest using Atom's current stable release can collaborate with host using Atom with the new version of Electron
    - [x] Host and guest can collaborate when both are using Atom with the new version of Electron
    <details>
    <summary>Steps</summary>

    1. Open a file
    1. Share a portal
    1. Have a guest join the portal
    1. When guest edits the text in the file, verify that the host sees those changes
    </details>

## Text Input/Keybindings

See how to [setup keyboard layouts](https://github.com/atom/maintainers-log/blob/master/how-tos/setup-keyboard-layouts.md).

- [x] IME not working (https://github.com/atom/atom/issues/14911)
	- [x] macOS
	- [x] Windows 10
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Install an IME layout, for example Pinyin simplified  1. Open Atom and use the layout you installed as the keyboard layout
  1. Example, if you picked Pinyin simplified type in `zhongwenshuru`

  **Expected:** in Pinyin simplified `中文输入` is expected

  gif

  **Issues we've seen:** Only shows latin first character and not every character typed.

  gif
  </details>

- [x] macOS: Key binding with composition characters are ignored (https://github.com/atom/atom/issues/15189)
  <details>
  <summary>Repro steps</summary>

  1. Open your keymap.cson file and add the following:
      ```cson
      'atom-text-editor':
        # use hjkl; vim-like when pressing alt (word by word, paragraph by paragraph)
        # or alt (letter by letter)
        'alt-h': 'core:move-left'
        'alt-j': 'core:move-down'
        'alt-k': 'core:move-up'
        'alt-l': 'core:move-right'
      ```
  1. Save keymap.cson and reload atom.
  1. Try the new keymappings under `ABC - Extended` keyboard layout

  **Expected**: the keybindings work

  **Issues we've seen:** it types out the modified keys and ignores the key mapping
  </details>

- [x] macOS: Composition characters mess up insertion point (https://github.com/atom/atom/issues/15344)
  <details>
  <summary>Repro steps</summary>

  1. Open keymap.cson and add the following:
      ```cson
      'atom-text-editor':
        'alt-n': 'core:move-down'
        'alt-o': 'core:move-down'
      ```
  1. Have the following in your buffer:
      ```
      Foo
      Bar
      ```
  1. Have the cursor at the beginning of file(before F character) Type alt-n, then arrow right, then insert a character. Observe that the character is inserted at the beginning of the line (where the alt-n left you).
  1. Repeat steps using <kbd>alt-o</kbd> instead of <kbd>alt-n</kbd>.

  **Expected**: Both alt-o and alt-n behave the same

  **Issues we've seen:**
  bug

- [x] Ubuntu: Keystrokes involving <kbd>ctrl</kbd> resolve to the default layout instead of the active layout (https://github.com/atom/atom/issues/13170)

  <details>
  <summary>Repro steps</summary>

  **This should be tested on Linux with gnome**

  1. Install a Linux ditro with gnome, for example Ubuntu
  1. Install French AZERTY and English US QWERTY layouts
  1. Change the default layout to be French AZERTY
  1. Open Atom and switch to English US QWERTY layout
  1. Press ctrl-w

  **Expected**: `core:close` to dispatch (Or the keybinding-resolver to resolve to ctrl-w). Should be resolving to the keyboard layout that is chosen and not the OS default layout.

  **Issues we've seen:** `core:undo` dispatched because it was resolved as ctrl-z because AZERTY has Z where W is on QWERTY.
  </details>

- [x] Other keyboard layouts on new Electron version
  - [x] macOS: ABC - Extended
  - [x] macOS: Slovak
  - [x] macOS: U.S. International
  - [x] macOS: Squirrel (https://github.com/rime/squirrel)
  - [x] macOS: Full-Width Alphanumeric (Google) - Japanese layout  (https://www.google.co.jp/ime/)
  - [x] Windows: U.S.
  - [x] Linux: Pinyin Simplified

## UI

- [x] tree-view drag image (https://github.com/atom/tree-view/pull/1054)
	- [x] macOS
	- [x] Windows 10
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Open a project in Atom with multiple files and a few folders
  1. Drag a file into a folder

  **Expected:**  
  image

  **Issues we've seen:**

  image
  </details>

- [x] drag-and-drop indicator (https://github.com/atom/tree-view/pull/1055, https://github.com/atom/tabs/pull/426, https://github.com/atom/tabs/pull/437)
	- [x] macOS
	- [x] Windows 10
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Open Atom with a few folder projects on tree-view (you can do this on terminal in a directory that has existing folder and having a space between each folder. Example: `atom folderA folderB folderC`)
  1. Drag and drop all of the folders to reorder them on Atom

  **Expected:**
  The placeholder indicates where the folder/project is being dropped to.

  screen shot 2017-03-29 at 16 31 16

  **Issues we've seen:**
  No placeholder shows up after drag and dropping

  screen shot 2017-03-29 at 16 30 51
  </details>

- [x] Large file rendering (https://github.com/atom/atom/issues/16591)
	- [x] macOS
	- [x] Windows 10
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Open a file that has over one million lines
  1. Scroll down to the bottom

  **Expected:** To not regress the number of lines that can be rendered. Rendering to be correct for lines past a certain point. Atom 1.25  can render around 800k to 1 million lines correctly.

  **Issues we've seen:** Increased number of lines rendered but bad rendering past a certain point

  bad renderer
  </details>

- [x] Loss of subpixel AA when the cursor is at the end of long lines (https://github.com/atom/atom/issues/16889, https://github.com/atom/atom/pull/16595)
	- [x] macOS
	- [x] Windows 10
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Open [text-editor.js](https://github.com/atom/atom/blob/2e19cf4a7c0a4d624b1f9c1072cd292de112cdb0/src/text-editor.js) in Atom
  1. Copy the first 21 lines to a new untitled window
  1. Turn on soft wrapping and change language mode to javascript
  1. Resize the Window so it's soft wrapped
  1. On line 15 type `a` until the you reach the end of the window

  **Expected:** To not lose subpixel AA

  **Issues we've seen:** Loss of subpixel AA. Both when soft wrapping was [enabled](https://github.com/atom/atom/pull/16943) and [disabled](https://github.com/atom/atom/pull/16595).

  subpixel aa loss softwrap
  </details>

- [x] Scrolling horizontally shift + scroll wheel (https://github.com/atom/atom/pull/12696#issuecomment-288615912)
	- [x] macOS
	- [x] Windows 10
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Open a file that has long lines
  1. Turn off soft wrapping and resize the window so you have a horizontal scrollbar
  1. Press shift and scroll in both directions using the mouse wheel

  **Expected:** File to scroll horizontally in both directions

  **Issues we've seen:** File does not scroll horizontally at all in any direction
  </details>

- [x] Scrollbars misbehaving on the first file that is opened (https://github.com/atom/atom/pull/12696#issuecomment-251299649)
  <details>
  <summary>Repro steps</summary>

  1. Open Atom
  1. Open some file that has content enough to have a vertical scrollbar
  1. Close Atom
  1. Open Atom and look at the vertical scrollbar

  **Expected:** Scrollbar to be visible

  **Issues we've seen:** Scrollbar is not visible and is flickering when you are editing
  </details>

- [x] Middle clicking on unsaved tab (https://github.com/atom/atom/issues/15197)
	- [x] macOS
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Open Atom and open a new unsaved file.
  1. Make edits to the unsaved file and middle click on the tab.

  **Expected:**
  Clicking save/cancel or the options on the dialog works.

  **Issues we've seen:**
  The UI and the dialog is unable to receive mouse clicks. You can still choose options via Keyboard, but not mouse.
  </details>

- [x] Linux: Atom scrolls even when not focused (https://github.com/atom/atom/issues/15482)
  <details>
  <summary>Repro steps</summary>

  1. Open Atom with a large enough file that has a scrollbar
  1. Open a different application and place it over the Atom window
  1. Scroll with the mouse inside the other window
  1. Focus the Atom window

  **Expected:** Atom window should keep the original scroll position

  **Issues we've seen:** The Atom window scrolls after it is focused
  </details>

## Other

- [x] Deprecation warnings (https://github.com/atom/atom/pull/12696#issuecomment-288871751)
	- [x] macOS
	- [x] Windows 10
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  **This should be tested on macOS, Linux and Windows with community packages installed**

  1. Open Atom
  1. Open the Developer tools console on the master branch and check for deprecation warnings
  1. Open the Developer tools console on the electron upgrade branch and check for deprecation warnings
  1. Compare the two outputs

  **Expected:** No new deprecation warnings

  **Issues we've seen:** New deprecation warnings both from core and community packages
  </details>

- [x] Supported Versions of OS (https://github.com/atom/atom/issues/15297)
	- [x] macOS
	- [x] Windows 10
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Check the list of supported platforms [Electron Master](https://github.com/electron/electron/blob/master/docs/tutorial/supported-platforms.md)
  1. Check what version is listed as minimum for each platform on https://atom.io and https://atom.io/faq

  **Expected:** https://atom.io and https://atom.io/faq to display the same versions as the Electron documentation

  **Issues we've seen:** macOS version support changed and https://atom.io and https://atom.io/faq was not updated
  </details>

- [x] macOS : Native tabs (https://github.com/atom/atom/pull/14711)
  <details>
  <summary>Repro steps</summary>

  1. Open two atom windows on mac
  1. Go to View in menus and check `Show Tab Bar`
  screen shot 2017-06-03 at 5 10 32 pm
  1. Do this for both Atom windows.
  1. Drag one atom window to the other via tab bar

  **Expected:**
  Native Tab bar shows up and able to drag different windows to each other.  Also make sure UI isn't messed up.

  **Issues we've seen:**
  Native Tab Bar doesn't work and messes up UI when enabled
  </details>

- [x] Ubuntu with KDE: Menu uses 100% CPU (https://github.com/electron/electron/issues/8455, https://github.com/atom/atom/issues/13885)
  <details>
  <summary>Repro steps</summary>

  1. Install Atom on Ubuntu KDE.  
  1. Enable kde plasma global menu in System Settings -> Application Style -> Widget Style -> Fine Tuning tab -> Menubar style -> Application Menu widget -> Add a menubar Panel to desktop
  1. Start atom
  1. Try to use the desktop menu

  **Expected:**
  Desktop menu items work

  **Issues we've seen:**
  Desktop menu items do nothing when you click on things.
  </details>

- [x] macOS: Slovak QWERTZ (https://github.com/atom/atom-keymap/issues/223)
  <details>
  <summary>Repro steps</summary>

  1. Install Slovak keyboard layout on mac
  1. Open keyboard viewer to see the keys are are suppose to show up and open keyboard resolver on atom.
  1. hit `cmd+'`.

  **Expected:**  Resolves to `cmd+'` like it shows on keyboard viewer on mac.

  **Issues we've seen:** It resolves to `ctrl+§`
  </details>

- [x] macOS: IME jump (https://github.com/atom/atom/issues/15696)
  <details>
  <summary>Repro steps</summary>

  1. Install an IME layout, for example Chinese pinyin
  1. Type one character

  **Expected:**
  Expected the IME to be positioned at under the character you entered
  **Issues we've seen:** The IME window is in the top left corner. When you enter the second character it jumps to be positioned under the text
  </details>

---

/cc @codebytere

### CODE REVIEW

**Comment by jasonrudolph** [comment]
The core render tests are passing now. 😅 

Only two packages have failing tests: the archive-view package and the github package.

I'm hopeful that we can resolve the archive-view failures by:

1. Publishing a new release of ls-archive that incorporates with the changes in https://github.com/atom/node-ls-archive/pull/10 
2. Publishing a new version of archive-view that depends on the new version of ls-archive

I'll look into the github package failures next.

**Comment by jasonrudolph** [comment]
[Electron 2.0 uses Node 8.9.3](https://electronjs.org/releases#2.0.0). Atom's build currently uses Node 6.9.4 [A]. Should we update Atom's build to match the Node version used in Electron?

@as-cii: Do you happen to know whether the Node version in the Atom build needs to match the Node version that's in the version of Electron that we're using?

---

[A] There are a handful of places where we specify a dependency on Node 6.9.4. It's in [`.travis.yml`](https://github.com/atom/atom/blob/35f8977e898c03ec65c3f42d318969e82b7f75b7/.travis.yml#L18), [`appveyor.yml`](https://github.com/atom/atom/blob/35f8977e898c03ec65c3f42d318969e82b7f75b7/appveyor.yml#L22), and [`circle.yml`](https://github.com/atom/atom/blob/35f8977e898c03ec65c3f42d318969e82b7f75b7/circle.yml#L20-L21). And in the flight manual, we say that [you need Node.js 6.x or later](https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#requirements-1) to build Atom.

**Comment by Arcanemagus** [comment]
On the other hand, we should probably still have _something_ checking that Node.js v6 still works to build Atom, at least until it's maintenance period ends or we drop support for it due to this:

> And in the flight manual, we say that you need Node.js 6.x or later to build Atom.

**Comment by smashwilson** [comment]
Lol, what

```
AssertionError: More than one application to run tests against was found. /home/travis/build/atom/atom/out/app/node_modules/github/lib/atom,/home/travis/build/atom/atom/out/app/node_modules/github/test/atom,/home/travis/build/atom/atom/out/atom-1.28.0-dev-358d6dd-amd64/atom
```

The `lib/atom` folder within atom/github is relatively new. I'm guessing that's just tripping up some path location logic?

**Comment by smashwilson** [comment]
Okay, that's fixed. Those two dialog cancellation tests are still timing out on CircleCI, though.

**Comment by jasonrudolph** [comment]
> - [x] Get CI passing

✅😅 

Big thanks to @smashwilson. :zap:

**Comment by daviwil** [comment]
Nice work!  I'm building this branch now to dogfood it until we're ready to merge this PR.

**Comment by daviwil** [comment]
Built and ran Atom successfully from this branch!  One weird thing I noticed, our SVG-rendered Atom logo in the About screen is broken:

image

Did something change in the Chromium renderer related to SVG?

**Comment by daviwil** [comment]
@lee-dohm let me know that this problem shows up in 1.28-dev without the Electron 2.0 change, so that's not the culprit here!

**Comment by ckerr** [comment]
I'm super happy to see this getting unstuck. Thank you @jasonrudolph and @codebytere for doing this! :green_heart:

**Comment by simurai** [comment]
> @daviwil One weird thing I noticed, our SVG-rendered Atom logo in the About screen is broken

Seems unrelated to this branch, happens on master too. Made a new issue: https://github.com/atom/about/issues/78

**Comment by smashwilson** [comment]
For my own reference, here's the stacktrace that @jasonrudolph is seeing:

```
Uncaught (in promise) Error: Cannot find module '../node_modules/string_decoder/lib/string_decoder.js'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Users/j/github/atom/out/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Users/j/github/atom/out/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (file:///Users/j/github/atom/out/Atom.app/Contents/Resources/app.asar/static/index.js:40:43)
    at require (internal/module.js:11:18)
    at customRequire (/Users/j/github/atom/out/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at get_Decoder (/Users/j/github/atom/out/Atom.app/Contents/Resources/app/node_modules/split/index.js:12:37)
    at split (/Users/j/github/atom/out/Atom.app/Contents/Resources/app/node_modules/split/index.js:20:28)
    at /Users/j/github/atom/out/Atom.app/Contents/Resources/app/node_modules/what-the-status/index.js:37:18
    at new Promise (<anonymous>)
    at parse (/Users/j/github/atom/out/Atom.app/Contents/Resources/app/node_modules/what-the-status/index.js:16:16)
    at /Users/j/github/atom/out/Atom.app/Contents/Resources/app/node_modules/github/lib/git-shell-out-strategy.js:614:60
    at Generator.next (<anonymous>)
    at step (/Users/j/github/atom/out/Atom.app/Contents/Resources/app/node_modules/github/lib/git-shell-out-strategy.js:104:197)
    at /Users/j/github/atom/out/Atom.app/Contents/Resources/app/node_modules/github/lib/git-shell-out-strategy.js:104:367
    at <anonymous>
```

**Comment by smashwilson** [comment]
@jasonrudolph: I suspect the committing problem is a regression in Electron's asar integration - the fs-extra (or fs) module is no longer able to see directories within `/Users/smashwilson/src/atom/atom/out/Atom.app/Contents/Resources/app.asar/`.

**Comment by smashwilson** [comment]
Sidenote: I really really wish the package tests that run as part of the atom/atom builds ran against the _snapshotted and .asar-bundled_ code. There are a host of issues that can be introduced in that process and we have no way currently of catching them.

**Comment by jasonrudolph** [comment]
> I suspect the committing problem is a regression in Electron's asar integration - the fs-extra (or fs) module is no longer able to see directories within `/Users/smashwilson/src/atom/atom/out/Atom.app/Contents/Resources/app.asar/`.

@codebytere: Is this something you can help us with?

How to reproduce:

1. Install Atom built from this branch [[atom-mac.zip](https://7476-3228505-gh.circle-artifacts.com/0/Users/distiller/atom/out/atom-mac.zip)]
2. Open any git repository in Atom
3. Change a file and save it
4. Open the git tab and stage the changes
5. Click the "commit" button
6. Observe that the change was not committed
7. Open the console and observe the following error:
    > Uncaught (in promise) Error: ENOTDIR: not a directory, copyfile '/Applications/Atom.app/Contents/Resources/app.asar/node_modules/github/bin/git-askpass-atom.sh' -> '/tmp/github-11848-53871-116kyba.1tjh/git-askpass-atom.sh'

**Comment by jasonrudolph** [comment]
> #### Full-Width Alphanumeric (Google) - Japanese layout  (https://www.google.co.jp/ime/)
> **This should be tested on macOS**
> **macOS	:**
> - [ ] ✅   Verified

@Ben3eeE @ungb: Can you help me understand how to test this item from the test plan ☝️?

I installed and enabled that keyboard layout, but I don't know how to tell if it's behaving correctly.

**Comment by Ben3eeE** [comment]
@jasonrudolph I believe that item comes from https://github.com/atom/atom/issues/15696 and https://github.com/atom/atom/issues/15783. We should probably reference these issues in the test plan and expand the steps

**Comment by codebytere** [comment]
@jasonrudolph possibly! flying back to durham today, sorry for late follow-up!

**Comment by Ben3eeE** [comment]
@jasonrudolph Running this branch as part of daily work to see if I notice anything. I also tested some of the items in the test plan. Most of the Windows things are checked off already though :zap: 

**Big Files:**
It seems the rendering limit is now ~2 million lines which is a huge improvement and the bad rendering is no longer happening and we are back to everything just being black. We still can't click on the content past ~1 million lines because we never get a click event. The vertical scrollbar limit has also seems to have increased and is now the same as the rendering limit. I need to get another "really big file" soon because mine is only 2.8 million lines long :sweat_smile: 

image

**Loss of subpixel AA:**
I verified this and checked it off.

**Comment by jasonrudolph** [comment]
@codebytere: In case it helps, regarding the [problem committing from the GitHub package (i.e., the suspected asar issue)](https://github.com/atom/atom/pull/17273#issuecomment-387490306), it seems to be due a change that occurs somewhere between Electron 1.8.6 and Electron 2.0.0.

Committing from the GitHub package works when using the Electron 1.8.6 build of Atom from https://github.com/atom/atom/pull/16755.  But it fails when using the Electron 2.0.0 build of Atom from this pull request.

- [atom-mac.zip](https://7485-3228505-gh.circle-artifacts.com/0/Users/distiller/atom/out/atom-mac.zip) @ Electron 1.8.6
- [atom-mac.zip](https://7482-3228505-gh.circle-artifacts.com/0/Users/distiller/atom/out/atom-mac.zip) @ Electron 2.0.0

**Comment by jasonrudolph** [comment]
It seems that Atom loses [subpixel rendering](https://discuss.atom.io/t/how-can-i-tell-if-subpixel-antialiasing-is-working/18586) on macOS with Electron 2.0. (Subpixel rendering is working on Windows 10 and Ubuntu.)

Steps to reproduce:

1. Open a new buffer
2. Type any text (e.g., `abc`)
3. Take a screenshot
4. Zoom in real close
5. Observe absence of subpixel rendering

#### Atom 1.27-beta (using Electron 1.7)

screen shot 2018-05-09 at 10 51 46 am

#### Atom 1.28-dev (using Electron 1.8.6)

screen shot 2018-05-09 at 10 59 02 am

#### Atom 1.28-dev (using Electron 2.0.0)

screen shot 2018-05-09 at 10 52 18 am

---

@codebytere @ckerr: Is this something you can help us resolve?

**Comment by lee-dohm** [comment]
@jasonrudolph Depending on the DPI of your screen, [this may be expected](https://github.com/atom/atom/issues/10977#issuecomment-189483239). I'll try to find the Chromium bug tracker references I mention there for more details.

**Comment by jasonrudolph** [comment]
> @jasonrudolph Depending on the DPI of your screen, this may be expected. I'll try to find the Chromium bug tracker references I mention there for more details.

@lee-dohm: Thanks for pointing that out! That inspired me to check on my Retina display, and I am _indeed_ seeing subpixel rendering there. So, I'm going to remove [that item](https://github.com/atom/atom/pull/17273#issuecomment-387772838) from the list of regressions related to this upgrade.

**Comment by 50Wliu** [comment]
Here's a regression I'm seeing: branch name and push/pull status bar icons now show an underline when hovering whereas they didn't before.

github-underline

**Comment by jasonrudolph** [comment]
> I'm seeing: branch name and push/pull status bar icons now show an underline when hovering whereas they didn't before.

@50Wliu: Thanks for pointing that out. I'm pretty sure that's a change in the GitHub package, and not a result of the Electron upgrade. I installed Atom from the current master branch (using Electron 1.7.14) and then installed `github@0.14.0-3`, and I'm seeing those same underlines.

I'll ping the folks working on the GitHub package to see if they're aware of that change.

**Comment by jasonrudolph** [comment]
I'm trying to test the final item in the checklist, but I think the repro steps might be out of date:

> 1. Install Atom on Ubuntu KDE.
> 2. Enable kde plasma global menu in System Settings -> Application Style -> Widget Style -> Fine Tuning tab -> Menubar style -> Application Menu widget -> Add a menubar Panel to desktop

In the "Fine Tuning" tab, I don't see anything about "Menubar style."

image

@Ben3eeE or @daviwil: Would either of you happen to know what I need to do to replicate these setup steps? I'm using Ubuntu 18.04 and this version of KDE:

image

**Pull request merged**
