### PR TITLE
Try removing marked

### PR DESCRIPTION
**Pull request by icecream17**
I can't figure out why marked is needed. It seems like it's never used

### CODE REVIEW

**Comment by icecream17** [comment]
Ok, I see that it *is* used once in `spec`, but in an unused import.

**Comment by DeeDeeG** [comment]
`marked` was added in this commit (not part of a PR): https://github.com/atom/atom/commit/61651db0b07a9f4cef349c66b2d24165adf69679 and removed in https://github.com/atom/atom/pull/12903 (specifically here: [diff](https://github.com/atom/atom/pull/12903/files#diff-ead5e9aa04941cb232e75ec036298fd488e390a95db368f8a429aefdb567a5e8)).

_(I got this from trawling through the [`git blame`](https://www.git-scm.com/docs/git-blame) (for example, [here](https://github.com/atom/atom/blame/v1.57.0/package.json#L122)) of `package.json` and `spec/atom-reporter.coffee`...)_

If I understand correctly, it was used to render some logging output as fancy markdown, which I presume was only seen while running the tests. But that's from just a quick look, so I might be wrong. In any case, all use of `marked` directly in Atom core (not as a sub-dependency of another package) does seem to have been removed.

**Comment by icecream17** [comment]
Hmm, settings-view says `^1.2.0` but I wonder if `1.2.9` actually breaks settings-view somehow
https://github.com/atom/atom/blob/0ede4a6ec190643aeea6f624a0b24f07a77013fc/package-lock.json#L7070-L7081

**Comment by DeeDeeG** [comment]
Yeah, I just did some CI runs to test that, looks like it to me.

:x: This PR: https://dev.azure.com/DeeDeeG/b/_build/results?buildId=1189&view=results
:heavy_check_mark: This PR, but revert `package-lock.json` changes https://dev.azure.com/DeeDeeG/b/_build/results?buildId=1188&view=results

Given these results, I think reverting the change in `package-lock.json` should do it. (I don't really understand how `package.json` can be updated by this PR and have no effect on `package-lock.json`, but it looks like that's correct somehow. Deduping is weird I guess?)

**Review by sadick254 — APPROVED** [review]

**Pull request merged**
