### PR TITLE
Upgrade electron to fix command-backtick bug

### PR DESCRIPTION
**Pull request by maxbrunsfeld**
Fixes https://github.com/atom/atom/issues/10852

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
Ok for me, command-backtick now works immediately, instead of failing to work for the first few seconds after startup. @joshaber Hopefully the worse behavior that you were seeing will be resolved as well.

**Comment by joshaber** [comment]
:boom: :camel:

**Comment by lee-dohm** [comment]
@amytruong you may want to play with this too?

**Comment by amytruong** [comment]
:+1: @lee-dohm

**Comment by amytruong** [comment]
I think I may have found a (pretty small) issue. 
Verifying this on master, I noticed:
cmd-backtick switches windows from oldest to newest
cmd-shift-backtick switches from oldest to newest

On beta:
cmd-backtick: newest to oldest
cmd-shift-backtick: from oldest to new

**Comment by joshaber** [comment]
Great find @amytruong! I opened https://github.com/atom/electron/issues/4577 about this.

**Comment by abe33** [comment]
Hmm, sorry to butt-in this late, but running on master (1.7.0-dev-f88051e) I don't see any fix on this. I'm using a french keyboard with custom layout to remove the dead key on backticks. Has it been reported already?

**Comment by joshaber** [comment]
@abe33 I haven't seen any reports like that. An issue would be great!

**Comment by abe33** [comment]
@joshaber sorry, I didn't see your reply, creating one right away.

**Comment by simplyandyg** [comment]
I'm running Atom Version 1.15 and still seam to have this issue where command-back tick does not seem to register with Atom. When using the Keybinding Resolver and pressing command + back tick, only cmd shows up in the Resolver.

Command + back tick combo is working fine for other apps on my comp such as Chrome.

**Comment by lee-dohm** [comment]
@simplyandyg Please open a new issue and fill out the bug template so that we can properly triage this.

**Comment by simplyandyg** [comment]
@lee-dohm my bad. Figured out my issue. Not a problem with Atom. I'll try to stop being such a newb.

**Comment by lee-dohm** [comment]
> But the Keybinding Resolver does still show that only cmd was pressed. I can open an issue for that.

This isn't a bug. The OS intercepts some keybindings and Atom doesn't receive them. There's really nothing we can do about that.

**Comment by simplyandyg** [comment]
@lee-dohm okay, that makes sense. I was curious if something like that might be the reason, which is why I hadn't opened a bug yet. Thanks for the info!

**Pull request merged**
