### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by lukecaputo**
change spelling: "judgement" to "judgment".

### CODE REVIEW

**Comment by 50Wliu** [comment]
So this is really interesting.  I've always spelled it as `judgement`, and Chrome's dictionary tells me that it's a valid word.  However, when searching it up on Google, the word is `judgment` but underneath it says `noun: judgement`.
Looks like this is a case of American English vs British English again.
Also...http://grammarist.com/spelling/judgment-judgement/

**Comment by lukecaputo** [comment]
"If you write “judgement” you should also write “colour.”"

I didn't realize there were multiple accepted spellings for this. Learn something new every day!

**Comment by kevinsawicki** [comment]
I'm going to cite the definitive source on this

**Comment by thomasjo** [comment]
> I'm going to cite the definitive source on this

Haha, brilliant, Sir. Simply brilliant :skull:

**Pull request merged**
