### PR TITLE
Fix context menu right click not working ( alternative fix )

### PR DESCRIPTION
**Pull request by asturur**
### Identify the Bug

The upgrade to electron 9.4.4. broke the context menu click.
The issue is tracked in #22018

The stack trace point to the fact that they payload for the message is no more serializable
The change in the api that broke the code should be this:
https://www.electronjs.org/docs/breaking-changes#behavior-changed-values-sent-over-ipc-are-now-serialized-with-structured-clone-algorithm

### Description of the Change

My fix was to remove the reference to atomWindow from the payload, the part that is not serializable.

### Alternate Designs

There is also this other fix here that i noticed after making this one:
https://github.com/atom/atom/pull/22046

### Possible Drawbacks

Well a value removed from the payload can of course have drawbacks.
I have no understanding why we are sending a reference to the window in the payload if we are sending the message to that exact same window.

Does anyone knows why that is needed?
The window is probably a large object and serializing it won't let the instance itself travel with the message, but it should become just a bunch of data.

### Verification Process

The only verification process is me trying the right click menu on my local build on macosx and the PR tests

### Release Notes

- fixes right click menu on atom with electron 9+

### CODE REVIEW

**Comment by fahad12346** [comment]
https://www.electronjs.org/fiddle

**Comment by asturur** [comment]
@sadick254 you have any idea what we do with that command detail there?

**Comment by asturur** [comment]
hi @darangi, i see we have a fix and we can close this PR now.
I was looking into insight of what we do with this extra command detail in the message.
Any information you can give?

**Comment by aminya** [comment]
Doesn't this fix #22024 by coincidence?

**Comment by asturur** [comment]
Not sure.
The issue was atomWindow property not being serializable under electron 8, Atom stop running the right click command event, and not complaining about it at all.

If some of those issue are stopping Atom to complete the tests, yes this pr ( and the merged one ) could have already fixed it.

My solution was to remove it, since everything was working without it.
@darangi solution was to serialize it with structured clone library, but i would love to understand what atom is doing with that property. Because i could not find a use for it.

**Comment by asturur** [comment]
Still interested in the topic :D anyone available?

**Comment by aminya** [comment]
Is `commandDetail.atomWindow` used anywhere?

**Comment by asturur** [comment]
That is what i was trying to look into. Is not used in atom codebase at all, not with a  full text search at least.
I understand the fix we merged for the menu is safer, but it also add a new dependency to the project ( for how much is small ) and to me this seems like the moment to look into it. From git blame it was added in 2014
https://github.com/atom/atom/commit/9128041c202e89b57a8014f4a18b6276019087c2

But i m not sure how that value is used since the atomWindow is serialized and not more a reference to the original window.

I compiled the version with this commit 5 days ago and i m using it waiting for the fixed nightly to come out.

@sadick254  or @darangi do you have any insight?

**Comment by sadick254** [comment]
@asturur `item.commandDetail.atomWindow` is not used anywhere in the codebase but passed around and sent as args to the receiver of the `context-command` action. https://github.com/atom/atom/blob/master/src/main-process/atom-window.js#L378

Since the context menu has already been fixed can we safely close this?

**Comment by asturur** [comment]
i know is passed, but if you look at the command, those are just strings and do not seems to use the reference to a copied data of the atom window anywhere.
What data is in the atom window we need for the context menu to work?
I do not mind about the PR we can close it, i mind about the conversation if is possible.

- was preserving this property the best thing to do?
- is a serialized version of the instance useful at all?

If we can ditch the property and not add a dependency, isn't better?

**Comment by sadick254** [comment]
I have done a little bit of digging into the source code. I can't see anywhere where we use the passed `atomWindow` reference.  Removing `atomWindow` would be ideal as the serialized version isn't useful at all.

Right now we have a failing CI due to the [first context menu fix](https://github.com/atom/atom/pull/22046). Could you include a revert commit of that change on this branch?

**Comment by asturur** [comment]
Sure i think i can. I got a failing build too and i fixed with the second commit. I ll update it tomorrow early for me

**Comment by asturur** [comment]
Seems like now this PR is affected by timeouts in windows

**Comment by darangi** [comment]
> Seems like now this PR is affected by timeouts in windows

Yeah, a CI re-run will resolve that

**Comment by darangi** [comment]
Thanks for the contribution 🙇🏾  @asturur

**Comment by aminya** [comment]
@asturur Thanks for your perseverance on the topic. This kind of non-trivial contribution is very interesting and valuable!

**Comment by asturur** [comment]
i stubbornly use atom while evetyone tells me to switch to vscode. I m happy to help and to learn electron.js

**Pull request merged**
