### PR TITLE
GitHub 0.36.5 to beta

### PR DESCRIPTION
**Pull request by smashwilson**
Upgrade the GitHub package on the beta channel to the latest release.

### CODE REVIEW

**Review by tomas1971 — APPROVED** [review]

**Review by tomas1971 — APPROVED** [review]

**Review by bullibasti — COMMENTED** [review]
@tomas1971

**Comment by aminya** [comment]
This should be updated now after merging #21903

**Review by aminya — CHANGES_REQUESTED** [review]
This should be updated now after merging #21903

**Comment by smashwilson** [comment]
Nah, I'd need to create a new PR to backport to beta, because the beta release branch is different now.

**Pull request closed without merging**
