### PR TITLE
Remove deprecated code

### PR DESCRIPTION
**Pull request by thomasjo**
:warning: WIP :warning: 

**NOTE**: This PR is currently based on #7877. We should rebase this on top of `master` once #7877 gets merged.
## 

Refs https://github.com/atom/atom/issues/5164

### CODE REVIEW

**Comment by benogle** [comment]
Thanks for taking this on @thomasjo

**Comment by nathansobo** [comment]
Working on rebasing this and finishing it off today.

**Comment by nathansobo** [comment]
Snagged on some ThemeManager spec failures... getting close though. @thomasjo if you want to step back in, just let me know.

**Comment by nathansobo** [comment]
All the remaining Grim references should be necessary to support post 1.0 deprecations and the deprecation infrastructure in general.But there may be infrastructure for supporting deprecated code paths that I somehow missed, but no references to to `shouldIncludeDeprecatedAPIs` or obvious deprecations remain.

I still want to remove the dependency on `serializable`, before merging this. Shouldn't take long.

**Comment by thomasjo** [comment]
@nathansobo I can step back in when I get back from my vacation, so this coming weekend.

**Comment by nathansobo** [comment]
Thanks for getting this started @thomasjo!

**Comment by as-cii** [comment]
Awesome! :clap: :clap: :clap:

**Pull request merged**
