### PR TITLE
Fix #14716: Error when deserializing TreeView for project

### LINKED ISSUE #14716: Uncaught Error: Setting active pane that is not present in pane container
[Enter steps to reproduce:]

@ungb's repro steps from [below](https://github.com/atom/atom/issues/14716#issuecomment-322986916):

1. Open Atom with a project.
2. Rlight Click `Close pane` in the tree-view,  Notice nothing happens
3. right click and remove the project.
4. Tree-view disappears,  Toggle it back open
5. right click and click add folder back
6. Tree view remains empty and if you open dev tools you see error from https://github.com/atom/atom/issues/14454#issuecomment-322984675
7. close tree-view and open it back up and left click on the `tree view`.

---

1. Open Atom
2. Open a recently opened project folder
3. Open/reopen tree pane a few times
4. Click/right-click tree pane a few times

**Atom**: 1.18.0-beta2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Setting active pane that is not present in pane container

```
At /Applications/Atom Beta.app/Contents/Resources/app/src/pane-container.js:253

Error: Setting active pane that is not present in pane container
    at PaneContainer.didActivatePane (/Applications/Atom Beta.app/Contents/Resources/app/src/pane-container.js:253:21)
    at Pane.module.exports.Pane.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/pane.js:875:20)
    at Pane.module.exports.Pane.focus (/Applications/Atom Beta.app/Contents/Resources/app/src/pane.js:269:25)
    at atom-pane.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/src/pane-element.js:51:25)
```

### Commands

```
     -0:36.7.0 window:toggle-full-screen (input.hidden-input)
     -0:32.2.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-material-syntax.theme-one-dark-ui)
     -0:21.8.0 application:reopen-project (div.tool-panel.tree-view)
  4x -0:17.1.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-material-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
atom-clock 0.1.8 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-terminal-tab 0.2.0 
build 0.68.0 
build-make 0.13.0 
clojure-indent 0.2.0 
django-atom 0.2.4 
file-type-icons 1.3.4 
fizzy 0.21.0 
git-time-machine 1.5.9 
hyperclick 0.0.40 
hyperlink-hyperclick 1.3.4 
improved-chester-atom-syntax 0.3.0 
ink 0.6.5 
language-crystal-actual 0.35.0 
linter 2.1.4 
linter-ruby 1.2.5 
linter-ui-default 1.6.0 
one-tab 0.10.0 
proto-repl 1.4.20 
release-notes 0.53.0 
scroll-through-time 0.2.0 
symbol-gen 1.3.1 
tab-title 0.3.3 
tree-ignore 0.6.2 
typewriter 0.7.0 
unfancy-file-icons 0.11.0 
wakatime 7.0.3 
```

### PR DESCRIPTION
**Pull request by daviwil**
This change fixes an issue that appears when the user removes the last
project from the workspace and then re-adds it.  At this time an error
is thrown from within ItemRegistry because the PaneContainer that
holds the TreeView in the left-most dock does not clear out its
existing ItemRegistry before deserializing the old TreeView state.

The fix is to create a new ItemRegistry when a PaneContainer is
deserialized so that the previous Pane's items are not retained.

### CODE REVIEW

**Comment by daviwil** [comment]
The `Setting active pane that is not present in pane container` error that some users have experienced as a result of this bug isn't reproducible on 1.25.0-dev as of today, so I think it must have been fixed elsewhere.  This fix resolves the core issue, that the pane containing the TreeView is left in a broken state after it doesn't deserialize correctly.

**Comment by daviwil** [comment]
Also noticed that [src/item-registry.coffee](https://github.com/atom/atom/blob/master/src/item-registry.coffee) looks like a pretty easy candidate for decaffeination, is it cool if I do that here or in a separate PR?

**Comment by maxbrunsfeld** [comment]
> is it cool if I do that here

:+1:

**Review by maxbrunsfeld — APPROVED** [review]

**Comment by daviwil** [comment]
Thanks!  Added the decaffeinated file

**Pull request merged**
