### PR TITLE
Fix install on a symlinked $INSTALL_DIR/bin

### PR DESCRIPTION
**Pull request by n-riesco**
The installation script `script/grub install --install-dir $INSTALL_DIR`
is broken on linux machines if `$INSTALL_DIR/bin` happens to be a
symlinked folder.

This PR fixes the installation task `build/tasks/install-task.coffee`
and the launching script `atom.sh` to allow for symlinked folders.

### CODE REVIEW

**Comment by lee-dohm** [comment]
I'm going through old PRs to see if they can be salvaged or should be closed. Is this something that should still be updated or fixed?

**Comment by n-riesco** [comment]
This still seems to be an issue with atom v1.5.0-beta3 :

```shell
$ script/build --build-dir ~/install/atom-build
Node: v0.10.25
npm: v2.13.3
Installing build modules...
=> Took 2310ms.

Installing apm...
=> Took 790ms.

Deleting old packages...
/home/user/install/atom/apm/node_modules/atom-package-manager/bin/apm: line 28: /home/user/install/atom/apm/node_modules/atom-package-manager/bin/node: No such file or directory
```

I will rebase this PR and check whether it still fixes the problem.

**Comment by n-riesco** [comment]
Travis fails with `Error Downloading Update: Could not get code signature for running application`.

I don't see how this is related to this PR. Is there anything else I could do?

**Comment by 50Wliu** [comment]
Both failures are because of a language-javascript update that I pushed to master without testing, sorry about that!  I'll work on fixing them.  You can safely ignore them in the meantime.

**Comment by damieng** [comment]
The build system has been totally rewritten since this PR and doesn't use grunt any more. Please file a new issue if this is still a problem.

**Pull request closed without merging**
