### PR TITLE
Add option editor.showCursorWhenSelecting - Cursor Visible While Selecting

### PR DESCRIPTION
**Pull request by colelawrence**
This is a very common feature for most IDEs, I've used the same identifier as CodeMirror's option in this case `showCursorWhenSelecting`.

This is a very small fix for something that cannot be addressed with a plugin AFAIK, thank you.

image

### CODE REVIEW

**Comment by ZombieHippie** [comment]
I will create my test cases for this, and then resubmit this pull request.

**Comment by ZombieHippie** [comment]
Unable to run tests on Windows which is a bummer for people that want to contribute, I'll look for an issue similar to this topic, or make one.

**Comment by ZombieHippie** [comment]
Please restart the travis ci build tests.

**Comment by 50Wliu** [comment]
Restarted.

**Comment by ZombieHippie** [comment]
Will address the aforementioned spec error and reopen.

**Pull request closed without merging**
