### PR TITLE
Add ELECTRON_NO_ATTACH_CONSOLE in BufferedNodeProcess

### PR DESCRIPTION
**Pull request by BinaryMuse**
Potential fix for #11471

### CODE REVIEW

**Comment by Arcanemagus** [comment]
This fixes the test case for me in v1.8.0-beta0 :tada:

**Comment by Arcanemagus** [comment]
Fixed it in `linter-jshint` as well.

**Comment by Altiano** [comment]
Is this fix the issue of developing electron app on Atom (need to add `set ATOM_SHELL_INTERNAL_RUN_AS_NODE=" ` on terminal-plus plugin before run `electron .`)

**Comment by lee-dohm** [comment]
@Altiano the environment variable `ATOM_SHELL_INTERNAL_RUN_AS_NODE` was renamed to `ELECTRON_RUN_AS_NODE` some time ago. I don't know about running Electron apps from inside Atom using terminal-plus. This isn't intended as a fix for that since it isn't a bug that I am aware of. If there is an open Issue somewhere for it, please post a link so that I can read up on it :grinning:

**Comment by Altiano** [comment]
I don't know if there is an issue in here but there is on termianl-plus: https://github.com/jeremyramin/terminal-plus/issues/96

**Pull request merged**
