### PR TITLE
Update subword regex

### LINKED ISSUE #7656: Add non-English letters to subword regex
I made some changes to my subword regex after I submitted the Atom PR.  One being I added support for non-English characters to the regex.  I'm willing to submit a fix, but wanted to get a issue started in case there are objections.

Basically, I use these in the regexes:
```coffee
lowercaseLetters = 'a-z\\u00DF-\\u00F6\\u00F8-\\u00FF'
uppercaseLetters = 'A-Z\\u00C0-\\u00D6\\u00D8-\\u00DE'
```
https://github.com/dsandstrom/atom-subword-navigation/blob/b579b03bb95e6a2cdb634a7411b40cb29bd6c5c4/lib/subword-navigation.coffee#L62

### PR DESCRIPTION
**Pull request by dsandstrom**
Fixes #7656 #7658

I added underscore to the snake case/camel case regex segments so that we can skip over it when moving right and left.  In addition, I added non-English letters to the subword regex for better compatibility.

Sorry about combining these into one PR, but I thought it would save time and hassle.

### CODE REVIEW

**Comment by nathansobo** [comment]
Thanks so much @dsandstrom. Really appreciate the attention to detail on this one.

**Comment by dsandstrom** [comment]
Thanks @nathansobo.  I got the Atom Merit Badge in the mail yesterday.  Very nice of you guys.

**Comment by nathansobo** [comment]
Glad you got it. We thought it would be cool to thank contributions like this with some atoms in addition to electrons.

**Comment by benogle** [comment]
> with some atoms in addition to electrons

We mashed them together with all the love in the world. Seriously thanks for contributing :heart:

**Pull request merged**
