### PR TITLE
⬆️ Bump github@0.36.8

### PR DESCRIPTION
**Pull request by asturur**
Bump github package from `0.36.7` to  `0.36.8`

### CODE REVIEW

**Review by sadick254 — COMMENTED** [review]
Don't forget to update GitHub under `packageDependencies` and fill out the PR details.

**Comment by asturur** [comment]
I did not even know that part of package.json

**Comment by sadick254** [comment]
`packageDependencies`  is specific to Atom and contains packages that Atom ships with.

**Review by sadick254 — APPROVED** [review]

**Comment by aminya** [comment]
This PR should have gone to the master branch.

**Comment by asturur** [comment]
that will be handled by the dependabot right?

**Comment by aminya** [comment]
It should, but when you make a manual PR please merge it to master unless it really depends on the target branch.

**Pull request merged**
