### PR TITLE
Improve the Windows build process

### PR DESCRIPTION
**Pull request by damieng**
Gradually improving the Windows build experience, so far:
- **clean** deletes all specified folders (doesn't stop on first missing one)
- **build** removes any path entry containing a msbuild.exe (avoids node-gyp errors)

### CODE REVIEW

**Comment by SaadLaggoune** [comment]
yeah, you are right, but windows version have a lot things wrong, sometimes i can't write '}' it's make me made, Atom Editor is good but needs to improve Windows OS experience .

**Comment by damieng** [comment]
Hi @SaadLaggoune this PR is specifically about improving the build process itself. There are various issues and improvements for Windows happening right now - keep an eye on the Windows tags on PR and Issues for more updates.

**Comment by ZombieHippie** [comment]
@damieng are there things we can work on to expedite run spec test suites on Windows? Thanks for putting some focus in this direction.

**Comment by damieng** [comment]
Feel free to investigate any specs failures on Windows and set-up PR's for them.  Right now a couple of them actually crash atom so I'd recommend using the prefix-with-f trick to run individual specs - e.g. 'fdescribe' instead of describe to just run that spec suite. Once fixed remove the f.

I'm trying to nail down the path issues right now of which there are many as various url/libs try and treat windows paths as linux paths and invert the slashes.

**Pull request merged**
