### PR TITLE
⬆️ spell-check 0.74.2

### PR DESCRIPTION
**Pull request by Arcanemagus**
### Requirements for Contributing a Bug Fix

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only fix an existing bug. To contribute other changes, you must use a different template. You can see all templates at https://github.com/atom/atom/tree/master/.github/PULL_REQUEST_TEMPLATE.
* The pull request must update the test suite to demonstrate the changed functionality. For guidance, please see https://flight-manual.atom.io/hacking-atom/sections/writing-specs/.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see https://github.com/atom/atom/tree/master/CONTRIBUTING.md#pull-requests.

### Identify the Bug

https://github.com/atom/spell-check/issues/210

### Description of the Change

Update spell-check to v0.74.2.

### Alternate Designs

N/A.

### Possible Drawbacks

A bug was introduced in https://github.com/atom/spell-check/pull/271 that breaks something else.

### Verification Process

Atom was launched in development mode with the changes applied verifying that the fix worked.

### CODE REVIEW

**Comment by daviwil** [comment]
Hey @Arcanemagus, can you also update [this line](https://github.com/atom/atom/blob/f25e61adb530feb4ff4557f0c1797e09ce121df1/package.json#L221) in `package.json`?  The tarball line gets updated automatically once you run `script/bootstrap` after changing the package version in the `packageDependencies` section so you'll never have to touch that one manually.

**Comment by noname2534** [comment]
ในวันที่ พ. 26 ก.ย. 2018 23:51 David Wilson <notifications@github.com>
เขียนว่า:

**Comment by Arcanemagus** [comment]
Updated, ran `./script/bootstrap` again just to make sure that didn't change anything else 😉.

**Comment by daviwil** [comment]
Thanks a lot!  Once the CI goes green again I'll merge it ✨

**Pull request merged**
