### PR TITLE
Bug in moving selected lines down

### PR DESCRIPTION
**Pull request by Aakash1312**
There was a bug in moving lines down. 
The bug can be reproduced in the following steps:
- Make a text file with last line blank
- Select the entire row of third last line
- Try moving down. It won't move

output

### CODE REVIEW

**Comment by nathansobo** [comment]
Hi @Aakash1312... after testing this out it's not clear how the behavior differs. Can you post 2 animations, 1 with the original behavior and one with the change applied.

**Comment by Aakash1312** [comment]
@nathansobo 
Here is the gif without change:
output2

and here is the fix
output

as you can see, you cannot move the selected line down beyond line number 7 in the first part.

**Comment by benogle** [comment]
Is this still an issue @Aakash1312? If so, can you rebase on master and write a spec?

**Comment by benogle** [comment]
I cannot reproduce at this time. Closing. @Aakash1312 if you can reproduce it still, feel free to reopen.

**Pull request closed without merging**
