### PR TITLE
Update all native modules and their dependents to Nan 2

### LINKED ISSUE #8508: Atom will not build against iojs 3.2.0+ / node 4
I have commented on the node-runas issue which I believe to be the cause of this, but perhaps it should be a new issue (and will get more exposure here):

```
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:682:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.17
gyp ERR! command "/usr/bin/iojs" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/SBo/atom-1.0.7/build/node_modules/runas
gyp ERR! node -v v3.2.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 3.10.17
npm ERR! argv "/usr/bin/iojs" "/usr/bin/npm" "--userconfig=/tmp/SBo/atom-1.0.7/build/.npmrc" "install" "--loglevel" "error"
npm ERR! node v3.2.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/SBo/atom-1.0.7/build/npm-debug.log
```

Here is the full npm-debug.log: https://gist.github.com/ryanpcmcquen/8e798b2d172b96c5d9ab

And the node-runas issue:

https://github.com/atom/node-runas/issues/11

### PR DESCRIPTION
**Pull request by zcbenz**
This is independent from #8779 and doesn't require an update of Electron. The good thing is all native modules are now update-to-date, and we no longer need to worry the build would break when we update a module or package to a later version.

The only change is to update the modules to use Nan 2, the build is green, but we might probably encounter bugs due to the update.

Fixes #8508

/cc @as-cii @nathansobo

### CODE REVIEW

**Comment by 50Wliu** [comment]
Since this bumps all NaN dependencies to ^2, this should fix #8508 right?

**Comment by zcbenz** [comment]
> Since this bumps all NaN dependencies to ^2, this should fix #8508 right?

Yeah it should be able to fix that.

**Comment by as-cii** [comment]
This looks good to me, I'll try to build it later today and see if anything breaks. If after a first :eyes: it works fine I think we can just :ship: it.

Thanks, @zcbenz!

**Comment by paulcbetts** [comment]
:clap:

**Comment by as-cii** [comment]
I haven't noticed any regression so far, so I think this could be :ship:ped as soon as the merge conflicts get fixed. 

Great job, @zcbenz! :star2:

**Pull request merged**
