### PR TITLE
Support `atom` protocol links when links are handled

### LINKED ISSUE #16888: Atom/Core URL handler support for Markdown inside Datatip
### Prerequisites

 [ X]   * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
 [ X]   * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
[ X]    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
[ X]    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
[ X]    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

MD preview and MD datatips (hovers) don't support `atom/core` URL handlers from #15935. Would be useful if I want to provide source code links inside the datatip (hover)

### Steps to Reproduce

1. Create an MD file with a link similar to `[This is a link](atom://core/open/file?filename=<path to file>)`
2. Open MD preview
3. Click on the link - nothing happens. At the same time if one switches the URL to `http://www.bbc.com` the link would work

**Expected behavior:**
The file specified by its path open in Atom text editor

**Actual behavior:**
Core URLs not supported

**Reproduces how often:**
100%

### Versions
All verions up to 1.25-beta2

### Additional Details
Looking for directions... What to look at if I am to provide a patch for this

### PR DESCRIPTION
**Pull request by BoykoAlex**
### Requirements

Should fix #16888 Markdown preview and hover/datatips MD links with `atom://` URLs should have the right handling.

### Description of the Change
This seems to be the right spot to fix it, however there might be a more elegant solution invoking the URI handler since `urlHandlerRegistry` seem to be meant to be a private member rather than public. Nevertheless, it makes the use case I had trouble with work nicely.

### Why Should This Be In Core?
`atom://` registry and handling points belongs to the core

### Benefits
Ability to put source links in hover documentation

### Possible Drawbacks
Not sure

### Verification Process
Ad-hoc manual testing of MD preview and hovers containing valid `atom://` links

### Applicable Issues
#16888

### CODE REVIEW

**Comment by BoykoAlex** [comment]
Is there stuff to fix for me? Please let me know :-)

**Comment by daviwil** [comment]
Hey @BoykoAlex, sorry for the delay.  I've been seeing some weird CI failures during the snapshot phase that I can't explain so I'm going to restart it again to see if it's resolved.  If it's still broken we may need to investigate further!

**Comment by UziTech** [comment]
Any update on this?

**Comment by daviwil** [comment]
Finally got a [clean VSTS build](https://github.visualstudio.com/Atom/_build/results?buildId=6371&view=logs), merging this now.  Thanks @BoykoAlex!

**Pull request merged**
