### PR TITLE
Add that atom can be built with iojs 2.x

### PR DESCRIPTION
**Pull request by ryanpcmcquen**
Confirmed here: https://github.com/atom/atom/issues/8508

### CODE REVIEW

**Comment by 50Wliu** [comment]
Can you also update `windows.md` and `osx.md`?  Thanks :)

**Comment by ryanpcmcquen** [comment]
@50Wliu squashed and done!

**Comment by 50Wliu** [comment]
Windows actually needs two places where it needs updating (see Windows 8) :wink:.

**Comment by ryanpcmcquen** [comment]
Oops! @50Wliu should be good now. :shipit:

**Comment by 50Wliu** [comment]
:+1:

**Pull request merged**
