### PR TITLE
Refactor install script for linux (install dev channel parallel, use icon themes)

### LINKED ISSUE #12993: Icon looks bad on GNOME
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

The Atom icon looks bad on GNOME. On KDE and Unity the icon looks as expected.

atom-icon-switcher
atom-icon-topbar
emacs-icon-topbar

(Make sure to view images at 100% to see the problem)
### Versions

``` bash
$ atom-beta --version
Atom    : 1.12.0-beta1
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0

$ apm-beta --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.10.1

$ gnome-shell --version
GNOME Shell 3.22.0
```

### PR DESCRIPTION
**Pull request by MoritzKn**
### Description of the Change

* Some refactoring on the install script (mainly on the linux part) (1.-3. commit).
* Change the install script to create a separate installation for the dev channel (`atom-dev`) like it is already done for the beta channel (`atom-beta`) (4. commit).
* Change the way icons are handled in the xdg desktop file. This replaces the absolute path used previously with a icon name. The name will then be interpreted by the desktop environment, which in turn selects the icon from a icon theme. This is also how the desktop files in the dep and rpm packages already work. (5. commit).
* Change the install script to copy the application icons (in all resolutions) to the default icon theme. This is required to make to point above work when no alternative icon theme is used or the alternative icon theme does not provide an icon. (5. commit).

### Alternate Designs

None

### Why Should This Be In Core?

* Refactors core code.
* The beta channel is already installed in parallel so the dev channel should be too.
* The new way desktop files are handled is more "linuxy" and preferable as default.

### Benefits

* Cleaner code
* Allows all channels to be installed in parallel.
* Users are able to use alternative icon themes with atom; makes atom more hackable.
* The desktop environment gets to choose between different resolutions.
* Aligns the way the manually installed version behaves with the what is installed from a package.

### Possible Drawbacks

None known

### Applicable Issues

* Perhaps fix #12993 (icon scaling issue).
* Fixes icon behavior mentioned in #14480 (wrong icon path). This is fixed with the 2. commit and with the alternative design from the 5. commit.

### CODE REVIEW

**Comment by MoritzKn** [comment]
I just noted that the parallel installation of the dev channel can't work, because the shell script at `/usr/local/bin/atom-dev` won't execute `/usr/local/share/atom-dev/atom`. Still have to find a solution for that...

**Comment by ungb** [comment]
@daviwil any chance you can take a 👀  at this PR?

**Comment by daviwil** [comment]
Sure!  @MoritzKn, your last comment indicates you still had a problem to solve but I see you've made some commits since then.  Is the script done at this point?  I'll give it a try in a little while :)

**Comment by daviwil** [comment]
This is pretty cool!  I like the .desktop entry creation for Atom Dev:

image

I've also tested your changes on Windows and macOS and I don't see any negative impact to the existing installation behavior there.  It'd be nice to have something similar for macOS too, I might take a shot at that sometime in the future :)

I'll check with other folks on the team tomorrow to see if there's anything else we need to verify before merging this.  Thanks a lot for your work here!

**Comment by MoritzKn** [comment]
> your last comment indicates you still had a problem to solve but I see you've made some commits since then. Is the script done at this point?

The PR is done. I fixed the problems mentioned in the last comment with the following comments. Sorry for the confusion; should have added another comment to clearify.

**Comment by daviwil** [comment]
Thanks a ton for putting this together @MoritzKn!

**Pull request merged**
