### PR TITLE
Oxford Comma

### PR DESCRIPTION
**Pull request by lukecaputo**
Add a comma.

### CODE REVIEW

**Comment by lukecaputo** [comment]
What is invalid about correcting the README's grammar errors?

**Comment by 50Wliu** [comment]
Sorry, under other circumstances I would have elaborated.  It's just that we've been getting a lot of low-quality and/or conflicted PRs lately (see the closed PRs list) so I've been quick to close them.

Your PR fell in the second category.  I'm not sure if you noticed, but your fork is currently 7742 commits behind `master`.  The current README does not contain the grammar error you were attempting to fix.  Thanks for the intention though :smile:.

**Comment by lukecaputo** [comment]
The volume of PRs is understood, however, that sentence *is* grammatically incorrect. 1, 2, and 3; not 1, 2 and 3. Keep the PR closed, but understand the correct usage and employment of commas in the English language. 😁

**Comment by thomasjo** [comment]
@lukecaputo You're misreading what @50Wliu has written; your fork of the Atom source code is 7742 commits *behind* the `master` branch in [atom/atom](https://github.com/atom/atom). You need to sync your fork with the upstream changes.

<p align="center">lukecaputo_atom__the_hackable_editor</p>

Additionally, as noted by @50Wliu, your change is invalid because the text you changed no longer exists in the [*current* README.md](https://github.com/atom/atom/blob/1b6cc82e978cefa3571e4efa9612e4d4751e04a5/README.md#documentation)

Finally, the usage of the oft-named *Oxford comma* is not a requirement in the (international) English language, and has nothing to do with grammar. Because I'm busy, I'll lazily refer you to the Wikipedia article on the [serial comma](https://en.wikipedia.org/wiki/Serial_comma).

**Comment by lukecaputo** [comment]
Perfectly understood, thank you. That is my fault. 

I'm not ignorant to the oxford comma's usage. However, someone can't use it two sentences above, then claim they don't use it in a different spot. It's use was deliberate in meaning and continuity.

**Comment by thomasjo** [comment]
> However, someone can't use it two sentences above, then claim they don't use it in a different spot. It's use was deliberate in meaning and continuity.

That's a perfectly valid reason for changing it. Consistency is good 👍 
If you find further inconsistencies (in the current documentation), don't be afraid to submit PRs. 

Thanks for wanting to help out! 🙇

**Pull request closed without merging**
