### PR TITLE
Build on Windows 8.1 with msysgit

### PR DESCRIPTION
**Pull request by damccull**
More detailed documentation on how to build on windows 8.1 with msysgit. One issue I've found with this is that the package manager doesn't download packages right because of git not being on the path. I'll update as I figure it out.

If anyone knows how to specify the location of git binaries without having it on the path, please let me know.

### CODE REVIEW

**Comment by lee-dohm** [comment]
I'm going through old PRs to see if they can be salvaged or should be closed. Is this something that should still be in the build instructions?

**Comment by damieng** [comment]
Do we want to support building with msysgit? It's quite a niche target and another thing to add to the test matrix.

**Comment by paulcbetts** [comment]
:-1:

**Comment by lee-dohm** [comment]
Thanks for the feedback, guys.

@damccull Thank you very much for contributing.

**Pull request closed without merging**
