### PR TITLE
:bug: Fix window size is not updated on resize

### PR DESCRIPTION
**Pull request by ypresto**
https://github.com/atom/atom/issues/8295#issuecomment-206484993

### CODE REVIEW

**Comment by 50Wliu** [comment]
Hi @ypresto, can you please add a spec to test this change?  Thanks!

**Comment by ypresto** [comment]
wow.. test-editor-component-spec.js is too long...

**Comment by ypresto** [comment]
Added test!

**Comment by 50Wliu** [comment]
Woo, thanks!

**Comment by ypresto** [comment]
Fixed conflict..!

**Comment by ypresto** [comment]
one more rebase..!

**Comment by nathansobo** [comment]
Thanks for tracking this down. What do you think about fixing this via a window `resize` event handler? We had one at some point and I'm not sure how it was removed. That would keep the `pollDOM` method lighter which will save battery power.

**Comment by nathansobo** [comment]
I see, looks like we bind the `resize` event in the view scheduler and just call the pollers. These properties should probably be pretty cheap to read so I'm just going to merge. Thanks very much for finding and fixing this. Pretty embarrassing bug! ✨ ✨ ✨

**Comment by nathansobo** [comment]
Fixes #8295

**Pull request merged**
