### PR TITLE
Fix incorrect indentation on setAppUserModelId

### LINKED ISSUE #7374: Pinning Atom to the Windows taskbar duplicates the icon
Since 0.210.0, it appears that Atom gets two icons instead of just one if Atom is pinned to the Windows taskbar. Clicking the pinned icon will open another icon that represents the running app. I would expect the first instance of Atom to reuse the pinned icon rather than adding a new one.

### PR DESCRIPTION
**Pull request by anaisbetts**
Fixes #7374

### CODE REVIEW

**Comment by jonathandelgado** [comment]
+1, thanks @paulcbetts

**Comment by nathansobo** [comment]
Once we get a green build I'll release yet another hotfix with this.

**Comment by nathansobo** [comment]
I cherry-picked this into stable at 47f973db3801ab13ccd8530632b944cf1865dddc so we can hotfix. Thanks @paulcbetts!

**Comment by paulcbetts** [comment]
:+1: :cool: :sparkling_heart:

**Pull request closed without merging**
