### PR TITLE
⬆️  find-and-replace@0.219.5

### PR DESCRIPTION
**Pull request by darangi**
Resolves the [electron upgrade](https://github.com/atom/atom/pull/21079) [blocker](https://github.com/atom/find-and-replace/issues/1129)

### CODE REVIEW

**Comment by UziTech** [comment]
Can we get some PRs merged (or at least commented on) as well as updating these packages?

**Comment by UziTech** [comment]
Is anyone actually maintaining find-and-replace?

**Comment by DeeDeeG** [comment]
I tested this. I can confirm the fix worked for me.

_(On [a branch I made](https://github.com/DeeDeeG/atom/commits/electron-6-take-two-merge-package-updates) with this and #21096 merged into `electron-6.1.12-bump-electron-packager-from-git`, both bugs went away. :+1:)_

- Find in project --> Find and Replace in project works now, tested with Electron 6.
- Package info/settings view can be scrolled, tested with Electron 6.

My build artifacts are here: https://dev.azure.com/DeeDeeG/b/_build/results?buildId=149&view=artifacts&type=publishedArtifacts

**Comment by aminya** [comment]
> Is anyone actually maintaining find-and-replace?

I have this problem with many packages in Atom. That is why I created our atom-community fork. There are no maintainers for the packages, and we do not have any access to the organization! Now Atom organization is a closed organization with very minimal community involvement and very slow improvements. There are no maintainers for the packages (even though they are open source!). I am not sure how GitHub wants to advance this ecosystem with only two/three developers around.

**Comment by darangi** [comment]
> I tested this. I can confirm the fix worked for me.
> 
> _(On [a branch I made](https://github.com/DeeDeeG/atom/commits/electron-6-take-two-merge-package-updates) with this and #21096 merged into `electron-6.1.12-bump-electron-packager-from-git`, both bugs went away. 👍)_
> 
> * Find in project --> Find and Replace in project works now, tested with Electron 6.
> * Package info/settings view can be scrolled, tested with Electron 6.
> 
> My build artifacts are here: https://dev.azure.com/DeeDeeG/b/_build/results?buildId=149&view=artifacts&type=publishedArtifacts

Thanks for confirming this 🚀

**Pull request merged**
