### PR TITLE
Add asar support in Atom

### PR DESCRIPTION
**Pull request by kevinsawicki**
Reverts atom/atom#6242 and brings back #5382 
### Packages To Test

These packages use a buffered process which might have issues inside an `.asar` archive.
- [x] Symbols View
- [x] Notifications
- [x] Package Generator
- [x] Settings View
- [x] Tree View
- [x] Update Package Dependencies
- [x] `apm` populating the compile cache on package install
### Platforms To Test
- [x] Windows
  - Verify atom and apm commands work with installer
  - Verify no long paths
- [x] Mac
  - Verify atom and apm commands install from system menu
- [x] Linux
  - Verify atom and apm commands work from native package installation
### Results
- Startup appears 100-200ms faster on my Windows 8.1 VM running inside Parallels
- Windows installer appears to be much snappier

### CODE REVIEW

**Comment by kevinsawicki** [comment]
I think this is ready to :ship: after 0.191 is out.

If anyone from @atom/core or @atom/non-github-maintainers has time to test out this branch, that would be awesome.

Basically just checkout this branch, run `script/build`, open Atom, and see if anything is broken or if startup feels faster/slower, or anything else seems off.

Thanks!

**Comment by thomasjo** [comment]
Seems promising so far! Startup feels about the same as before, so pretty good. Not noticed anything broken yet.

**Comment by mnquintana** [comment]
Looks good so far! Here's my Timecop diff:

### `master`
screenshot 2015-04-13 19 21 24

### This branch
screenshot 2015-04-13 19 09 16

Haven't found anything broken yet.

**Comment by 50Wliu** [comment]
Seems all right so far but I haven't used Atom much today.

**Comment by philipgiuliani** [comment]
Wow thats a big improvement :) Really nice job!

**Comment by benogle** [comment]
People are going to freak when 193 comes out.

**Comment by kevinsawicki** [comment]
Huge thanks to everyone who tested it out :mountain_cableway:

**Comment by maxbrunsfeld** [comment]
Badass :dragon_face:

**Pull request merged**
