### PR TITLE
Tildify path in title bar

### PR DESCRIPTION
**Pull request by lgeiger**
This will shorten the directory path displayed in the title bar
PR:
bildschirmfoto 2016-09-01 um 02 14 06
Master:
bildschirmfoto 2016-09-01 um 02 23 43

### CODE REVIEW

**Comment by 50Wliu** [comment]
:-1: on this as it introduces another dependency and because this is unexpected behavior on Windows.

**Comment by lgeiger** [comment]
@50Wliu Got it. I didn't thought about Windows.

**Comment by iolsen** [comment]
I agree with @50Wliu. A version of this that didn't introduce a dependency and didn't modify the displayed path on Windows would get a 👍 from me.

**Comment by lgeiger** [comment]
I opened a PR (https://github.com/atom/fs-plus/pull/32) to include this functionality in `fs-plus`. This won't add another dependency and doesn't have a effect on windows.

**Comment by lgeiger** [comment]
I'm going to close this and reopen when https://github.com/atom/fs-plus/pull/32 is merged.

**Pull request closed without merging**
