### PR TITLE
:arrow_up: timecop@0.33.0

### PR DESCRIPTION
**Pull request by thedaniel**

### CODE REVIEW

**Comment by jerone** [comment]
:shipit:

**Comment by izuzak** [comment]
Seems like the pull request can't be merged due to merge conflicts. 

screen shot 2015-09-19 at 11 43 16

Let me clean that up and we can merge this then. Thanks for the bump, @jerone

**Comment by izuzak** [comment]
The build failures don't seem to be related to this change, so I'm merging this.

**Comment by jerone** [comment]
:tada:

**Pull request merged**
