### PR TITLE
Don't assign default path for `showSaveDialog` unless it exists

### LINKED ISSUE #14732: "Save As" for new file doesn't default to a sensible directory location
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When creating a new file and hitting Save, the save dialog doesn't seem to have any particular directory set and defaults to a platform-dependent location.

### Steps to Reproduce

1. Create a new untitled file
2. Save it

**Expected behavior:**

"Save As" dialog should default to a sensible location (most likely the project root, which definitely _used_ to be the behaviour)

**Actual behavior:**

**On Ubuntu**, Save dialog opens at "Recently Used", sometimes making it a pain to find the logical place to save the file.

**On mac**, seems to default to project root directory, but **only** for the first window opened (I assume it defaults to the process's cwd)

Can't speak for windows right at the moment I'm afraid

Directory is set fine if you're hitting "save as" from a file that already exists.

**Reproduces how often:**

Every time

### Versions

Currently 1.18 beta but basically every version since #13978 was reported

### Additional Information

I guess #13978 got closed because the desired behaviour was fixed on mac for the first-opened window and for already-existing files. Looks like this was also reported in #14304 but that was closed because it didn't follow the template.

### PR DESCRIPTION
**Pull request by kuychaco**
Fixes #14732

Problem: "Save As" for a new file would default to the previously used directory, instead of the open project folder in Atom. 

A regression was introduced where we were assigning the default path to be `undefined` when there was no file path for an item, as in the case of a brand new, unsaved file. When no default path is specified the operating system defaults to displaying the previously used directory.

The fix was to simply not set the default path in `Pane.prototype.saveItemAs` if the item has no path, and let `AtomWindow.prototype.showSaveDialog` set it based on the project paths, which happens later on down the code path.

### CODE REVIEW

**Comment by 50Wliu** [comment]
@kuychaco you might want to take a look at #15160, which uses a slightly different approach.

**Comment by kuychaco** [comment]
Ah yes, thanks for pointing that PR out @50Wliu. I totally missed it somehow. 

The approach in #15160 addresses part of the problem, but won't account for if there are multiple folders open in the project and the desired default directory is anything other than the first folder. In this PR, we're effectively taking the same approach, but letting `AtomWindow` decide which folder to default to based on the project.

**Comment by kuychaco** [comment]
Hmmm, turns out `AtomWindow`'s way of deciding is to simply take the first path in `loadSettings.initialPaths`, which seems to be the most recently added folder. It's not the most intelligent way of determining the default path when there are multiple folders in the project, but it seems to be what we were doing before the regression (reference https://github.com/atom/atom/commit/c6cae5b8fdfea982084b068a0b38a7c988c52f51). 

In any case, this fix as-is gets us to the expected behavior for a majority of the cases and restores the previous functionality. Any other improvements for handling multiple folders in a project can be handled in a separate PR.

**Comment by nathansobo** [comment]
Nice work @kuychaco.

**Pull request merged**
