### PR TITLE
Use native promises instead of Q library

### PR DESCRIPTION
**Pull request by nathansobo**

### CODE REVIEW

**Comment by YuriSolovyov** [comment]
Why not use bluebird as a faster drop-in replacement? Just for sake of removing deps?

**Comment by nathansobo** [comment]
> Why not use bluebird as a faster drop-in replacement?

I just want the simplest, most minimal API that can work. Bluebird seems better than Q from afar but I'd rather just go with the most minimal, standard solution if I'm going to bother making these changes.

Unfortunately, this is now blocked on [upgrading to the latest Electron](https://github.com/atom/atom/pull/7877), and making sure we're on a version that includes the change made in https://github.com/atom/electron/pull/2447.

**Comment by nathansobo** [comment]
`atom-rpm` build failure is spurious. This is building cleanly. Merging at long last.

**Comment by nathansobo** [comment]
Oh, after I resolve these conflicts. :grimacing:

**Comment by maxbrunsfeld** [comment]
awesome :fire: awesome :fire: awesome :rocket:

**Pull request merged**
