### PR TITLE
Tab Length Detection

### PR DESCRIPTION
**Pull request by dolsenj**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change
Currently, tab length for the text editor is set depending on what programming language is being used. This PR sets the text editor's tab length automatically when a file is opened to be edited. The tab length is calculated by an algorithm which takes an array of the lines of code in the file being edited as input and outputs the calculated tab length, accounting for variability in tab length. This change was made in workspace.js in the didChangeActivePaneItemOnPaneContainer method because tab length detection is done whenever the active pane item is changed. 

### Alternate Designs
There were four alternative designs for the tab detection algorithm. They were determining tab length by finding the Greatest Common Divisor, Minimum Width, Comparing lines, and using a Neural network. Comparing lines was chosen because it performed the best amongst the four algorithms for correctly determining tab length when testing on different files of code. For more information, refer to this [article](https://medium.com/firefox-developer-tools/detecting-code-indentation-eff3ed0fb56b) on tab length detection. 

### Why Should This Be In Core?
This PR should be in the Core because it was requested to be in the core by the issue report. Tab length is also a part of the text editor itself so changing the core makes sense. 

### Benefits
Users with unique tab length preferences do not need to manually change the default tab length every time they use Atom. For example, users who use four space tabs for JavaScript, two space tabs for Python, or three space tabs for another language do not need to change the default tab length.

### Possible Drawbacks
A possible drawback is that tab length detection is performed when it is not necessary to do so.

### Verification Process
We verified that new and changed functionality works as expected by adding Jasmine specs to the workspace-spec.js file. We performed four tests on tab length detection. We ran a test on a normal JavaScript file with tab length of 2, a file with tab length of 4, a file with tab length of 3, and a file with a tab length of two but also has variability in tab length. In each case, tab length detection returned the expected tab length correctly and the changes did not introduce any regressions. We also used Travis CL to perform continuous integration testing and had a successful build.  Currently, testing on CircleCI and AppVeyor.

### Applicable Issues
https://github.com/atom/atom/issues/3043

### CODE REVIEW

**Review by maxbrunsfeld — CHANGES_REQUESTED** [review]
Hey @dolsenj, this is a great feature; thanks for taking it on! Overall, your logic for inferring tab length looks good. There's a few changes I'd like to see regarding *where* the new logic should be implemented and *how* we compute the most frequent indent length.

I don't think that the code should live in `Workspace`. There is already some very closely-related functionality in `TextEditor` in a method called [`usesSoftTabs`](https://github.com/atom/atom/blob/d50349f0042f347a193229f7af5fa042631c2fbc/src/text-editor.js#L3611-L3620). This method examines the first 1000 lines of the buffer in order to decide whether to use tabs or spaces for indentation.

I think that what we should do is create a new method called `TextEditor.getCurrentSoftTabLength()`, which checks if the buffer uses spaces or tabs. If we encounter a hard tab character first, we should simply return `null`, to indicate that the editor doesn't use soft tabs. Otherwise, we should perform your logic for detecting indent length.

This new method would basically *replace* the current `usesSoftTabs` method. We would have to keep the old method for compatibility, but we could implement it in terms of the new method, like this:

```js
usesSoftTabs() {
  return this.getCurrentSoftTabLength() != null
}
```

This new method can then be used in the `TextEditorRegistry` to configure each editor's tabLength setting, instead of just using `usesSoftTabs` [like we do today](https://github.com/atom/atom/blob/d50349f0042f347a193229f7af5fa042631c2fbc/src/text-editor-registry.js#L157-L164).

It's important that we limit the number of lines that we scan, because otherwise this would severely slow down the opening of large files. Even 1000 lines may be too many, because the old `usesSoftTabs` code used to break out as soon is it found an indented line, whereas we'll need to keep going. We'll have to measure the performance impact. If it turns out to be expensive at all, one option would be to break the loop once we've seen some number of indentation changes, like 5.

**Comment by maxbrunsfeld** [comment]
Also, it looks like you accidentally checked in some files that were not checked in previously, and also changed the CircleCI config file. Could you undo that stuff? Finally, you might want to rebase your branch onto the latest master; CI may be failing because of some issues that have already been fixed on master.

**Comment by dolsenj** [comment]
Hey @maxbrunsfeld, I attempted to undo my changes and do a rebase of my branch onto the latest master. In trying to do this, I accidentally did a force push on my version of master which closed the pull-request.

Is it possible to re-open the pull-request or should I make a new pull-request to continue working on task?

**Comment by daviwil** [comment]
@dolsenj Sorry for the delay!  Looks like GitHub won't allow me to reopen this PR because it thinks there aren't any new commits on your `master` branch.  Could you try opening a new PR?  Thanks a lot!

**Pull request closed without merging**
