### PR TITLE
Fix indentation for languages without indent pattern

### LINKED ISSUE #8013: Auto-indent on newline broken in 1.0.2
Auto-indent on newline works in 1.0.1 but is broken in 1.0.2.

To test, I'm opening a new file (Command-N) and typing a line that starts with a tab. When I press return I expect the next line to have the same indentation. The behaviour is as expected on 1.0.1 but there is no indentation on the next line in 1.0.2.

I tested the behaviour by installing 1.0.1 and 1.0.2 packages from https://github.com/atom/atom/releases. I'm using Mac OSX Yosemite and vanilla installs of Atom with no third party plugins.

Cheers,

Martin

### PR DESCRIPTION
**Pull request by svanharmelen**
Fixes #8013

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
Thanks for figuring this out. Can you add a test for this using the plain text grammar or something?

**Comment by svanharmelen** [comment]
Sure, will add a quick test...

**Comment by svanharmelen** [comment]
@maxbrunsfeld added a test... Review at will :wink:

**Comment by maxbrunsfeld** [comment]
Nice! Thanks @svanharmelen.

**Pull request merged**
