### PR TITLE
Improve incompatible native module error message

### LINKED ISSUE #6671: Auto Indent isn't idempotent
I'm using Atom 0.196.0 on Ubuntu. I thought it might have been a plugin causing the problem, but you can see from the video below that the bug exists in safe mode too.

It seems like I can pretty reliably get Auto Indent to do the right thing if I strip all indentation before triggering it. I know this was working in 0.188, but because you don't [provide a PPA](https://github.com/atom/atom/issues/2956) or any other [automated update mechanism](https://github.com/atom/atom#debian-linux-ubuntu) I don't get every version.

autoindent

### LINKED ISSUE #6771: Atom should specify which incompatible native module caused `require` to fail
It would be nice in a package with many native modules, if the logged message in the console was not:

> Failed to require the main module of 'git' because it requires an incompatible native module.
Run `apm rebuild` in the package directory to resolve.

but was instead:

> Failed to require the main module of 'git' because it requires 'module-name', an incompatible native module.
Run `apm rebuild` in the package directory to resolve.

### PR DESCRIPTION
**Pull request by Glavin001**
Close #6771.

### CODE REVIEW

**Comment by Ben3eeE** [comment]
I think you linked the wrong issue.

**Comment by Glavin001** [comment]
Absolutely did. Sorry about that. Fixed linked issue.

**Comment by Glavin001** [comment]
Also force pushed an amended commit message with the correct issue reference.

**Comment by thomasjo** [comment]
@Glavin001 How do you feel about either of these variants?

1. _[…] requires incompatible native **modules** […]_
~~~
Failed to require the main module of '#{@name}' because it requires incompatible native modules (#{_.map(@incompatibleModules, 'name').join(', ')}).
Run `apm rebuild` in the package directory and restart Atom to resolve.
~~~
2. _[…] requires **one or more** incompatible native **modules** […]_
~~~
Failed to require the main module of '#{@name}' because it requires one or more incompatible native modules (#{_.map(@incompatibleModules, 'name').join(', ')}).
Run `apm rebuild` in the package directory and restart Atom to resolve.
~~~

Just makes it read better in case there are actually more than one incompatible module.
Extremely minor thing though, I know. Let me know what you think, then I'll merge this.

**Comment by Glavin001** [comment]
I like the `[…] requires **one or more** incompatible native **modules** […]` message. I'll make the appropriate changes when I get home late today. Thanks!

**Comment by lee-dohm** [comment]
Updated and merged as #12158.

**Pull request merged**
