### PR TITLE
Master

### PR DESCRIPTION
**Pull request by FlowerBoot**
README汉化完成

### CODE REVIEW

**Comment by thomasjo** [comment]
Sorry, we are not going to translate the (main) README from English to Chinese.

**Comment by steelbrain** [comment]
You could however make a subdir of translated manual. Like it's done in the electron repo. Or maybe we could create a separate docs repo where the translations live.
What do you think @thomasjo ?

**Comment by thomasjo** [comment]
I vote no for translating anything in this repo. Translations in https://github.com/atom/docs would be nice in theory, but seeing how outdated some aspects of the current (english) documentation is, I'm super reluctant about adding translations anywhere.

I'll let other folks from @atom/feedback chime in since I'm likely being overly pessimistic.

**Comment by lee-dohm** [comment]
I agree with @thomasjo. My priorities for translation would be:

1. Atom itself
1. Flight Manual
1. Developer documentation

**Pull request closed without merging**
