### PR TITLE
:arrow_up: tree-view@0.224.0

### PR DESCRIPTION
**Pull request by Ben3eeE**
## Description of the change

Atom 1.25 and 1.26 ships with tree-view@0.221.3. This is an older version that has not been upgraded since the [tests were not passing](https://github.com/atom/tree-view/issues/1203). This failing test has been [fixed in tree-view@0.223.0](https://github.com/atom/tree-view/pull/1225). After this was merged tree-view was bumped to 0.222.0 instead of 0.223.0. This seemed like a mistake and that the intent was to upgrade to tree-view@0.223.0. I asked about this and @50Wliu confirmed that it seems like we should be on tree-view@0.223.0. I tried upgrading tree-view directly on the master branch but there seems to be a [failing test on circleci](https://circleci.com/gh/atom/atom/7273) after upgrading.

Comparing the current shipped version and the latest version:
https://github.com/atom/tree-view/compare/v0.221.3...v0.223.0

Comparing the current version on atom/atom master branch with the latest version:
https://github.com/atom/tree-view/compare/v0.222.0...v0.223.0

/cc: @50Wliu @daviwil

### CODE REVIEW

**Review by daviwil — APPROVED** [review]
Thanks a lot Linus!

**Comment by Ben3eeE** [comment]
Updated the description so it's clear why this was opened as a PR.

**Comment by daviwil** [comment]
I've only been able to replicate this test failure on macOS, not sure what the difference is there.  Will look into it some more tomorrow.

**Comment by UziTech** [comment]
Any update on this?

Atom v1.29 still has tree-view@0.222.0

**Comment by Ben3eeE** [comment]
@UziTech I'll ping the team about updates.

@50Wliu FYI: I changed this PR to 0.224.0. You did all the commits between 0.223.0 and 0.224.0 🙂

**Comment by maxbrunsfeld** [comment]
Ok, made some progress on this. The failures are due to https://github.com/atom/tree-view/pull/1048. When the tree-view tests are run as part of Atom's CI, the project folder is set to `atom/node_modules/tree-view/spec/fixtures`, which matches Atom's `.gitignore` because it's inside of `node_modules`.

I think I need to adjust the failing test to use a temp directory as its project folder so that paths will not be considered as ignored.

**Comment by maxbrunsfeld** [comment]
The latest failure is a keybinding-resolver failure which looks like a flake.

```
2018-08-21T00:24:36.2759500Z KeyBindingResolverView
2018-08-21T00:24:36.2774560Z   when a keydown event occurs
2018-08-21T00:24:36.2792500Z     it displays all commands for the keydown event but does not clear for the keyup when there is no keyup binding
2018-08-21T00:24:36.2810360Z       TypeError: Cannot read property 'textContent' of null
2018-08-21T00:24:36.2829920Z         at it (/Users/vsts/agent/2.136.1/work/1/s/node_modules/keybinding-resolver/spec/keybinding-resolver-view-spec.js:49:80)
2018-08-21T00:24:36.2853890Z         at <anonymous>
2018-08-21T00:24:36.2861710Z 
2018-08-21T00:24:36.2869680Z 
2018-08-21T00:24:36.2886220Z Finished in 0.205 seconds
2018-08-21T00:24:36.2902710Z 3 tests, 5 assertions, 1 failure, 0 skipped
```

**Comment by 50Wliu** [comment]
Thanks a ton @maxbrunsfeld!  Will be great to have all the new tree-view improvements.

**Comment by Ben3eeE** [comment]
Thanks @maxbrunsfeld :confetti_ball: Excited to see all the new tree-view improvements get released.

**Pull request merged**
