### PR TITLE
Added prevent option to ::onWillDestroyPaneItem()

### PR DESCRIPTION
**Pull request by ericcornelissen**
### Description of the Change

This PR implements the feature requested in issue #12376. It adds a method to the parameter of the `::onWillDestroyPaneItem` callback named `prevent` which allows packages to prevent a tab from closing by adding an event listener via `::onWillDestroyPaneItem`

### Alternate Designs

An alternative for the requested feature overall isn't really present, as the previous implementation would close the tab no matter what or request the user to safe in case of unsaved changes. Both of these are unwanted behaviour as described in #12376.

As for alternative ways to implement the functionality, I considered `prevent` to be a (boolean) value instead of a function. However, this seemed not such a good choice mainly because I find it more intuitive to use as a function, but also because JavaScript can't enforce the value to be a boolean.

### Why Should This Be In Core?

As explained in #12376, the problem is that it isn't part of the core. As of now it is nearly impossible to implement this as a package, and non of the solutions I could think of are even remotely elegant (e.g. recording what tab(s) closed and reopening them after they've been closed).

### Benefits

It will help developers of packages prevent the unwanted closing of "special" tabs e.g. when "Close all tabs" is called by the user. This has, for example, been requested in [this](https://github.com/ericcornelissen/pinned-tabs-for-atom/issues/20) issue on one of my own packages.

### Possible Drawbacks

When used incorrectly this functionality could make closing tabs impossible for users. However, simply disabling the package that uses this functionality incorrectly will solve the problem.

### Applicable Issues

N/A

### CODE REVIEW

**Comment by ericcornelissen** [comment]
@50Wliu (or anyone else), I was wonder if you could help me here?

After I pushed some commits to this PR yesterday all CI systems have failed for some mysterious reason, I can build Atom locally. Also, the logs do not point to something related to my changes, but instead to a build issue related to node-gyp (see [AppVeyor](https://ci.appveyor.com/project/Atom/atom/build/5313/job/8g9wo82gf2w1jo5a#L275))... Maybe it possible to restart the CI systems?

**Comment by 50Wliu** [comment]
AWS was down yesterday.  I've restarted all three.

**Comment by pmlodawski** [comment]
+1 for this pull request, I was looking for this functionality.

**Comment by ericcornelissen** [comment]
> Build execution time has reached the maximum allowed time for your plan (90 minutes).

Build timeout on AppVeyor (see [link](https://ci.appveyor.com/project/Atom/atom/build/7726/job/qk4k3icsp5g4sm79/messages)) 😞

**Review by sadick254 — CHANGES_REQUESTED** [review]
Hey @ericcornelissen. Apologies we didn't get to review this on time. This is a really good patch and I would like for it to be part of Atom. I have noticed on the CI, the linting step is failing. An easy fix for this would be to run `script/lint --fix` from the root of the project. Let me know if there is anything I can do to help out.

**Comment by ericcornelissen** [comment]
Hi @sadick254, better late than never I guess :smile: 

I would be more than happy to pick this up again but not sure how to go about that given that I removed my original fork. I tried to fork again and (force) push changes to the same branch, but that didn't seem to do anything... Any suggestions in that regard?

**Comment by 50Wliu** [comment]
Hey Eric, can you try allowing maintainers edit access to your PR? You can find instructions on how to do so here if you're not familiar with the option: https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

If that works, I can see if editing from the web UI is enough to get things back in order -- at the very least, GitHub isn't showing the PR coming from an unknown repository, which is a good sign 😊.

**Comment by ericcornelissen** [comment]
I'm not seeing the option to allow maintainers to edit the PR in the UI :confused: 

Any other suggestion, or should we close this and create a new PR?

**Comment by sadick254** [comment]
@ericcornelissen Let's close this PR and open another one.

**Pull request closed without merging**
