### PR TITLE
Improve support for international keyboards

### PR DESCRIPTION
**Pull request by nathansobo**
Closes https://github.com/atom/atom-keymap/issues/35
Closes https://github.com/atom/atom-keymap/issues/34

This PR includes a new version of `atom-keymap` with changes described in https://github.com/atom/atom-keymap/pull/144.

The basic idea is that we will never shadow the ability to type an ASCII character with any key binding. Most of this logic is handled in `atom-keymap` and is describe in the above PR.

In addition to the keymap changes, we are forced to omit keyboard shortcuts for application menu items if there's a possibility they could interfere with typing `AltGraph`-modified characters on international layouts. This means that `alt-` bindings on Mac and `ctrl-alt-` bindings on Windows won't show up in the menu, but the bindings will still work so long as they don't conflict.

I'd appreciate it if international users could give this a try by downloading binaries from the build provider for their platform. You can find links to builds of this PR in the build status section at the bottom of this page, then navigate to the "artifacts" section:
- For Windows, go to AppVeyor artifiacts
- For Mac, go to Circle artifacts
- For Linux, go to Travis, where you can find the S3 download URLs in the build log

### CODE REVIEW

**Comment by ccoenen** [comment]
**My Platform: Windows 10 / 64bit (not that it matters) / German Keyboard Layout**

I'll go over all the keys that don't work in 1.10 for me and how it compares to the new version. This is sorted by position on the keybard in english text reading direction.

* `²` and `³` <kbd>AltGr+2</kbd> and <kbd>AltGr+3</kbd> worked before, keeps working
* `{[]}` <kbd>AltGr+7</kbd> through <kbd>AltGr+0</kbd> worked before, keeps working. (You may wonder how one even programs on a german keybard, right now. And you would be right.)
* `\` <kbd>AltGr+ß</kbd> works fine (did not do anything before) :+1: 
* `@` <kbd>AltGr+Q</kbd> will insert an @ symbol (reflowed text before) :+1:
* `€` <kbd>AltGr+E</kbd> worked before, keeps working.
* `~` <kbd>AltGr++</kbd> works fine (did not do anything before) :+1: 
* `|` <kbd>AltGr+<</kbd> worked before, keeps working
* `µ` <kbd>AltGr+M</kbd> works fine (did not do anything before) :+1: 

Additionally, on a german keyboard, there's no single key for `/`, so the usual shortcut <kbd>Ctrl+/</kbd> (to comment out a block of selected code) is actually <kbd>Ctrl+Shift+7</kbd> - because `/` is <kbd>Shift+7</kbd>. Earlier, this did not work at all  (just did nothing), on this branch it works as expected! :+1: (so this might well have fixed https://github.com/atom/atom-keymap/issues/34 along the way)

**Comment by Ben3eeE** [comment]
I can add results from 1.10 and results on Windows 10 later during the day, here is a report from `1.12-dev-88f4799` with all <kbd>AltGr</kbd> keys I could think of.

**My Platform: Windows 7 / 64bit (not that it matters) / Swedish Keyboard Layout**

| Key | Keybind | Can Write | Keybinding Resolver
|-----|---------|-------|-----------------------
| @ |<kbd>AltGr+2</kbd> | Yes | <kbd>@</kbd>
| £ | <kbd>AltGr+3</kbd> | Yes | <kbd>Ctrl+Alt+3</kbd>
| $ | <kbd>AltGr+4</kbd> | Yes | <kbd>$</kbd>
| { | <kbd>AltGr+7</kbd> | Yes | <kbd>{</kdb>
| [ | <kbd>AltGr+8</kbd> | Yes | <kbd>[</kbd>
| ] | <kbd>AltGr+9</kbd> | Yes | <kbd>]</kbd>
| } | <kbd>AltGr+0</kbd> | Yes | <kbd>}</kbd>
| \ | <kbd>AltGr++</kbd> | Yes | <kbd>\\</kbd>
| ~ | <kbd>AltGr+¨</kbd> | Yes | <kbd>Ctrl+Alt+]</kbd> bound to `editor:unfold-current-row`
| &#124; | <kbd>AltGr+<</kbd> | Yes | <kbd>&#124;</kbd>
| € | <kbd>AltGr+€</kbd> | Yes | <kbd>Ctrl+Alt+E</kbd>
| µ | <kbd>AltGr+m</kbd> | No | <kbd>Ctrl+Alt+M</kbd> bound to `bracket-matcher:select-inside-brackets`

**Comment by vgrigoriu** [comment]
Windows 10, Romanian Programmers keyboard: AltGr + I (î) and AltGr + Q (â) don't work. AltGr + (A, S, T) work fine.

**Comment by thomasjo** [comment]
@vgrigoriu Can you verify whether those keybinds that don't work are bound to commands on your setup? I suspect they are, but would be great to verify my assumption.

Easiest way to check is to use the keybinding resolver (`ctrl-.`).

**Comment by vgrigoriu** [comment]
AltGr-Q appears as ctrl-alt-q - autoreflow:reflow-selection. AltGr-I as ctrl-alt-i - window:toggle-dev-tools.

**Comment by thomasjo** [comment]
@vgrigoriu Thanks for verifying 🙇

**Comment by vgrigoriu** [comment]
Also not working:
- AltGr-[ - editor:fold-current-row
- AltGr-] - editor:unfold-current-row (they're supposed to be „ and ”)
- AltGr-. - bracket-matcher:close-tag (this is », which admitedly is a character rarely used)

**Comment by nereusz** [comment]
Windows 10, Polish Programmers keyboard. Two polish letters still not working (due to default shortcuts):
* AltGr+o (should produce `ó`) - in `win32.cson` combination `ctrl-alt-o` is binded to `application:add-project-folder`
* AltGr+z (should produce `ż`) - in `win32.cson` combination `alt-ctrl-z` is binded to `editor:checkout-head-revision`

**Comment by Ben3eeE** [comment]
I tested all keys on Windows 10 and see no difference. I did notice that <kbd>AltGr+5</kbd> writes <kbd>€</kbd> and resolves to <kbd>Ctrl+Alt+5</kbd>. Didn't even know that this existed as a possibility as it is not printed on my keyboard but seems to be the case in every program on Windows 10.

Did also notice that this PR breaks the `keyboard-localization` package, maybe understandably so. Some keys that are supposed to be dead on first press write Dead in the document when activated and for example <kbd>!</kbd> resolves to <kbd>Shift+!</kbd> instead of <kbd>!</kbd>

**Comment by ccoenen** [comment]
The hope is, that this PR will make the (very much appreciated!) package `keyboard-localisation` obsolete by fixing the original problem.

@Ben3eeE What keyboard layout are you on?

**Comment by Ben3eeE** [comment]
Swedish keyboard layout, said in my first comment :point_up_2:

**Comment by nathansobo** [comment]
So far, this PR only protects basic ASCII characters required for typical programming from being shadowed by bindings. Characters like `µ`, `î`, `„`, and `ż`, because they are outside of basic ASCII, are not protected by default... This approach is really important on OS X because `⌥ ` is used really aggressively by Apple to provide alternative keys for every key in every layout, keys which are often much less important than the `alt-` bindings they would be replacing.

My original thinking was to apply the same approach on Windows, favoring the ability to type a default `ctrl-alt-` binding unless it interfered with typing characters like `[`, `@` etc. Based on this feedback I'm starting to think that's the wrong approach on Windows. Unlike OS X, Windows layouts seem to be much more sparing with `AltGr`-modified characters, so it's probably safe to assume that if an `AltGr` variant exists, the user wants to have access to it. Does that seem reasonable to everyone?

I've asked our Windows expert @damieng to propose comprehensive reform to our default bindings on Windows, but that's going to take more time. For now, are people comfortable making there own bindings for things that conflict with `AltGr` characters?

**Comment by Zireael07** [comment]
AltGr-modified characters are unavoidable in some languages - Polish (ó and ż) and Romanian, for instance.

@Ben3eeE: Are you using AltGr to enter Ä? Or is Swedish keyboard layout using some other option?

**Comment by thomasjo** [comment]
@Zireael07 On Swedish keyboards `äöå` each have their own physical key. Similarly `æøå` have their own keys on Norwegian and Danish keyboards.

**Comment by Ben3eeE** [comment]
@nathansobo This is an improvement over the previous behavior for sure. For me this would work fine because the conflicting keys is something I never use when programming, except I am unsure about ~ thought. ~ is a common ascii character that conflicts with a keybinding and is also used in some programming languages?

**Comment by nathansobo** [comment]
Thanks to everyone for the thorough investigation and help on this. I've pushed another commit upgrading `atom-keymap` to to 6.3.4, which includes changes from https://github.com/atom/atom-keymap/pull/145 to always favor alt-graph variants on Windows if they exist. This should allow all AltGr characters, not just ASCII, to be typed on Windows without interference from bindings.

Are people cool creating their own bindings for the defaults that end up getting shadowed until we can reform our default set?

**Comment by Ben3eeE** [comment]
@nathansobo This is an improvement but writing ~ is still not working correctly. The ~ character is on a weird key on swedish layout where every combination is dead on the first press and on the next press the character appears. This is because we use it to write characters like ã by first typing <kbd>AltGr+¨</kbd> and then <kbd>a</kbd>. The possible characters to write with this key are  <kbd>¨</kbd> without modifier, <kbd>^</kbd> with shift modifier and <kbd>~</kbd> with AltGr modifier. All work fine and report dead except ~.

I am cool with having it like this and making my own keybindings until you can reform the default set.

Full test results for comparison below:

**My Platform: Windows 10 / 64bit (not that it matters) / Swedish Keyboard Layout / `1.12-dev-290c4ec`**

| Key | Keybind | Can Write | Keybinding Resolver
|-----|---------|-------|-----------------------
| @ |<kbd>AltGr+2</kbd> | Yes | <kbd>@</kbd>
| £ | <kbd>AltGr+3</kbd> | Yes | <kbd>£</kbd>
| $ | <kbd>AltGr+4</kbd> | Yes | <kbd>$</kbd>
| { | <kbd>AltGr+7</kbd> | Yes | <kbd>{</kdb>
| [ | <kbd>AltGr+8</kbd> | Yes | <kbd>[</kbd>
| ] | <kbd>AltGr+9</kbd> | Yes | <kbd>]</kbd>
| } | <kbd>AltGr+0</kbd> | Yes | <kbd>}</kbd>
| \ | <kbd>AltGr++</kbd> | Yes | <kbd>\\</kbd>
| ~ | <kbd>AltGr+¨</kbd> | Yes | <kbd>Ctrl+Alt+]</kbd> bound to `editor:unfold-current-row`, should be dead first keypress
| &#124; | <kbd>AltGr+<</kbd> | Yes | <kbd>&#124;</kbd>
| € | <kbd>AltGr+E</kbd> | Yes | <kbd>€</kbd>
| µ | <kbd>AltGr+M</kbd> | Yes | <kbd>µ</kbd>
| å | <kbd>å</kbd> | Yes | <kbd>å</kbd>
| ä | <kbd>ä</kbd> | Yes | <kbd>ä</kbd>
| ö | <kbd>ö</kbd> | Yes | <kbd>ö</kbd>
| Å | <kbd>Å</kbd> | Yes | <kbd>Shift+Å</kbd>
| Ä | <kbd>Ä</kbd> | Yes | <kbd>Shift+Ä</kbd>
| Ö | <kbd>Ö</kbd> | Yes | <kbd>Shift+Ö</kbd>
| ½ | <kbd>Shift+§</kbd> | Yes | <kbd>½</kbd>
| ! | <kbd>Shift+1</kbd> | Yes | <kbd>!</kbd>
| " | <kbd>Shift+2</kbd> | Yes | <kbd>"</kbd>
| ¤ | <kbd>Shift+4</kbd> | Yes | <kbd>¤</kbd>
| % | <kbd>Shift+5</kbd> | Yes | <kbd>%</kbd>
| & | <kbd>Shift+6</kbd> | Yes | <kbd>&</kbd>
| / | <kbd>Shift+7</kbd> | Yes | <kbd>/</kbd>
| ( | <kbd>Shift+8</kbd> | Yes | <kbd>(</kbd>
| ) | <kbd>Shift+9</kbd> | Yes | <kbd>)</kbd>
| = | <kbd>Shift+0</kbd> | Yes | <kbd>=</kbd>
| ? | <kbd>Shift++</kbd> | Yes | <kbd>?</kbd>
| \` | <kbd>Shift+´</kbd> | Yes | <kbd>\`</kbd> (shift-dead first time then resolves to ` which is correct)
| ^ | <kbd>Shift+¨</kbd> | Yes | <kbd>^</kbd> (shift-dead first time then resolves to ^ which is correct)
| * | <kbd>Shift+'</kbd> | Yes | <kbd>*</kbd>
| _ | <kbd>Shift+-</kbd> | Yes | <kbd>_</kbd>
| : | <kbd>Shift+.</kbd> | Yes | <kbd>:</kbd>
| ; | <kbd>Shift+,</kbd> | Yes | <kbd>;</kbd>
| < | <kbd><</kbd> | Yes | <kbd><</kbd>
| > | <kbd>Shift+<</kbd> | Yes | <kbd>></kbd>

**Comment by nathansobo** [comment]
Pushed another upgrade of `atom-keymap` with changes from https://github.com/atom/atom-keymap/pull/146, which I think should resolve the issues with dead keys on Mac and Windows. Linux will take more work.

@Ben3eeE Can you test again once we get another green build and see if dead keys on the Swedish layout like `¨` are resolving to the correct keystrokes? @thomasjo Maybe you could give this a spin on macOS as well?

**Comment by Ben3eeE** [comment]
@nathansobo Dead keys all work in the latest commit and doesn't resolve to some other combination. This changes it so that they never resolve to dead. So if you for some reason would want to bind a command to ~ it would activate when you want to write ã. Maybe it is fine like this I have no idea how other programs work or what the expected behavior would be in this case as I have never had the idea to bind something to a dead key.

I tested all combinations as previously and everything still works. I double checked that this still closes https://github.com/atom/atom-keymap/issues/34. I bound some commands to some keys to verify that it worked as expected. :+1: :ship:

**Comment by thomasjo** [comment]
@nathansobo Zero issues on macOS, and did not notice any issues in Ubuntu 16.04. "Dead keys" such as `¨` work as expected. Additionally I have no problems producing the tilde character (`~`). So I guess `se` and `no` layouts differ in that regard.

**Comment by Guichaguri** [comment]
All issues with an [ABNT2 keyboard](https://en.wikipedia.org/wiki/Portuguese_keyboard_layout) seems to be fixed, including all dead keys.
I'm glad <kbd>ctrl+?</kbd> is finally fixed, it used to be recognized as <kbd>ctrl+Á</kbd>.

**Comment by nathansobo** [comment]
@Ben3eeE What happens when this combines with `keyboard-localization`. Is Atom completely broken? Do any features of `keyboard-localization` remain relevant in the face of these changes?

**Comment by Ben3eeE** [comment]
@nathansobo It changes every keybind to include the modifier so for example typing <kbd>@</kbd> resolves to <kbd>AltGr+@</kbd>. Which means if I bind something to <kbd>@</kbd> it doesn't activate with `keyboard-localization` installed. I actually found it activates when typing <kbd>"</kbd> which resolves to <kbd>Shift-"</kbd>. Also something is weird with <kbd>~</kbd> activating it prints `Dead` in my `TextEditor`.
So having `keyboard-localization` installed combined with this makes nothing work as expected. Almost every key using <kbd>AltGr</kbd> and <kbd>Shift</kbd> modifiers stop working. In it's current state I see no use for `keyboard-localization` after these changes land on stable.

Included full test tables for comparison below.

# Without `keyboard-localization`
**My Platform: Windows 10 / 64bit (not that it matters) / Swedish Keyboard Layout / `1.12-dev-290c4ec`**

| Key | Keybind | Can Write | Keybinding Resolver
|-----|---------|-------|-----------------------
| @ |<kbd>AltGr+2</kbd> | Yes | <kbd>@</kbd>
| £ | <kbd>AltGr+3</kbd> | Yes | <kbd>£</kbd>
| $ | <kbd>AltGr+4</kbd> | Yes | <kbd>$</kbd>
| { | <kbd>AltGr+7</kbd> | Yes | <kbd>{</kdb>
| [ | <kbd>AltGr+8</kbd> | Yes | <kbd>[</kbd>
| ] | <kbd>AltGr+9</kbd> | Yes | <kbd>]</kbd>
| } | <kbd>AltGr+0</kbd> | Yes | <kbd>}</kbd>
| \ | <kbd>AltGr++</kbd> | Yes | <kbd>\\</kbd>
| ~ | <kbd>AltGr+¨</kbd> | Yes | <kbd>~</kbd>
| &#124; | <kbd>AltGr+<</kbd> | Yes | <kbd>&#124;</kbd>
| € | <kbd>AltGr+E</kbd> | Yes | <kbd>€</kbd>
| µ | <kbd>AltGr+M</kbd> | Yes | <kbd>µ</kbd>
| å | <kbd>å</kbd> | Yes | <kbd>å</kbd>
| ä | <kbd>ä</kbd> | Yes | <kbd>ä</kbd>
| ö | <kbd>ö</kbd> | Yes | <kbd>ö</kbd>
| Å | <kbd>Å</kbd> | Yes | <kbd>Shift+Å</kbd>
| Ä | <kbd>Ä</kbd> | Yes | <kbd>Shift+Ä</kbd>
| Ö | <kbd>Ö</kbd> | Yes | <kbd>Shift+Ö</kbd>
| ½ | <kbd>Shift+§</kbd> | Yes | <kbd>½</kbd>
| ! | <kbd>Shift+1</kbd> | Yes | <kbd>!</kbd>
| " | <kbd>Shift+2</kbd> | Yes | <kbd>"</kbd>
| ¤ | <kbd>Shift+4</kbd> | Yes | <kbd>¤</kbd>
| % | <kbd>Shift+5</kbd> | Yes | <kbd>%</kbd>
| & | <kbd>Shift+6</kbd> | Yes | <kbd>&</kbd>
| / | <kbd>Shift+7</kbd> | Yes | <kbd>/</kbd>
| ( | <kbd>Shift+8</kbd> | Yes | <kbd>(</kbd>
| ) | <kbd>Shift+9</kbd> | Yes | <kbd>)</kbd>
| = | <kbd>Shift+0</kbd> | Yes | <kbd>=</kbd>
| ? | <kbd>Shift++</kbd> | Yes | <kbd>?</kbd>
| \` | <kbd>Shift+´</kbd> | Yes | <kbd>\`</kbd>
| ^ | <kbd>Shift+¨</kbd> | Yes | <kbd>^</kbd>
| * | <kbd>Shift+'</kbd> | Yes | <kbd>*</kbd>
| _ | <kbd>Shift+-</kbd> | Yes | <kbd>_</kbd>
| : | <kbd>Shift+.</kbd> | Yes | <kbd>:</kbd>
| ; | <kbd>Shift+,</kbd> | Yes | <kbd>;</kbd>
| < | <kbd><</kbd> | Yes | <kbd><</kbd>
| > | <kbd>Shift+<</kbd> | Yes | <kbd>></kbd>

# With `keyboard-localization` installed
**My Platform: Windows 10 / 64bit (not that it matters) / Swedish Keyboard Layout / `1.12-dev-dbb8dec`**

| Key | Keybind | Can Write | Keybinding Resolver
|-----|---------|-------|-----------------------
| @ |<kbd>AltGr+2</kbd> | Yes | <kbd>AltGr-@</kbd>
| £ | <kbd>AltGr+3</kbd> | Yes | <kbd>AltGr-£</kbd>
| $ | <kbd>AltGr+4</kbd> | Yes | <kbd>AltGr-$</kbd>
| { | <kbd>AltGr+7</kbd> | Yes | <kbd>AltGr-{</kdb>
| [ | <kbd>AltGr+8</kbd> | Yes | <kbd>AltGr-[</kbd>
| ] | <kbd>AltGr+9</kbd> | Yes | <kbd>AltGr-]</kbd>
| } | <kbd>AltGr+0</kbd> | Yes | <kbd>AltGr-}</kbd>
| \ | <kbd>AltGr++</kbd> | Yes | <kbd>AltGr-\\</kbd>
| ~ | <kbd>AltGr+¨</kbd> | Yes | <kbd>AltGr-~</kbd> Writes `Dead` in the `TextEditor`.
| &#124; | <kbd>AltGr+<</kbd> | Yes | <kbd>AltGr-&#124;</kbd>
| € | <kbd>AltGr+E</kbd> | Yes | <kbd>AltGr-€</kbd>
| µ | <kbd>AltGr+M</kbd> | Yes | <kbd>AltGr-µ</kbd>
| å | <kbd>å</kbd> | Yes | <kbd>å</kbd>
| ä | <kbd>ä</kbd> | Yes | <kbd>ä</kbd>
| ö | <kbd>ö</kbd> | Yes | <kbd>ö</kbd>
| Å | <kbd>Å</kbd> | Yes | <kbd>Shift+Å</kbd>
| Ä | <kbd>Ä</kbd> | Yes | <kbd>Shift+Ä</kbd>
| Ö | <kbd>Ö</kbd> | Yes | <kbd>Shift+Ö</kbd>
| ½ | <kbd>Shift+§</kbd> | Yes | <kbd>½</kbd>
| ! | <kbd>Shift+1</kbd> | Yes | <kbd>Shift-!</kbd>
| " | <kbd>Shift+2</kbd> | Yes | <kbd>Shift-"</kbd> (Activates on @)
| ¤ | <kbd>Shift+4</kbd> | Yes | <kbd>Shift-¤</kbd>
| % | <kbd>Shift+5</kbd> | Yes | <kbd>Shift-%</kbd>
| & | <kbd>Shift+6</kbd> | Yes | <kbd>Shift-&</kbd>
| / | <kbd>Shift+7</kbd> | Yes | <kbd>Shift-/</kbd>
| ( | <kbd>Shift+8</kbd> | Yes | <kbd>Shift-(</kbd>
| ) | <kbd>Shift+9</kbd> | Yes | <kbd>Shift-)</kbd>
| = | <kbd>Shift+0</kbd> | Yes | <kbd>Shift-=</kbd>
| ? | <kbd>Shift++</kbd> | Yes | <kbd>Shift-?</kbd>
| \` | <kbd>Shift+´</kbd> | Yes | <kbd>Shift-\`</kbd>
| ^ | <kbd>Shift+¨</kbd> | Yes | <kbd>Shift-^</kbd>
| * | <kbd>Shift+'</kbd> | Yes | <kbd>Shift-*</kbd>
| _ | <kbd>Shift+-</kbd> | Yes | <kbd>Shift-_</kbd>
| : | <kbd>Shift+.</kbd> | Yes | <kbd>Shift-:</kbd>
| ; | <kbd>Shift+,</kbd> | Yes | <kbd>Shift-;</kbd>
| < | <kbd><</kbd> | Yes | <kbd><</kbd>
| > | <kbd>Shift+<</kbd> | Yes | <kbd>Shift-></kbd>

**Comment by Ben3eeE** [comment]
Also :point_up: is only on keys that resolve to a character you want to type, a keybinding that doesn't resolve to some character on my layout still works with `keyboard-localization` installed for example binding <kbd>Ctrl+Alt+1</kbd>. So it's not as bad as I made it sound maybe I just realized right now that the tables I keep posting don't include tests for some keybind that doesn't resolve to a character.

**Comment by nathansobo** [comment]
Okay, so I'm tentatively thinking that we shouldn't do anything drastic like automatically disabling the localization package, since you seem to still be able to write various characters and if anybody uses the `altgr-` binding variants, it's not going to work without that package since we don't produce `altgr-*` keystrokes.

**Comment by Ben3eeE** [comment]
Seems I was mistaken and it looks the same way without this pr now and is just the way it behaves. All these keybindings back and forth are getting confusing.

**Comment by nathansobo** [comment]
@Ben3eeE You're telling me. I'd like to express my appreciation again for all your help as we have waded through this.

**Comment by Ben3eeE** [comment]
The only issue that remains with `keyboard-localization` + this PR combined that I can find after I unconfuse myself and retest things is that it writes `Dead` in the `TextEditor` when I type tilde. This does not happen on Beta. Wonder why tilde is always the problematic character. Probably nothing major as you are still able to type tilde its just preceded by Dead. Something to keep in mind when this lands on stable as it might create an issue report or question on the forums.

Happy to help contributing for something that I will have much use for in the near future. Thanks for the work on this @nathansobo 🎉

**Comment by MarcoHat** [comment]
great job! 😄

**Comment by johan-boule** [comment]
Has anyone tested this on Linux?

**Comment by 50Wliu** [comment]
Yep - @thomasjo did on Ubuntu 16.04.

**Comment by simonepri** [comment]
My Platform: Windows 10 / 64bit / **Italian Keyboard Layout** / 1.11.0-beta5

With the **italian** keyboard i'm not able to type **']'** (closing square bracket)
All others **AltGr** characters are correctly typed.

This is the **italian** layout:
207npfa

**Comment by nathansobo** [comment]
@simonepri Hang tight, 1.12 beta should be out next week with the fixes.

**Comment by RoboWeb** [comment]
How to setup now polish programmer keyboard?
After update atom to v.1.12.4 and deprecated "keyboard-localistation" package - polish keyboard localisation dsn't work... It confused me...
I need this: http://kbd-intl.narod.ru/images/pl-programmers.png

**Comment by Ben3eeE** [comment]
@RoboWeb You should not have to do anything to setup for your keyboard. First of all try to disable `keyboard-localization` the package is deprecated and should no longer be needed. Please open a new issue at https://github.com/atom/atom-keymap/issues if the keyboard doesn't work for you detailing exactly which keys don't work and the problem you are experiencing. Along with additional information like operating system.

**Comment by MichaelKueller** [comment]
Is this also going to be implemented for Linux?

**Comment by ccoenen** [comment]
@MichaelKueller this ticket is over a year old, as far as I know, this should work on all platforms. If you have problems with the keyboard support, it's probably better to open a new ticket with the specific problem you're facing.

**Pull request merged**
