### PR TITLE
Fix `chrome-sandbox` file permissions

### LINKED ISSUE #20756: Atom v1.47.0 immediately crashes on Linux
Thanks for reaching out!

### Prerequisites

* [an X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>
    * Thanks for reaching out!

### Description

Thanks for reaching out!

- Debian amd64 GNU/Linux 10 (buster)
- GNOME 3.30.2
- Atom installed from Atom's official package repository using APT

One can use [`debian-live-10.4.0-amd64-gnome.iso`](https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/) to reproduce this bug.

Possibly related: #20289

```
$ strace -f atom --version 2>& 1 | grep +++
[pid  5410] +++ exited with 0 +++
[pid  5412] +++ exited with 0 +++
[pid  5411] +++ exited with 0 +++
[pid  5413] +++ exited with 0 +++
[pid  5414] +++ exited with 0 +++
[pid  5415] +++ exited with 0 +++
[pid  5417] +++ exited with 0 +++
[pid  5416] +++ exited with 0 +++
[pid  5418] +++ exited with 0 +++
[pid  5420] +++ killed by SIGTRAP +++
[pid  5419] +++ killed by SIGTRAP +++
+++ exited with 133 +++
```

```
$ atom
/usr/bin/atom: line 190:  5558 Trace/breakpoint trap   nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
[5558:0519/193533.492727:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /usr/share/atom/chrome-sandbox is owned by root and has mode 4755.
```

```
$ stat /usr/share/atom/chrome-sandbox
  File: /usr/share/atom/chrome-sandbox
  Size: 5185424   	Blocks: 10128      IO Block: 4096   regular file
Device: 17h/23d	Inode: 137009      Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-05-19 19:03:47.000000000 +0000
Modify: 2020-05-18 19:58:57.000000000 +0000
Change: 2020-05-19 19:03:57.648004641 +0000
 Birth: -
```

```
$ dpkg -c atom_1.47.0_amd64.deb | grep chrome-sandbox
-rwxr-xr-x root/root   5185424 2020-05-18 19:58 ./usr/share/atom/chrome-sandbox
```

Thanks for reaching out!

### Steps to Reproduce

1. Run Atom.

**Expected behavior:**

Atom should run.

**Actual behavior:**

It does not.

**Reproduces how often:**

100%.

### Versions

```
$ apt show atom
Package: atom
Version: 1.47.0
Priority: optional
Section: devel
Maintainer: GitHub <atom@github.com>
Installed-Size: 627 MB
Depends: git, libgconf-2-4 (>= 3.2.5) | libgconf2-4, libgtk-3-0 (>= 3.9.10), libgcrypt11 | libgcrypt20, libnotify4, libxtst6, libnss3 (>= 2:3.22), python | python2, gvfs-bin, xdg-utils, libx11-xcb1, libxss1, libasound2 (>= 1.0.16), libxkbfile1, libcurl3 | libcurl4, policykit-1 Thanks for reaching out!
Recommends: lsb-release
Suggests: libsecret-1-0, gir1.2-gnomekeyring-1.0
Download-Size: 124 MB
APT-Manual-Installed: yes
APT-Sources: https://packagecloud.io/AtomEditor/atom/any any/main amd64 Packages
Description: A hackable text editor for the 21st Century.
 Atom is a free and open source text editor that is modern, approachable, and hackable to the core.
```

```
$ apm --version
apm  2.4.5
npm  6.2.0
node 10.2.1 x64
atom 1.47.0
python 2.7.16
git 2.20.1
```

After manually fixing the file's permissions:

```
$ atom --version
Atom    : 1.47.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
```

### Additional Information

Thanks for reaching out!

### PR DESCRIPTION
**Pull request by descear**
Fixes: #20756

### CODE REVIEW

**Comment by Descear** [comment]
I was hoping that the Azure Pipeline check would run automatically so that I could figure out what to do.

Can someone please manually trigger that check for this PR?

**Comment by lkashef** [comment]
Hey @Descear, thanks for your contribution.

The PR normally triggers the CI but I think being a fork + draft status blocked the CI, I marked the PR as "Ready to Review" and the CI got triggered.

**Comment by Descear** [comment]
> I marked the PR as "Ready to Review" and the CI got triggered.

Thanks, @lkashef.

As of the last commit, this PR is now _actually_ ready for review.

**Comment by darangi** [comment]
Hi, @Descear, can you add your branch name to this file? `script/vsts/release-branch-build.yml` ? e.g https://github.com/atom/atom/blob/33ac859bfef4a5c8d2f06e66ea13f604df2e3e1e/script/vsts/release-branch-build.yml#L5 so we get to download .deb and .rpm artifacts that will be uploaded to the pipeline? This particular change will be reverted if we all confirm it works as expected.

**Comment by Descear** [comment]
The latest commit appears to have fixed the issue.

Checking the artefacts:

```
$ dpkg -c atom-amd64.deb | grep chrome-sandbox
-rwsr-xr-x root/root   5185424 2020-05-29 01:12 ./usr/share/atom-dev/chrome-sandbox
```

```
$ rpm -qlv atom.x86_64.rpm | grep chrome-sandbox
-rwsr-xr-x    1 root   root   5185424 May 28 20:17 /usr/share/atom-dev/chrome-sandbox
```

Atom launches fine on these distros after their respective package artefact is installed:
- Debian 10
- Fedora 32 (forced to use `chrome-sandbox`, see https://github.com/atom/atom/issues/20756#issuecomment-635672070)

Both distros:

```
$ stat /usr/share/atom-dev/chrome-sandbox
[...]
Access: (4755/-rwsr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
[...]
```

These commits should be reverted before this PR is merged:
- 73bd087
- 368f790

**Comment by darangi** [comment]
Great work! 🥳  @Descear, can we revert commits https://github.com/atom/atom/commit/73bd087fa3ed741f21e9e9b0cad945c9dce56be2 and https://github.com/atom/atom/commit/368f790a398759d3c8c9e12d5decd02eb317ef34? So we can merge this in?

**Comment by Descear** [comment]
I've made the reverts. Please proceed.

**Comment by Jackfritt** [comment]
There are still problems I wrote [here](https://github.com/atom/atom/issues/20756#issuecomment-633985833) 
With 1.46.0 this was possible:
sudo atom /root/.bashrc

Also writing files to directory without direct write access a Policy-Kit Window popped up
and asked for sudo password. Then it wrote the file to this directory.

Thx for reading :) and support.

**Comment by lkashef** [comment]
Hey @Jackfritt, thanks for your report 🙇‍♂️

The fix is available in Nightly and will be patched in the next release.

**Comment by Jackfritt** [comment]
> Hey @Jackfritt, thanks for your report bowing_man
> 
> The fix is available in Nightly and will be patched in the next release.

I tried 1.48.0 on latest patched Debian Buster
still not functional. 

LC_ALL=C sudo atom /root/.bashrc

kvm@j-esser:~/src/m2m_sql$ /usr/bin/atom: line 190: 18834 Trace/breakpoint trap   nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
[18834:0612/141736.319903:FATAL:atom_main_delegate.cc(194)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


atom /home/some.other.users_home_dir/new_test.file

Saving file gives error message 
"Unable to save file: Permission denied '/home/some.other.users_home_dir'"
instead of Policy-Kit Window popped up and asked for sudo password.

**Review by morrisjallah — COMMENTED** [review]
https://stackoverflow.com/jobs/developer-jobs-using-typescript

**Pull request merged**
