### PR TITLE
Update deprecation-cop.less

### PR DESCRIPTION
**Pull request by RyanPisuena**
### Description of the Change

Removing '!important argument from background-color of deprecation-cop'

### Quantitative Performance Benefits

According to #18174 , removing !important makes changing background color changes easier

### Possible Drawbacks

May mess with current background color settings

### Verification Process

Did not verify

### Applicable Issues

N/A

### CODE REVIEW

**Review by simurai — CHANGES_REQUESTED** [review]
👍  on removing `!important`.

Maybe `!important` could also be removed when hovering the `.deprecation-info`?

https://github.com/atom/atom/blob/af4f144237ab3044d979d5faad83668e622d579d/packages/deprecation-cop/styles/deprecation-cop.less#L31

**Review by simurai — CHANGES_REQUESTED** [review]
👍  on removing `!important`.

Maybe `!important` could also be removed when hovering the `.deprecation-info`?

https://github.com/atom/atom/blob/af4f144237ab3044d979d5faad83668e622d579d/packages/deprecation-cop/styles/deprecation-cop.less#L31

**Comment by RyanPisuena** [comment]
@simurai changes made

**Review by simurai — APPROVED** [review]

**Comment by simurai** [comment]
CI failure seems unrelated (timeout), merging.

Thanks @RyanPisuena 🙇

**Pull request merged**
