### PR TITLE
Select screen rows when click-dragging in gutter

### PR DESCRIPTION
**Pull request by nathansobo**
/cc @izuzak for :microscope: 
### Before:

gutter-selection-before
### After:

gutter-selection-after

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
Nice! :gem:

**Comment by izuzak** [comment]
Thanks for the ping, @nathansobo! Yeah, this is how things were before, but we intentionally switched to buffer rows in https://github.com/atom/atom/pull/5814 (which was a fix for https://github.com/atom/atom/issues/5738). 

I'm not strongly against this change, but just wanted to mention that I personally find it more intuitive if buffer rows are selected when you click in the gutter, and that's also the behavior in Sublime (as far as I can tell by reading my previous comments on this topic). I'm on a brand new laptop this week so don't have all the other editors installed -- would be great if someone could see how some other editors behave. And would be nice to hear from other folks what's more intuitive for them.

**Comment by mehcode** [comment]
**Sublime**
When you click on a line number, it selects the _buffer row_.

When you click and drag to select text, it only highlights whole _buffer rows_ on the line number gutter but it selects one _screen row_ of text at a time when dragging up.

---

If we could mimic Sublime here I think we could solve both use cases nicely (smooth drag-to-select and click to select line).

**Comment by izuzak** [comment]
Thanks for double-checking, @mehcode :heart: -- yeah, I'd be :+1: on that approach.

**Comment by nathansobo** [comment]
@lee-dohm In https://github.com/atom/atom/pull/8350#issuecomment-131154926 other issue you said this:

> I would suggest using screen lines in the case of soft wrap, but in the case of folding, it should use buffer lines.

Can you expand a bit on this and get more specific about the behavior you'd prefer?

**Comment by lee-dohm** [comment]
Absolutely, sorry I wasn't clear in the first place ...

If I click here:

napkin 08-14-15 9 23 08 am

I would expect it to only select from `Status]` through the end of that screen line. But if I go to a folded section of code and click here:

napkin 08-14-15 9 25 29 am

I would expect it to select the entire folded section in the buffer, not just the screen line.

**Comment by nathansobo** [comment]
I've updated the PR to select the initially clicked *buffer row*, but then select screen rows on drag. It feels smooth but still intuitive on the initial click.

select-by-buffer-then-screen

**Comment by izuzak** [comment]
Just took this for a test drive and it feels great. :zap: again @nathansobo

**Pull request merged**
