### PR TITLE
Upgrade to Chrome 41

### LINKED ISSUE #309: Native Emoji Support
It would be awesome to support native emoji.

Right now I just see nothing when I try to paste one in:

image

Compare to Safari:

image

Though unfortunately Chrome is broken too, so maybe this isn't something we can fix:

image

### PR DESCRIPTION
**Pull request by zcbenz**
This PR upgrades atom-shell to v0.22.1, which uses Chrome 41 and io.js 1.5.1.

Fixes #309.

screen shot 2015-03-19 at 9 22 46 am

### CODE REVIEW

**Comment by zcbenz** [comment]
Chrome 41 nows [forces using sub-pixel font scaling](https://code.google.com/p/chromium/issues/detail?id=362112), bringing back the [incorrect character size issue](https://github.com/atom/atom/pull/3495). /cc @atom/core

**Comment by nathansobo** [comment]
Taking a look at the character measurement issue now. @zcbenz would it be feasible to investigate the measurement problems at the native level? In the meantime I'll try to find a workaround.

**Comment by zcbenz** [comment]
@nathansobo I can patch libchromiumcontent to turn off sub-pixel font scaling if you want. The measurement problem is a bug of blink, which is hard to investigate in a short time.

**Comment by kevinsawicki** [comment]
@zcbenz just to confirm, we won't need to bump any of our native libraries to go from chrome 40 to 41?

**Comment by kevinsawicki** [comment]
>  I can patch libchromiumcontent to turn off sub-pixel font scaling if you want.

I think this is the right move so we can get chrome 41 out without having the font measurement stuff block it. 

@zcbenz has you noticed if the tree view rendering problems went away in chrome 41? #4924

**Comment by zcbenz** [comment]
@kevinsawicki I haven't tried this branch enough because the measurement bug made Atom hard to use, I'll retry after patching libchromiumcontent.

**Comment by zcbenz** [comment]
> @zcbenz just to confirm, we won't need to bump any of our native libraries to go from chrome 40 to 41?

No. The version of Nan used by our native libraries are compatible with Chrome 41.

**Comment by zcbenz** [comment]
After playing with this branch for some time, I think everything is working fine. The tree-view rendering issue is still there, exactly the same with Chrome 40.

One possible problem is `String.contains` has been removed completely in Chrome 41, though it has never been a standard method, some packages are still using it (`japanese-wrap` is one of them, but it could be the only one). We can polyfill it, but I don't think we should since it has never been a standard.

**Comment by thomasjo** [comment]
> After playing with this branch for some time, I think everything is working fine.

I haven't noticed any regressions or problems either. This looks good to me! Merge after v0.188.0 ships?

**Comment by kevinsawicki** [comment]
> Merge after v0.188.0 ships?

Yeah, I'd like to get 0.188 out first, and then have this go in in 0.189 (or later if needed).

**Pull request merged**
