### PR TITLE
Fix source maps for typescript and babel on Windows

### PR DESCRIPTION
**Pull request by damieng**
The source maps for babel and typescript never worked correctly on windows as the path was treated by the Chromium debugger as relative because it was not prefixed with file:///.  This led to a weird issue where the source map was thought to be in a different folder to the generated JS.

This corrects it using the same approach we use for Coffeescript and also removes the 'App load time' which is the last thing spewing onto the command line at start-up now Electron has been upgraded.

### CODE REVIEW

**Comment by 50Wliu** [comment]
This should fix most of #9923, if not all of it, right?

**Comment by damieng** [comment]
Quite how the different system reports what to me looked like a completely invalid path I'm not quite sure.  

I suspect this will remove or reduce the amount of types 4 (file incorrect root) and 5 (windows incorrect root) in your list but this doesn't do anything to resolve the differences between types 1 (windows correct), 2 (file correct) and 3 (windows inverted slashes).

**Comment by damieng** [comment]
As an aside I'd like to see everything as type 2 for consistency both internally and with other platforms.

**Comment by Ingramz** [comment]
@damieng this one needs to be prefixed as well, right?https://github.com/atom/atom/blob/5fc240580130f9dfb738f355a635eb21eb8b0e17/src/compile-cache.js#L102

**Comment by damieng** [comment]
I'm not sure we even need that line/block of code.  It applies it after calling the compiler and all three of our compilers already add the source map url.

**Comment by Ingramz** [comment]
@damieng currently I am seeing two distinct file entries for transpiled files in my dev tools (1.12.0-dev-7929e26).

shot1
Hovering over, says `application-delegate.coffee (from source map)`
Copy link address gives `file:///C:/projects/atom/out/app/src/application-delegate.coffee`

shot2
Hovering over, says `/C:/projects/atom/out/app/src/application-delegate.coffee`
Copy link address gives `/C:/projects/atom/out/app/src/application-delegate.coffee`

Adding the `file://` prefix to previously mentioned position merged those two entries. I haven't tried without the block. What confuses me however is that the extension for those files is `.coffee` and contents of them is plain javascript.

**Comment by Ingramz** [comment]
Update: the highlighted block is not needed (can/should be removed) and the issue exists because src directory is missing `.coffee` files, making debugging practically impossible.

**Pull request merged**
