### PR TITLE
 Add opened files and folders to recent documents menu

### PR DESCRIPTION
**Pull request by DouweM**
Title says it all!

screen shot 2015-11-15 at 20 51 23

Closes https://github.com/atom/atom/issues/3935

### CODE REVIEW

**Comment by 50Wliu** [comment]
Will this also work on Windows and Linux?

**Comment by alexandernst** [comment]
This uses https://github.com/atom/electron/blob/master/docs/api/app.md#appaddrecentdocumentpath-os-x-windows , so it's not actually *in* Atom itself, but a helper (kind of) for the OS. I'd vote :+1: for this only if this is implemented for Linux too (inside Atom's menu).

**Comment by DouweM** [comment]
@50Wliu It uses an Electron helper method that works on OS X and Windows, but is currently unimplemented for Linux.

@alexandernst It would be nice if `app.addRecentDocument` were supported on Linux, but that would need to happen in Electron, not Atom. Once this PR is accepted into Atom, if someone ever implements `addRecentDocument` for Linux, it will start working for Atom immediately. I feel like that's outside the scope of this particular PR, though.

**Comment by 50Wliu** [comment]
Sounds good to me then.

**Comment by alexandernst** [comment]
This is not (easily) possible in Linux. xdg might have something like a "standart" for such a thing, but it's up to each DE how this standart should be followed.

On the other hand, IMHO, this isn't as simple as having the recent files list inside Atom itself, in a submenu of "File".

On Windows, you'd have to go to the start menu, then find Atom, then click on the right arrow: win

On Linux, well, it depends on the DE as I said, but in KDE 5 for example that would be main menu -> recent documents -> scroll down to the "recent docs" section.

Now compare how easier would it be if Atom had that same feature in it's own menu: menu

**Comment by alexandernst** [comment]
All that said, I'm totally :+1: for this feature, it's just that this should be extended to Linux support too, which means a submenu in Atom's main menu.

**Comment by DouweM** [comment]
@alexandernst That makes sense, many OS X apps have an "Open Recent" menu under File too, in addition to the menu under the dock icon. 

It would be nice to get that menu on all platforms, but this sounds like something that would need to be done in Electron using C++ since it should use the same API that already exists for the OS X/Windows-specific bindings and be available to all Electron apps, which is unfortunately outside of my ability at this point.

**Comment by mnquintana** [comment]
@alexandernst That would definitely be great to have, but I think that can be a separate PR. Adding a menu item for recent documents is being tracked here: https://github.com/atom/atom/issues/4241

**Comment by DouweM** [comment]
@mnquintana Anything I can do to help this PR along?

**Comment by kevinsawicki** [comment]
>  Anything I can do to help this PR along?

@DouweM looks like there are conflicts, mind updating them?

**Comment by DouweM** [comment]
@kevinsawicki Done.

**Comment by kevinsawicki** [comment]
One last quick question before merging, do you know if this list grows infinitely? Does the OS handle capping it at a reasonable number like a dozen or so?

**Comment by DouweM** [comment]
@kevinsawicki Yep, that's handled by OS X, which is the only OS for which `app.addRecentDocument` is currently implemented:

```objc++
void Browser::AddRecentDocument(const base::FilePath& path) {
  NSURL* u = [NSURL fileURLWithPath:base::mac::FilePathToNSString(path)];
  [[NSDocumentController sharedDocumentController] noteNewRecentDocumentURL:u];
}
```

See [`noteNewRecentDocumentURL:`](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSDocumentController_Class/#//apple_ref/occ/instm/NSDocumentController/noteNewRecentDocumentURL:) and [`maximumRecentDocumentCount`](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSDocumentController_Class/#//apple_ref/occ/instp/NSDocumentController/maximumRecentDocumentCount).

**Comment by kevinsawicki** [comment]
> Yep, that's handled by OS X

Awesome, thanks for this :+1:

**Comment by DouweM** [comment]
@kevinsawicki Thanks for merging!

**Pull request merged**
