### PR TITLE
autoindent lines with moveLineUp/moveLineDown

### PR DESCRIPTION
**Pull request by joseramonc**
Related to #7546, added the `autoIndentSelection if should autoIndent`. A demo of the change:

autoindentmoveline

### CODE REVIEW

**Comment by YuriSolovyov** [comment]
Shouldn't there be an option in settings for that?

**Comment by maxbrunsfeld** [comment]
> Shouldn't there be an option in settings for that?

It looks like it already respects the existing `core.autoIndent` scoped config option. It makes sense to me to use the same option as auto-indenting on newline insertion. Thoughts?

**Comment by maxbrunsfeld** [comment]
Could you add a test for this @joseramonc?

**Comment by YuriSolovyov** [comment]
@maxbrunsfeld if so, it would be nice to have this metioned in setting description

**Comment by joseramonc** [comment]
@maxbrunsfeld Added tests for `editor.moveLineUp()` and `editor.moveLineDown()`, hope they are right, they were passing locally

**Comment by maxbrunsfeld** [comment]
Sorry for letting this go quiet for a while; there were some network-related CI failures. I re-ran the build.

**Comment by joseramonc** [comment]
@maxbrunsfeld It seems that just one build failed, is there some guide or help to debug this locally? Tests are passing on my computer :disappointed:

**Comment by 50Wliu** [comment]
You can safely ignore the symbols-view error; that spec is super-flaky right now.

**Comment by maxbrunsfeld** [comment]
@joseramonc Thanks for the ping. Great work!

**Comment by stefanbuck** [comment]
@joseramonc Thanks for this great feature, love it :tada:

**Comment by dorian-marchal** [comment]
Thanks a lot for your contribution but this breaks a pretty common use case : https://discuss.atom.io/t/move-line-without-auto-indent/23754
Could we have an other option in settings to disable this specific behaviour ?

__Original message :__

> I don't want my lines to auto indent when I move them.

> How can I change this behaviour ?

> Example :

>

**Comment by alexandernst** [comment]
Perhaps an option to disable auto-indent when moving lines in plain-text files?

**Comment by dorian-marchal** [comment]
> Perhaps an option to disable auto-indent when moving lines in plain-text files?

Note that this is not specific to Markdown / Plain Text :

optimised

**Comment by alexandernst** [comment]
@as-cii As per the gif @dorian-marchal just posted, I'd say auto-indent shouldn't trigger when changing lines from the same "lexical" line. Or make it understand what lexical line breaks are and make it work accordingly.

**Comment by maxbrunsfeld** [comment]
OK, it looks like this feature seems to have undesirable consequences pretty often, even in contexts where auto-indent is desirable for text insertion.

@joseramonc I think we may need to remove this feature until Atom's auto-indentation system is good enough to avoid these problems.

**Comment by snowsunny** [comment]
Just like @dorian-marchal has demonstrated this feature wreaks havoc on indentation for code spanning multiple lines. It would be nice to have a separate setting to enable or disable auto-indent specifically for this feature. EG: "editor.indentOnLineMove", when set to false it won't automatically indent but editor.autoIndent will remain untouched/active.

@dorian-marchal I kludged it with this custom command.
```coffee
atom.commands.add 'atom-text-editor', 'my:move-line-up', ->
  editor = atom.workspace.getActiveTextEditor()
  if atom.config.get('editor.autoIndent')
    atom.config.set('editor.autoIndent', false)
    editor.moveLineUp()
    atom.config.set('editor.autoIndent', true)
  else
    editor.moveLineUp()

atom.commands.add 'atom-text-editor', 'my:move-line-down', ->
  editor = atom.workspace.getActiveTextEditor()
  if atom.config.get('editor.autoIndent')
    atom.config.set('editor.autoIndent', false)
    editor.moveLineDown()
    atom.config.set('editor.autoIndent', true)
  else
    editor.moveLineDown()
```
and
```cson
'.platform-linux atom-workspace atom-text-editor:not([mini])':
  'ctrl-shift-up': 'my:move-line-up'
  'ctrl-shift-down': 'my:move-line-down'
```

**Comment by dorian-marchal** [comment]
@snowsunny It works just fine, thank you :+1:

**Comment by snowsunny** [comment]
@dorian-marchal I’m happy to help :+1:

**Comment by jeancroy** [comment]
Maybe make this an option ? It seems useful for people that mostly use language with clear indent scoping block (like html, JavaScript)

I also feel that re-arranging item in hanging indent is somewhat rare.

**Comment by mnquintana** [comment]
Making this an option sounds :cool: to me – that way we could scope it only to grammars that play nicely with this.

**Comment by geoffkembel** [comment]
Adding another vote for making this a separate option from auto-indent. For someone who moves multiple lines regularly, this is a real killer.

In the meantime, thanks to @snowsunny for the workaround.

**Comment by jeancroy** [comment]
In what kind of scenario auto-indent works well but this does not ?
I was under the impression that this only make auto-indent flaws more apparent.

**Comment by eddiemonge** [comment]
Yes please for separating this into its own flag.

**Comment by snowsunny** [comment]
@eddiemonge  Please try this keymap.
```cson
# for mac
'.platform-darwin atom-workspace atom-text-editor:not([mini])':
  'ctrl-cmd-up': 'my:move-line-up'
  'ctrl-cmd-down': 'my:move-line-down'
```

**Comment by phwh** [comment]
Also, auto-indent while moving doesn't work well with Python code. Here is an example:

atom-indent-issue

**Comment by radiac** [comment]
This can be pretty dangerous when writing python. For example, moving a line from above an `if` statement to underneath it makes the code conditional. If you don't notice the indentation change, it can take quite a while to figure out why your code has stopped working.

Definitely needs to be an option, and probably off by default in python - and I'd imagine any other language with significant whitespace. In the meantime, thanks @snowsunny - you are my internet hero of the day.

There is now a related issue where this is being discussed further: https://github.com/atom/atom/issues/10524

**Pull request merged**
