### PR TITLE
Replace pixelated BrowserWindow icon

### PR DESCRIPTION
**Pull request by simurai**
**Update II** We could wait with this since it might get fixed in Atom Shell: https://github.com/atom/atom-shell/issues/863

**Update**: It now only adds a `32px` icon, see https://github.com/atom/atom/pull/5047#issuecomment-69874810

This PR adds icons as `png` in multiple resolutions. See https://github.com/atom/atom/issues/4811#issuecomment-69702057

I tested it locally on Windows 8.1. Not by making a new build, but just adding it manually. It seemed to work, but I only have a non hi-res screen. So not sure if it will pick up the 1.5x or 2x version for higher DPIs.

### CODE REVIEW

**Comment by paulcbetts** [comment]
@simurai Lemme have a look

**Comment by paulcbetts** [comment]
Hm, no dice, though I think it's definitely better:

**Comment by simurai** [comment]
:disappointed:  but thanks for testing.

I found another strange thing. I had Atom pinned in the dock. It looked fine:

capture2

But when un-pinned and opening Atom again, it picked the `16px` icon.

capture

Pinning again, makes it pick up the `ico` file and it looks fine.

**Comment by paulcbetts** [comment]
I'm not sure if multi-DPI works here - can you just give the 48x48 one a unique name and use it?

**Comment by simurai** [comment]
Yeah, we could.. but then we're back at the beginning that the top left icon in the main Atom window is pixelated.

capture3

**Comment by simurai** [comment]
Just tested with a `32px` icon. Top right looks better, task bar less. Hmm.. maybe the best compromise?

capture4

Once you pin the icon, then it looks nice.

capture5

**Comment by simurai** [comment]
Ok, I changed this PR to only use the `32px` icon. It's not ideal, but maybe the best compromise.

**Comment by simurai** [comment]
Atom Shell is gonna allow to use the `ico` file: https://github.com/atom/atom-shell/issues/863#issuecomment-70197230

Gonna close this for now and make a new PR.

**Pull request closed without merging**
