### PR TITLE
Remove shadow DOM from `atom-text-editor`

### PR DESCRIPTION
**Pull request by as-cii**
### Background

Back in #3943, we started rendering text editor contents inside a shadow DOM boundary to prevent outer style sheets from altering the editor inner contents. Although this introduced many benefits, it carried several tradeoffs too.

In particular, we started duplicating some of the style sheets (`{context: 'atom-text-editor'}`) inside each shadow root so that package and theme authors could still be able to explicitly target the editor visual elements. An alternative solution to this problem that we suggested (before the shadow DOM spec was finalized) was to use `/deep/` and `::shadow` pseudo selectors, which unfortunately are now [being deprecated](https://bugs.chromium.org/p/chromium/issues/detail?id=489954).

Even more importantly, this architecture was getting in the way of making `atom-text-editor` a reusable component, because it made it even more coupled to Atom and its ecosystem. Other problems involved things like #4590, and a more complex user experience for package and theme authors in general. Ultimately, we started feeling like the extra complexity of the shadow DOM wasn't worth its benefits.
### Removing shadow DOM from `atom-text-editor`

This pull request aims at removing the shadow DOM in a way that prevents elements within `atom-text-editor` that we don't fully control (i.e. the grammar scopes applied as CSS classes to every line's inner `<span>`) from being mistakenly styled from the outside. Specifically, every syntactic class name will now be prepended with `syntax--`; styling a JavaScript operator, for example, should now look like the following:

``` css
.syntax--source.syntax--js .syntax--operator {
  color: green;
}
```

Given the wide scope of this change, we are trying to reduce package breakage to a minimum by [transforming deprecated selectors automatically](https://github.com/atom/atom/blob/as-deprecate-shadow-dom/src/style-manager.js#L251-L306) and emitting a deprecation in [deprecation-cop](https://github.com/atom/deprecation-cop). Applying these transformations can be quite onerous and therefore we have introduced a layer of caching in 07d56b2 to ensure their performance impact stays low after the first time Atom is launched. 

Other notable changes include:
- Block decorations rendering has been rewritten from scratch (it previously worked only with the shadow DOM).
- When the editor is focused, `document.activeElement` will now return the hidden `<input>` inside `atom-text-editor`, instead of `atom-text-editor` itself. I could find only one third party package relying on this behavior, and I am going to submit a pull request shortly to use `document.activeElement.closest('atom-text-editor')` instead.
- Any Grim or style sheet deprecation will now cause specs to fail, see [`ensureNoDeprecatedFunctionCalls`](https://github.com/atom/atom/blob/as-deprecate-shadow-dom/spec/spec-helper.coffee#L121) and [`ensureNoDeprecatedStylesheets`](ensureNoDeprecatedStylesheets).
- Rendering flashes for decorations has been broken for a long time, but removing the shadow DOM highlighted the cause of the issue, and so they have been fixed in 1091b0e.
  
  flash
### Conclusion

Removing the shadow DOM is an important step for the editor's future, as doing so will allow us to extract it, clean it up and optimize it. Considering the invasive nature of this change, we are planning to :ship: it after rolling the railcars next week, so that everyone can build it from master and extensively test it for an entire release cycle.

Before merging this, we will also need to merge the following core package pull requests, so that we stop using any deprecated API or selector, and make the test suite green again:
- [x] :arrow_up: autocomplete-plus (https://github.com/atom/autocomplete-plus/pull/779)
- [x] :arrow_up: autosave (https://github.com/atom/autosave/pull/71)
- [x] :arrow_up: atom-dark-syntax (https://github.com/atom/atom-dark-syntax/pull/31)
- [x] :arrow_up: atom-dark-ui (https://github.com/atom/atom-dark-ui/pull/64)
- [x] :arrow_up: atom-light-syntax (https://github.com/atom/atom-light-syntax/pull/9)
- [x] :arrow_up: atom-light-ui (https://github.com/atom/atom-light-ui/pull/36)
- [x] :arrow_up: base16-tomorrow-dark-theme (https://github.com/atom/base16-tomorrow-dark-theme/pull/31)
- [x] :arrow_up: base16-tomorrow-light-theme (https://github.com/atom/base16-tomorrow-light-theme/pull/11)
- [x] :arrow_up: bookmarks (https://github.com/atom/bookmarks/pull/70)
- [x] :arrow_up: command-palette (https://github.com/atom/command-palette/pull/72)
- [x] :arrow_up: deprecation-cop (https://github.com/atom/deprecation-cop/pull/70)
- [x] :arrow_up: find-and-replace (https://github.com/atom/find-and-replace/pull/789)
- [x] :arrow_up: git-diff (https://github.com/atom/git-diff/pull/111)
- [x] :arrow_up: markdown-preview (https://github.com/atom/markdown-preview/pull/436)
- [x] :arrow_up: package-generator (https://github.com/atom/package-generator/pull/45)
- [x] :arrow_up: one-dark-syntax (https://github.com/atom/one-dark-syntax/pull/79)
- [x] :arrow_up: one-dark-ui (https://github.com/atom/one-dark-ui/pull/168)
- [x] :arrow_up: one-light-syntax (https://github.com/atom/one-light-syntax/pull/24)
- [x] :arrow_up: one-light-ui (https://github.com/atom/one-light-ui/pull/77)
- [x] :arrow_up: settings-view (https://github.com/atom/settings-view/pull/862)
- [x] :arrow_up: solarized-dark-syntax (https://github.com/atom/solarized-dark-syntax/pull/76)
- [x] :arrow_up: solarized-light-syntax (https://github.com/atom/solarized-light-syntax/pull/26)
- [x] :arrow_up: wrap-guide (https://github.com/atom/wrap-guide/pull/60)
- [x] :arrow_up: apm (https://github.com/atom/apm/pull/615)
- [x] :arrow_up: first-mate (https://github.com/atom/first-mate/pull/80)
- [x] :memo: Update the flight manual (https://github.com/atom/flight-manual.atom.io/pull/281)

/cc: @atom/core

### CODE REVIEW

**Comment by as-cii** [comment]
We still need to update the flight manual to describe the new `syntax--` convention for CSS selectors, and the deprecation of `::shadow`. This can be addressed separately from this pull request, though, so I think we can go ahead and 🚢 this.

**Comment by nathansobo** [comment]
✨✨✨✨🍝

**Comment by Alhadis** [comment]
Good freaking riddance. Not a fan of needless complexity, and this is definitely a step in the right direction.

Not sure why two dashes were needed, but NBD. Any developer would take two hyphens over two stylesheets, hahaha.

**Comment by simurai** [comment]
> Any developer would take two hyphens over two stylesheets, hahaha.

😀  Well, double dash makes the `syntax` prefix be more separated from the rest. Useful when there are multiple words involved.. like `syntax--property-name`. [BEM](http://getbem.com/naming/) naming convention uses it for modifier classes.

**Comment by Alhadis** [comment]
... ugh, I was hoping it wasn't inspired by BEM. Not a fan. I'll pretend it's inspired by `--var` instead.

But hey, not complaining, if it simplifies the hell out of things and breaks Atom's component-architecture free of precisely 4 padlocks that were chaining us down. =)

👌

**Comment by ioquatix** [comment]
Is it just me or does anyone else find the `syntax--` prefix pretty ugly? Why not just `syntax-`?

**Comment by simurai** [comment]
@ioquatix It might look strange, but it makes it more clear where the prefix ends, also see https://github.com/atom/atom/pull/12903#issuecomment-259674789

For example with a single dash `syntax-attribute-name`, the prefix could be `syntax-` or `syntax-attribute-`. By using double dash `syntax--attribute-name`, it's clear that `syntax--` is the prefix.

**Comment by Alhadis** [comment]
There are dozens of ways this could have been done, and none are more or less correct than any other.

image

**Comment by ioquatix** [comment]
> For example with a single dash syntax-attribute-name, the prefix could be syntax- or syntax-attribute-. By using double dash syntax--attribute-name, it's clear that syntax-- is the prefix.

Doesn't CSS provide a nice semantic way to implement prefixes, e.g. `.syntax.attribute-name` or `.syntax .attribute-name`?

**Comment by mmcbride1007** [comment]
That isn't exactly what it's for, and that changes the specificity of the selectors. Your selector would then be 2 classes for every syntax style instead of one class.

All that aside, what's the goal here? They've spent countless hours implementing this across a large code base, I don't see them changing this unless there's a really good reason to do so.

**Comment by Alhadis** [comment]
Uh, no, combined and descendant combinators aren't a good way to implement prefixes. For a start, it changes the specificity of CSS classes. Secondly, it elevates the risk of incorrectly applying styles to elements that happen to already exist with those class-names.

**Comment by Alhadis** [comment]
AHAHAH dat timing.

**Comment by mmcbride1007** [comment]
@Alhadis haha that happens far too often :smile:

**Comment by ioquatix** [comment]
> it changes the specificity of CSS classes

What is the practical implication of this w.r.t. Atom's editor?

> it elevates the risk of incorrectly applying styles to elements that happen to already exist with those class-names.

Is this actually a problem, though? Or just "it might be a problem"?

Also, the passive aggressive behaviour isn't really creating a great vibe here. I'm really interested in the tradeoffs as from the outside it looks like a pretty big trade-off but it's not clear what the advantages are and they aren't well explained in the blog post on atom.io.

**Comment by 50Wliu** [comment]
> Or just "it might be a problem"?

This is a very real problem.  language-c at one point had scope names that included `.notification` in them.  When Notifications were introduced, there was much unhappiness as any syntax theme that had styled the `notification` class was now inadvertently styling Notifications as well.

**Comment by ioquatix** [comment]
> This is a very real problem. language-c at one point had scope names that included .notification in them. When Notifications were introduced, there was much unhappiness as any syntax theme that had styled the notification class was now inadvertently styling Notifications as well.

Is this the only instance of the problem?

Couldn't it be solved by scoping the CSS selector?

**Comment by Alhadis** [comment]
@ioquatix You need to remember that class-names are arbitrary. Prefixing them indiscriminately is the safest way to shield them from unexpected and unwanted styling.

**Comment by mmcbride1007** [comment]
I appreciate your interest in the problem here, but the way they solved this really works quite well. As a theme author, it was trivial for me to update my themes to the new selectors, so I'd say they did a pretty good job.

So far the only concern I've read is that you find the syntax ugly which, to be fair to the maintainers, isn't a great reason to reimplement something of this magnitude...

**Comment by Alhadis** [comment]
FWIW, I also find the syntax unsightly, but I appreciate the fact it's functional, self-explanatory, and the least likely to introduce "issues" with developing themes or language grammars.

You can always alias it locally using a Less variable or something.

**Comment by ioquatix** [comment]
> You need to remember that class-names are arbitrary. Prefixing them indiscriminately is the safest way to shield them from unexpected and unwanted styling.

Your absolutely correct. But, what's wrong with using `.syntax .language .attribute-name` (where you obviously replace .language with something specific). I actually use this in a syntax highlighter I wrote, and it works really well. It allows you to do semantic queries, e.g. style all variables, or all ruby variables, etc.

> I appreciate your interest in the problem here, but the way they solved this really works quite well. 

That's great, I'm interested in understanding more about how it works. But, I'm also interested in how the above case is handled, (e.g. style all variables, style all ruby variables, etc)

> As a theme author, it was trivial for me to update my themes to the new selectors, so I'd say they did a pretty good job.

Yes, I also have several packages for Atom which will need to be updated, so that's good to hear.

> So far the only concern I've read is that you find the syntax ugly which, to be fair to the maintainers, isn't a great reason to reimplement something of this magnitude...

I didn't mean to sound like I don't appreciate the work that's gone into this. I don't think I said anywhere to re-implement anything. I'm just voicing my concern about the syntax. I don't think the trade-offs of this choice were well discussed anywhere and as you've said yourself, it's a fairly deep and fundamental change to the way styling works within Atom.

**Comment by Alhadis** [comment]
> But, what's wrong with using `.syntax .language .attribute-name` (where you obviously replace .language with something specific).

`.attribute-name` is at risk of being targeted by a theme or package's styling, which broadly targets `.attribute-name` in its stylesheet.

**Comment by ioquatix** [comment]
> .attribute-name is at risk of being targeted by a theme or package's styling, which broadly targets .attribute-name in its stylesheet.

Isn't any class name at risk of being targeted by a theme or package's CSS? What makes `.syntax--` less likely to be a problem?

**Comment by 50Wliu** [comment]
A few reasons.
1. We are implementing this now, and featuring a blog post about it.  People will know/learn not to use `.syntax--` for things not related to syntax highlighting.
2. Every scope is prepended with `.syntax--`.
3. While `.syntax-name` is fairly common, double-dashes in CSS is much less common, disregarding BEM.

Basically, the chances that someone _by accident_ decides to create something with a class name of `.syntax--whatever` that isn't related to syntax highlighting and then style it in their CSS file is far lower than before.

**Comment by danielbayley** [comment]
In a syntax theme I am working on, I utilise _[postcss-prefixer]_ to add all the `syntax--` noise without having to actually deal with that in my source files… I get the reasoning here, but I'm just thinking it would be a much better “DX” if we did something similar in core instead?

**Comment by Alhadis** [comment]
Wasn't it possible to prefix class selectors automagically if the stylesheet's filename ended with ".syntax.less"? Or am I remembering wrong?

I recall reading about something like that somewhere...

**Comment by danielbayley** [comment]
@Alhadis I've never heard of that… without PostCSS you mean?

**Comment by simurai** [comment]
> Wasn't it possible to prefix class selectors automagically if the stylesheet's filename ended with ".syntax.less"? Or am I remembering wrong?

I think that didn't prefix selectors, but it loaded the stylesheet into `atom-text-editor`'s Shadow DOM boundary. So you didn't have to use `::shadow`.

**Comment by agus725** [comment]
second

**Comment by agus725** [comment]
- [ ] j

**Comment by quangnam15091977** [comment]
[]() @as-cii

**Comment by quangnam15091977** [comment]
> `[]() 

`

**Comment by emir0103** [comment]
Ffg

**Comment by Tanapl02** [comment]
> ### Background
> 
> 
> 
> Back in #3943, we started rendering text editor contents inside a shadow DOM boundary to prevent outer style sheets from altering the editor inner contents. Although this introduced many benefits, it carried several tradeoffs too.
> 
> 
> 
> In particular, we started duplicating some of the style sheets (`{context: 'atom-text-editor'}`) inside each shadow root so that package and theme authors could still be able to explicitly target the editor visual elements. An alternative solution to this problem that we suggested (before the shadow DOM spec was finalized) was to use `/deep/` and `::shadow` pseudo selectors, which unfortunately are now [being deprecated](https://bugs.chromium.org/p/chromium/issues/detail?id=489954).
> 
> 
> 
> Even more importantly, this architecture was getting in the way of making `atom-text-editor` a reusable component, because it made it even more coupled to Atom and its ecosystem. Other problems involved things like #4590, and a more complex user experience for package and theme authors in general. Ultimately, we started feeling like the extra complexity of the shadow DOM wasn't worth its benefits.
> 
> ### Removing shadow DOM from `atom-text-editor`
> 
> 
> 
> This pull request aims at removing the shadow DOM in a way that prevents elements within `atom-text-editor` that we don't fully control (i.e. the grammar scopes applied as CSS classes to every line's inner `<span>`) from being mistakenly styled from the outside. Specifically, every syntactic class name will now be prepended with `syntax--`; styling a JavaScript operator, for example, should now look like the following:
> 
> 
> 
> ``` css
> 
> .syntax--source.syntax--js .syntax--operator {
> 
>   color: green;
> 
> }
> 
> ```
> 
> 
> 
> Given the wide scope of this change, we are trying to reduce package breakage to a minimum by [transforming deprecated selectors automatically](https://github.com/atom/atom/blob/as-deprecate-shadow-dom/src/style-manager.js#L251-L306) and emitting a deprecation in [deprecation-cop](https://github.com/atom/deprecation-cop). Applying these transformations can be quite onerous and therefore we have introduced a layer of caching in 07d56b2 to ensure their performance impact stays low after the first time Atom is launched. 
> 
> 
> 
> Other notable changes include:
> 
> - Block decorations rendering has been rewritten from scratch (it previously worked only with the shadow DOM).
> 
> - When the editor is focused, `document.activeElement` will now return the hidden `<input>` inside `atom-text-editor`, instead of `atom-text-editor` itself. I could find only one third party package relying on this behavior, and I am going to submit a pull request shortly to use `document.activeElement.closest('atom-text-editor')` instead.
> 
> - Any Grim or style sheet deprecation will now cause specs to fail, see [`ensureNoDeprecatedFunctionCalls`](https://github.com/atom/atom/blob/as-deprecate-shadow-dom/spec/spec-helper.coffee#L121) and [`ensureNoDeprecatedStylesheets`](ensureNoDeprecatedStylesheets).
> 
> - Rendering flashes for decorations has been broken for a long time, but removing the shadow DOM highlighted the cause of the issue, and so they have been fixed in 1091b0e.
> 
>   
> 
>   flash
> 
> ### Conclusion
> 
> 
> 
> Removing the shadow DOM is an important step for the editor's future, as doing so will allow us to extract it, clean it up and optimize it. Considering the invasive nature of this change, we are planning to :ship: it after rolling the railcars next week, so that everyone can build it from master and extensively test it for an entire release cycle.
> 
> 
> 
> Before merging this, we will also need to merge the following core package pull requests, so that we stop using any deprecated API or selector, and make the test suite green again:
> 
> - [x] :arrow_up: autocomplete-plus (https://github.com/atom/autocomplete-plus/pull/779)
> 
> - [x] :arrow_up: autosave (https://github.com/atom/autosave/pull/71)
> 
> - [x] :arrow_up: atom-dark-syntax (https://github.com/atom/atom-dark-syntax/pull/31)
> 
> - [x] :arrow_up: atom-dark-ui (https://github.com/atom/atom-dark-ui/pull/64)
> 
> - [x] :arrow_up: atom-light-syntax (https://github.com/atom/atom-light-syntax/pull/9)
> 
> - [x] :arrow_up: atom-light-ui (https://github.com/atom/atom-light-ui/pull/36)
> 
> - [x] :arrow_up: base16-tomorrow-dark-theme (https://github.com/atom/base16-tomorrow-dark-theme/pull/31)
> 
> - [x] :arrow_up: base16-tomorrow-light-theme (https://github.com/atom/base16-tomorrow-light-theme/pull/11)
> 
> - [x] :arrow_up: bookmarks (https://github.com/atom/bookmarks/pull/70)
> 
> - [x] :arrow_up: command-palette (https://github.com/atom/command-palette/pull/72)
> 
> - [x] :arrow_up: deprecation-cop (https://github.com/atom/deprecation-cop/pull/70)
> 
> - [x] :arrow_up: find-and-replace (https://github.com/atom/find-and-replace/pull/789)
> 
> - [x] :arrow_up: git-diff (https://github.com/atom/git-diff/pull/111)
> 
> - [x] :arrow_up: markdown-preview (https://github.com/atom/markdown-preview/pull/436)
> 
> - [x] :arrow_up: package-generator (https://github.com/atom/package-generator/pull/45)
> 
> - [x] :arrow_up: one-dark-syntax (https://github.com/atom/one-dark-syntax/pull/79)
> 
> - [x] :arrow_up: one-dark-ui (https://github.com/atom/one-dark-ui/pull/168)
> 
> - [x] :arrow_up: one-light-syntax (https://github.com/atom/one-light-syntax/pull/24)
> 
> - [x] :arrow_up: one-light-ui (https://github.com/atom/one-light-ui/pull/77)
> 
> - [x] :arrow_up: settings-view (https://github.com/atom/settings-view/pull/862)
> 
> - [x] :arrow_up: solarized-dark-syntax (https://github.com/atom/solarized-dark-syntax/pull/76)
> 
> - [x] :arrow_up: solarized-light-syntax (https://github.com/atom/solarized-light-syntax/pull/26)
> 
> - [x] :arrow_up: wrap-guide (https://github.com/atom/wrap-guide/pull/60)
> 
> - [x] :arrow_up: apm (https://github.com/atom/apm/pull/615)
> 
> - [x] :arrow_up: first-mate (https://github.com/atom/first-mate/pull/80)
> 
> - [x] :memo: Update the flight manual (https://github.com/atom/flight-manual.atom.io/pull/281)
> 
> 
> 
> /cc: @atom/core
> 
> 

Exit

**Comment by Tanapl02** [comment]
Ok

**Pull request merged**
