### PR TITLE
alphabetical order packageDependencies

### PR DESCRIPTION
**Pull request by fscherwi**
For a better Overview!

### CODE REVIEW

**Comment by 50Wliu** [comment]
A very large :-1: on this.  Previously dependencies were sorted in subsections, then grouped alphabetically.  Want to update a theme?  Look near the top.  Language?  They're at the bottom.  With this change that's not possible anymore and one could argue it's *less* organized.

**Comment by thomasjo** [comment]
I'm with @50Wliu on this one. Hence :-1: from as well.

**Comment by mnquintana** [comment]
I appreciate you trying to clean up `package.json`, but I agree with @thomasjo and @50Wliu - the packages weren't in a random order, but rather, grouped by category, so this actually makes the dependency list less organized.

**Comment by fscherwi** [comment]
@50Wliu But if i want to change a package i don't look at the category, i look at the name of the package!

**Comment by 50Wliu** [comment]
@fscherwi <kbd>Ctrl+F</kbd>/<kbd>Cmd+F</kbd> should work fine.  In addition, once you've changed a few, you know exactly where to look.

**Pull request closed without merging**
