### PR TITLE
:arrow_up: languages

### PR DESCRIPTION
**Pull request by Ben3eeE**
Includes https://github.com/atom/language-c/pull/302 that changes the scope for primitive types.
Includes https://github.com/atom/language-go/pull/160
Includes https://github.com/atom/language-ruby/commit/0208636827aef4f420c5d94ec4ef43bbaf8a264e

This doesn't change how anything looks when using any of the core syntax themes but some community themes will get primitive types in C/C++ highlighted correctly again when using tree-sitter.
Also some community themes rely on the root scope to highlight things. language-go and language-ruby is updated for this.

### CODE REVIEW

**Comment by Ben3eeE** [comment]
/cc: @chbk this includes the language-go regression you found and the same fix for ruby.

**Comment by chbk** [comment]
@Ben3eeE I also found the same issue with language-python. The `source.python` scope isn't there.

**Comment by Ben3eeE** [comment]
@chbk I don't see this issue. The source.python scope is there for me and in the grammar. Can you open a separate issue with more details?

**Comment by chbk** [comment]
@Ben3eeE I opened issue [283](https://github.com/atom/language-python/issues/283).

**Pull request merged**
