### PR TITLE
detect symbolic link packages

### PR DESCRIPTION
**Pull request by aminya**
### Description of the Change

This is a fix for https://github.com/atom/atom/pull/20899. It follows symbolic links and checks if they are a directory (`fs.isDirectorySync` does that internally). 

This only uses `fs.isDirectorySync` for symbolic links and still has higher performance compared to using this function for everything. `fs.dirent` is faster compared to `fs.stat`.

### Verification Process

- Make a symbolic link from a folder to `.atom/packages`
- This change now detects if that symbolic link is a directory. Previous pull request did not

### Release Notes

- Fix the issue that symbolic links are not detected as packages in the previous nightly.

### CODE REVIEW

**Comment by aminya** [comment]
@lkashef This catches a regression that happened for symbolic links at https://github.com/atom/atom/pull/20899.

**Comment by lkashef** [comment]
Hi @aminya, thanks for the follow up.

Can you check the CI it looks like your PR didn't pass linting.

**Comment by aminya** [comment]
You're welcome. I ran `script/lint --fix`. This should be fixed now.

**Comment by aminya** [comment]
@lkashef This is ready to go. The CI's failure is unrelated.

**Comment by aminya** [comment]
@lkashef I made this patch just one day after the previous one was merged. I was expecting it to appear in the same version. Now the nightly versions are bumped and we will have a faulty Atom version. Could you merge this before bumping another version?

**Comment by lkashef** [comment]
Rerunning CI https://github.visualstudio.com/Atom/_build/results?buildId=78282&view=results

**Comment by UziTech** [comment]
There should be a test written for this regression so it doesn't happen in the future

**Comment by aminya** [comment]
@UziTech I added a test, but I am not sure how can I reinforce package loading when Atom has already done this. is it `atom.packages.loadPackages();`?

**Comment by aminya** [comment]
@sadick254 This is ready. I added a test too. Could you merge this now?

**Comment by anwarnafa** [comment]
4E38410B-D6C3-497F-8AD3-4D418677AE2D

**Comment by aminya** [comment]
@sadick254 Any plan to merge this?

**Comment by sadick254** [comment]
@aminya I have this PR on my radar. My plan is to review it and possibly merge it after the `1.51` release.

**Comment by UziTech** [comment]
@sadick254 if this gets released after the v1.51.0 release than v1.51.0 will be broken. No linked packages will work. This should be merged and released as v1.51.0-beta1 before v1.51.0 becomes stable.

**Comment by sadick254** [comment]
@UziTech I have read the comments and looked at the PR https://github.com/atom/atom/pull/20899 that introduced the regression. I will include this in the `1.51` release and `1.52-beta` releases.

**Comment by iwalkaloneatnighy** [comment]
Go
Ahead

**Pull request merged**
