### PR TITLE
Convert line endings when copy and pasting

### LINKED ISSUE #8365: Copy-paste doesn't work properly with Unix-style line endings under Windows
Copying (Ctrl+C-Ctrl+V) from a file with Unix-style line ending (LF) doesn't work as expected, since line endings are _preserved_ on the clipboard.

This causes a wide range of issues:
- you can't paste text in an application that doesn't handle LF (notepad for example, but if you're using vim over PuTTY that also doesn't work)
- even if the other app handles LF, you have to be consistent, so you can't paste text from an CRLF file into a LF one or vice versa

This issue is briefly discussed in #2822, and it is the reason of #5808.

**All other editors convert line endings in text placed on the clipboard** (Sublime Text, jEdit, etc.), so in this regard Atom behaves rather strangely compared to other editors.

The proposed solution in #2822 (configurable line endings) is insufficient since it's based on the assumption that _all_ files edited by the user are using the same line ending.
For example, if I've got a file with LF line endings and I'd like to use copy-paste, then I **have to convert it to CRLF** and then **copy the text** I want, and **then convert it back to LF** to preserve the original format. I wouldn't call editing LF files on Windows a rare use case, especially among Atom's users.

Atom should convert any text's line ending to the platform's native line ending _before_ it is placed on the clipboard. This conversion should only be done on the content that is placed on the clipboard—the text in the buffer should not be changed.

### PR DESCRIPTION
**Pull request by winstliu**
### Requirements for Adding, Changing, or Removing a Feature

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must contribute a change that has been endorsed by the maintainer team. See details in the template below.
* The pull request must update the test suite to exercise the updated functionality. For guidance, please see https://flight-manual.atom.io/hacking-atom/sections/writing-specs/.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see https://github.com/atom/atom/tree/master/CONTRIBUTING.md#pull-requests.

### Issue or RFC Endorsed by Atom's Maintainers

#8365, endorsed by @maxbrunsfeld [here](https://github.com/atom/atom/issues/8365#issuecomment-433170963).

### Description of the Change

Whenever text is copied to the clipboard, all line endings are converted to the underlying OS's default line endings (CRLF on Windows, LF otherwise). Fixes #8365.

### Alternate Designs

I could have done `const os = require('os')` and then used `os.EOL` instead of hardcoding the line endings in `clipboard.js`, but that didn't seem worth it.

This could also be implemented as a Windows-only feature, which I believe is how VSCode does it.

### Possible Drawbacks

Sometimes you may want to explicitly copy the text as-is without conversions, and this will prevent that.

### Verification Process

On Windows, I copied text with LF line endings and pasted them into http://www.unit-conversion.info/texttools/hexadecimal/, which confirmed that the pasted text had `0d 0a` (CRLF).

### Release Notes

Line endings are now converted when copy and pasting.

### CODE REVIEW

**Comment by 50Wliu** [comment]
Note: this won't affect pasting in Atom that much: copying LF and pasting it into another LF file will still result in LF line endings, not CRLF.

**Comment by 50Wliu** [comment]
Hmm, this breaks some tests. I can add a boolean option whether to do the conversion or not.

**Comment by rafeca** [comment]
Hey! 👋

We have recently started using [`prettier`](http://prettier.io/) and this has caused major
style changes on the Atom JS codebase (you can check [the related PR](https://github.com/atom/atom/pull/19391)).

This is good news: now the Atom code is more consistent and it's much easier to re-format the code to
follow the codestyle (now you only need to run `script/lint --fix`).

This change caused conflicts on your PR that we have automatically solved, hope you don't mind 😄

With ❤️, the Atom team.

**Review by sadick254 — APPROVED** [review]
Hey @50Wliu, I have just resolved some conflicts on this and I think it's good to go. Thank you for your contribution.

**Comment by 50Wliu** [comment]
@sadick254 feel free to merge, I really shouldn't have merge permissions anymore :).

**Pull request merged**
