### PR TITLE
Update Electron to 0.36.12

### LINKED ISSUE #11198: Atom 1.7.0 beta0 crashes on startup under Arch Linux
Hi,

I have noticed that Atom 1.7.0-beta0 crashes on startup on Arch Linux. Despite this, Atom 1.6.0 installed on the same Arch Linux installation is working fine without issue. It does not matter if I start 1.7.0-beta0 from the command-line with `atom-beta` or from its `.desktop` file launcher. I have tried launching it with `atom-beta --safe .` and still it crashed on me. `atom-beta` returns the following output, if it helps:

```bash
/usr/bin/atom-beta: line 115: 14844 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
App load time: 434ms
Failed to get crash dump id.
Report Id: 
Failed to get crash dump id.
Report Id: 
```

How did I install Atom 1.7.0 beta0? By running `makepkg -si --noconfirm` in [this subdirectory](https://github.com/fusion809/PKGBUILDs/tree/master/atom-editor-beta) of my PKGBUILD GitHub repository. In case I end up updating this GitHub repo, here is the present PKGBUILD I am using:

```bash
# Contributor: Matheus de Alcantara <matheus.de.alcantara@gmail.com>
# Maintainer: Brenton Horne <brentonhorne77 at gmail dot com>

pkgname=atom-editor-beta
_pkgrel=0
_pkgver=1.7.0
pkgver="${_pkgver}.${_pkgrel}"
pkgrel=1
pkgdesc='Chrome-based text editor from GitHub - Beta Channel'
arch=('x86_64' 'i686')
url='https://github.com/atom/atom'
license=('MIT')
depends=('alsa-lib' 'gconf' 'gtk2' 'libgnome-keyring' 'libnotify' 'libxtst' 'nodejs' 'nss' 'python2')
optdepends=('gvfs: file deletion support')
makedepends=('git' 'npm')
conflicts=('atom-editor-beta-bin')
install=atom.install
source=("https://github.com/atom/atom/archive/v${_pkgver}-beta${_pkgrel}.tar.gz")
sha256sums=('d370f725a1b6fab0583f7d412f189a3c35603a7472a6566b188d0c2ae7e98bdf')

prepare() {
	cd "$srcdir/atom-${_pkgver}-beta${_pkgrel}"

  sed -i -e "/exception-reporting/d" \
	       -e "/metrics/d" package.json

  sed    -e "s/<%= description %>/$pkgdesc/" \
         -e "s|<%= appName %>|Atom Beta|"\
         -e "s|<%= installDir %>/share/<%= appFileName %>/atom|/usr/bin/atom-beta|"\
         -e "s|<%= iconPath %>|atom-beta.png|"\
         -e "s|GNOME;||" \
         -e "s|text/plain;|application/javascript;application/json;application/postscript;application/x-csh;application/x-desktop;application/x-httpd-eruby;application/x-httpd-php;application/x-httpd-php3;application/x-httpd-php4;application/x-httpd-php5;application/x-latex;application/x-msdos-program;application/x-ruby;application/x-sh;application/x-shellscript;application/x-sql;application/x-tcl;application/x-tex;application/xhtml+xml;application/xml;application/xml-dtd;application/xslt+xml;text/css;text/csv;text/html;text/plain;text/xml;text/xml-dtd;text/x-asm;text/x-bibtex;text/x-boo;text/x-c++;text/x-c++hdr;text/x-c++src;text/x-c;text/x-chdr;text/x-csh;text/x-csrc;text/x-dsrc;text/x-diff;text/x-eiffel;text/x-fortran;text/x-go;text/x-haskell;text/x-java;text/x-java-source;text/x-lua;text/x-makefile;text/x-markdown;text/x-objc;text/x-pascal;text/x-perl;text/x-php;text/x-python;text/x-ruby;text/x-scala;text/x-scheme;text/x-sh;text/x-tcl;text/x-tex;text/x-vala;text/yaml;|" \
         resources/linux/atom.desktop.in > resources/linux/atom-beta.desktop
}

build() {
	cd "$srcdir/atom-${_pkgver}-beta${_pkgrel}"

	export PYTHON=/usr/bin/python2
	until ./script/build --build-dir "$srcdir/atom-build"; do :; done
}

package() {
	cd "$srcdir/atom-${_pkgver}-beta${_pkgrel}"

	script/grunt install --build-dir "$srcdir/atom-build" --install-dir "$pkgdir/usr"

	if [[ -d "$pkgdir/usr/share/atom" ]]; then
  	mv "$pkgdir/usr/share/atom" "$pkgdir/usr/share/atom-beta"
	fi
  if [[ -f "$pkgdir/usr/bin/atom" ]]; then
		mv "$pkgdir/usr/bin/atom" "$pkgdir/usr/bin/atom-beta"
  fi
	if [[ -d "$pkgdir/usr/share/atom-beta/resources/app/apm" ]]; then
		mv "$pkgdir/usr/share/atom-beta/resources/app/apm" "$pkgdir/usr/share/atom-beta/resources/app/apm-beta"
  fi
	if [[ -f "$pkgdir/usr/share/atom-beta/resources/app/apm-beta/node_modules/.bin/apm" ]]; then
		mv "$pkgdir/usr/share/atom-beta/resources/app/apm-beta/node_modules/.bin/apm" "$pkgdir/usr/share/atom-beta/resources/app/apm-beta/node_modules/.bin/apm-beta"
  fi
	if [[ -f "$pkgdir/usr/bin/apm" ]]; then
		rm "$pkgdir/usr/bin/apm"
	fi
	ln -sf "${pkgdir}/usr/share/atom-beta/resources/app/apm-beta/node_modules/.bin/apm-beta" "${pkgdir}/usr/bin/apm-beta"
	if [[ -f "$pkgdir/usr/share/applications/atom.desktop" ]]; then
  	rm "$pkgdir/usr/share/applications/atom.desktop"
	fi
	install -Dm644 resources/linux/atom-beta.desktop "$pkgdir/usr/share/applications/atom-beta.desktop"
	install -Dm644 resources/app-icons/beta/png/1024.png "$pkgdir/usr/share/pixmaps/atom-beta.png"
	install -Dm644 LICENSE.md "$pkgdir/usr/share/licenses/$pkgname/LICENSE.md"
}
```

and here is the `atom.install` file:

```bash
post_install() {
  update-desktop-database -q
}

post_upgrade() {
  post_install
}

post_remove() {
  post_install
}
```

Thanks for your time,
Brenton

### PR DESCRIPTION
**Pull request by winstliu**
Continuation of #10983.

Closes #10983.
Fixes #11198.

/cc @drewmnoel

### CODE REVIEW

**Comment by joefitzgerald** [comment]
Bump up to 0.36.12?

**Comment by 50Wliu** [comment]
> Bump up to 0.36.12?

Nice catch!  No idea that existed.

**Comment by Nikki1993** [comment]
Archlinux, builds fine and atom operates as usual.

**Comment by 50Wliu** [comment]
The failing spec seems to be flaky on master so it can probably be ignored.

**Comment by joefitzgerald** [comment]
Friends don't let friends let flakey tests stay flakey :laughing:

**Comment by Nikki1993** [comment]
Atom is still broken on master without this PR. Same as in another PR, can we get this merged asap?

**Comment by n0f3** [comment]
what are the failing checks referring to?

**Comment by libeclipse** [comment]
Months of waiting simply to update electron.

**Comment by n0f3** [comment]
@50Wliu you mentioned that the failing spec seems to be flaky on master as well, does this need to be rebuilt, or can we just approve this PR back to master? I'm wondering if there is anything that we can do to speed this process up

**Comment by lee-dohm** [comment]
What can be done to help speed the process up is if people can give us an idea of what testing they have done to ensure that this doesn't create any regressions. We all want to update to the latest version but only the Atom team is on the hook if a regression is introduced. Since Electron can affect literally anything from Atom's UI to how it interacts with the underlying OS to what JavaScript features are available, *any* Electron upgrade is potentially a breaking change.

So, if people want to help, here's what you can do:

1. Build the branch
1. Run the entire test suite (including all built-in packages) by executing `script/test`
1. Use Atom in a *wide variety* of tasks (preferably the same tasks on different operating systems)

If you run into any problems, get steps to reproduce the problem and verify that the problem does not exist on the latest `master`. If you can do that, report it here.

If you do not run into any problems, add a link to a detailed report here (you can store the report in a [Gist](https://gist.github.com)) of the things you did including:

1. The Atom version including the change number you ran
1. What OS, OS version and machine specs you run Atom on
1. What kinds of tasks you performed
1. What packages you have installed
1. Your entire `config.cson` (feel free to redact anything you consider sensitive, but don't just remove the content ... indicate that something was redacted)
1. Anything else you consider relevant

**Comment by Nikki1993** [comment]
I went as far as updating, locally, electron to 37.5 and in my 2 days of testing I noticed 0 regressions on ArchLinux, Gnome-Shell running under X. Main workflow consists of developing websites with AngularJS with a couple of extra community packages. 

Building latest from master, running 1.9.0 DEV atom version and the build is successful.  Only changes made were edits to package.json to upgrade electron to 37.5 and changes listed in this PR. 

script/test shows no problems apart from 

```
Running "mkdeb" task
>> /usr/bin/fakeroot: line 178: dpkg-deb: command not found
Warning: null Use --force to continue.
Error: null
  at ChildProcess.<anonymous> (/home/nikki/git/atom/build/tasks/task-helpers.coffee:61:37)
  at emitTwo (events.js:100:13)
  at ChildProcess.emit (events.js:185:7)
  at maybeClose (internal/child_process.js:850:16)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
 
```

But that's 99% because of the fact that I am using Arch and not a debian based system hence the mkdeb issue. 

My Confg.cson 
```

"*":
  "activate-power-mode":
    screenShake: {}
  "atom-beautify":
    css:
      newline_between_rules: true
      no_lead_zero: true
      preserve_newlines: true
      selector_separator_newline: true
    general:
      _analyticsUserId: "0db11db5-33b9-49c0-898e-6cde6f599b50"
    html:
      indent_size: 2
      wrap_attributes_indent_size: 2
    scss:
      indent_size: 2
      newline_between_rules: true
      no_lead_zero: true
      preserve_newlines: true
  "atom-material-ui":
    colors:
      abaseColor:
        red: 21
        green: 101
        blue: 192
        alpha: 1
      accentColor:
        red: 255
        green: 0
        blue: 0
        alpha: 1
    tabs:
      tintedTabBar: true
    treeView:
      blendTabs: true
      compactList: true
    ui:
      panelContrast: true
      panelShadows: true
  "autoclose-html":
    legacyMode: true
  core:
    autoHideMenuBar: true
    themes: [
      "atom-material-ui"
      "atom-material-syntax"
    ]
  editor:
    backUpBeforeSaving: true
    fontFamily: "Iosevka"
    fontSize: 16
    softWrap: true
  "exception-reporting":
    userId: "c3cbdaa4-0055-9ead-7c6d-707da5f15280"
  "linter-scss-lint":
    executablePath: "/home/nikki/.gem/ruby/2.3.0/bin/scss-lint"
  welcome:
    showOnStartup: false
```

Packages installed:

- activate-power-mode
- atom-beautify
- atom-material-syntax
- atom-material-ui
- autoclose-html
- emmet
- file-icons
- git-plus
- git-time-machine
- linter
- linter-scss-lint
- minimap
- pigments 

I hope this helps, I do understand that the electron in question is 0.36.12 but I do believe there is no active regressions (at least in general sense of use) to update electron to 0.37.5.

**Comment by libeclipse** [comment]
That's actually quite helpful. Thanks.

I've been running this patched branch for a few days now. Running smoothly so far. I'll attach config and logs after some more testing.

**Comment by amytruong** [comment]
**Mac and Windows*
Basic Smoke Test
- [x] Run through Welcome Guide
- [x] Install and update Packages - fails to delete/uninstall with a message but closing/re-opening app fixes the problem
screen shot 2016-04-11 at 10 58 21 am
- [x] Install and update Themes (same as :point_up: with themes)
- [x] Verify speed and response time
- [x] Verify scrolling is fast
- [x] Verify File menu bars/navigation is functioning 

@50Wliu not sure if these are related to Electron at all but on stable, packages and themes are fine. Just giving you a heads up _just in case_

**Comment by amytruong** [comment]
Also, noticed something a little odd. If you select/unselect options, the "Default" will go in & out.
weird

**Comment by lee-dohm** [comment]
@Nikki1993 Please stick to the branch as implemented. We're not looking at updating to Electron v0.37.x yet. Let's constrain testing reports on this PR to ones that actually test this PR.

**Comment by Nikki1993** [comment]
@lee-dohm understand. I was testing this PR for the past week and no issues arise, using 0.36.12 electron. Everything what I wrote for 0.37.5 electron applies to 0.36.12 no regressions that I can find that would disturb the workflow.

**Comment by lee-dohm** [comment]
> no regressions that I can find **that would disturb the workflow**.

As someone who used to work in QA, the bolded text doesn't fill me with confidence that no regressions were actually found :wink:

**Comment by Nikki1993** [comment]
@lee-dohm again, there is only so much that can be found. I tested atom from the point I am using it and everything is flawless. I try to go above and beyond, but priority atm is to get atom in a **working** condition for Arch users. I always leave a seed of doubt, hence the 

> no regressions that I can find that would disturb the workflow.

Naturally, I tend to test software extensively when the time allows but presently atom is broken on Arch based systems and causes headaches to update. I feel like if no problems are found that would break things even further, it's safe to merge and deploy. This PR is a successor to different PR which has been around for a few weeks already. 

P.S. I am interested in QA testing and I support that a great deal of tests should be executed before merging framework changes, however when things are broken I believe things can be sped up a little bit :P

**Comment by lee-dohm** [comment]
I appreciate where you're coming from and, in general, agree with your point of view. What we're looking for is "regressions". My apologies for assuming that everyone is familiar with the term. A regression is defined as something that used to work that no longer does. So yes, we're on the same page.

What confused me about your phrasing is that it sounded like you had found regressions (again, things that once worked that no longer do) but had discounted them as not disruptive to some workflow. Since exhaustive testing is generally not possible in any non-trivial system (and definitely not possible in one of Atom's size), any regression is cause for concern. But from your latest message, it sounds like you didn't find any regressions ... just things that haven't ever worked on Arch?

**Comment by libeclipse** [comment]
>definitely not possible in one of Atom's size

The irony.

**Comment by Nikki1993** [comment]
@lee-dohm my apologies. I have always had troubles expressing myself clearly. 

1. Yes, I am aware what regressions are, so we are indeed on the same page. 
2. I did not find any regressions.
3. To my knowledge, everything on Arch works as expected. There are no things that are not working, apart from Atom not starting without electron bump we are discussing in this PR. :) 
4. ??? profit :D 

I hope I made myself clear now and apologies once again for confusion on my part.

**Comment by alyst** [comment]
Not 100% sure if it's related, but since the upgrade to 1.7.0 (the latest `atom-editor` ArchLinux package that now builds from this PR branch) `julia-client` package fails to load with the message
```
ENOENT, common/api/lib/shell.js not found in /usr/share/atom/resources/atom.asar

Error: ENOENT, common/api/lib/shell.js not found in /usr/share/atom/resources/atom.asar
    at notFoundError (ATOM_SHELL_ASAR.js:110:13)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:435:9)
    at compileFileAtPath (/usr/share/atom/resources/app.asar/src/compile-cache.js:69:23)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:207:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/astukalov/.atom/packages/julia-client/lib/package/commands.coffee:1:25)
    at Object.<anonymous> (/home/astukalov/.atom/packages/julia-client/lib/package/commands.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/astukalov/.atom/packages/julia-client/lib/julia-client.coffee:1:12)
    at Object.<anonymous> (/home/astukalov/.atom/packages/julia-client/lib/julia-client.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:173:16)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
```
(the same error as in JunoLab/atom-julia-client#117)

**Comment by lee-dohm** [comment]
> the latest atom-editor ArchLinux package that now builds from this PR branch

This is really concerning to me. Is this accurate?

**Comment by lee-dohm** [comment]
> my apologies. I have always had troubles expressing myself clearly.

@Nikki1993 No apologies necessary :grinning: We got everything figured out. Thank you for helping work on this! :bow:

**Comment by Nikki1993** [comment]
@lee-dohm I just know that my thoughts are faster than I can type/speak them. :D 

Let me know if there is any additional steps/tests/etc that I can do, since I just noticed you are an Atom member, to speed up the merge of PR.

**Comment by lee-dohm** [comment]
@Nikki1993 Well, since @amytruong found some potential regressions :point_up: Can you try to reproduce them on your machine?

**Comment by Nikki1993** [comment]
I can confirm the julia-client crash on atom from latest master

`Error: Invalid package /usr/local/share/atom/resources/atom.asar
    at invalidArchiveError (ATOM_SHELL_ASAR.js:137:13)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:430:9)
    at compileFileAtPath (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:69:23)
    at Object.defineProperty.value [as .js] (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:207:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/nikki/.atom/packages/julia-client/lib/package/commands.coffee:1:25)
    at Object.<anonymous> (/home/nikki/.atom/packages/julia-client/lib/package/commands.coffee:1:1)
    at Module._compile (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/nikki/.atom/packages/julia-client/lib/julia-client.coffee:1:12)
    at Object.<anonymous> (/home/nikki/.atom/packages/julia-client/lib/julia-client.coffee:1:1)
    at Module._compile (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/local/share/atom/resources/app.asar/src/package.js:715:27)
    at /usr/local/share/atom/resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/usr/local/share/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/local/share/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/local/share/atom/resources/app.asar/src/package-manager.js:457:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/local/share/atom/resources/app.asar/src/package-manager.js:536:30)
    at /usr/local/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:452:29
    at exit (/usr/local/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/local/share/atom/resources/app.asar/src/buffered-process.js:215:47)
    at /usr/local/share/atom/resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/usr/local/share/atom/resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)` 

I do believe that this is not electron issue as looking at issues reported to julia-client package atom version there was 1.5.3 when the first crash occurred.

I will check if issue is present on stable 1.6.x on Windows.

**Comment by lee-dohm** [comment]
When you say "latest master", are you referring to Atom's latest master? Or the atom-editor Arch Linux package's latest master?

**Comment by Nikki1993** [comment]
@lee-dohm latest Atom's master from git. I build atom-editor myself, not through Arch AUR system.

**Comment by Nikki1993** [comment]
However, julia-client is **NOT** crashing on Atom 1.6.2 Windows 10 64bit.

**Comment by lee-dohm** [comment]
Ok, since it is from the latest master. Please open a separate issue for it.

**Comment by alyst** [comment]
@lee-dohm `atom-editor` AUR package uses 1.7.0 release + the patch based on this PR as a hotfix. So it could be a regression in the stable atom 1.7.0 (unless it's some `julia-client` internal bug).

**Comment by 50Wliu** [comment]
The fact that atom-editor is (only partially) patching in this PR in is _extremely_ concerning.
As described in a couple of places, the filepaths for common Electron modules were changed, and Atom's module cache needs to be updated to reflect that (as has been done in this PR).  However based on @Nikki1993 and @alyst's reports, it appears that `atom-editor` failed to include the entire PR diff and only updated the Electron version.

@amytruong I've actually been experiencing that for a while now (at least for two packages) on master.

**Comment by alyst** [comment]
@50Wliu Sorry for the confusion, I've checked the [patch](https://aur.archlinux.org/cgit/aur.git/commit/?h=atom-editor&id=276db3d0b4e88103bd7121d672f00c18bdd16ca4) that the AUR package is actually using and it *does not* look like the whole PR (however, I have really no idea how it should look). OTOH @Nikki1993 reports the independent build has the same issue.

**Comment by 50Wliu** [comment]
Upon looking closer at @Nikki1993's error, that one doesn't seem to be due to module require problems and seems to me like something is wrong with `atom.asar`.

**Comment by sjug** [comment]
@50Wliu: If you didn't ship utterly broken releases then I wouldn't need to patch them. I'm working on a more comprehensive patch covering the whole PR for the julia issue.

**Comment by 50Wliu** [comment]
[This test](https://github.com/atom/atom/blob/043982ca3d6b2debeb0f1f542c64bcfc0c1c824d/spec/module-cache-spec.coffee#L11) should have failed prior to the path updates, but it didn't, maybe because [this expect](https://github.com/atom/atom/blob/043982ca3d6b2debeb0f1f542c64bcfc0c1c824d/spec/module-cache-spec.coffee#L17) doesn't have an assertion (eg `.toBeTruthy()`)?  I'll see if I can get it working properly.

@amytruong I'm seeing the `default` flicker even on Atom `1.9.0-dev-043982c`.

**Comment by 50Wliu** [comment]
The aforementioned spec has been fixed and I found a bug as a result :smile:.

**Comment by alyst** [comment]
I was trying to build AUR package using the patch from this branch (not including the changes from the last hour) instead of the `package.patch`, but then Atom was freezing again at startup even in the safe mode (although AFAIR non-patched atom 1.7.0 was not showing the file contents at all, the patched one showed it).
When I additionally included the changes from the `package.patch` (`nodegit` is updated to 0.12.2), everything was fine, including the `julia-client` package.
However, there are currently difficulties with APM packages downloading and I had to restart the `atom-edit` package build several times, so I'm not entirely sure if the freezing is really related to `nodegit`.

**Comment by sjug** [comment]
@alyst The 1.7.0-4 package now contains all of this PR which went up about 15 minutes ago.

The nodegit update is a i686 specfic issue patch unrelated to this PR.

**Comment by alyst** [comment]
@sjug Thanks, 1.7.0-4 so far is working fine for me.

**Comment by ryanpcmcquen** [comment]
All works here. Everything in `script/test` passes (except for `mkdeb`, which I cannot test on **Slackware**):

```
~/Downloads/atom-wl-drewmnoel-electron:$ script/test
Node: v4.4.3
npm: v2.13.3
Installing build modules...
=> Took 2764ms.

Installing apm...
=> Took 841ms.

Deleting old packages...
Removing .atom-ci-fingerprint ✓
=> Took 1116ms.

Installing modules ✓
=> Took 3167ms.

Deduping modules ✓
=> Took 3445ms.

Running "output-disk-space" task

Running "download-electron" task

Running "download-electron-chromedriver" task

Running "build" task

Running "babel:dist" (babel) task

Running "coffee:glob_to_multiple" (coffee) task
>> 334 files created.

Running "prebuild-less:src" (prebuild-less) task
>> 0 files compiled, 1891 files reused

Running "cson:glob_to_multiple" (cson) task
>> 172 files compiled to JSON.

Running "peg:glob_to_multiple" (peg) task
Generating parser from "node_modules/snippets/lib/snippet-body.pegjs"...
Parser "~/Downloads/atom-wl-drewmnoel-electron/out/Atom/resources/app/node_modules/snippets/lib/snippet-body.js" generated in 26ms.

Running "generate-license:save" (generate-license) task

Running "generate-module-cache" task

Running "compile-packages-slug" task

Running "fingerprint" task
Wrote ci fingerprint: ~/Downloads/atom-wl-drewmnoel-electron/node_modules/.atom-ci-fingerprint 9c072ab8dc1aa60545b237c27666af2e0e74cd14

Running "set-version" task

Running "check-licenses" task

Running "standard:src" (standard) task

Linting files...

✓ No Problems

Running "coffeelint:src" (coffeelint) task
>> 118 files lint free.

Running "coffeelint:build" (coffeelint) task
>> 29 files lint free.

Running "coffeelint:test" (coffeelint) task
>> 73 files lint free.

Running "csslint:src" (csslint) task
>> 0 files lint free.

Running "lesslint:src" (lesslint) task
>> 29 files lint free.

Running "generate-asar" task

Running "mktar" task
>> Created ~/Downloads/atom-wl-drewmnoel-electron/out/atom-1.8.0-dev-amd64.tar.gz

Running "publish-build" task

Running "upload-assets" task

Done, without errors.


Execution Time (2016-04-19 14:35:44 UTC)
loading tasks             1.9s  ▇▇ 3%
build                     6.4s  ▇▇▇▇▇ 12%
babel:dist                1.2s  ▇ 2%
coffee:glob_to_multiple   7.1s  ▇▇▇▇▇ 13%
prebuild-less:src         1.1s  ▇ 2%
generate-license:save    821ms  ▇ 1%
generate-module-cache     1.2s  ▇ 2%
check-licenses           566ms  ▇ 1%
standard:src              1.2s  ▇ 2%
coffeelint:src            5.2s  ▇▇▇▇ 9%
coffeelint:build         557ms  ▇ 1%
coffeelint:test           8.3s  ▇▇▇▇▇▇ 15%
lesslint:src              1.5s  ▇ 3%
generate-asar             6.3s  ▇▇▇▇▇ 11%
mktar                    11.5s  ▇▇▇▇▇▇▇▇ 21%
Total 55.2s

~/Downloads/atom-wl-drewmnoel-electron:$
```

It is great to have a working Atom again!

**Comment by 50Wliu** [comment]
There's no need to run `script/test` on Linux as no tests are actually run.

**Comment by ryanpcmcquen** [comment]
@50Wliu what is all the output then?

**Comment by 50Wliu** [comment]
As I briefly described in #11516, that's just Atom building itself and then making sure it can publish a release.  Currently only OS X runs the specs when `script/test` is run.

**Comment by as-cii** [comment]
Thanks @50Wliu and @drewmnoel! 🎉

**Pull request merged**
