### PR TITLE
Upgrade Squirrel for Windows

### PR DESCRIPTION
**Pull request by kevinsawicki**
Long time coming, upgrades to Squirrel for Windows 0.99.3 via upgrading the grunt plugin for creating electron installers.

### CODE REVIEW

**Comment by paulcbetts** [comment]
:+1: :sparkles:

**Comment by kevinsawicki** [comment]
@paulcbetts there is nothing special we need to do for migrations right? Squirrel should handle this upgrade like others right?

I only ask based on the bit changelog of things since we last upgraded, thanks.

**Comment by paulcbetts** [comment]
@kevinsawicki The only thing I can think of is when we added back in BSDiff, you should test an upgrade first. Build the app, install the public version then:

```sh
cd \Users\NAME\AppData\Local\Atom
update.exe --update \path\to\the\atom-build\Installers
```

If it works, you're :gem:

**Comment by kevinsawicki** [comment]
>  you should test an upgrade first.

Followed your instructions and was able to go from official 1.0.3 to the 1.0.4 draft release, thanks for your help :+1:

**Comment by maaarghk** [comment]
I have been on 1.0.3 for a while and turns out 1.0.5 has been downloaded on my system. Atom.sh / atom.cmd were not updated during this download and the "Check for updates" menu said 1.0.3 was the latest version? Related? Windows 10, FYI.

**Pull request merged**
