### PR TITLE
Upgrade pathwatcher

### PR DESCRIPTION
**Pull request by fscherwi**
Upgrade pathwatcher, which has no API-changes and better support for UNIX-like systems!

### CODE REVIEW

**Comment by lee-dohm** [comment]
@maxbrunsfeld @50Wliu is there anything between v6.2 and v6.3 of pathwatcher that necessitates this upgrade? From looking at the history, it looks mostly like CI and build changes?

**Comment by 50Wliu** [comment]
Looks like 6.3.0 might help out people trying to build Atom on OpenBSD/FreeBSD (#6035, though they don't seem to have had troubles with pathwatcher yet).  Other than that, it looks like the upgrade is just for the sake of upgrading.  I never got any warnings when building Atom on Windows and VS2015, so *shrug*.  Perhaps that's only when directly building pathwatcher.

**Comment by damieng** [comment]
We should probably bump right up to 6.5 as there are some fixes for watching root of drives on Windows, treating move to trash as delete on the Mac etc.

**Comment by fscherwi** [comment]
@damieng changed pathwatcher to 6.5

**Comment by lee-dohm** [comment]
Thanks for this!

If you could include whatever testing you've done before submitting the PR, that would be helpful :grinning:

**Pull request merged**
