### PR TITLE
Add code of conduct to contributing guidelines

### PR DESCRIPTION
**Pull request by bkeepers**
I have discussed this with @atom/core and they intend to adopt and uphold this code of conduct. It will apply to all repositories in the [@atom GitHub organization](https://github.com/atom), the [discussion forum](https://discuss.atom.io/), and [chat rooms](http://atom-slack.herokuapp.com/).

A blog post on atom.io will be coming soon about it.

### CODE REVIEW

**Comment by nathansobo** [comment]
:+1:

**Comment by mnquintana** [comment]
:+1: 

Should this maybe be in its own section in CONTRIBUTING? What about adding it to the Readme too?

**Comment by kevinsawicki** [comment]
> What about adding it to the Readme too?

I think it should be in the README

**Comment by kevinsawicki** [comment]
Thanks for this @bkeepers it is a great step forward :feet:  :+1:

**Comment by batjko** [comment]
I haven't read through the details yet, and I'm sure it's the right move forward. But what's the expected impact on this CoC? Does it change anything the core devs or the community currently do in any significant way?

**Comment by kevinsawicki** [comment]
> But what's the expected impact of this CoC?

The only immediate expected impact is that when people visit the chat room, repo, and forums, they know the project has a code of conduct in place.

> Does it change anything the core devs or the community currently do in any significant way?

No significant changes, but it does present a document to refer to when discussing potential conduct issues with people.

**Comment by batjko** [comment]
Ok understood. :+1: 
I'll read into the details some more as well.

**Pull request merged**
