### PR TITLE
⬆️ electron-notarize@1.0.0

### PR DESCRIPTION
**Pull request by atom-build**
Bumps electron-notarize from 0.2.1 to 1.0.0

### CODE REVIEW

**Review by ekr696-beep — APPROVED** [review]

**Review by aminya — CHANGES_REQUESTED** [review]
This needs rebasing

**Review by ekr696-beep — APPROVED** [review]

**Comment by sadick254** [comment]
The commits could use a little bit of clean up. Maybe squash them to `⬆️ electron-notarize@1.0.0`

**Comment by darangi** [comment]
@sadick254 , I will go ahead and squash the commits

**Comment by sadick254** [comment]
@darangi I have squashed and merged. Don't worry about it.

**Pull request merged**
