### PR TITLE
Bundle the hyperclick package

### PR DESCRIPTION
**Pull request by oclbdk**
This will allow 3rd parties to start creating packages to allow users to perform actions by clicking on text.

Note the BSD-3-Clause license and patent grants.

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
@oclbdk Thanks for starting up this discussion in an issue. We like what you've done with hyperclick so far, but we aren't ready to bundle it with Atom yet.

Here are some we would need you to do:
* [ ] Extract the `ctags` logic from `symbols-view` into a new package (called `hyperclick-ctags` or something) that provides a `hyperclick.provider` service. Our team uses this ctags functionality every day while developing Atom. This will allow us to start using hyperclick instead, so that we can start to find any bugs, missing features or performance issues with the package.
* [ ] Show us some other of your open-source packages that use hyperclick.

Some things that your team and the @atom/core team need to discuss together:
* [ ] Consider moving the ability to define mouse event handlers into Atom core, so that other packages besides hyperclick can do things like this using Atom's command system.
* [ ] Add a way of selecting a suggestion when there are multiple suggestions for the same symbol. This should work like Atom's other select lists.

And some for the Atom team to do:
* [ ] Discuss with our legal team whether we can bundle a package w/ hyperclick's license and patent grants.
* [ ] Discuss if we have any issues w/ bundling a package that uses Flow and Babel.

These lists are a work in progress. @atom/core please feel free to add or adjust items.

**Comment by thedaniel** [comment]
I added a list item for moving the package repo into @atom.

**Comment by oclbdk** [comment]
Thanks for the comments! I'll get working on the features (i.e. ctags provider, selection for multiple suggestions).

If this code gets moved into @atom, we could probably use the MIT license. @jamesgpearce @bolinfest

**Comment by oclbdk** [comment]
After talking with a legal representative from Facebook, we should be able to use the MIT license.

**Comment by kevinsawicki** [comment]
Closing this out for now, will reopen once this is closer to a shippable state.

**Pull request closed without merging**
