### PR TITLE
Indent Works Properly When AutoIndent Is Unchecked

### PR DESCRIPTION
**Pull request by ebroom2014**
This is in regard to https://github.com/atom/atom/issues/10407

Before when the `AutoIndent` was unchecked and you were to copy and paste a section of text with a newline character, it would still indent. See bug report for more details. [Here is a video of the original bug.](https://youtu.be/S0rydB18HtM)

In this changed code in `selection.coffee` it checks to see if `AutoIndent` is checked before it does the indent adjustment. [You can see atom working properly here.](https://youtu.be/vhU2I4xq3PY)

### CODE REVIEW

**Comment by ebroom2014** [comment]
Also, I updated the Linux README because I had some troubleshooting errors that were not written about in the README and I know of others who have had the same problem. There were also some spelling errors that I fixed.

Also, I added an uninstall portion of the Linux README because I could not find a compiled list of how to uninstall Atom anywhere. I thought this would be helpful for others.

**Comment by 50Wliu** [comment]
You seem to have inadvertently reverted many recent changes to the Linux build instructions.  Can you please create a new PR for the build instruction changes to make reviewing easier?  Thanks.

**Comment by ebroom2014** [comment]
I did inadvertently revert some changes to the Linux build instructions. I have pushed the correct file for PR up. Thank you for noticing this.

**Comment by sadick254** [comment]
Hey @ebroom2014 , I know this PR has been open for a long time. Apologies for not being able to look into it in a timely manner. There have been many changes on Atom since this PR was authored i.e We migrated a good number of our source files from `CoffeeScript to `Javascript`. This has led to some conflicts on this PR that are not easily resolvable. 

I have created a separate PR that supersedes this one. I will close this for now but don't hesitate to reach out in case of any queries. 

Thank you for your contribution.

**Pull request closed without merging**
