### PR TITLE
Fixes #10388 for Linux Based Systems

### LINKED ISSUE #10388: Atom's Documentation Does Not Tell the End User dpkg Requires Git to be Installed
I recieved this error while installing atom via dpkg: 
```bash
$ sudo dpkg --install atom-amd64.deb
[sudo] password for mhiiva: 
Selecting previously unselected package atom.
(Reading database ... 160643 files and directories currently installed.)
Preparing to unpack atom-amd64.deb ...
Unpacking atom (1.3.3) ...
dpkg: dependency problems prevent configuration of atom:
 atom depends on git; however:
  Package git is not installed.

dpkg: error processing package atom (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Errors were encountered while processing:
 atom
```
I have looked over the [Atom on Linux](https://atom.io/docs/v0.194.0/getting-started-installing-atom#atom-on-linux) and the [README](https://github.com/atom/atom/blob/master/README.md), and I found no mention of git being a requirement for atom to be installed. Could this be mentioned in the [README](https://github.com/atom/atom/blob/master/README.md) and [Getting Started Docs](https://atom.io/docs/v0.194.0/getting-started-installing-atom)?

### PR DESCRIPTION
**Pull request by michaelhiiva**
I added a few additions for Linux based on how to install git.

### CODE REVIEW

**Comment by benogle** [comment]
Do we need to educate people on installing git? cc @atom/feedback

**Comment by mnquintana** [comment]
I think instead of adding specific instructions for installing Git, we should add a "Prerequisites" section that just lists the things we expect users to have already set up on their machines (Git included). That way we don't have to maintain installation instructions for them.

**Comment by maxbrunsfeld** [comment]
> That way we don't have to maintain installation instructions for them.

:+1:

**Comment by lee-dohm** [comment]
> we should add a "Prerequisites" section that just lists the things we expect users to have already set up on their machines (Git included).

We could include links to at least the home page if not installation instructions?

**Pull request closed without merging**
