### PR TITLE
Electron 9.4.1

### PR DESCRIPTION
**Pull request by mfonville**
Electron ~9.4.0~ 9.4.1 is more recent stable than 9.3.5

### CODE REVIEW

**Comment by mfonville** [comment]
@sadick254 Should be trivial

**Comment by asturur** [comment]
Is there any macos build for this branch to test it out?

**Comment by DeeDeeG** [comment]
@asturur I can make one. Are you on a specific OS (Linux, macOS, Windows)? There have been some build problems affecting some OSes with the Electron 9 upgrade at the moment, and the upgrade isn't finished yet, but there are workarounds, so I think I could build for any OS.

**Comment by asturur** [comment]
i m on macos 10.15.7, or if there is a consistent way to build i m fine building it.

I just did non want to mess up with brew too much since i m worried to messup some libraries as i did in the past

**Comment by DeeDeeG** [comment]
Here is a build I did in my fork's CI: https://dev.azure.com/DeeDeeG/b/_build/results?buildId=959&view=artifacts&pathAsName=false&type=publishedArtifacts

Direct download link: https://dev.azure.com/DeeDeeG/_apis/resources/Containers/11598672/atom-mac.zip?itemPath=atom-mac.zip%2Fatom-mac.zip

**Comment by asturur** [comment]
Thank you it works great, feels smoother than the latest nightly.
I know is probably a placebo effect :)

**Comment by ThatXliner** [comment]
When is this going to be merged?

**Comment by DeeDeeG** [comment]
So, just to be clear, this is to bump the "Electron 9" effort up from 9.3.5 to 9.4.x

The main thing blocked is getting the app fully working and tests passing on Electron 9, generally speaking. I suppose it wouldn't hurt to merge this to the Electron 9 PR, with the understanding that there is still work to do for Electron 9 more generally.

**Comment by asturur** [comment]
just to add my 2 cents, i tried the build more and i realized sometimes it was impossible to quit or start new windows  or add project folders.

Now this could also be caused by my addons setup not ready for electron 9.

Not blaming anynone, just saying it wasn't as smooth as it seemed first 2 days.

**Comment by DeeDeeG** [comment]
Hi @asturur, I think that was fixed in https://github.com/atom/atom/pull/21847 but it didn't make its way to the Electron 9 branches yet.

Not sure if others see this, but opening project folders and files wasn't working very well for me on the Electron 9 branch last time I tried it.

**Comment by sadick254** [comment]
I can confirm that opening projects/files is still buggy on the electron 9 branch.

**Comment by mfonville** [comment]
Thanks for merging.

I tried opening projects and files but have not experienced those problems, using the build from https://github.com/atom/atom/pull/21777/commits/a241462bbff56c344e0d3db2822c1080a3d1fb89

**Comment by DeeDeeG** [comment]
> I tried opening projects and files but have not experienced those problems, using the build from a241462

@mfonville if you don't mind, what OS are you using? Is this Linux (Ubuntu)?

**Comment by mfonville** [comment]
Yes, Ubuntu Linux 20.10

Though Atom had forgotten my recent project history when I switched back to the stable build (using the same atom configuration directory)

**Pull request merged**
