### PR TITLE
Add troubleshoot info about missing https helpers

### PR DESCRIPTION
**Pull request by SeriousM**
I'm using Win7 x64 with the git-bash with version 1.9.2.msysgit.0.
For some reason I can't build the package because it can't find the https helpers.
I found [this atom issue](https://github.com/atom/atom/issues/2206#issuecomment-43443805) which helped me a lot and I thought I need to add this information in the build readme.

Here is my error log for reference. 

```
 (master) /c/OWN/SCM-Store/GitHub/atom/atom$ script/build

Installing modules ✗

> atom@0.99.0 preinstall C:\OWN\SCM-Store\GitHub\atom\atom
> node -e 'process.exit(0)'


npm ERR! git fetch -a origin (https://github.com/atom/bootstrap.git) fatal: Unable to find remote helper for 'https'
npm ERR! Error: Command failed: fatal: Unable to find remote helper for 'https'
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:637:15)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:743:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\OWN\\SCM-Store\\GitHub\\atom\\atom\\apm\\node_modules\\atom-package-manager\\bin\\node.exe" "C:\\OWN\\SCM-Store\\GitHub\\atom\\atom\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\OWN\\SCM-Store\\GitHub\\atom\\atom\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\root\\.atom\\.apmrc" "install" "--target=0.11.10" "--arch=ia32" "--quiet" "--msvs_version=2010"
npm ERR! cwd C:\OWN\SCM-Store\GitHub\atom\atom
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! code 128
npm
 (master) /c/OWN/SCM-Store/GitHub/atom/atom$
```

### CODE REVIEW

**Comment by izuzak** [comment]
I was looking into this old PR and wondering if it's something we should close or clean up and merge. It seems that quite a few folks reported this problem https://github.com/atom/atom/issues/2206. As far as I understand, it's possible that Git is in the PATH, but not that's not enough for some reason? A user wrote up detailed instructions which worked for him in [this comment](https://github.com/atom/atom/issues/2206#issuecomment-47729113). 

@paulcbetts @kevinsawicki Any thoughts on this one? Wish I knew more about Windows.

**Comment by izuzak** [comment]
Ahh, there's another PR to add those detailed build instructions: https://github.com/atom/atom/pull/2803

**Comment by paulcbetts** [comment]
The clue is in the build output:

>  (master) /c/OWN/SCM-Store/GitHub/atom/atom$ script/build

Stop using Bash as your shell and all of these weirdo problems will go away

**Comment by lee-dohm** [comment]
I apologize for letting this PR go for so long without resolution. Is this something that still needs to be added to the build instructions? Or is this PR superseded by #2803. Let us know!

**Comment by lee-dohm** [comment]
Thanks for the work went into this PR @SeriousM. Let us know if this is something you want to update in the future.

**Comment by SeriousM** [comment]
@lee-dohm The PR is two years old, I don't build atom myself anymore since there are automatic builds available. Thanks

**Pull request closed without merging**
