### PR TITLE
Save state of open windows more frequently

### PR DESCRIPTION
**Pull request by maxbrunsfeld**
We now save the open windows whenever:
- A new window is opened
- A window loses focus
- A window is closed (unless it's the last window open on linux or windows)
- `atom.exit()` is called

Refs #6466

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
@kevinsawicki could you :eyes: this code when you get a chance? I moved the logic for quitting when closing the last window on linux/windows to support the saving behavior. I tested it on Ubuntu and everything seemed :ok_hand:.

**Comment by kevinsawicki** [comment]
Looks good to me.

Just want to confirm, the window closed event fires when you quit the app via `cmd-q` and also calling `atom.exit()`?

I always forget if there are certain cases where it doesn't.

**Comment by maxbrunsfeld** [comment]
It looks like that event is not triggered if you call `atom.exit()`. Do you think we should we save the open windows in the `will-exit` handler so that they still get saved if you call that method?

**Comment by kevinsawicki** [comment]
> Do you think we should we save the open windows in the will-exit handler so that they still get saved if you call that method?

Sounds good :+1:

**Comment by rebornishard** [comment]
nice :+1:   
thank you, now i can click 'x' button properly :dancers:

**Pull request merged**
