### PR TITLE
Add settings to enable and disable softTabs autodetection

### PR DESCRIPTION
**Pull request by Abdillah**
This solved the issue (partly), discussed on #3719.

I create new config item to specify tabType used by default. But, it clearly conflicting with softTabs config item. I didn't remove it, even I think it's safe to be removed, is it?

tabtype

### CODE REVIEW

**Comment by mnquintana** [comment]
Thanks for contributing! [This seems to break a lot of specs](https://travis-ci.org/atom/atom/builds/73663507) – you'll need to fix those before this can be considered for merging.

**Comment by Abdillah** [comment]
Ok, I don't aware of that tailing spec test and neither I have test it myself.
Thanks for pointing.

**Comment by Abdillah** [comment]
__Checkpoint One__
Up to this point is test-error free, at least in my computer. 
If travis say so, I'm ready for review..

**Comment by benogle** [comment]
I've created a new PR to add this setting at #8356. This PR is trying to do too much (new API methods, setting config in the editor), and it is lacking specs. I have used a couple commits from this PR in the new one.

**Comment by Abdillah** [comment]
@benogle Great! Thanks.
I will closes this, as I intent the same things as #8356.

**Pull request closed without merging**
