### PR TITLE
Support semanticolor

### PR DESCRIPTION
**Pull request by sharedprophet**
### Issue or RFC Endorsed by Atom's Maintainers

#19151

### Description of the Change

Pass node text to grammar for leaf parser nodes.

### Alternate Designs

This is the only way for grammars to use the text to determine styling.

### Possible Drawbacks

Performance penalty of unmarshalling from native text buffer is mitigated by only passing text for leaf nodes.

### Verification Process

I have been running with this locally for over a week with no issues.

### Release Notes

Pass syntax node text to grammar for leaf parser nodes, to support grammars that determine styling based on token values.

### CODE REVIEW

**Comment by ret394** [comment]
please elaborate on performance issues, seems brief. mention no of ops, O(n) or O(log n), etc.

**Comment by sharedprophet** [comment]
Re: performance penalty, I am referring to @maxbrunsfeld's comment [here](https://github.com/atom/atom/issues/19151#issuecomment-486081208):

> The `.nodeText` accessor on the `TreeCursor` has some performance cost. It needs to read a string from the native text buffer, and for internal syntax nodes (like a function declaration) it may be a very big string. And that line of code executes _many_ times per syntax-highlighted line. So I'd like to avoid that performance cost if possible.

This solution avoids calling the `.nodeText` accessor on most long strings, by only calling it on syntax nodes with no children.

**Comment by ocoka** [comment]
Hi to all Atom comunity, and all mantainers, if you can, you have a time and possibility, please promote this PR to positive decision to merge. Today more and more plugin developers are living for VSCode, but there are several gems that make Atom still the best, and great "SemanticColor" extension is one of them

**Comment by HugoMcPhee** [comment]
Is there anything needed to help to get this through?
For a temporary fix, semanticolor still works in separately downloadable atom v1.42

**Comment by lkashef** [comment]
@sharedprophet could you please make sure the CI is green, currently it's failing due to lint errors.

You can check the linting, by navigating to your repo and running `script/lint` from command line.

**Comment by sharedprophet** [comment]
Looks like some unrelated tests timed out on Win64...?

**Comment by lkashef** [comment]
@sharedprophet re-running the ci

**Comment by sharedprophet** [comment]
Win64 tests seem flaky... something is up with the promises on there. It is [failing on a PR to fix typos](https://github.visualstudio.com/Atom/_build/results?buildId=72655&view=logs&j=4fbced83-508e-5fe0-c978-5c71ec0fc506&t=0cce7676-f298-5a2d-7f62-c11c27855377) and that doesn't seem right.

**Comment by ocoka** [comment]
Hello, as I see PR is ready and reviewed, but CI failed for non related stuff... What is the next step, maybe rerun CI again, and cross the fingers ? )

**Comment by ocoka** [comment]
image
Hi, strange thing ... but oldier builds than that run is present

**Comment by lkashef** [comment]
New CI Run https://github.visualstudio.com/Atom/_build/results?buildId=77881&view=results

**Comment by ocoka** [comment]
Hello,
in the link, provided by @lkashef all state are green,
image
why CI state in this thread still shows some errors ?!

**Comment by lkashef** [comment]
Thanks @ocoka for the heads up.

When the build is expired/deleted from Azure Devops, and a new manual run (instead of pushing a dummy commit) against the PR doesn't get picked up by the Github, that's why I provided the link above.

---

Thanks @sharedprophet for the contribution, I will go ahead and merge this PR

**Comment by jeff-hykin** [comment]
Is there a place I can find more info on this?  (Both accessing text nodes inside grammars and semanticolor)

**Comment by DeeDeeG** [comment]
@jeff-hykin the [diff](https://github.com/atom/atom/pull/20212/files) is pretty small, and there is a new [test](https://github.com/atom/atom/pull/20212/files#diff-bd6345b8aaaa4685a5b17cf80d42ef08) that presumably demonstrates the functionality. I hope that can shed some light on the changes.

**Comment by sharedprophet** [comment]
@jeff-hykin inside a grammar, the change will sometimes provide the node text as a second parameter to the `idForScope` function. You can only take advantage of this if you are creating a grammar with code rather than a normal TreeSitter or TextMate grammar file, though.

**Comment by jeff-hykin** [comment]
@sharedprophet Ah thanks for the explanation that's what I was curious about 👍

And thanks @DeeDeeG

**Pull request merged**
