### PR TITLE
Add app name to the Quit menu on macOS

### PR DESCRIPTION
**Pull request by sindresorhus**
To adhere to the macOS Human Interface Guidelines: https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/MenuBarMenus.html

### CODE REVIEW

**Comment by sindresorhus** [comment]
// @daviwil

**Comment by 50Wliu** [comment]
Updated link. https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-bar-menus#app-menu

Should this display 'Quit Atom Beta', 'Quit Atom Dev', etc. for the relevant channels, or is just 'Quit Atom' good enough?

**Comment by sindresorhus** [comment]
@50Wliu I went with hardcoding the name as that's how it's done in the `About Atom` menu item.

**Comment by lee-dohm** [comment]
Thanks for this!

**Pull request merged**
