### PR TITLE
Added context menu for cinnamon desktop enviroment (Linux)

### PR DESCRIPTION
**Pull request by passeride**
This is just to get a simple context menu for cinnamon desktop enviroment (Nemo file manager)

### CODE REVIEW

**Review by sadick254 — APPROVED** [review]
Looks Good. 👍

**Review by Tinaket7676 — COMMENTED** [review]
_PpFq218uJd6DLVzdcME5Jw

**Comment by catscarlet** [comment]
A little confused.
Cinnamon Nemo can already open anything with Atom by using **Open With**.

DSC_5586


There is no need to make a nemo.action to do such a thing. Also I didn't see any uninstall .sh, nor any not-cinnamon-desktop has this.

**Comment by jnuernberg** [comment]
The piece of code introduced with this commit seems to cause an error, when launching atom from command line:
```
$ atom test.txt
cp: cannot stat 'resources/linux/desktopenviroment/cinnamon/atom.nemo_action': No such file or directory
```
System is linux mint 20.3 cinnamon, atom installation via apt. Fresh install.

As far as I can diagnose it, the atom script (usually located at `/usr/bin/atom`) cannot locate the `atom.nemo_action` file when not compiling from source. I would suggest to comment/disable this bit of code in the startup for now. 

As nicely pointed out by @catscarlet, Nemo can already open anything with atom using Open With

**Comment by jnuernberg** [comment]
Good evening, 

I just opened issue #25294 on this issue. 
This persistent error message is annoying. 

Best regards.

**Pull request merged**
