### PR TITLE
Update docs for Gutter

### PR DESCRIPTION
**Pull request by MaximSokolov**

### CODE REVIEW

**Comment by thomasjo** [comment]
@MaximSokolov Thanks for contributing. I'm guessing you made these changes because you couldn't find anything specific to `Gutter` on https://atom.io/docs/api/?

The existing docs looks valid, except for the fact that `GutterContainer` and `Gutter` have not been marked as e.g. *Extended*, so they don't currently generate any entries as part of the documentation generation. See e.g. https://github.com/atom/atom/blob/v1.0.3/src/clipboard.coffee#L16 for an example on how to mark a class as *Extended*. Whether you close this PR and open a new one with the correct changes, or rework this one is up to you. If you want to keep this one, nuke the two commits and start again from a clean slate.

Let me know if you need more specific guidance :bow:

**Comment by maxbrunsfeld** [comment]
I don't think that the `GutterContainer` or `Gutter` classes need to be made public. We *could* do that if there was a need, but that would be a much bigger change, and a commitment to supporting the direct use of those classes.

In the meantime, I think @MaximSokolov is correct that the detailed docs should go on the method that *is* public, `TextEditor::addGutter`. So I would actually say this looks fine as is.

**Comment by thomasjo** [comment]
Isn't it a little bit problematic returning an object that is then essentially undocumented? How are people supposed to reason about the `Gutter` object returned from e.g. `TextEditor::addGutter`? I can see how not exposing `GutterContainer` makes sense, but `Gutter` is already returned from a public method, so it should itself be made public (*extended*) in my opinion. It's essentially already de-facto public.

**Comment by MaximSokolov** [comment]
`GutterContainer` and `Gutter` classes should be fixed anyway. These classes now don't generate on Atom.io at all.

**Comment by maxbrunsfeld** [comment]
Ah, you're right. `Gutter` should be extended, but not `GutterContainer`.

**Comment by thomasjo** [comment]
> Ah, you're right. Gutter should be extended, but not GutterContainer.

:ok_hand: 

@MaximSokolov So what you should do is
 1. Mark `Gutter` as *Extended*,
 2. Revert the `{Gutter}` -> `gutter` changes in `text-editor.coffee`.

Then I think this is ready to :ship:

**Comment by maxbrunsfeld** [comment]
:+1:

**Comment by MaximSokolov** [comment]
Sure, I'll do it.

**Comment by thomasjo** [comment]
> Sure, I'll do it.

Awesome. Thanks!

**Comment by MaximSokolov** [comment]
I'm not sure about Gutter::decorateMarker(), because TextEditor::decorateMarker() exist. So, i didn't edit it.

**Comment by MaximSokolov** [comment]
I realized the difference between `Gutter::decorateMarker` and `TextEditor::decorateMarker`.
The first method creates decoration for custom `Gutter`. The second creates decoration for gutter with name `line-number`. Needs to update docs for `Gutter::decorateMarker`

**Comment by MaximSokolov** [comment]
I didn't update docs for `Gutter::decorateMarker` yet.

**Comment by MaximSokolov** [comment]
I copied docs related to gutter from `TextEditor::decorateMarker` to `Gutter::decorateMarker`
I think it's time to :eyes: review.

**Comment by MaximSokolov** [comment]
Also I found a [related issue](https://github.com/atom/atom/issues/7397)

**Comment by MaximSokolov** [comment]
Don't merge it yet. I will make commit history more clear.

**Comment by MaximSokolov** [comment]
Done.

**Comment by nathansobo** [comment]
Thanks so much @MaximSokolov! I made a few adjustments and merged this to master.

**Comment by nathansobo** [comment]
If you have any interest in writing an article about these APIs, would love to feature it on the Atom blog.

**Comment by MaximSokolov** [comment]
I don't speak English so well to write articles. Anyway I am glad my help is appreciated.

**Comment by MaximSokolov** [comment]
Gutter::decorateMarker -> {Decorations section}

**Comment by nathansobo** [comment]
??

**Comment by MaximSokolov** [comment]
@nathansobo I am not sure should be Gutter::decorateMarker  in the `Visibility` section

**Comment by nathansobo** [comment]
Oops. Sorry about that. I'll move it for the next release.

**Comment by MaximSokolov** [comment]
TextEditor::decorateMarker has no arguments now. I guess bacause of ba7af0b9cd3

https://atom.io/docs/api/v1.0.8/TextEditor#instance-decorateMarker
https://atom.io/docs/api/v1.0.9/TextEditor#instance-decorateMarker

**Comment by nathansobo** [comment]
You're right. Looks like I don't fully understand our docs system after all. I thought those headings weren't needed. I corrected on master... will see about pushing some new docs on Monday morning.

**Pull request merged**
