### PR TITLE
Support a single scope name field on Tree-sitter grammars

### PR DESCRIPTION
**Pull request by maxbrunsfeld**
### Background

When we originally [introduced](https://github.com/atom/atom/pull/16299) Tree-sitter parsers into Atom, we gave them entirely new root scope names, which we called *ids* instead of scope names. The plan was to make scope descriptors work differently with the new parsers, containing entries for each node in the syntax tree.

Since then, we've received a lot of issues about the new scope names causing problems. A lot of packages use scope names to control activation. We've also realized that we should be able to simply replace TextMate parsers with Tree-sitter parsers with the *same* scope name without introducing any breaking changes.

### Change

This PR remove the mechanisms for Tree-sitter grammars to track their correspondence to TextMate grammars while keeping separate scope names. Instead, we're just going to use the same scope names. I believe this will result in less overall confusion for users when we turn on Tree-sitter by default.

Fixes https://github.com/atom/atom/issues/17820
Fixes https://github.com/atom/atom/issues/17859

### CODE REVIEW

**Comment by t9md** [comment]
I found another scope incompatibility.

- `editor.bufferRangeForScopeAtPosition()` takes scope specifier as string, but behavior is not consistent.

Can I expect this to be fixed too?

When cursor is at `|` char in following text.

```javascript
let a, b /* 2nd |var */, c
```

In both TextMateParser and TreeSitterParser, command `Editor: Log Cursor Scope`(`alt-cmd-p`) shows `source.js` and `comment.block.js`.
But when I tried to use `.comment.block` as scope for `bufferRangeForScopeAtPosition` to retrieve block comment range, TreeSitterParser return nothing whereas TextMateParser return block-comment range.
Seemingly TreeSitter expect different scope string specifier.

```javascript
const editor = atom.workspace.getActiveTextEditor()
const range = editor.bufferRangeForScopeAtPosition(".comment.block", editor.getCursorBufferPosition())
if (range) {
  console.log(editor.getTextInBufferRange(range))
}
// -> In TextMateParser: output "/* 2nd |var */"
// -> In TreeSitterParser: no ouptut
```

Some of the vim-mode-plus's function depends on this behavior.

**Comment by maxbrunsfeld** [comment]
Thanks for pointing that out, @t9md. I will fix this.

**Comment by t9md** [comment]
Thanks for the quick response as always!
I still have several issues on vim-mode-plus when switching from TextMate parser to TreeSitter parser.
Mostly it is related to scopes compatibility and tokenized buffer. Am I OK to ask about it here?

**Comment by t9md** [comment]
@maxbrunsfeld Could you check and give comment on the following issue?
I can't find a good solution for now.
https://github.com/t9md/atom-vim-mode-plus/issues/1095

**Pull request merged**
