### PR TITLE
Change in-app menu for reporting issues to point to the CONTRIBUTING guide section on submitting issues

### PR DESCRIPTION
**Pull request by izuzak**
Currently, clicking the "Report issue" menu option in Atom takes the user to the New Issue form on GitHub for atom/atom. 

screen shot 2015-04-07 at 13 48 47

I think that's great -- it allows users to quickly report issues. However, it doesn't assist users in creating a good bug report or feature request. We've noticed lots of issues created without even basic information such as Atom version, OS, expected behavior, and screenshots. 

This PR changes the in-app menu option to instead point users to the [CONTRIBUTING guide section on submitting issues](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues). That section explains which information users should include in issues and also points them to the debugging guide. This will introduce an additional step in the process for creating issues, but it will hopefully result in higher quality issues which are easier to triage (and fix). :pray: 

Also, I slightly updated the CONTRIBUTING guide to state this goal more clearly, include a link to the New Issue form in the first bullet, and point to package repositories in the section on submitting issues. The CONTRIBUTING guide will see a lot more updates in the near future, this is just a first step.

cc @atom/core @atom/issue-triage

### CODE REVIEW

**Comment by benogle** [comment]
:+1:

**Comment by thedaniel** [comment]
This is such a good idea.

**Comment by kevinsawicki** [comment]
:ship:ing this to get it into 0.190

**Comment by kevinsawicki** [comment]
and a huge :+1:

**Pull request merged**
