### PR TITLE
Bump nodegit

### PR DESCRIPTION
**Pull request by joshaber**
_Continuation of https://github.com/atom/atom/pull/11401._

This adds support for 32-bit linux systems. See #10819

### CODE REVIEW

**Comment by joshaber** [comment]
We're failing/racing now on a test in `status-bar` 😞

**Comment by BinaryMuse** [comment]
@joshaber I noticed this is on 1.8-beta but not on 1.7 (as far as I can tell; 1.7 is using nodegit 0.12.0); any reason we shouldn't get this in the next patch?

**Comment by ZuBB** [comment]
just want to let subscribers know that I have yesterday unhold atom 1.7.1 from webupd8team team and installed it again and all was OK (no subject error occured)

**Comment by roshimon** [comment]
Upgrading to atom 1.8.0-beta1 has fixed the issue for me. Working flawlessly now :)

**Comment by joshaber** [comment]
@BinaryMuse I didn't think there was any reason it needed to be fast-tracked.

**Pull request merged**
