### PR TITLE
Lint JavaScript specs

### PR DESCRIPTION
**Pull request by winstliu**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

Lints specs written in JS.

### Alternate Designs

None.

### Why Should This Be In Core?

Because everything else gets linted in core?

### Benefits

Better code quality.

### Possible Drawbacks

None.

### Applicable Issues

None.

### CODE REVIEW

**Comment by 50Wliu** [comment]
Not quite sure if the `eslint-disable-line no-unused-var` statements are the best way to handle the ffit stuff.

**Comment by ericcornelissen** [comment]
Alternatively you could just removed the unused variables :wink: I would suggest one change tho, on [line 13 in `lint-java-script-paths.js`](https://github.com/atom/atom/blob/37f43fb0f5c669a66271029d65f198c83ba882e4/script/lib/lint-java-script-paths.js#L13) I would change `'main-process'` by `'**'`, and remove line 12. This way all tests in the ./spec folder and subfolders will be linted.

Furthermore, your changes seem alright, I don't see why you won't lint the test suites. 😃

**Comment by 50Wliu** [comment]
> This way all tests in the ./spec folder and subfolders will be linted.

We don't want to lint the fixtures folder though.

**Comment by ericcornelissen** [comment]
> We don't want to lint the fixtures folder though.

In that case this seems like a good solution 😄

**Comment by sadick254** [comment]
Thanks for opening this PR!

This has already been done on master. Now we also lint the spec files.

**Pull request closed without merging**
