### PR TITLE
Use unique text editor title in window and tab titles	

### PR DESCRIPTION
**Pull request by DouweM**
I have two files, `app/services/notes/create_service.rb` and `app/services/issues/create_service.rb`.

Right now it's impossible to find which is which using either the window or tab title:

screen shot 2015-11-16 at 20 16 02

screen shot 2015-11-16 at 20 16 10

With these changes, it is:

screen shot 2015-11-16 at 20 18 28
screen shot 2015-11-16 at 20 18 36

Both now use `<item>::getLongTitle` which delegates to `TextEditor::getUniqueTitle` in the case of `TextEditor` items.

Besides this, `TextEditor::getUniqueTitle` was modified to match Sublime Text's behavior, where `features/index.html`, `features/main/index.html` and `contact/index.html` will show as `index.html — features`, `index.html — features/main` and `index.html — contact` rather than `features/index.html — features`, `features/.../index.html` and `features/index.html`. With the original implementation, the difference between the first two would still be difficult to spot, and the actual filename could be pushed out of the tab if the directory names were especially long.

PS. I used em-dashes rather than 'normal' dashes since this was developed in conjunction with #9620.

### CODE REVIEW

**Comment by DouweM** [comment]
Once af22a149bdd8989f5c279863ff319bdc652d7c66 lands in master, I will move `getUniqueTitle` to `getLongTitle`.

**Comment by DouweM** [comment]
@benogle Anything I can do to help this PR along?

**Comment by benogle** [comment]
cc @maxbrunsfeld

**Comment by n054** [comment]
4242.3
 no language set
 ATOM_SPECS_TASK=core NODE_VERSION=0.12
 24 min 13 sec
 This was the only failing test on 4bc4c68. But when I came here to comment all checks passed.

**Comment by maxbrunsfeld** [comment]
Thanks for improving this. Your algorithm is easier to understand than the old one too :+1:.

**Comment by mik01aj** [comment]
I wonder why you were seeing:

    create_service.rb - app/service/......  |  create_service.rb - app/service/......

Because in such situations, I normally saw:

    notes/create_service.rb  |  issues/create_service.rb

...which was imho way better. I recently upgraded and I now see:

    create_service.rb - notes  |  create_service.rb - issues

I don't like the change. Is there any way to get the old behaviour back?

**Pull request merged**
