### PR TITLE
Do not create an AutoUpdateManager when in test mode.

### PR DESCRIPTION
**Pull request by bolinfest**
Tests should be 100% reproducible, but `AutoUpdateManager` introduces unpredictable behavior, so it should not be installed when Atom is launched via `apm test`.

### CODE REVIEW

**Comment by bolinfest** [comment]
Ah, good catch @kevinsawicki!

**Comment by kevinsawicki** [comment]
@bolinfest we have a few specs that verify events out of the auto updater so instead of not creating it in test mode, I think we should just disable it from checking for updates so it can still be tested but it won't ever actually cause an update to be performed.

**Comment by kevinsawicki** [comment]
:ship: Thanks for this @bolinfest

**Comment by bolinfest** [comment]
@kevinsawicki sounds good to me!

**Pull request merged**
