### PR TITLE
Fix 64-bit Windows builds

### LINKED ISSUE #10450: %1 is not a valid Win32 application
Trying to use Atom on or after `4d740d33468a2fe427c379fc6a0719efcb89930a` results in a NodeGit error `%1 is not a valid Win32 application`.

Full stack trace:
```
Error: %1 is not a valid Win32 application.
\\?\C:\Program Files\Atom\resources\app.asar.unpacked\node_modules\nodegit\build\Release\nodegit.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:162:18)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:173:16)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Program Files\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Program Files\Atom\resources\app.asar\node_modules\nodegit\lib\nodegit.js:8:12)
    at Module._compile (C:\Program Files\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Program Files\Atom\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Program Files\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:/Program Files/Atom/resources/app.asar/src/git-repository-async.js:4:24)
    at Module._compile (C:\Program Files\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Program Files\Atom\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Program Files\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Program Files\Atom\resources\app.asar\src\git-repository.js:12:24)
    at Object.<anonymous> (C:\Program Files\Atom\resources\app.asar\src\git-repository.js:424:4)
    at Module._compile (C:\Program Files\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Program Files\Atom\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Program Files\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
```

Also reported by @Haacked at #10271.

/cc @joshaber, @johnhaley81

EDIT: Forgot to mention that I'm running Windows 10 x64.

### PR DESCRIPTION
**Pull request by joshaber**
Fixes #10450.

It turned out to be a combination of a couple things: I accidentally broke it in the async-git branch, but we were also missing one 32-bit override.

### CODE REVIEW

**Comment by 50Wliu** [comment]
Just tried building this but it still doesn't seem to work :confused:.

**Comment by joshaber** [comment]
@50Wliu In what way did it not work? Did you clean + nuke all caches?

**Comment by 50Wliu** [comment]
...nope, forgot to `script\clean`.  Ugh.  I'll try again tomorrow.

**Comment by joshaber** [comment]
No worries! Sadly it's not smart enough to realize the architecture changed and re-fetch without cleaning.

**Comment by 50Wliu** [comment]
Yep, fixed after clearing the cache!  Thanks @joshaber! :sparkling_heart:

**Comment by joshaber** [comment]
:metal:

**Comment by Pistachin** [comment]
Hi,

I was thinking about reporting my own issue, quite similar to yours, but I decided to first ask here and then if needed, proceed with the reporting my own issue.

The thing is that, me beeing a greenie in using atom (I've just used it to write some code, I haven't touched many things) I don't fully understand all the solutions and code you mention here.

My problem is this:

image

I wouldn't know if my problem is solved as the one you had, and as I said, I don't fully understand your solution. Like, in what file are you doing these changes? I don't find a 'scripts' directory in my '.atom' directory (even less, a bootstrap file).

Any help? Thanks in advance and, do you think it's better that I report my own issue?

**Pull request merged**
