### PR TITLE
⬆️ focus-trap@6.0.1

### PR DESCRIPTION
**Pull request by atom-build**
Bumps focus-trap from 2.4.5 to 6.0.1

### CODE REVIEW

**Comment by sadick254** [comment]
`focus-trap` doesn't work as intended because of a change introduced to add a delay before autofocus. Here is the PR that introduces that change https://github.com/focus-trap/focus-trap/pull/51.

**Comment by sadick254** [comment]
I have opened a PR on the `focus-trap` repo to fix the problem highlighted on the comment above. https://github.com/focus-trap/focus-trap/pull/154. Once this is merged we should be good to bump and merge this PR.

**Comment by stefcameron** [comment]
Please bump to `focus-trap@6.1.0` and configure your traps with the new `delayInitialFocus: false` option. That should resolve your issue, and thanks for @sadick254's contribution to add the new option.

**Comment by sadick254** [comment]
@stefcameron Thank you for facilitating the change. Really appreciate the work you are doing with `focus-trap`

**Comment by stefcameron** [comment]
> @stefcameron Thank you for facilitating the change. Really appreciate the work you are doing with `focus-trap`

My pleasure!

**Pull request merged**
