### PR TITLE
Update Electron to 0.36.11

### PR DESCRIPTION
**Pull request by drewmnoel**
Pulls in a fix for freetype2 on some systems

### CODE REVIEW

**Comment by drewmnoel** [comment]
Build errors `ENOENT` for `shell.js` and a build timeout. Maybe restart?

**Comment by 50Wliu** [comment]
The ENOENT failures for `remote.js` and `shell.js` are because they got moved around in 0.36.11.  `remote.js` is now at `lib/renderer/api/remote.js`, and `shell.js` is at `lib/common/api/shell.js`.  It looks like the two specs in question got missed during the 0.35.0 deprecation cleanup.  Can you try changing [this line](https://github.com/atom/atom/blob/master/spec/atom-environment-spec.coffee#L341) to `require('electron').remote.require('auto-updater')` instead?  Something similar for [this line](https://github.com/atom/atom/blob/master/spec/window-event-handler-spec.coffee#L78), except it would be `{shell} = require 'electron'`.  The last failure looks like a flaky timeout spec that's unrelated to this PR.

**Comment by 50Wliu** [comment]
I believe the reason Tree View is timing out is because it's also relying on the deprecated `require` syntax for `shell`, as is clear when you try starting Atom running 0.36.11.  I'll go fix that now~

In addition:
@steelbrain, @arcanemagus: `linter` is using the same deprecated syntax for `clipboard`, which means it fails to activate using Electron 0.36.11.
@tombell: Something very similar with `travis-ci-status` and `shell`.

**Comment by 50Wliu** [comment]
@drewmnoel Can you please rebase this on master to get the tree-view fix?

**Comment by drewmnoel** [comment]
Just did, let's see how this goes.

**Comment by steelbrain** [comment]
@50Wliu It has already been fixed in master, we'll be releasing soon

**Comment by 50Wliu** [comment]
The four remaining failures for package specs should be fixed now as well on master.

**Comment by drewmnoel** [comment]
Two timeout failures (blinking cursor in core, general timeout error in packages). A restart should fix the core test at least, probably the package one too.

**Comment by 50Wliu** [comment]
@drewmnoel Turns out I missed a `require('remote')` in settings-view which caused those specs to hang.  Mind pulling in the latest changes again?

**Comment by drewmnoel** [comment]
Almost there! In the theme manager spec this time.

**Comment by drewmnoel** [comment]
Checks are all good now, thanks @50Wliu!

**Comment by 50Wliu** [comment]
:green_heart:

**Comment by drewmnoel** [comment]
What are the next steps to get this merged in? I'm excited to be able to update my `freetype2` finally :smiley:

**Comment by joshaber** [comment]
@drewmnoel We'll spend some time testing it and then merge if it seems stable. Thanks for all your work on it!

**Comment by joshaber** [comment]
Hmm, looks like this needs a merge in from `master` to get #11153.

**Comment by 50Wliu** [comment]
In addition, in order to prevent any community packages from breaking because of the bump to 0.36.11, it looks like [these lines](https://github.com/atom/atom/blob/41161dd462a1be9073752a34b4809612f933da6e/src/module-cache.coffee#L205-L213) will need to be updated to correspond to the new file locations.

**Comment by drewmnoel** [comment]
Okay, sure just let me know if I need to fast-forward my branch or anything

**Comment by joshaber** [comment]
@drewmnoel Are you interested making the changes @50Wliu outlined?

**Comment by steelbrain** [comment]
@50Wliu released a linter update that's compatible with the latest electron

**Comment by 50Wliu** [comment]
Closes #11198.

**Comment by fusion809** [comment]
If it helps with the "needs-testing" property I just built it and it seems to be working fine with freetype2 2.6.3.

**Comment by Nikki1993** [comment]
I second @fusion809, everything works as expected.

**Comment by 50Wliu** [comment]
@drewmnoel are you still interested in finishing this pull request?

**Comment by libeclipse** [comment]
Locally made changes and compiled. Fixed the crashes due to freetype and seems to be working perfectly.

**Comment by n0f3** [comment]
hi, just checked out pull request locally and tested, atom editor is no longer crashing, freetype version 2.6.3-1

**Comment by Nikki1993** [comment]
So can we get this merged asap to return things to working order? :)

**Comment by 50Wliu** [comment]
> So can we get this merged asap to return things to working order? :)

This PR still requires changes.

**Pull request closed without merging**
