### PR TITLE
Disable folding if enableFolding config is false.

### PR DESCRIPTION
**Pull request by russlescai**
(This replaces previous PR #3740).

Allows the disabling of Code Folding. This attempts to solve Issue #3709.

This PR adds a config to check if folding is disabled.

Tasks:
- [x] Disable Code Folding in Gutter if config item is set to be disabled (and unfold all when disabled to show all code)
- [x] Add place to configure if folding is enabled or not - this can be added to users' config file (added to config-schema)
- [x] Ensure no other places enable folding...
- [x] Disable/hide Folding menu if config item is set to be disabled
- [ ] Add scoped configuration
- [ ] Add specs

### CODE REVIEW

**Comment by izuzak** [comment]
@russlescai Hey! Just wondering if you were going to finish the work in this pull request? Do you need help or just don't have time to work on it? If you need help or have questions -- please feel free to ping us. If you don't have time -- we should consider closing this or letting someone else from the community finish it. Would you be okay with that?

**Comment by russlescai** [comment]
Hi @izuzak - tbh I had issues implementing the scope config at the time, then forgot all about it.

I am happy to finish it off now over the next few days (and definitely ok if someone else from the community would like to finish  it off too :P ).

In my experience I have had issue resolving merge conflicts in a PR before, so I will probably create a new PR from the latest version of code to help it automatically merge. 

Does that sound ok?

**Comment by russlescai** [comment]
I have reviewed this PR and the code is no longer valid against the latest master branch.
Key changes which affect it are:
* atom.comfig.observe/atom.comfig.onDidChange changes
* isFoldableAtBufferRow is no longer used.

To implement this then they would need to start again, thus I am closing this PR.

**Comment by izuzak** [comment]
>  so I will probably create a new PR from the latest version of code to help it automatically merge.

Sounds good :+1: If you think you won't have time to finish this, you can just leave a comment in [the issue](https://github.com/atom/atom/issues/3709) with a link to the PRs and a note about what's left to be done. Thanks again!

**Comment by russlescai** [comment]
Recreated PR #5844 which merges with master branch.

**Pull request closed without merging**
