### PR TITLE
Update info on persisting inotify settings on linux

### PR DESCRIPTION
**Pull request by jakob-bebop**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

improve the documentation on how to make Atom work on linux (mostly Arch I guess).

The previous version already read "if this works you can make the setting persistent", however the method described only persisted until next boot. This PR describes how to make it persistent after reboot also.

### Why Should This Be In Core?

Atom displays a link to this file when file watching doesnt work as expected

### CODE REVIEW

**Comment by sadick254** [comment]
@jakob-bebop I know this has been open for a long time now. This PR's now contains conflicts that need resolving.

**Comment by todd664** [comment]
Fucking quit texting my phone

**Comment by ThatXliner** [comment]
> Fucking quit texting my phone

Try unwatching the repo
Screen Shot 2021-05-25 at 1 28 34 PM

**Comment by sadick254** [comment]
Thank you for your PR!

We haven't gotten a response to our request to resolve the conflicts. I'm going to close this but don't hesitate to reach out when the conflicts are resolved,  we'll be happy to reopen the PR.

**Pull request closed without merging**
