### PR TITLE
Don't open dev tools on uncaught errors in headless tests

### PR DESCRIPTION
**Pull request by nathansobo**
This is an attempt to debug mysterious failures we're seeing on CI. Our theory is that the dev tools are getting opened due to an uncaught exception and causing subsequent tests to fail.

/cc @as-cii @maxbrunsfeld

### CODE REVIEW

**Comment by as-cii** [comment]
The build for 2cb84bf exhibited the same hypothetical uncaught exception, but it seems like dev tools got opened anyways. 

In e58a911 I added the [ELECTRON_ENABLE_LOGGING](https://github.com/electron/electron/blob/master/docs/api/environment-variables.md#electron_enable_logging) environment variable, which should emit every log message from the renderer process (including the one [reporting that the document isn't focused](https://github.com/atom/atom/blob/4d2641962e6b9d70948792f7f1d6f7bf46725e38/spec/spec-helper.coffee#L213-L214)). I restarted the build for that commit several times without ever being able to reproduce the issue again. 

I suspect all those logging statements are skewing timings enough to obscure the race condition.

**Comment by nathansobo** [comment]
I'm tempted to just abandon this PR. @as-cii do you think it's worth changing this?

**Comment by as-cii** [comment]
Seems like on master builds have gotten less flaky, so yeah let's close this and maybe reopen if spurious errors show up again in the future.

**Comment by Arcanemagus** [comment]
Closing this based on the above discussion, please re-open this if it's still something that is needed!

**Pull request closed without merging**
