### PR TITLE
"open with" fix for context menu

### PR DESCRIPTION
**Pull request by jamilservicos**
"open with" for folder on context menu

### CODE REVIEW

**Comment by jamilservicos** [comment]
suggestion: add in .deb "control" one postinst

```
#!/usr/bin/env bash
update-alternatives --remove editor /usr/bin/atom
update-alternatives --install /usr/bin/editor editor /usr/bin/atom 0
if hash desktop-file-install 2>/dev/null; then
echo hash;
	desktop-file-install /usr/share/applications/atom.desktop
fi
update-desktop-database
```

**Comment by 50Wliu** [comment]
@jamilservicos What exactly does this fix?

**Comment by jamilservicos** [comment]
"open with" context menu to open "project folder" directly of the nautilus

**Comment by damieng** [comment]
This should probably be optional. We removed this behavior by default on Windows because people complained about it appearing all over the shell there.

**Comment by passeride** [comment]
But definitely leave it as an option, love that feature. I have a [commit](https://github.com/atom/atom/pull/13414) to get this this to work on Cinnamon, but this might make it redundant.

**Review by ghost — APPROVED** [review]

**Review by wuffs — CHANGES_REQUESTED** [review]
Delete All logs

**Comment by sadick254** [comment]
Hey @jamilservicos. Apologies for not looking into this on time. I know this PR has been here for a very long time, during that time Atom has seen a number of changes. Due to the changes, this PR has now become outdated. Is it possible for you to resolve the conflicts?

**Comment by jamilservicos** [comment]
> Hey @jamilservicos. Apologies for not looking into this on time. I know this PR has been here for a very long time, during that time Atom has seen a number of changes. Due to the changes, this PR has now become outdated. Is it possible for you to resolve the conflicts?


if you refer about the change in "resources/linux/atom.desktop.in", it is already in the current version.

**Comment by sadick254** [comment]
@jamilservicos Yes, I can see the change in the current version. We should then close this PR. Thank you.

**Pull request closed without merging**
