### PR TITLE
:arrow_up: fuzzy-finder@0.84.0

### PR DESCRIPTION
**Pull request by mnquintana**
Adds fuzzy match character highlighting

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Awesome, I'll take a look at this today

**Comment by mnquintana** [comment]
Also, I'm not totally sure on this, but I feel like we should add highlighting to all the other SelectLists before we ship this (just for consistency) – symbols-view and command-palette off the top of my head

**Comment by kevinsawicki** [comment]
> but I feel like we should add highlighting to all the other SelectLists before we ship this (just for consistency)

Yeah, that sounds good

**Comment by kevinsawicki** [comment]
I think this is worth shipping in the next release before we it into the symbols view and command palette, it is probably most helpful in the fuzzy finder where you have lots of paths that may be very similar and the visual cue is really helpful.

Thanks so much for reviewing and merging the fuzzy finder pull request :ship:

**Pull request merged**
