### PR TITLE
Don't share overlayDimensions across instances

### PR DESCRIPTION
**Pull request by nathansobo**
Relates to #8295 

Thanks to @matthewwithanm for finding this error. @matthewwithanm do you think this definitively closes that issue?

@Ben3eeE would you mind testing this out and see if the behavior is improved in that one flickering case you found dragging panes?

cc @lee-dohm

### CODE REVIEW

**Comment by matthewwithanm** [comment]
@nathansobo!! Thanks for such a quick turnaround on this 😊

I can't say for certain if it's a definitive fix for #8295, but it does fix the situation that I was able to repro!

**Comment by nathansobo** [comment]
> but it does fix the situation that I was able to repro!

I'm going to be optimistic then...

Closes #8295

**Comment by nathansobo** [comment]
Thanks again for tracking this down. Pretty embarrassing but I'm happy to have your team on our side! ❤️ :zap:

**Comment by Ben3eeE** [comment]
Thanks for the summon. This does seem to fix the problem.

Thanks @nathansobo

**Comment by jeremyfa** [comment]
Man, I wake up this morning and see this wonderful merge! This is the most annoying issue I am experiencing with atom, I need to test this right now from git and will tell you if it worked. And let's be optimistic yes 👍

**Comment by jeremyfa** [comment]
The fix seems to work :D ! Thanks a lot for the efforts ❤️

**Comment by Ben3eeE** [comment]
@jeremyfa Awesome to hear! Thanks for testing it out and reporting back :bowing_man:

**Comment by ypresto** [comment]
Wow great work...!!! Thanks a lot!!

**Pull request merged**
