### PR TITLE
Fix handling of "empty" language injections with Tree-sitter

### LINKED ISSUE #676: JavaScript syntax highlighting breaks then spreads when using innerHTML = ``
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Javascript syntax highlighting breaks by using back ticks with `innerHTML` which then spreads around the file if edited.

### Steps to Reproduce

1. Open atom and make a new file (You don't need to save it, but if you do save a `.js` file)
2. Set the syntax to JavaScript if not already set
3. Paste in this text
``` js
class Testing {
	test(ele) {
		this.testingAgain(ele);
	}
	testingAgain(ele) {
		// ele.innerHTML = ``;
	}
}
```
4. **First issue:** Un-comment line 6. Notice how the syntax highlighting doesn't show up 
5. **Second issue** Cut all text from the file, then re paste it. Notice how none of the syntax highlighting is working.

**Expected behavior:**

All syntax highlight should work properly.

**Actual behavior:**

``` js
ele.innerHTML = ``;
```
Seems to break the syntax highlighting of its own line, but then if you try to edit lines around it, the broken syntax highlighting seems to **_spread_** through the rest of the file.
If you open a JS file that already has this line in it, depending on the size of the file will depend on how many lines don't get the syntax highlighting. Its really quite weird.

**Reproduces how often:**
Every time 

### Versions

macOS: 10.14.6

Atom: 1.48.0
Electron: 5.0.13
Chrome: 73.0.3683.121
Node: 12.0.0

### Additional Information

Video of the syntax highlighting breaking:
issue1

Video of the syntax highlighting issue spreading though the file:
issue2

(Sorry for the low quality)

### LINKED ISSUE #20884: [language-rust-bundled] Combo of use::{something, *} and quoted str breaks highlighting
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

If there is a nested star in a use statement and a quoted str, highlighting breaks after the star:

image

### Steps to Reproduce

This is some simple code that produces the issue:

```
use crate::checks::{self, *};

pub fn foo() -> Result<(), Box<dyn error::Error>> {
    let string = "foo";

    Ok(())
}
```

**Expected behavior:**

Removing quotes fixes issue (I know this won't compile). Notice the highlighting in the fn declaration:

image

Un-nesting or removing the star also fixes issue:

image

**Actual behavior:**

See description

**Reproduces how often:**

100% of the time

### Versions

```
$ atom --version
Atom    : 1.47.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0

$ apm --version
apm  2.4.5
npm  6.2.0
node 10.2.1 x64
atom 1.47.0
python 2.7.16
git 2.24.1
```

MacOS, Catalina 10.15.4 (19E287)

### LINKED ISSUE #20897: Rust Syntax Highlighting: Attribute in Proc Macro Breaks Syntax Highlighting if
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Including an assignment attribute inside a proc. macro (i.e. `#[x(y = z)]`) followed by a string literal breaks the current rust syntax parser. 

### Steps to Reproduce

1. Open a new file, with the syntax highlighter set to Rust.
2. Enter the following code:
    ```
    #[x(y = z)]
    struct W();

    let x = "hello";
    ```
3. After the introduction of the string literal, the highlighting breaks.

**Expected behavior:**

The syntax highlighting should continue to work.

**Actual behavior:**

It reproduces 100% of the time, even in more complex situations.

### Versions

```
Atom    : 1.47.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
MacOS   : 10.15.5 
```

### Additional Information

I suspect that the parser is looking for a string literal in the attribute in a greedy manner and gets confused when it encounters one later.

### LINKED ISSUE #21093: Syntax highlighting is broken in many languages and it spreads around the file
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Syntax highlighting appears to be broken in a number of different languages. I had made this post in this repo earlier https://github.com/atom/language-javascript/issues/676 about an issue in the JS language after updating to 1.47 https://github.com/atom/atom/releases/tag/v1.47.0 , but it got moved over to the JS language repo. I have gone through all the releases from 1.41 - 1.49 (current) and 1.47 is the first release where this issue is present (in both normal versions, and safe mode versions).
The effected languages that I have seen since 1.47 have been:

- JavaScript
- TypeScript
- HTML
- Ruby
- Rust (edited)

But who knows how many other languages are affected. This is defiantly not an isolated issue within a language as all 4 of these ones broke on release 1.47

The thing that makes this bug so strange (I go into detail a bit more on my previous issue above), is that if lines around the effected line are edited, the broken syntax highlighting spreads around the file. And if the code is copy-pasted into an empty file, or opened for the first time, multiple lines around the effected line all break.

### Steps to Reproduce

1. Open any version of atom past release 1.47
2. Set the language to one of the 4 mentioned above
3. Copy-paste the provided code for said language (In additional information section)

**Expected behavior:**

The syntax highlighting working normally all the time.

**Actual behavior:**

Starting at 1.47 onwards, when the syntax highlighting breaks, it makes the affected line go white. But when lines around the affected line are edited, the broken syntax highlighting seems to spread around the rest of the file.

**Reproduces how often:**

100% of the time after 1.47

### Versions

1.46 Issue **not present**:
Atom    : 1.46.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.46.0
python 2.7.10
git 2.21.1

1.47 Issue **now present**:
Atom    : 1.47.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0

apm  2.4.5
npm  6.2.0
node 10.2.1 x64
atom 1.47.0
python 2.7.10
git 2.21.1

1.49 Current as of time of writing:
Atom    : 1.49.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0

apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.49.0
python 2.7.10
git 2.21.1

macOS 10.14.6

### Additional Information

Code snippets for each language.

- Javascript & TypeScript:
```js
let ele = document.getElementById("test");

ele.innerHTML = ``;
// Comment out the line above from the start, then select all, cut, then past. Highlighting now works
// Highlighting worked fine in 1.46
```
The issue in this one is the backticks on line 3.

- HTML:
```html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8">
		<script></script> 
		<!-- Comment out the line above from the start, then select all, cut, then past. Highlighting now works -->
		<!-- Highlighting worked fine in 1.46 -->
		<title></title>
	</head>
</html>
```
The issue in this one is the entire `<script>` tag

- Ruby:
```ruby
def test(string)
	s = StringScanner.new(string)
	
	while !s.eos?
		s.scan(/\(/)
		
		s.scan(/\)/)
		
		# Comment out lines 5 and 7, then select all, cut, then past. Highlighting now works
		# Highlighting worked fine in 1.46
	end
end
```
The issue in this one is the REGEX in the scan looking for opening and closing parentheses. Other REGEX's appear to work fine.

Edit: Added Rust: (https://github.com/atom/atom/issues/20884)
```rust
use crate::checks::{self, *};

pub fn foo() -> Result<(), Box<dyn error::Error>> {
    let string = "foo";

    Ok(())
}
```
and (https://github.com/atom/atom/issues/20897)
```rust
#[x(y = z)]
struct W();

let x = "hello";
```

### Side note
I was able to find a workaround for the JavaScript and TypeScript languages which is at the bottom of my previous issue https://github.com/atom/language-javascript/issues/676 . I haven't found a workaround for the HTML or Ruby languages though

### PR DESCRIPTION
**Pull request by maxbrunsfeld**
### Identify the Bug

Fixes #21093
Fixes #20884
Fixes #20897
Fixes https://github.com/atom/language-javascript/issues/676

1. The Rust grammar had a bug that caused poor error recovery.

2. There was a bug would occur in documents with language injections, where the injected document is empty. Examples include:
    * An empty string assigned to a node's `innerHTML` property in JavaScript. Usually, we highlight the contents of these strings as HTML.
      ```js
      node.innerHTML = "";
      ```
    * An empty script tag in an HTML document. Usually, we would parse the tag's contents this script tag as JavaScript:
      ```html
      <div>
        <script></script>
      </div>
      ```
    * In Ruby or JavaScript, a regular expression literal whose entire contents consist of escape sequences. Usually we highlight the contents of the regular expression using regex syntax:
      ```ruby
      s.search /\n/
      ```

The bug would cause us to accidentally *skip* highlighting large sections of the document.

### Description of the Change

These *injected* syntax trees are each associated with a *Marker* in the LanguageMode's `injectionsMarkerLayer`. This PR ensures that, when a language injection is empty, its marker is destroyed.

I also upgraded to the latest version of `tree-sitter-rust` in order to fix the last two issues mentioned in #21093, which were. unrelated, but easy to address.

### Verification Process

Create files containing all of the code examples in #21093. See that the syntax highlighting is all correct. Edit this files in a variety of ways and see that syntax highlighting stays correct.

### Release Notes

> Fixed a syntax highlighting bug that caused inconsistent and missing highlighting in several languages.

### CODE REVIEW

**Comment by sadick254** [comment]
Do we need to bump `tree-sitter-rust`?

**Comment by maxbrunsfeld** [comment]
> Do we need to bump `tree-sitter-rust`?

Yeah. I mentioned in the body that the problems described in the linked issue have two different causes. One of the problems was just a bug in `tree-sitter-rust` that has already been fixed. I think [this](https://github.com/tree-sitter/tree-sitter-rust/commit/1c37782a5528979a22991f8ed50dd3d3e423ac92) was the Tree-sitter-rust commit that fixed it.

**Comment by darangi** [comment]
Thanks 🙇🏾‍♂️  @maxbrunsfeld

**Comment by maxbrunsfeld** [comment]
Thanks for getting this merged @darangi!

**Comment by Rua** [comment]
When will this appear in stable Atom?

**Comment by odedharth** [comment]
Was this merged into 1.54.0? because this issue is not fixed in that version.

**Comment by darangi** [comment]
@odedharth, it is yet to hit stable, but you can get it in nightly

**Comment by 1gg24j** [comment]
https://github.com/atom/atom/issues/21804

**Pull request merged**
