### PR TITLE
Replaced OS X Yosemite-era icon with macOS Big Sur icon for Atom for Macs

### PR DESCRIPTION
**Pull request by andylin2004**
### Issue or RFC Endorsed by Atom's Maintainers

https://github.com/atom/atom/issues/21128

### Description of the Change

I replaced the older default icon for Atom with the Big Sur-style icon for Atom for Macs only. Windows icons is still the same.

### Alternate Designs

- Keeping the icon as is: it would fail to fit within the Apple icon design for Big Sur.
- Replacing all icons: there has not been any major icon overhaul on Windows that necessitate an icon change for Windows too.
- Separating the icon based on what macOS version the user is using: there isn't an implementation of this in Electron.

### Possible Drawbacks

- Mac users using macOS Catalina and below will see the Big Sur-esque icon instead of the OS X Yosemite-esque icon.

### Verification Process

The verification process is not needed, as this is just an icon swap with the same file extension (between the icon being replaced and replacement icon).

### Release Notes

The app icon on macOS has been changed to reflect the style in macOS Big Sur.

### CODE REVIEW

**Comment by chiss22** [comment]
Thank you! It looks beautiful!

**Review by sadick254 — COMMENTED** [review]
This looks really good. I would be glad if you could also add icons for nightly and beta versions of Atom.

**Review by sadick254 — COMMENTED** [review]
Is there a reason for deleting beta/atom.icns

**Comment by andylin2004** [comment]
Screen Shot 2021-05-12 at 10 09 45 AM It was not deleted--I think that because I changed the beta icon to look more like the Big Sur icons, the file size became smaller. Refer to the screenshot of my local git of Atom that have already been pushed to my remote.

**Review by sadick254 — APPROVED** [review]

**Comment by kaungkin499** [comment]
https://github.com/kaungkin499/kinkaung499/commit/c60b78b7d156882a4b56572ea14aad806d5815d0

**Comment by jasoncoker925** [comment]
I want to invest in your company 😃

**Comment by Rmf77** [comment]
https://solo.top/0x412a3F1BBCF24cbB898aBB517FcAE4c94Ea76089

**Pull request merged**
