### PR TITLE
Update build-status.md

### LINKED ISSUE #22669: docs/build-instructions/build-status.md is outdated
Due to changes over time with testing, some of the packages now use different testing tools like Github Actions, so now the page above is outdated.

I'm not sure how to update the `Electron` row, but this is added to the todo list anyways.
Link for convenience: <https://github.com/atom/atom/blob/master/docs/build-instructions/build-status.md>

### PR DESCRIPTION
**Pull request by icecream17**
### Requirements for Contributing Documentation

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only contribute documentation (for example, markdown files or API docs). To contribute other changes, you must use a different template. You can see all templates at <https://github.com/atom/.github/tree/master/.github/PULL_REQUEST_TEMPLATE>.

### Description of the Change

Generally just updates the badges

Adds note about the electron version
Updates the apm badge
Update the electron badges: https://github.com/electron/electron/blob/v9.4.4/README.md

### Notes

Some of the packages have been moved into Atom Core, and don't have test badges
Some columns are changed

### Release Notes

Docs: Update docs/build-instructions/build-status.md

Fixes #22669

### Current progress

- [x] packages
- [x] libraries
- [x] tools
- [x] languages

-----
[View rendered docs/build-instructions/build-status.md](https://github.com/icecream17/atom/blob/update-build-status/docs/build-instructions/build-status.md)

### CODE REVIEW

**Comment by darangi** [comment]
The linting is causing the CI to fail, Can you fix it?

**Comment by icecream17** [comment]
I'm not sure how to update the dependency badges for the packages, leaving them alone for now

**Review by ghost — APPROVED** [review]
#22751 #22791 #22751 #10663 And set permissions- Only for private access or use for Ambjörn Sköld is the only authorized everywhere on the internet streams or any life streams or network streams online or remotely connected to any device’s  and all sites including windows, digital “Matrix of the humans world” No public access or use is allowed

**Comment by icecream17** [comment]
@ESA-Security-Group's approval is spam, I'm definitely not finished, ignore

**Review by sadick254 — COMMENTED** [review]
Hey @icecream17. We have since moved most of our packages to Github Actions. The best way forward would be to update all the package badges to badges provided by Github Actions.
It would be super helpful if the updates were done on this PR.

**Comment by icecream17** [comment]
Github's commit diff is terrible, but I'm using "markdown tables generator" which is easier than changing the tables manually.

In any case here's the links
https://github.com/atom/atom/blob/master/docs/build-instructions/build-status.md
https://github.com/icecream17/atom/blob/update-build-status/docs/build-instructions/build-status.md

**Comment by sadick254** [comment]
@icecream17 I have checked the links provided, we would like to remove the Travis ci and Appveyor columns. If a package doesn't have any Github CI badges leave it blank for now.

**Comment by icecream17** [comment]
I've finished all the packages

The only packages that don't have a github action are the ones merged into atom, wow!

Sidenote:
It's weird that those commits fail tests. Even though the error is unrelated, it's really consistent.

**Comment by sadick254** [comment]
@icecream17 apologies for this. I forgot to mention libraries, tools and libraries as well. We should remove Circle CI and Travis CI columns. We are almost there.

**Comment by icecream17** [comment]
Done!

Note: The following don't have github actions
clear cut
jasmine focused
property accessors
season
pegjs

**Comment by sadick254** [comment]
@icecream17 Thank you for all the work done on this PR. Could you mark it as ready for review?

**Pull request merged**
